### ISSUE TITLE
Opening gazebo, rviz, and navstack process in different orders will affect connections

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1006]
I can only get navstack to work reliably when gazebo is already open, and rviz after navstack is up.

Its probably DDS/RMW related that's out of our control but leaving the ticket to later come back to

**Comment by mlherd** [comment]
They should be run in this order:

1- Gazebo
2- TB3 Bringup
3- Navigation Bringup
4- Rviz

It will probably not work if you run them in a different order.

**Comment by SteveMacenski** [comment]
@mlherd the point I was making is that that's _bad_ and should not be the case. This is an issue needing to be resolved but its probably more deeply rooted than this repo but its a bug to start the tracking down process

**Comment by mlherd** [comment]
I agree. I just wanted to add the right order here, so if someone reads this issue, they will at least know the right order.

**Comment by SteveMacenski** [comment]
I did some more digging on this front, it really is going to be something so far below this project that its not really worth addressing here. A multitude of tickets across the ecosystem express a similar issue so its not worth keeping in our queue.
