### ISSUE TITLE
Register nodes as components + launch files to use component container

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#1013]
## Feature request
Make all nodes components with default launch files using the component container to load into the same process (or at least optional launch file along with the distributed one) 

Need to register them and then make a launch file using them. 

#### Feature description
We've discussed the potential for the stack to be configured into different processes by utilizing components in ROS2, yet none of our nodes have been registered as components. We should make this change to enable this use case. 

See https://index.ros.org/doc/ros2/Tutorials/Composition/

#### Implementation considerations

- Components need to have NodeOptions as the constructor argument, not sure what impact that has on the signature of the nodes in the stack.

**Comment by shivaang12** [comment]
Do you any high level planning of how you want to approach this? I think we might need to split the nodes in order to make them compatible for running standalone as well as through component.

**Comment by SteveMacenski** [comment]
They should all work to my knowledge just registering in the CMakelists and with the cpp macros. They all derive from the node type and take in `NodeOptions`.

**Comment by SteveMacenski** [comment]
PR open and to be merged.
