### ISSUE TITLE
[Map server] filename give date at end to avoid overwriting data by accident

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1019]

**Comment by crdelsey** [comment]
You mean for map_saver?

**Comment by SteveMacenski** [comment]
Yes, the map saver executable but its the map server package I guess I was categorizing

**Comment by SteveMacenski** [comment]
This ticket awards @SteveMacenski 1 point for the TTS competition

(though I cant win my own competition so...)
