### ISSUE TITLE
rviz display for heatmap of robot poses

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1025]
There was a debug tool in navfn that published occasional markers of the robots position as it proceeded towards a goal, resulting in a kind of sparse heatmap. 

This ticket would be for creating an RVIZ display of the same information utilizing additional capabilities in the RVIZ plugin infrastructure and displaying additional information as a better generalized debug tool

**Comment by crdelsey** [comment]
@SteveMacenski Can you add a description for everyone's benefit

**Comment by SteveMacenski** [comment]
@crdelsey is this something you still feel should be readded?

**Comment by crdelsey** [comment]
As I recall, we thought this should be an RViz feature, so we should close the issue in our repo.
