### ISSUE TITLE
no transformation between the base_footprint frame  and the map frame

### ISSUE THREAD

**Issue by ZakariaChekakta** [ros-planning/navigation2#1034]
## Bug report

**Required Info:**

- Operating System:
  -    Ubuntu 18.04

- Installation type:
  -   Source

- Version or commit hash:
  - Dashing version

- DDS implementation:
  - Default Fast-RTPS

#### Steps to reproduce issue

```
ros2 launch nav2_bringup nav2_simulation_launch.py
```

#### Expected behavior
display the robot model in RVIZ and it should be no issues in the transformation 
#### Actual behavior
![1](https://user-images.githubusercontent.com/12950797/62994271-fae18900-be95-11e9-84c4-43699acf21d3.png)
![2](https://user-images.githubusercontent.com/12950797/62994268-f7e69880-be95-11e9-881a-cc83dee756ae.png)

**Comment by SteveMacenski** [comment]
In order for the robot to navigate and have that costmap be updated, there has to be a valid map->base link transform. Do you see this consistently when launching say, 3x in a row?

If you subscribe to the tf topic do you see odom->base footprint and map->odom transforms over the pipe? If so then its rviz’s connection to the lot.

**Comment by ZakariaChekakta** [comment]
@SteveMacenski , I have just run echo to the /tf topic to see if there is a transformation between map and base_footprint, and suddenly, in rviz  the robot model appears and the transformation too. I don't understand why it happened like that but thank you 
![Screenshot from 2019-08-15 11-22-15](https://user-images.githubusercontent.com/12950797/63068945-0c876700-bf50-11e9-82d7-480e5b3f2917.png)

**Comment by crdelsey** [comment]
I suspect there are bugs in FastRTPS, the way ROS 2 is using it, or the way multicast is operating on your network. Sometimes it seems that publishers and subscribers don't see each other. Then when you do a ros2 topic echo, that triggers rediscovery and things start to work again.

I'm guessing though. I haven't had a chance to really debug these types of issues yet.
