### ISSUE TITLE
Open Navigation2_Experiental repo?

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1046]
In the past, packages that weren't quite ready for prime time were added to an `_experiemental` package. 

ex.
https://github.com/ros-planning/navigation_experimental
https://github.com/ros-industrial/abb_experimental
https://github.com/ros-industrial/kuka_experimental

both in order to give them faster speeds of development and make a distinction between elements of the project that were stable for production use and things you should use with vigilance.

Should we break out navigation2_experimental to a new repo? I don't know anyone's done this for ROS2 yet or if that's even the right way to go necessarily.

**Comment by mkhansen-intel** [comment]
We've discussed this a little bit internally, and for now we were settled on just putting experimental things in the nav2_experimental package within this repo. This way at least we know these things are getting code review and CI the same as everything else in the repo. We're open to changing this in the future, it just seemed like extra work right now. If you want to create the repo and help maintain it, we could move that package over and start submitting PRs to it.
