### ISSUE TITLE
Behavior tree xml files installed outside of package share directory

### ISSUE THREAD

**Issue by rotu** [ros-planning/navigation2#1090]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18
- Installation type:
  - binaries

#### Steps to reproduce issue
```
sudo apt install ros-dashing-nav2-behavior-tree
```

#### Expected behavior
The behavior tree xml files are somewhere below `/opt/ros/dashing/share/nav2_bt_navigator`

#### Actual behavior
Behavior tree xml files get installed to `/opt/ros/dashing/behavior_trees`

**Comment by mkhansen-intel** [comment]
Yes, that seems like a bug to me
