### ISSUE TITLE
Document how to run 'updown' test in README or somewhere

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#1092]
## Feature request
Add documentation for how to run the updown test

**Comment by SteveMacenski** [comment]
@mkhansen-intel @crdelsey do you intend in doing this? I don't really know anything about that test to document myself.

**Comment by crdelsey** [comment]
There is a brief explanation here.

https://github.com/ros-planning/navigation2/blob/1ec7b205ddee240273ac6ba5d218d050e8ab4f4c/nav2_system_tests/src/updown/updownresults.py#L17-L26

I could move this to a readme. 

@mkhansen-intel You made a bunch of changes to this test, but I don't see them in the branch. DId you ever get those changes working? I don't recall.

**Comment by mkhansen-intel** [comment]
I updated the test and got it working without requiring simulation in #1413. I'll add a README file to the folder with simple instructions for running it.
