### ISSUE TITLE
Should we override the lethal_threshold value or not? 

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#112]
In src/libs/nav2_util/src/costmap.cpp, there is the line:

  lethal_threshold_ = std::max(std::min(lethal_threshold_, 100), 0);

Why do we override the lethal_threshold here? Seems that if the client sets it to some value, we should honor that or throw/assert if it isn't valid.

**Comment by SteveMacenski** [comment]
This maximum of 100 is by convention in the costmaps, making it higher would result in situations where no lethal obstacles are able to be marked. While I don't see personally much value in that, I suppose we could allow people do to unadvisable things if they choose. I'll add a warning.
