### ISSUE TITLE
rviz lagging while navigating

### ISSUE THREAD

**Issue by yathartha3** [ros-planning/navigation2#1155]
## Bug report
Rviz lagging while navigating. Is anyone else seeing this problem, or have tried with other DDS implementations?

**Required Info:**

- Operating System:
  - OS and version (Ubuntu 18.04)

- DDS implementation:
  - rmw_implementation used Fast-RTPS

#### Actual behavior
![rviz_lagging](https://user-images.githubusercontent.com/12860979/65451050-466f4700-ddf3-11e9-9ae2-7ad3d78a0ad4.gif)

The terminal prints out the "usual" dropped message such as:
[INFO] [rviz]: [signalFailure] Drop message: frame 'base_scan' at time 452.601 for reason(0)
[INFO] [rviz]: [signalFailure] Drop message: frame 'odom' at time 1569260413.444 for reason(0)

**Comment by SteveMacenski** [comment]
I usually see this on wifi networks, though from the limited set of data shown its hard to figure out if everything is lagging, or its just TF

**Comment by yathartha3** [comment]
Closing now. Will test it and reopen if needed.
