### ISSUE TITLE
Update system test to use NavigateToPose Action

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#1168]
## Feature request
The current system test sends a goal by publishing to the /goal topic. We should update the test with ability to use the NavigateToPose action instead.

#### Feature description
This will test the action interface and ensure that it's working correctly, including the feedback and 'success' from the action. Instead of checking the robot's position to determine pass/fail, the action method would get the pass fail status based on the return of 'success' or not from the action.

#### Implementation considerations
It would be best to add this capability without losing coverage of the topic based mechanism also. So adding this as an option that can be selected at run time similar to the "Astar" and "Dijkstra" testing options. Maybe "Astar" continues to use the /goal topic and "Dijkstra" uses the action to maximize test coverage.

**Comment by orduno** [comment]
@mkhansen-intel I can take this one. Switching to use an action interface is part of the solution for #1274.
