### ISSUE TITLE
Small documentation typo @ navigation2/nav2_core/include/nav2_core/recovery.hpp

### ISSUE THREAD

**Issue by shivaang12** [ros-planning/navigation2#1170]
I was going through this file and I suspect a possible typo in recovery.hpp. In this file, name of the class is "Recovery" but it is documented as "GlobalPLanner" on the line number 27.

P.S. I am apologizing in advance if this is just my misunderstanding instead of typo. I am looking for ways to contribute to this repo. Thanks!

**Comment by mlherd** [comment]
It seems like a typo to me too. Could you fix it and submit a PR for it?

**Comment by shivaang12** [comment]
@mlherd 

I can do it! Thank you so much!
