### ISSUE TITLE
Test multiple sensor input support

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1227]
Support for multiple obstacle sensor sources exists in the obstacle/voxel layer. We need to test and verify it works.

@SteveMacenski There is no support for multiple sensor sources in AMCL. Do you think we need it there as well?

**Comment by SteveMacenski** [comment]
AMCL never before supported it, but if you see opportunity to support I wouldn't oppose!

**Comment by ninamwa** [comment]
Is it a requirement that a subscribed topic for the obstacle layer is /scan? I tried testing with two different scan topics, named scan_1 and scan_2. When setting the initial pose in Rviz, nothing happens and the transform from map to odom is never created. When changing the topics to /scan and /scan_2, the initialization is fine again. But then it does look like only the /scan topic is included in the local costmap..
