### ISSUE TITLE
Website improvements

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1228]
Content updates:
- [x] replace getting started navigation gif so its not terrible.
- [x] slam tutorial needs a gif / image
- [ ] move slam gif to top
- [x] more images, graphics, videos, and gifs in index and description pages. Any index or short page needs graphics. Non-turtlebot.
- [x] update readme hyperlinks
- [x] Make the following pages much better: build pages
- [x] remove word "system" and version 0.2.3
- [x] quickstart tab doesnt mention its master
- [x] build instructions for specific distributions should use debians NOT repos file. And lets put it all into the same workspace now. 
- [x] quickstart build script at top of master build page, or let them expand one or another to use.
- [x] reduce trouble shoot guide duplicates and add more (transform issue, lifecycle, etc)
- [x] somewhere we need to mention the message types of the server actions and give a full block diagram overview in detail
- [x] add rb1 base and tiago for robots shown working from Office Marathon 2 paper experiments
- [x] clear demo without lidar or lidar based mapping since that keeps being asked. At least document that also that's not required
- [x] fix transform available plugin hyperlink

New pages / content: 
- [ ] marathon experiments
- [ ] Roadmap (ackermann, non-circular, non-flat, moderner techniques. Grad, hybrid/lattice, MPC/TEB, time/velocity profiles, dynamic detection/tracking, ML on data, redo AMCL faster/better, lanes/keepout/speed/etc, multistory, multimodal mapping and localization [vision + lidar])
- [x] Capabilities description (navigate, waypoints, bt into larger systems, plugins, servers, clear description for when to use plugins and when to create new server w/ data flow)
- [x] Setup guide like in [nav1 wiki](http://wiki.ros.org/navigation) (odom sources, tf, sensor streams), [configuration guide](http://wiki.ros.org/navigation/Tutorials/Navigation%20Tuning%20Guide) and descriptions.  [here](http://wiki.ros.org/navigation/Tutorials/RobotSetup) [here](https://arxiv.org/pdf/1706.09068.pdf). Parameter description and defaults. update viable parameters and namespaces in configuration section for DWB/controller/planner/navfn #1589 
- [x] list of known plugins external (costmap [stvl, npvl], planner, controller [teb], recovery)
- [x] Migration builds between distributions (dashing->eloquent [new waypoint follower, rehomologated world model into plan/control servers, created recovery plugins and added backup and wait, created nav2_core interfaces for controller and planners plugins, integrates with SLAM, STVL, and TEB, many bew Bt nodes, map server refactor, many stability improvements, using Tf based positioning, moving from tasks to rclcpp actions], eloquent->foxy [namespacing of params, new dwb params from ROS1 sync, controller interface update,  set default BT plugins, many stability improvements, separate nav and localization lifecycle managers to reduce interdependency of localization/slam algorithm, all BT nodes are now plugins, fixes async issues in Bt navigator])
- [x] an "about" page
- [x] Comparison page ROS1 nav to ROS2
- [x] Robots using
- [x] repo structure
- [x] Contributing -> getting involved: what's there +  contribution guidelines actually describe the useful information: weekly meetings, process of tickets -> PRs, etc. +  (discourse, answers, github ticket, contribution, maintaining, using)
- [x] concepts descriptions (behavior trees, our specific BTs, our planners, our controllers, localization, mapping, what is planning / control, what is a costmap, how we use it and layers).  clear description/demo without lidar or lidar based mapping since that keeps being asked. At least document that also that's not required
- [x] read through [this](https://github.com/risckaust/risc-documentations/blob/master/docs/source/1-ros-navigation.rst) and see there are useful nuggets
- [x] http://wiki.ros.org/navigation analyze documentation and add appropriate action items

Formatting:
 - [x] host on navigation.ros.og
- [x] move website to a new repo
- [x] missing gif in getting started page
- [x] Navigation2 -> Navigation 2
- [x] Remove titles with "Navigation2" as a prefix, we know what the project is if we're on the site
- [x] Remove all move_base or nav1 references from home page, or any page other than comparison
- [x] website max width restriction so paragraphs don't appear as a single line
- [x] build instructions -> build and install
- [x] remove use case recommendations page
- [x] architecture slide without background
- [x] center videos and images https://sphinx-rtd-theme.readthedocs.io/en/stable/demo/demo.html#directives
- [x] images throughout single pages consistent sizes
- [x] start each tutorial page with the successful outcome to be had at the end
- [x] all images vectors
- [x] all videos properly scaled for aspect ratio and gif-ified if appropriate
- [x] remove (or put on top) all non-hidden section lists
- [x] sidebar needs to be wider for text to not go to next line
- [x] remove documentation guidelines boilerplate

**Comment by SteveMacenski** [comment]
how those all are structured, their plugin definitions, what messages they send around, relative rates, behavior tree how it works and how we use it, our custom BT nodes, lifecycle manager. 

Behavior tree concept, action server concept, lifecycle manager concept.

**Comment by SteveMacenski** [comment]
@gimait if you're so interested, it would be helpful if you could help make some media for the website! The  first two tasks:

```
replace getting started navigation gif so its not terrible.
slam tutorial needs a gif / image
```

Are pretty straight forward with a screen video if you're interested. The goal of these are to have visual examples for all tutorials and pieces of documentation. The SLAM tutorial currently has no gif and the getting started gif at the very end is a poor example of navigation from the very early days (note all the recovery behaviors being triggered and generally struggling). If you could make one that represents the current state of things that aren't poor, that would be awesome and save me a bunch of time (and your videos enshrined into the halls of this project forever).

**Comment by gimait** [comment]
For sure, I'll take a look at that :)

**Comment by gimait** [comment]
@SteveMacenski could you give me some feedback on the gifs I added in [f3c7c64](https://github.com/gimait/navigation2/commit/f3c7c643ebbf9442937472d1b77283ece52581a3)?
I could change framerate and/or resolution. Is there a size limit I should be aware of for these files?

**Comment by SteveMacenski** [comment]
For both, I'd say increase the frame rate a bunch so that its smooth, we don't want it to be choppy. Your recordings are 800x400 while the originals are 600 x 375. Not saying that's necessarily the right resolution, but its big enough to get the point across but small enough to save space. Finally, try also compressing the mp4 before gifing it to decrease size. @mlherd any recommendations on that?

For the navigation: I'd say remove the local costmap since its a little distracting, the global and plan is illustrative enough.

For the slam: Can you increase the laser max distance (temporarily) for this demo? Its a little subtle why only the left 90 degrees is marking. Its not immediately clear to folks that don't do SLAM alot that its because those other beams shown are out of range. Or just have it building the map in a smaller room that it can see more of. The gif only shows a few feet of which very little is actually mapped.

**Comment by mlherd** [comment]
I use [ezgif](https://ezgif.com/maker) to create gifs since it has all the tools I need.

-20 fps (15 seconds) should give you good results. Even 10 fps will look good if you really need more seconds. Another option, you can seed up the video a little bit if 15 seconds is not enough.
-Keep the resolution as high as possible ex: 600px

By the way, it seem like the realtime factor drops in Gazebo when tb3 start moving. You can get rid of the camera, depth camera plugins etc in the robot model if you don't use them. It will help you increase the real time factor.

**Comment by gimait** [comment]
Awesome! thanks for the help! I’ll push some better gifs soon.

**Comment by gimait** [comment]
@SteveMacenski, @mlherd, what do you think about the new gifs?

**Comment by SteveMacenski** [comment]
Both great!

**Comment by mlherd** [comment]
They both show the expected results, so they are good. The lag between RVIZ and Gazebo is a bit noticeable, but it is fine.

**Comment by mlherd** [comment]
> @SteveMacenski, @mlherd, what do you think about the new gifs?

They both show the expected results, so they are good. The lag between RVIZ and Gazebo is a bit noticeable, but it is fine.

**Comment by gimait** [comment]
>  The lag between RVIZ and Gazebo is a bit noticeable, but it is fine.

I disabled cameras etc from the robot on gazebo, and although it improved the real time factor, it didn't really help with the lag. Do you have any ideas on how could I fix this?
Otherwise I'll create a pr for the current gifs.

**Comment by SteveMacenski** [comment]
I think this is fine - honestly didnt notice it I'm so used to gazebo doing gazebo-y-things
