### ISSUE TITLE
[ros2_amcl] Refactoring the README.md

### ISSUE THREAD

**Issue by shivaang12** [ros-planning/navigation2#1236]
#### Feature description

Refactoring the nav2_amcl/README.md, removing the "current plan" section, as all the mentioned issues in the section are already closed. Or may be rename that section to some thing else.

**Comment by mlherd** [comment]
@shivaang12 Would you like to do the changes and submit a PR? Thanks in advance!

**Comment by shivaang12** [comment]
Sure, Thanks!
