### ISSUE TITLE
Add Autolocalization as an action server

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#1254]
## Feature request
Auto-localization action server

#### Feature description

As a user, I'd like to be able to tell my robot to "Auto-localize" in some cases. 
1. When it first powers up / starts in the map, instead of having to send an initial pose, I'd like it to try to localize itself
2. When it get's confused or lost (recovery behavior)

I think if the Autolocalization feature was wrapped with an "Autolocalize" action, then the action could be called either from the RViz GUI in case 1 above, or from the Behavior Tree as in case 2 above.
#### Implementation considerations

I believe the autolocalization code is still here in the repo, not sure if it got removed at some point, but it could be forward ported if it was. Adding the action server part shouldn't be difficult (famous last words).

Also, before this wasn't practical because we weren't doing collision checking during backup & spin, now we are so it should be OK to move the robot around a little bit to localize it.

**Comment by SteveMacenski** [comment]
Isn't that dependent on not-proven DRL work? I'm not sure that should exist outside the experimental repo yet

**Comment by mhpanah** [comment]
> Isn't that dependent on not-proven DRL work? I'm not sure that should exist outside the experimental repo yet

This version is not dependent on the RL work.  In this version, the AutoLocalizer will naively spins and backups in its place to help the particles to converge (it may or may not converge depending on the environment, which in that case the user will know that it failed to converge).  But for the next version, the plan is to have the robot to navigate in such a way to optimally localize itself faster (potentially using RL).

**Comment by SteveMacenski** [comment]
@mhpanah @mkhansen-intel What's the status of this given the status of the RL work?

**Comment by SteveMacenski** [comment]
I'm closing for now -- if this is premature and there's something to be done, let me know and we can reopen and address what actions we should take.
