### ISSUE TITLE
[Tiny Ticket Sprint] 1 ticket award for every 20 methods given doxygen

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1256]
For every twenty (20) methods given doxygen documentation in the headers, I will award 1 ticket worth of points.

Maximum 3 ticket (points). 
If you plan to go this route, I require that you complete entire files and not pick and choose.

**Comment by SteveMacenski** [comment]
@shivaang12 has been awarded 1 point from this 

(for my later accounting)

**Comment by shivaang12** [comment]
Thanks @SteveMacenski !. I think I will do nav2_controller, if that's fine?

**Comment by SteveMacenski** [comment]
Sure thing!

**Comment by SteveMacenski** [comment]
@shivaang12 second documentation PR gets them another 1 point!

**Comment by shivaang12** [comment]
@SteveMacenski Are we dropping name "Global planner" just like "Local Planner"?

**Comment by SteveMacenski** [comment]
I hadn't thought much on global planner, I didn't have an issue with that term. I suppose it could just be "planner" now and that would be fine

**Comment by shivaang12** [comment]
Got it! I guess we were using term global just to distinguish it from local planner. Planner sounds cool!

**Comment by shivaang12** [comment]
@SteveMacenski I should get one more point?

**Comment by SteveMacenski** [comment]
Yup!
You have 3 (maximum) documentation points and are in the lead.

You're also welcome to keep working on documentation or other tickets ;)

**Comment by shivaang12** [comment]
Sure!

**Comment by shivaang12** [comment]
@SteveMacenski one more question, if you don't mind. Can anyone attend nav2_wg meeting?

**Comment by SteveMacenski** [comment]
**Yes**

Resounding yes

**Comment by SteveMacenski** [comment]
@shivaang12 as the winner of the tiny ticket sprint, you may select a graphic that i will place in my ROSCon presentation in China next week!

I'd offer the suggestion to not make my life too hard ;-) 

Please post your selected image to the discourse thread: https://discourse.ros.org/t/ros2-navigations-tiny-ticket-sprint-reward-for-winning/11080 no later than Monday at 6pm so I can get it in (and have a 14 hour flight to figure out what I'm going to do)

**Comment by shivaang12** [comment]
@SteveMacenski Thanks man! Could you give me more context into this graphic?

**Comment by shivaang12** [comment]
@SteveMacenski And also I don't want to make it difficult for you too. So if you can suggest some topics, it would be great.

**Comment by SteveMacenski** [comment]
Just an image, XKCD comic, a robot, I suppose a meme, etc anything you like, that’s appropriate for display. 

If you don’t want to make my life too hard, something graph or laser related since its graph-slam with lasers (who doesnt love lasers?!)
