### ISSUE TITLE
Remove TB3 model files, instead download at build

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#1266]
#### Feature description

As suggested [here](https://github.com/ros-planning/navigation2/pull/1243#issuecomment-542944123) we should probably download the files at build time.

#### Implementation considerations

Previously, we had to customize the model files to account for the `--ros-args` changes, however, that might be fixed now.

**Comment by SteveMacenski** [comment]
I think we should just close this. Its definitely a piece of technical debt, but at this point, we've modified the basic turtlebot3 files so much to work with depth cameras/lidars that we can't just install them from robotis's mainline anymore for basic testing and CI
