### ISSUE TITLE
Active action servers on shutdown aren't going quietly

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1274]
Locally, I'm seeing the CI tests success but on the SIGINT:

[controller_server-7] terminate called after throwing an instance of 'std::runtime_error'
[controller_server-7]   what():  Asked to publish result for goal that does not exist
OR
[bt_navigator-10] [ERROR] [bt_navigator]: Navigation failed
[bt_navigator-10] terminate called after throwing an instance of 'std::runtime_error'
[bt_navigator-10]   what():  Asked to publish result for goal that does not exist

and then causes their respective servers to crash, depending on the situation. Has anyone else noticed this? It seems like when the servers are being brought down, the action servers are still active trying to send an update on terminate that no longer exists. This isn't making the test fail, but that's not a good thing for us to be having going on.

I think there needs to be something protecting the active action servers on exit from trying to `terminate_goal()` or doing anything after the signal has occurred to shutdown so it goes quietly into the night

**Comment by shivaang12** [comment]
@SteveMacenski 
I also noticed this same issue on my computer, mine says "navigation failed".

**Comment by mkhansen-intel** [comment]
Can you paste in the entire log? Are you sure that the test passed? Keep in mind that sometimes the console output is out of order.

**Comment by mjeronimo** [comment]
Is the system being shut down before the processes are terminated? That is, invoke shutdown() service on the lifecycle manager before killing the processes. If this isn't happening the processes are being killed while in the Active state. They should be killed when in the Finalized state, after they've had a chance to stop threads, clean up their resources, etc.

**Comment by orduno** [comment]
I think that's the case, I'm working on a PR to solve this.
