### ISSUE TITLE
[cartographer_node-1] ERROR: unknown command line flag

### ISSUE THREAD

**Issue by AndreasAZiegler** [ros-planning/navigation2#1312]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04.1 LTS
- Version or commit hash:
  - ec4904be2af7dc5a6ed74dc46edac5ea4bfb6aab
- DDS implementation:
  - standard (I guess Fast-RTPS)

#### Steps to reproduce issue
* In the first terminal in workspace
```
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models
export TURTLEBOT3_MODEL=burger
ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
```
* In the second terminal in workspace
```
ros2 launch nav2_bringup nav2_navigation_launch.py
```
* In the third terminal in workspace
```
ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True
```

#### Expected behavior
Cartographer starting up and robot shown in rviz2

#### Actual behavior
Cartographer gives the following errors:
```
ros2 launch turtlebot3_cartographer cartographer.launch.py use_sim_time:=True
[WARN] [rcl]: Found remap rule 'use_sim_time:=True'. This syntax is deprecated. Use '--ros-args --remap use_sim_time:=True' instead.
[INFO] [launch]: All log files can be found below /home/andreasziegler/.ros/log/2019-10-29-15-26-54-078724-AndreasZiegler-1779
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [cartographer_node-1]: process started with pid [1792]
[INFO] [occupancy_grid_node-2]: process started with pid [1793]
[INFO] [rviz2-3]: process started with pid [1794]
[occupancy_grid_node-2] ERROR: unknown command line flag 'params-file'
[occupancy_grid_node-2] ERROR: unknown command line flag 'r'
[occupancy_grid_node-2] ERROR: unknown command line flag 'ros-args'
[cartographer_node-1] ERROR: unknown command line flag 'params-file'
[cartographer_node-1] ERROR: unknown command line flag 'r'
[cartographer_node-1] ERROR: unknown command line flag 'ros-args'
[ERROR] [occupancy_grid_node-2]: process has died [pid 1793, exit code 1, cmd '/opt/ros/eloquent/lib/cartographer_ros/occupancy_grid_node -resolution 0.05 -publish_period_sec 1.0 --ros-args -r __node:=occupancy_grid_node --params-file /tmp/launch_params_738fh22r'].
[ERROR] [cartographer_node-1]: process has died [pid 1792, exit code 1, cmd '/opt/ros/eloquent/lib/cartographer_ros/cartographer_node -configuration_directory /home/andreasziegler/ros/ros2_turtlebot3_ws/install/turtlebot3_cartographer/share/turtlebot3_cartographer/config -configuration_basename turtlebot3_lds_2d.lua --ros-args -r __node:=cartographer_node --params-file /tmp/launch_params_46p7kg0a'].
```

#### Additional information
I installed ros eloquent via apt. To install the navigation stack and to install the turtlebot stuff, I followed [this guide](https://github.com/ros-planning/navigation2/blob/master/doc/BUILD.md).

**Comment by AndreasAZiegler** [comment]
@mlherd Thanks for your answer
With ```ros2 launch turtlebot3_cartographer cartographer.launch.py --ros-args use_sim_time:=True``` I do not longer get the
```
[WARN] [rcl]: Found remap rule 'use_sim_time:=True'. This syntax is deprecated. Use '--ros-args --remap use_sim_time:=True' instead.
```
But I still get these errors which seem to crash the cartographer_node
```
[occupancy_grid_node-2] ERROR: unknown command line flag 'params-file'
[occupancy_grid_node-2] ERROR: unknown command line flag 'r'
[occupancy_grid_node-2] ERROR: unknown command line flag 'ros-args'
[ERROR] [occupancy_grid_node-2]: process has died [pid 3003, exit code 1, cmd '/opt/ros/eloquent/lib/cartographer_ros/occupancy_grid_node -resolution 0.05 -publish_period_sec 1.0 --ros-args -r __node:=occupancy_grid_node --params-file /tmp/launch_params_axv1re_t'].
[cartographer_node-1] ERROR: unknown command line flag 'params-file'
[cartographer_node-1] ERROR: unknown command line flag 'r'
[cartographer_node-1] ERROR: unknown command line flag 'ros-args'
[ERROR] [cartographer_node-1]: process has died
```

**Comment by mlherd** [comment]
It seems like I forgot to add -p :) Can you try the following command instead.

```ros2 launch turtlebot3_cartographer cartographer.launch.py --ros-args -p use_sim_time:=True```

**Comment by AndreasAZiegler** [comment]
Unfortunately, it looks like it makes no difference:
```
ros2 launch turtlebot3_cartographer cartographer.launch.py --ros-args -p use_sim_time:=True
[INFO] [launch]: All log files can be found below /home/andreasziegler/.ros/log/2019-10-30-11-01-55-090948-AndreasZiegler-2211
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [cartographer_node-1]: process started with pid [2226]
[INFO] [occupancy_grid_node-2]: process started with pid [2227]
[INFO] [rviz2-3]: process started with pid [2228]
[occupancy_grid_node-2] ERROR: unknown command line flag 'params-file'
[occupancy_grid_node-2] ERROR: unknown command line flag 'r'
[occupancy_grid_node-2] ERROR: unknown command line flag 'ros-args'
[ERROR] [occupancy_grid_node-2]: process has died [pid 2227, exit code 1, cmd '/opt/ros/eloquent/lib/cartographer_ros/occupancy_grid_node -resolution 0.05 -publish_period_sec 1.0 --ros-args -r __node:=occupancy_grid_node --params-file /tmp/launch_params_mmo84aca'].
[cartographer_node-1] ERROR: unknown command line flag 'params-file'
[cartographer_node-1] ERROR: unknown command line flag 'r'
[cartographer_node-1] ERROR: unknown command line flag 'ros-args'
[ERROR] [cartographer_node-1]: process has died [pid 2226, exit code 1, cmd '/opt/ros/eloquent/lib/cartographer_ros/cartographer_node -configuration_directory /home/andreasziegler/ros/ros2_turtlebot3_ws/install/turtlebot3_cartographer/share/turtlebot3_cartographer/config -configuration_basename turtlebot3_lds_2d.lua --ros-args -r __node:=cartographer_node --params-file /tmp/launch_params_7xkwqfop'].
```

**Comment by yathartha3** [comment]
@AndreasAZiegler It complaining about the params file, which you are currently trying to give using the command line.
You can specify the param file that you want to use in the launch file itself. Maybe peeking at nav2_bringup.launch in the nav2_bringup directory will help.

**Comment by AndreasAZiegler** [comment]
The only places I found ```params-file``` was in ```src/navigation2/nav2_system_tests/src/updown/test_updown_launch.py``` and in ```/src/navigation2/nav2_common/nav2_common/launch/node.py``` but as ```cartographer_node``` is started directly in ```cartographer.launch.py``` I don't think that's related.

Could it be related to this issue https://github.com/googlecartographer/cartographer_ros?/issues/1378

I just pulled the master branch and have commit ```1a1070ae8fd4aa19436773bd0877f5ec093f9170```

**Comment by mlherd** [comment]
@AndreasAZiegler Which method did you use to build or install Cartographer?

**Comment by AndreasAZiegler** [comment]
I installed it view ```apt-get install``` and have the following packages installed:
```
ros-eloquent-cartographer                           1.0.0-1bionic.20191024.042253        amd64        Cartographer is a system that provides real-time simultaneous localization and mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
ros-eloquent-cartographer-ros                       1.0.9000-1bionic.20191024.122706     amd64        Cartographer is a system that provides real-time simultaneous localization and mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.
ros-eloquent-cartographer-ros-msgs                  1.0.9000-1bionic.20191024.070421     amd64        ROS messages for the cartographer_ros package
```

**Comment by mlherd** [comment]
It seems like the turtlebot_cartographer launch file needs to be updated for eloquent. I would open an issue in their repo.

It requires a little bit more work, but you can look at what they do in their launch file and try to execute the nodes yourself. I haven't tested cartographer eloquent release to create maps yet, but I was able to install the package via apt and run cartographer_node and occupancy_grid_node individually.

ex:
ros2 run cartographer_ros cartographer_node -configuration_directory PATH_TO/config -configuration_basename turtlebot3_lds_2d.lua

**Comment by mlherd** [comment]
Since this is not a Navigation2 related issue, I close it. When you find a solution to this issue, please feel free to add a comment.

**Comment by ribinmathew** [comment]
> It seems like the turtlebot_cartographer launch file needs to be updated for eloquent or the way the cartographer nodes are executed is not correct. I would open an issue in their repo and check if anyone has run into the same issue.
> 
> It requires a little bit more work, but you can look at what they do in their launch file and try to execute the nodes yourself. I haven't tested cartographer eloquent release to create maps yet, but I was able to install the package via apt and run cartographer_node and occupancy_grid_node individually.
> 
> ex:
> `ros2 run cartographer_ros cartographer_node -configuration_directory PATH_TO/config -configuration_basename turtlebot3_lds_2d.lua`

ran into same issue...
