### ISSUE TITLE
Scoping global and local planner params

### ISSUE THREAD

**Issue by yathartha3** [ros-planning/navigation2#1314]
The dwb paramaters, and other local controller parameters should be underneath the controller_server scope.

Probably, we should scope the dwb parameters: eg
```
nav2_controller:
  ros__paramaters:
    dwb.param1 = 1
    dwb.param2 = 7
```

_Originally posted by @crdelsey in https://github.com/ros-planning/navigation2/pull/1045_

**Comment by orduno** [comment]
Same for the planner plugins in the `PlannerServer`.
