### ISSUE TITLE
Add documentation for lifecycle manager

### ISSUE THREAD

**Issue by yathartha3** [ros-planning/navigation2#1317]
Currently, there is no documentation for lifecycle manager.

**Comment by shivaang12** [comment]
Do you mean doxygen? Cause I have open pull request for it.

**Comment by yathartha3** [comment]
@shivaang12 Thanks for adding the doxygen.
However, I was not referring to that. I was referring to some documentation about the lifecycle manager and lifecycle nodes in general in the front page readme of the package. I am planning to do that soon.

**Comment by shivaang12** [comment]
@yathartha3 No worries!

**Comment by SteveMacenski** [comment]
@yathartha3 any update here? I see you self-assigned

**Comment by yathartha3** [comment]
@SteveMacenski Hadn't really worked on it. I will write it up this week, or by monday and submit a PR.

**Comment by SteveMacenski** [comment]
No, just trying to see if I poked the bear if it would get done faster ;-)

**Comment by yathartha3** [comment]
Addressed by #1392
