### ISSUE TITLE
Fix linter warnings for nav2_util pf, sensor, and laser

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#133]
Fix all linter issues in nav2_util for:
sensor
pf
map

**Comment by crdelsey** [comment]
This looks like a duplicate of #71

**Comment by mhpanah** [comment]
Fixed in PR#134.

**Comment by mhpanah** [comment]
@crdelsey We still need to fix linter warnings for map_loader and costmap. So let's not close #71 yet.
