### ISSUE TITLE
Can't visualize voxels from voxel layer

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#1333]
## Bug report

**Required Info:**

- Operating System:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue
Follow instructions from:
https://github.com/ros-planning/navigation2/blob/master/nav2_costmap_2d/README.md#to-visualize-the-voxels-in-rviz

#### Expected behavior
We should be able to view voxel markers in RVIZ.

#### Actual behavior
No markers shown in RVIZ.

**Comment by crdelsey** [comment]
@orduno Can you work with Yathartha to figure out what's going on with this?

**Comment by orduno** [comment]
*Update:* Didn't realize we're using a robot model without a depth camera, let's try again once #1249 is merged.

**Comment by mlherd** [comment]
@orduno #1249 is merged, so it should solve this issue.

**Comment by SteveMacenski** [comment]
Has this been brought to conclusion?
