### ISSUE TITLE
Nightly builds of connext, opensplice and cyclone are broken.

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1341]
## Bug report

**Required Info:**

- Operating System:
  - 
- Version or commit hash:
  - master as of today (Nov 11, 2019) and for the past few weeks
- DDS implementation:
  - 

#### Steps to reproduce issue
Look at Circle CI results for 
- [ ] test_rmw_cyclonedds_cpp
- [x] test_rmw_opensplice_cpp
- [ ] test_rmw_connext_cpp

at https://circleci.com/gh/ros-planning/navigation2/tree/master

These are all failing and have been for a while.

**Comment by SteveMacenski** [comment]
Would it be OK if we dropped down to 1 or 2 nightly RMW builds? Fast RTPS (because default) and Cyclone seem the most reasonable. 

Opensplice has been deprecated for Foxy & I'm not sure we've ever used Connext enough to make it worth the maintenance. 

I will be looking at this after I stand up CI
