### ISSUE TITLE
Create a navigation2_bringup package

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#135]
We need a package for launching the fulll navigation stack. This will be the primary way users launch the stack as a whole. Most ROS packages have a bringup, so this is pretty standard. This is where the main launch file should live. 

The command line should be something like this:
ros2 launch navigation2_bringup nav2_bringup.launch.py

**Comment by mkhansen-intel** [comment]
We can/should use Turtlebot3 as our default robot, but there shouldn’t be any hard coded dependencies on Turtlebot3 in the bringup launch. It should be a run-time parameter. Then the Turtlebot3 team for example will create a turtlebot3_navigation package which calls our navigation2_bringup with the correct parameters for TB3. For our testing, we can have navigation2_turtlebot3.launch.py or something like that in our system test directory.

**Comment by SteveMacenski** [comment]
Will be added to this PR as needing to not be in root for this reorg https://github.com/ros-planning/navigation2/pull/107
