### ISSUE TITLE
 Move bt plugin registration into their respective headers

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1351]
Allow for single-file definition of a new BT node and plugin, I think that would fully check my box that the behavior tree is modifiable without requiring a hard fork. This has similar methods then with how we deal with pluginlib plugins.

https://github.com/ros-planning/navigation/issues/941

Ah, ye ol' bookmarks finally got me. Mixed up navigation1 and 2

**Comment by crdelsey** [comment]
I'm not sure I understand this. Are you wanting to get rid of the .hpp files and move their contents into the .cpp file? For instance, the `SpinAction` class definition in spin_action.hpp could be moved to the spin_action.cpp file and we could get rid of the header.

**Comment by SteveMacenski** [comment]
Yes, see PR
