### ISSUE TITLE
Publish more information about navigation tasks

### ISSUE THREAD

**Issue by mlherd** [ros-planning/navigation2#1359]
Calculate and publish more information using a custom message type. For example;

- Total length of the current path
- Estimated Time of Arrival
- Total distance traveled in the current path
- Total time spent on the current navigation task
- Task completion percentage
- Total distance traveled since launch
- Total travel time since launch

Feel free to give suggestions.

**Comment by SteveMacenski** [comment]
@mlherd is that not in the same vein as this? https://github.com/ros-planning/navigation2/issues/1339

**Comment by mlherd** [comment]
You are right they are very similar. Github issue search failed me this time :) I am moving my metric suggestions there then.
