### ISSUE TITLE
Disable TravisCI

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1360]
## Bug report

The Travis build now times out frequently, exceeding the 50 min limit. I tried reducing the number of tests it runs, but it even times out just doing the build step.

To continue using Travis, we either need to reduce the amount of code we build, or figure out how to cache build objects.

The question is, do we keep making Travis work or is it time to stop using it.

**Comment by SteveMacenski** [comment]
+1 for getting rid of it at this point

**Comment by SteveMacenski** [comment]
Update name from discussion

**Comment by mkhansen-intel** [comment]
I just turned it off in the Travis settings. We shouldn't see it build any more. I think all that needs to be done is remove the status badge from the front 'README' page and optionally remove the .travis.yml file.
