### ISSUE TITLE
Multiple gzclient instances launched

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#1410]
Multiple gzclients are launched when running `nav2_multi_tb3_simulation_launch.py`.

Bug was introduced in https://github.com/ros-planning/navigation2/pull/1349.

**Comment by orduno** [comment]
For some reason, the condition for executing the process evaluates to `true` even when the `use_simulator` substitution is `false`. 

https://github.com/ros-planning/navigation2/blob/c2d93596084968376ccb3d6213621f1cf59fe7b5/nav2_bringup/bringup/launch/nav2_tb3_simulation_launch.py#L138-L141

**Comment by orduno** [comment]
Seems like [compounding conditions](https://github.com/ros2/launch/issues/105) is still an open problem.

**Comment by mlherd** [comment]
hmm.. interesting. I tested headless=true and false conditions, but I didn't test use_simulator argument since I didn't think anyone would launch tb3_simulation without simulation :) but you proved me wrong :D
