### ISSUE TITLE
Automatic docs publish CI step updates "last updated" date everyday.

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1421]
## Bug report

**Required Info:**

#### Description

Looking at the commit history of the gh-pages branch, you can see that the docs build step updates the "Last Updated" date to be the current date. This results in a new commit every day even if no docs have changed.
https://github.com/ros-planning/navigation2/commit/c86492ce78be52cfacb0d5f1696da0a4bf8fc008

The docs should reflect the date of the last update to the source material, not the last build

##### Additional info

The date must come from the timestamp on the file. Since CI checks out the repository clean each time, that date is always the current date.

There doesn't seem to be a built in option in git to change the last modified timestamp on the file automatically, but there are some bash scripts on-line that try to address that problem.

https://stackoverflow.com/questions/2179722/checking-out-old-file-with-original-create-modified-timestamps

I briefly tried this once but got weird time results. However, an approach like this seems likely the best solution.

**Comment by SteveMacenski** [comment]
@crdelsey do you know if we can just remove the "last updated" item on the website instead? Given the current status of our maintainers' time, I don't want to burn many cycles on a pretty superficial footer that near-no-one will look at
