### ISSUE TITLE
Is there a list of documentation items that we want to tackle?

### ISSUE THREAD

**Issue by yathartha3** [ros-planning/navigation2#1453]
After the eloquent release, one of our priorities was to improve documentation.
Can we create a list of them so that it is clear what needs to be done?

**Comment by SteveMacenski** [comment]
I think there's a few tickets open on this @yathartha3 
https://github.com/ros-planning/navigation2/issues/1396
https://github.com/ros-planning/navigation2/issues/1092
https://github.com/ros-planning/navigation2/issues/1317
https://github.com/ros-planning/navigation2/issues/1228

In addition to doxygen in all the remaining headers missing ( I think we're about 50% )

**Comment by yathartha3** [comment]
@SteveMacenski Got it.

**Comment by SteveMacenski** [comment]
Closing - doc tickets are still open (well the 2 that haven't already been dealt with)
