### ISSUE TITLE
Can't pass map to nav2_bringup_launch.py file

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#1470]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Version or commit hash:
  - master branch since 2873bfc3468a25a47483f22d17a232a83355dfc6

- DDS implementation:
  - Fast-RTPS (default)

#### Steps to reproduce issue

```
ros2 launch nav2_bringup nav2_bringup_launch.py map:=$PWD/src/navigation2/nav2_system_tests/maps/map_circular.yaml autostart:=True
```

#### Expected behavior
Nodes should start correctly with map given.

#### Actual behavior
```
[map_server-1] [INFO] [map_server]: Configuring
[map_server-1] [ERROR] []: Caught exception in callback for transition 10
[map_server-1] [ERROR] []: Original error: Could not open 'map.yaml': file not found
[map_server-1] [WARN] []: Error occurred while doing error handling.
[map_server-1] [FATAL] [map_server]: Lifecycle node entered error state
[lifecycle_manager-8] [ERROR] [lifecycle_manager]: Failed to change state for node: map_server
[lifecycle_manager-8] [ERROR] [lifecycle_manager]: Failed to bring up nodes: aborting bringup
````
#### Additional information
I bisected it to the commit above, trying to debug 'why' this is the case now.

**Comment by SteveMacenski** [comment]
@mkhansen-intel its this line https://github.com/ros-planning/navigation2/commit/2873bfc3468a25a47483f22d17a232a83355dfc6#diff-9ced65f168bb2611c9a7bb195a719d11R50

I resolved it in this PR https://github.com/ros-planning/navigation2/pull/1464

It was part of my "why the hell isn't this working for me?" discussion in that PR which I  resolved.

**Comment by mkhansen-intel** [comment]
This line of code seems to be the culprit:
https://github.com/ros-planning/navigation2/blob/1ec7b205ddee240273ac6ba5d218d050e8ab4f4c/nav2_bringup/bringup/launch/nav2_bringup_launch.py#L50

I'm not sure why this was changed to the default, or what the side effects of changing it back might be. @orduno can you tell me?

**Comment by orduno** [comment]
Changing the default value to an empty string should fix the problem without side effects -- but haven't been able to confirm as am having trouble running nav2.

**Comment by SteveMacenski** [comment]
I have confirmed, its in #1464

**Comment by yathartha3** [comment]
I tried what @orduno suggested, and changing the default value to an empty string __did solve__ the problem. I am able to run the stack and navigate.
