### ISSUE TITLE
Can we get a Github project created for tracking issues and milestones?

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#15]
@tfoote @wjwwood @dirk-thomas - can we get a Github Project created for the Navigation2 work so that we can have a public Kanban board for tracking issues and progress on the project? Thanks, Matt

**Comment by dirk-thomas** [comment]
I was under the impression that with the "admin" role you should be able to so. Anyway I enabled projects in the settings of this repo.

**Comment by mkhansen-intel** [comment]
Thanks, I should have looked there first, my bad. I didn't see the "Projects" tab for the repo so I thought it had to be enabled at the organization level. Next time I'll know.
