### ISSUE TITLE
turtlebot's not moving form the start pose when provided goal pose

### ISSUE THREAD

**Issue by shivaang12** [ros-planning/navigation2#1500]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```

```

#### Expected behavior
Should run towards goal pose
#### Actual behavior
[bt_navigator-7] [INFO] [1580954443.690200183] [bt_navigator]: Begin navigating from current location to (0.12, 0.50)
[controller_server-4] [INFO] [1580954443.755629504] [controller_server]: Received a goal, begin computing control effort.
[controller_server-4] [ERROR] [1580954443.763280965] [controller_server]: No valid trajectories out of 0! 
[controller_server-4] [WARN] [1580954443.767325770] [controller_server_rclcpp_node]: [follow_path] [ActionServer] Aborting handle.
[controller_server-4] [INFO] [1580954443.780334812] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[controller_server-4] [INFO] [1580954443.789625363] [local_costmap.local_costmap]: Received request to clear entirely the local_costmap
[planner_server-5] [INFO] [1580954443.791578541] [global_costmap.global_costmap]: Received request to clear entirely the global_costmap

#### Additional information

----

**Comment by shivaang12** [comment]
@SteveMacenski Do you know about this?

**Comment by SteveMacenski** [comment]
You didn't fill out any of the ticket. I can't really do or say anything with that.

I however was testing with stuff this morning, so my guess is its something with your setup.

**Comment by shivaang12** [comment]
It's working fine with my old repo.

**Comment by SteveMacenski** [comment]
Feel free to circle back when you have more information to share.

**Comment by shivaang12** [comment]
cool! If it's working for you then it's my system's fault. Thanks, I am closing the ticket then.
