### ISSUE TITLE
reduce time it takes to process NavigateToPose request

### ISSUE THREAD

**Issue by Jconn** [ros-planning/navigation2#1516]
merging in https://github.com/ros-planning/navigation2/pull/1515 adds another 200-300ms of latency to handling a NavigateToPose request, which is a lot. 

This comes from creating a new behavior tree every time a NavigateToPose request is accepted. That change is done to handle CoroActionNode's properly. But there should be a smarter way that doesn't take so much time.

**Comment by SteveMacenski** [comment]
Did you file a ticket with BehaviorTree.CPP on the reset?

**Comment by Jconn** [comment]
it is here https://github.com/BehaviorTree/BehaviorTree.CPP/issues/146

**Comment by SteveMacenski** [comment]
Awesome, thanks for linking it. 

Is this ticket something you have a a business reason to look into, or should I put this in the pool of tasks to try to find some interested parties to look at?

**Comment by Jconn** [comment]
I would put it in the pool - we aren't prioritizing performance issues yet

**Comment by SteveMacenski** [comment]
Ok, thanks for the update.

**Comment by facontidavide** [comment]
Hi,

I probably need to join this. I am sorry that my library is creating issues of this kind. I will try to dedicate time to this in the next days.

**Comment by SteveMacenski** [comment]
#1606 resolves
