### ISSUE TITLE
Can't run bt_navigator without specifying a ton of parameters

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1523]
See https://answers.ros.org/question/344030/nav2_bt_navigator-exception-in-callback/?answer=344120#post-id-344120

The OP is trying to ros2 run nav2_bt_navigator bt_navigator, but can't do it without specifying a long set of parameters, specifically naming all the libraries containing all the bt nodes that might be needed.

We should link in our bt nodes by default, or parse the XML and load any that are mentioned in the XML.

**Comment by SteveMacenski** [comment]
I think I actually removed that default library awhile back since it doesnt exist and therefore will always be wrong, which should help alleviate that issue in the future. 

Both of the suggestions would be beneficial.
