### ISSUE TITLE
Create Pluginlib plugins for AMCL sensor models

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#153]
to swap out uses of different models. Examples in laser, create plugins for the beam, MLE, and MLE prob models so you can swap at run time, but then also have the infrastructure to swap out at run time with any customly chosen one implemented.

Same with the odometry models for corrected-* and diff, omni

**Comment by mjeronimo** [comment]
I'd rather see us use a separate sensors package. That is, utilize ROS nodes for the various sensors instead of C++ plug-ins.

**Comment by SteveMacenski** [comment]
AMCL is generally an embedded process for many users, it would allow people to shoot themselves in the foot by writing some of these things in python. I'm not too familiar with the overhead and delays associated with DDS. Would the transport time and decode be essentially analog to a shared pointer when in the same process?

**Comment by SteveMacenski** [comment]
Sounds like the thought is to include in robot header not as plugins
