### ISSUE TITLE
Turtlebot world doesn't show up when running tb3_simulation_launch.py

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#1557]
## Bug report

When running the nav2 stack through the provided tb3_simulation_launch.py launch file, Gazebo starts and the turtlebot shows up, but not the turtlebot world

#### Steps to reproduce issue
```
> source navigation2_ws/install/setup.bash
> ros2 launch nav2_bringup tb3_simulation_launch.py
```

#### Expected behavior

![image](https://user-images.githubusercontent.com/39749483/75075196-1f0bcb80-54b2-11ea-806f-f4e22775de9e.png)

#### Actual behavior

![image](https://user-images.githubusercontent.com/39749483/75075119-fc79b280-54b1-11ea-9a7a-9f6ed66f5351.png)

#### Additional information

I'm just submitting the issue for documentation purposes, in cas someone else runs into this.

This problem is caused by failing to add the `turtlebot3_simulations/turtlebot3_gazebo/models/` directory to the gazebo model path. The fix is to run

```
export GAZEBO_MODEL_PATH=~/<path to turtlebot3_ws>/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models/
```

before running the launch file

**Comment by crdelsey** [comment]
I'm just submitting this issue because several of us were running into the problem. The fix at the end of the description above. We can close this as soon as a few people have had a chance to see this.

**Comment by SteveMacenski** [comment]
It appears I have it in my bashrc

```
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/s.macenski/Documents/turtlebot3_ws/src/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models
```

Good thinking past me.
