### ISSUE TITLE
Utilities package placeholder may need some organization

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#157]
As it exists today, it is a set of libraries from a number of other packages placed into it. The encapsulation of these ideas in packages seems not great given that right now all of the libraries have only a single user. I would think we'd want to keep them all together until a time when there is a use-case in development requiring code from a package to be more generally accessible. 

In this case, I think it should then be its own package, perhaps outside this repository, containing a specialized library for  general use.

A good example would be SBA <--> slam karto. They could be packaged together (though folks use it in a number of places) and exists as a separate package. Same with voxel grid <--> voxel layer. If its good for multiple purposes, perhaps it would be best to have them as separately maintained packages. 

The pf could be ros_localization_pf or something similar, etc

**Comment by mjeronimo** [comment]
@SteveMacenski Yes, I agree that they should eventually be separate packages. I see factoring and gathering the functionality here as an intermediate step to that goal. I'd like to rely on external packages for common functionality such as a particle filter, kalman filtering, etc. That being said, we may still have something left like some general utility functions that are used across packages.

**Comment by SteveMacenski** [comment]
I think leaving as is for now until at least Crystal is fine. This discussion can be tabled until after an MVP exists and how to best encapsulate the concepts that at that point still make the most sense. We may find some need to be put back, others added, or enough development to justify an external package.

**Comment by SteveMacenski** [comment]
I think now that the AMCL things are gone, its small enough its not worth addressing. I'd like to move the image loader over to it but that's not necessary
