### ISSUE TITLE
Discussion: enable topological navigation?

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#1590]
I'd like to request your input on whether nav2 should support topological navigation. 

Benefits:
- Might alleviate some issues from [constant replanning and update](https://github.com/ros-planning/navigation2/issues/1570)
- ...

**Comment by SteveMacenski** [comment]
> Use a sequence of waypoints (route) to represent the high-level global path

That's how a path is defined already. I don't understand

**Comment by orduno** [comment]
I've updated the issue description.

**Comment by SteveMacenski** [comment]
Can you define what you mean they that? Topographical navigation will mean different things to different people (planning vs perception in particular). 

I think a couple examples would help.

**Comment by fmrico** [comment]
Yes, I agree with @SteveMacenski . IMHO, it is more related to [planning](https://www.semanticscholar.org/paper/Planning-Topological-Navigation-for-Complex-Indoor-Mart%C3%ADn-Gines/398748d68d530db5caa954840842016c9d1813a3), and I think this is an application of navigation, not part of general navigation software.

**Comment by orduno** [comment]
[Here's](https://www.cpp.edu/~ftang/courses/CS521/notes/topological%20path%20planning.pdf) the interpretation I was considering.

**Comment by SteveMacenski** [comment]
This seems related (or the same?) as this ticket https://github.com/ros-planning/navigation2/issues/1595. 

I think what you're describing by that is using a sparse graph for planning (which could be computed by a PRM) where the nodes may or may not represent an area or location of interest. 

Are you referencing the sparse graph of landmarks in your question or are you describing the ability to say "navigate to the kitchen" based on semantic labeling of information? I suppose I think of these are 2 different problems. A sparse graph representation makes it so you can only navigate through topological graph points to get to your semantic label of interest, while navigating to that semantic label of interest just implies knowledge of the topology of the space.

**Comment by SteveMacenski** [comment]
@shrijitsingh99 related ticket

**Comment by SteveMacenski** [comment]
I think we're getting good discussions on including this type of behavior in the other #1595 ticket. Closing in favor of it.
