### ISSUE TITLE
Segfault when running map_saver cli with one param

### ISSUE THREAD

**Issue by wizkon** [ros-planning/navigation2#1592]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - from source 

#### Steps to reproduce issue
$ ./map_saver --fmt
$ ./map_saver --free

#### Expected behavior
Normally process ignoring the param as the log description. 

#### Actual behavior
[WARN] [map_saver_cli]: Argument ignored: --fmt should be followed by a value.
**Segmentation fault (core dumped)**

**Comment by SteveMacenski** [comment]
You didnt properly define a value as the error says. 

Feel free to submit a PR to fix it. It looks like the for loop in the arg parsing needs to exit failure on a false argument.
