### ISSUE TITLE
Paper of Navigation2

### ISSUE THREAD

**Issue by ninamwa** [ros-planning/navigation2#1596]
Hi. I have noticed that other ROS packages, like Cartographer, has a paper which should be cited, if Cartographer is used for research. Does it exist something similar for Navigation2? If not, what is the best place to cite, this github repo? 

Best regards

**Comment by SteveMacenski** [comment]
It's currently in peer review, so nothing to share at the moment. I suppose cite the repo -- I'm a pseudo-academic and I don't know off hand the best way to handle that. 

We'd prefer PRs to citations :wink:.
