### ISSUE TITLE
Documentation error: missing tb3_simulation_launch.py in Dashing

### ISSUE THREAD

**Issue by facontidavide** [ros-planning/navigation2#1607]
I am not sure if this is the right place to report this, but I am not able to follow the steps described here with Dashing installed:

https://ros-planning.github.io/navigation2/getting_started/index.html

Apparently, the release of Dashing of **nav2_bringup** does not contain the file  **tb3_simulation_launch.py**.

https://github.com/ros-planning/navigation2/tree/dashing-devel/nav2_bringup

**Comment by SteveMacenski** [comment]
The dashing eq is nav2_simulation_launch.py

I’ll update the docs to reflect that this is from eloquent and newer, thanks for the report. I think we need to overall make the docs consistent with Foxy with that release pending.
