### ISSUE TITLE
[docs] Turtlebot3 for eloquent

### ISSUE THREAD

**Issue by mohamedsayed18** [ros-planning/navigation2#1618]
#### Operating System:
* Ubuntu 18.04
* ROS_distro: eloquent

#### Steps to reproduce issue
 I'm trying to run this command ```sudo apt install ros-eloquent-turtlebot3* ```

#### Output
```
E: Unable to locate package ros-eloquent-turtlebot3*
E: Couldn't find any package by glob 'ros-eloquent-turtlebot3*'
E: Couldn't find any package by regex 'ros-eloquent-turtlebot3*'
```

**Comment by SteveMacenski** [comment]
Please file a ticket with the turtlebot folks: https://github.com/ROBOTIS-GIT/turtlebot3

In the mean time, you can simply install from source.
