### ISSUE TITLE
Enable github apps for ros-planning

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#162]
@tfoote - we'd like to enable Travis CI for this repo, but we can't do that unless github apps are enabled at the organization level. I'm not an organization admin, so I can't enable the apps myself. Can you or another admin please do that for us? 

If you do that, I should be able to add the Travis CI myself.

**Comment by tfoote** [comment]
Travis CI seems to use a webhook not a Github App, but I think it's setup successfully now. #168 appears to be triggered correctly

![image](https://user-images.githubusercontent.com/447804/46978406-b9206000-d083-11e8-9476-81e6e93fef9d.png)

I manually triggered a job too: https://travis-ci.org/ros-planning/navigation2
