### ISSUE TITLE
Robot class TODO list

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#163]
In Robot class, getCurrentVelocity method gets odometry msg which contains both twist and pose. getCurrentPose method gets pose msg which is estimated from localization module. To make this less confusing, rename the getCurrentVelocity method to getOdometry and also rename the getCurrentPose to getCurrentEstimatedPose.

Also, the following methods needs to be implemented in Robot class:
TODO(mhpanah):
-    getFootPrint()
-     robot types and SN or ID
-     Add unit and integration test
-     Be able to configure which topic name to subscribe to
-     Topic names for pose and odom should should be confifured with parameters
-     re-enable model_.getName() from getRobotName()

**Comment by SteveMacenski** [comment]
This class also needs timeouts, I'm looking through it for another ticket and once you recieve poses you store and then dish out after an initialization bool is set. There should be a timeout on the info in case something happens and info stops publishing you can produce a warning that you can't transform. I think TF should be involved here for this reason.

**Comment by mhpanah** [comment]
@SteveMacenski That's a good point, I agree. Initially, I was thinking to have the client to check the timestamp to see if the latest info is useful. However, it's safer to handle it in robot class in case the user is not checking the timestamp.  If the latest info is not within a pre-defined threshold the robot class can throw a warning and also provide the latest info that it has.

**Comment by mkhansen-intel** [comment]
@mhpanah - is this done?

**Comment by crdelsey** [comment]
@mkhansen-intel  No. Not done yet

**Comment by mhpanah** [comment]
> @mkhansen-intel No. Not done yet

We should all brainstorm to see what functionalities we need in robot class.  It's a low priority at the moment.
