### ISSUE TITLE
Footprint scaling in DWB

### ISSUE THREAD

**Issue by shrijitsingh99** [ros-planning/navigation2#1665]
#### Feature description
Add footprint scaling based on speed to DWB planner. This can be useful to ensure that the robot drives at slower speeds in narrow passages.

#### Implementation considerations
The parameters `scaling_speed` and `max_scaling_factor` can be implemented similar to DWA. The scaling can be done inside `ObstacleFootprintCritic`.

**Comment by SteveMacenski** [comment]
Closing for now until there's need for it
