### ISSUE TITLE
Deprecate use of geometry_msgs/PoseArray for particle cloud

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1679]
Per https://github.com/ros-planning/navigation2/pull/1677 we've updated the particle filter type. We've kept the original PoseArray being published for visualization in RVIZ and giving folks an opportunity to migrate more easily over the duration of Foxy. After Foxy, however, I would like to deprecate this to have only 1 message type publishing the particles. 

This should be done after Foxy release and a new Rviz2 plugin has been implemented to replace (ref https://github.com/ros-planning/navigation2/issues/1678) Once rviz2 plugin is in rviz2 and not in nav2, we should update the default rviz profiles. 

Reassess at the end of 2020.

**Comment by abhishek47kashyap** [comment]
Working on this, hopefully should be done by next weekend (03/21)
