### ISSUE TITLE
Revert temporary workaround in CI once libgazebo11 is released

### ISSUE THREAD

**Issue by ruffsl** [ros-planning/navigation2#1687]
Revert relevant commits from https://github.com/ros-planning/navigation2/pull/1684 once libgazebo11 is released. I.e once these are resolved:

- [x] https://github.com/ros-infrastructure/reprepro-updater/pull/75
- [x] https://github.com/ros/rosdistro/pull/24646
- [ ] https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1093

**Comment by SteveMacenski** [comment]
Thanks for looking into this.
