### ISSUE TITLE
Refactor laserReceived method of AMCL

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#169]
[WIP] This method is very long and it can possibly be refactored into several descriptive functions to improve code readability.

**Comment by mhpanah** [comment]
PR #310 is addressing this.

**Comment by crdelsey** [comment]
@mhpanah Can we close this now?

**Comment by mkhansen-intel** [comment]
@mhpanah - do we want to get this in to the Dashing release? If so, let's get the PR re-opened and merged.

**Comment by mhpanah** [comment]
> @mhpanah - do we want to get this in to the Dashing release? If so, let's get the PR re-opened and merged.

Will re-base and re-open the PR.
