### ISSUE TITLE
Add BT nodes to adjust replanning rate according to speed

### ISSUE THREAD

**Issue by naiveHobo** [ros-planning/navigation2#1740]
#### Feature description

A ```SpeedController``` node (analog to ```RateController``` and ```DistanceController```) should be added which would allow adjusting the replanning rate based on the current speed. ```RateController``` and ```DistanceController``` nodes have some drawbacks when used individually (#1701). Speed based rate of replanning seems like the natural solution to these drawbacks. Also makes for a good option for default behavior tree.

#### Implementation considerations

The ```SpeedController``` node can be implemented as an extension to ```RateController``` where the rate is scaled according to the current speed.
- By setting limits on the rate, it ensures the replanning happens even if the robot is not moving, offering a solution for the drawback of the ```DistanceController```.
- When the robot is moving at high speeds, the rate is increased accordingly and replanning is done more frequently, thus retaining the benefit of using the ```DistanceController```.
- When at a constant speed, the ```SpeedController``` boils down to a ```RateController```.

**Comment by naiveHobo** [comment]
I have an initial implementation for the node proposed. Here's how the replanning rate scales according to the current speed:

![speed](https://user-images.githubusercontent.com/22402940/81481392-7289ec00-924d-11ea-86a8-6faf6fb9c7a4.png)

The robot is stuck towards the end so the rate of replanning in that case is held at 0.1hz.

**Comment by SteveMacenski** [comment]
Can you link a PR to this?

**Comment by naiveHobo** [comment]
Yup, the scales can be set as node parameters. The replanning rate is in the range [0.1, 1.0] hz scaled to according to speed in the range [0, 0.25] m/s.
