### ISSUE TITLE
Create READMEs for key system components

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#176]
This is a meta-ticket for tracking the creation of README files for each component.

- [x] System overview with comparison to Move Base

- [x] AMCL / Localization

- [x] Map Server 

- [x] Costmaps

- [x] Mission Execution

- [x] Navigation

- [x] Global Planner

- [x] Local Planner

**Comment by mkhansen-intel** [comment]
Mine is in PR #182

**Comment by mkhansen-intel** [comment]
Also #195 for costmap_2d

**Comment by orduno** [comment]
Global Planner (Dijkstra Planner) is #198

**Comment by mkhansen-intel** [comment]
Leaving open to add BT Navigator README

**Comment by mkhansen-intel** [comment]
Can we get these README updates before Dashing release?

**Comment by SteveMacenski** [comment]
@mkhansen-intel will do. These are pretty easy ones. PR sometime this week.
