### ISSUE TITLE
Potentially unused code in twirlling.cpp

### ISSUE THREAD

**Issue by Marwan99** [ros-planning/navigation2#1766]
There is potentially a minor bug / unused code in the twirling dwb critic with the scale parameter. 

https://github.com/ros-planning/navigation2/blob/7c0ac74514506591c0d508a6bc10e42d1d67162f/nav2_dwb_controller/dwb_critics/src/twirling.cpp#L42-L44

The condition in the code above will always be false since the parameter would have been already declared in:https://github.com/ros-planning/navigation2/blob/7c0ac74514506591c0d508a6bc10e42d1d67162f/nav2_dwb_controller/dwb_core/include/dwb_core/trajectory_critic.hpp#L104-L108

Therefore the twirling parameter `scale` will always be 1. 

Is the intention for the default twirling parameter `scale`  to be 0 or 1?

**Comment by SteveMacenski** [comment]
Hi, filed a ticket in general DWB https://github.com/locusrobotics/robot_navigation/issues/57

You would be correct, the code in `twirling.cpp` can be removed, please submit a PR. I think it intent from ROS1 was that if the parameter wasn't given in a file to simply turn it off, but that didn't quite follow in the logic. Or potentially it was an artifact from early testing / tests that needed to create an implementation prior to its inclusion as a plugin.
