### ISSUE TITLE
Replacement for Dynamic Reconfigure and Parameter Server

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#177]
Prevalent throughout the navstack are usages of dynamic reconfigure servers & callbacks on parameter events. Since dynamic reconfigure is not supported in ROS2, we should aim to replace it with comparable functionality using ROS2 supported node and parameter interfaces. 

Notably, dynamic reconfigure features:
- code generation from cfg file
- initializing parameters via cfg file & callback 
- type & upper/lower bound validation
- parameter server event callback registration
- direct access to dynamic parameters via DynamicConfig object

Another concern is regarding the difference in parameter servers living on the node. In ROS2, nodes are clients unto their own hosted parameters and can optionally create a parameter client for other nodes. As opposed to a single parameter server, this motivates us to decide whether to create a "parameter server-like" node to house all parameters in the navstack or to host parameters on the appropriate nodes and ensure all clients to those nodes' parameters are in sync.

**Comment by mkhansen-intel** [comment]
Closed in PR #196
