### ISSUE TITLE
Add New Mapping Interface and Environmental Model

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#18]
Support an extensible framework of map representations via a Mapping Interface and incorporate relevant static, dynamic, object, and semantic map data into an Environmental Model to be used by map dependent algorithms. 

First aim is to support & refactor grid-based map representations such as [grid_map](https://github.com/ANYbotics/grid_map), [occupancy grids](http://docs.ros.org/api/nav_msgs/html/msg/OccupancyGrid.html), and [costmap_2d](http://wiki.ros.org/costmap_2d) with further aim to support interface for other tree/node-based representations such as [octomap](https://github.com/OctoMap/octomap).

**Comment by jbvo** [comment]
Something similar to this?
https://github.com/tue-robotics/ed

**Comment by bpwilcox** [comment]
> An environmental model similar to this?
> https://github.com/tue-robotics/ed

I did take a look at that repo. I think there are some interesting ideas to build from, though for the time being, we're going to focus on grid-based representations before we incorporate some of the more abstract object-based representations. An initial milestone for now would be to seamlessly integrate  grid_map, occupancy grid, costmap_2d, and perhaps octomap into an environmental model which can support these types and provide useful contextual/semantic information about the current environment. We're currently using the "layer" concept, similar in ways to costmap_2d. This would then be the provider for localization, planning, and control.

**Comment by mkhansen-intel** [comment]
I think this can be closed now as the environmental model (aka World Model) is being covered by #565
