### ISSUE TITLE
[nav2_map_server] Any reason for using a custom find*.cmake instead of the system one

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#1803]
nav2_map_server package uses a custom `find*.cmake` 
https://github.com/ros-planning/navigation2/blob/master/nav2_map_server/cmake_modules/FindGRAPHICSMAGICKCPP.cmake
Is it still needed ?

**Comment by SteveMacenski** [comment]
@rotu any input?

**Comment by ShivamPR21** [comment]
@doisyg hope this link will help [https://stackoverflow.com/a/23838081](either try to find pkgConfig.cmake or try to find it in default paths of your system)

**Comment by rotu** [comment]
I don't know what alternative you mean in the title. I wasn't able to find a CMake package for GraphicsMagick at the time I developed this, and if I did, I would have preferred to use that.

**Comment by SteveMacenski** [comment]
There you have it @doisyg. If there's another option, we'd be open to hearing about it

**Comment by SteveMacenski** [comment]
@doisyg have you found an alternative we should consider?

**Comment by doisyg** [comment]
Not 100% sure but I will try to PR next week or close this otherwise

**Comment by doisyg** [comment]
Sorry, I confused GraphicsMagick and ImageMagick which have some header files in common (i did a non trinary implementation of the map saver a couples of years ago with ImageMagick)
