### ISSUE TITLE
Voxel and Obstacle layers support minimum range parameter

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1809]
There is a maximum raytracing range for clearing, but there's no minimum parameter in case there's a minimum Z that's quite large. We don't want the robot removing real obstacles because of bogus measurements. 

[STVL](https://github.com/SteveMacenski/spatio_temporal_voxel_layer) I take care of this with a parameter named `min_z`. 

Requested: https://answers.ros.org/question/355150/obstacles-in-sensor-deadzone/

**Comment by shantanuwadnerkar** [comment]
Will be working on this

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation/pull/594

Starting point potentially from ROS1

**Comment by danieljeswin** [comment]
Will be working on this. Hope to have it done in 2-3 weeks
