### ISSUE TITLE
I can not open in Groot this xml because some tag are not defined in nav2_behavior_tree/nav2_tree_nodes.xml

### ISSUE THREAD

**Issue by olmerg** [ros-planning/navigation2#1838]
after install https://github.com/BehaviorTree/Groot I load the configuration file but some behacoir_tree did not open.

https://github.com/ros-planning/navigation2/blob/c33cc89d604232fdf87ff813fa24c76029b265a7/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml#L22

**Comment by SteveMacenski** [comment]
See readme https://github.com/ros-planning/navigation2/blob/master/nav2_behavior_tree/groot_instructions.md

**Comment by SteveMacenski** [comment]
@gramss a good example of need for BT docs on website!

**Comment by olmerg** [comment]
thanks, I follow those instructions and some XMLs load, but the file navigate_w_replanning_and_recovery.xml did not open.
