### ISSUE TITLE
Define guidelines for labeling git issues

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#184]
*What rules are we following when labeling an issue on git?*

Currently, we are adding a label of the corresponding package e.g. `nav2_<something>` followed by one of these: `enhancement, task, bug, help wanted`, etc. In addition, we haven't provided clear definitions to these.

I suggest each issue should have 4 labels corresponding to: `<Priority> <Functional Area> <Type>`
We can also have an optional one: `<Other>`

Here are some options I can think of for each group (trying to keep it simple and useful).

Group | Options
------- | ----------
Priority | 0 - critical, 1 - high, 2 -medium, 3 - low
Functional Area | nav2_<something>, architecture, CI, project management, etc
Type | bug, task, feature, maintenance, documentation, idea, help wanted, question

As an example, this issue would have the following labels:

**Define guidelines for labeling git issue** `|priority: high||area: project management||type: question|`

**Comment by mkhansen-intel** [comment]
In order for us to move completely off of our internal tools, management needed a way to track our work in Github issues and map them back to their internal stories and tasks. So we agreed that (internal) story = Github enhancement, (Internal) bug = Github bug (obviously) and (internal) task = Github task. So I’ve been triaging things into those 3 types. In your case what you listed as “maintenance” and “documentation” would just be generic task types, but the functional areas could be documentation for example.

Also, I'm OK with the Status if we can automate it, but not if we have to manually change them. That's too difficult and we won't stay disciplined enough (just being realistic) to keep it updated.
