### ISSUE TITLE
Add nav2_system_test for clearing costmaps

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#1846]
This would have shown us very quickly the regression in Fast_RTPS like in #1772 if we had some service test coverage. We also have action-based recovery tests in the `recoveries/` directory, I think we need to make a system test for clearing costmaps. This should be relatively simple:

- Create a costmap object 
- Create a test to call the clear service based on it
- test that it was cleared introspecting the object. 

The BT node unit tests test that the BT node works and the costmap unit tests shows that the clearing works, we need this to just close the loop that the intermediate process from the BT to the object works.

**Comment by tonynajjar** [comment]
As discussed on Slack, I'll take this

**Comment by SteveMacenski** [comment]
@tonynajjar any updates?

**Comment by tonynajjar** [comment]
Sorry for not updating earlier. I must admit, I gave it a first try and it turned out to require more prior knowledge than I imagined. I'm starting my vacation from my job today so will try to get back on it.

**Comment by tonynajjar** [comment]
Can you clarify what I need to test exactly.

I see the test test_clear_costmap_service.cpp which in fact tests that the BT node works but I don't see a costmap unit test where the actual clearing behaviour is tested. Is that what I should be testing, with no involvement of the BT?

**Comment by SteveMacenski** [comment]
Yes, exactly. We're looking to have a costmap up and then test that we can call those services and they have the expected results, shouldn't need a BT at all

**Comment by tonynajjar** [comment]
I've spent quite some time on that but unfortunately I have no good results. There are still some things I need to learn to be able to troubleshoot my blockers and now vacation is over so I have less time. Sorry but will have to leave this ticket.

**Comment by SteveMacenski** [comment]
Ok, thanks for letting us know!

**Comment by SteveMacenski** [comment]
Closing- this belongs in the larger testing discussion and no longer requires unique attention
