### ISSUE TITLE
movement_time_allowance has ending underscore.

### ISSUE THREAD

**Issue by tgreier** [ros-planning/navigation2#1875]
https://github.com/ros-planning/navigation2/blob/2b073964f166f00b0ed29c04bbcede3b278135b7/nav2_controller/src/progress_checker.cpp#L37

**Comment by SteveMacenski** [comment]
@tgreier this was fixed in foxy / master https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_controller/src/progress_checker.cpp#L37. We cannot backport that to eloquent due to API compatibility changes.
