### ISSUE TITLE
Take into account the orientation of the robot in the odom frame when performing the backup recovery 

### ISSUE THREAD

**Issue by Michael-Equi** [ros-planning/navigation2#1878]
# Feature request

#### Feature description
The existing implementation of the backup recovery uses a prediction step to make sure its actions wont cause a future collision however it only predicts movement in the x-axis of the odometry reference frame which ignores the fact that the robot may be at a different orientation such that moving in the x-axis of the odometry frame is not actually representative of the backward movement.

https://github.com/ros-planning/navigation2/blob/master/nav2_recoveries/plugins/back_up.cpp

**Comment by SteveMacenski** [comment]
Wait a minute... I'm pretty sure I filed and fixed that issue a couple years ago... did someone's merge conflict wipe that out? Ugh. Yeah, that appears to be an issue again.
