### ISSUE TITLE
Multiple definition error if tf_help.hpp is included in more than one source file.

### ISSUE THREAD

**Issue by ijsmallman** [ros-planning/navigation2#1879]
[https://github.com/ros-planning/navigation2/blob/master/nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/tf_help.hpp](https://github.com/ros-planning/navigation2/blob/master/nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/tf_help.hpp)

Multiple definition compilation error for `transformPose` if `tf_help.hpp` is included in more than one place. I found this bug when I tried to write two controller plugin options that each had `#include "nav_2d_utils/tf_help.hpp` in their header files (as done in the dwb controller plugin).

transformPose fuction definitions should be defined in a separate source file and only declared in tf_help.hpp

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- ROS2 Version:
  - Eloquent (but this bug will be in all ros2 variants)
- Version or commit hash:
  - 9f1d8a123dac4cc7407650fbf0b906560b7b2ed2
- DDS implementation:
  - not relevant

**Comment by SteveMacenski** [comment]
@ijsmallman please properly fill in the issue template & provide specific links about what you're referencing. We're not going to dig through the entire source tree to guess about what you're talking about.

**Comment by ijsmallman** [comment]
What issue template?

**Comment by SteveMacenski** [comment]
The one that you deleted when you filed this ticket. https://github.com/ros-planning/navigation2/issues/new

**Comment by ijsmallman** [comment]
It's a pretty straightforward fix - put function definitions in a separate cpp file. I can file a pull request when i get back from my break.

**Comment by SteveMacenski** [comment]
OK - sounds good

**Comment by SteveMacenski** [comment]
Any updates @ijsmallman

**Comment by ijsmallman** [comment]
I'm on holiday this week, I'll update on Monday
