### ISSUE TITLE
Navigation2 doesn't function well on Celeron

### ISSUE THREAD

**Issue by jeremylu0601** [ros-planning/navigation2#1883]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- ROS2 Version:
  - Foxy binaries 
- Version or commit hash:
  - foxy-devel
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
Use Celeron G3900TE to run Navigation2

#### Actual behavior
    [ERROR] [tf_help]: Transform data too old when converting from odom to map
#### Additional information
After I switched to i5-6500TE, Navigation2 functioned well and no error message popped out. 

----

**Comment by SteveMacenski** [comment]
Please ask on ros answers / soec out your machine for the resources you need

**Comment by jeremylu0601** [comment]
Got it.
Thanks for your response.
