### ISSUE TITLE
Add parameter for map topic in AMCL

### ISSUE THREAD

**Issue by Michael-Equi** [ros-planning/navigation2#1905]
#### Feature description
The AMCL node should have a parameter `map_topic` to configure the map topic similar to the parameter for the costmap layer which would allow for easy configuration of the node's map input without using remapping. 

#### Implementation considerations
Documentation would need to be added in the following locations:
https://navigation.ros.org/configuration/packages/configuring-amcl.html#parameters
https://github.com/ros-planning/navigation2/blob/master/doc/parameters/param_list.md

**Comment by SteveMacenski** [comment]
Didn't you submit a PR for this? I don't seem to be able to find it. 

Either way, I'd merge a PR with that

**Comment by Michael-Equi** [comment]
I made a PR for the sensor_topic not the map_topic

**Comment by SteveMacenski** [comment]
Got it. I'd merge that PR, also remember you have `remapping` you can use to remap the "map" topic to something else.

**Comment by Michael-Equi** [comment]
Just makes things a bit cleaner having it all in one configuration file.
