### ISSUE TITLE
Multiple nodes with same name

### ISSUE THREAD

**Issue by mikeferguson** [ros-planning/navigation2#1937]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy Binaries
- Version or commit hash:
  - 0.4.1-1

#### Steps to reproduce issue
Run the example navigation system, then run ros2 node list
```
ubr@ubr1:~$ ros2 node list
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/base_laser_node
/bt_navigator
/bt_navigator_rclcpp_node
/controller_reset
/controller_server
/controller_server_rclcpp_node
/global_costmap/global_costmap
/global_costmap/global_costmap_rclcpp_node
/global_costmap_client
/head_camera/container
/head_camera/depth_rectify
/head_camera/depth_registered_hw_metric_rect
/head_camera/driver
/head_camera/points_xyzrgb
/head_camera/rgb_rectify
/joy
/launch_ros_160677
/lifecycle_manager_navigation
/lifecycle_manager_navigation_service_client
/local_costmap/local_costmap
/local_costmap/local_costmap_rclcpp_node
/local_costmap_client
/planner_server
/planner_server_rclcpp_node
/recoveries_server
/recoveries_server_rclcpp_node
/robot_state_publisher
/teleop
/transform_listener_impl_5567f9d57e70
/transform_listener_impl_558af7fba4b0
/transform_listener_impl_558af80be6e0
/transform_listener_impl_564387f89a10
/transform_listener_impl_56462fdde380
/ubr_driver
/waypoint_follower
/waypoint_follower
```

#### Expected behavior
There would be only one waypoint_follower node - or maybe a waypoint_follower and a waypoint_follower_rclcpp_node

#### Actual behavior
There are two waypoint_followers.

#### Additional information
I looked through the code, but I'm not sure where the second node is getting created

**Comment by SteveMacenski** [comment]
Can you un-redact the nav2 nodes also you have up? Or are you just launching the waypoint follower node in this context?

**Comment by mikeferguson** [comment]
> Can you un-redact the nav2 nodes also you have up? Might help if I can see what else has duplicates, if any. Or are you just launching the waypoint follower node in this context?

Updated - I was just trying to reduce the list - this is basically running https://github.com/mikeferguson/ubr_reloaded/blob/ros2/ubr1_navigation/launch/navigation.launch.py and https://github.com/mikeferguson/ubr_reloaded/blob/ros2/ubr1_bringup/launch/robot.launch.py

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/1939 resolves

**Comment by SteveMacenski** [comment]
Thanks for  the report~
