### ISSUE TITLE
Waypoint Follower crashes when there are 0 waypoints

### ISSUE THREAD

**Issue by wilcobonestroo** [ros-planning/navigation2#1977]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04
- ROS2 Version: Foxy binary
- Version or commit hash: 0.4.3-1focal.20200826.191445
- DDS implementation: Fast-RTPS

#### Steps to reproduce issue

I followed the steps from the [Getting Started](https://navigation.ros.org/getting_started/index.html) page.
```
source /opt/ros/foxy/setup.bash
ros2 launch nav2_bringup tb3_simulation_launch.py
```

Then give the initial pose of the robot in Rviz.
Click on **Waypoint mode** in the Navigation 2 pane in Rviz
Click **Start Navigation** in the same window.

```
[rviz2-4] [INFO] [1599142019.529172333] [rviz2]: Sending a path of 0 waypoints:
[waypoint_follower-12] [INFO] [1599142019.530304491] [waypoint_follower]: Received follow waypoint request with 0 waypoints.
[ERROR] [waypoint_follower-12]: process has died [pid 12151, exit code -11, cmd '/opt/ros/foxy/lib/nav2_waypoint_follower/waypoint_follower --ros-args -r __node:=waypoint_follower --params-file /tmp/tmpnsrz8hdo -r /tf:=tf -r /tf_static:=tf_static'].
```

#### Expected behavior
Do nothing, as there are no waypoints given.

#### Actual behavior
Waypoint follower crashes

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/main/nav2_waypoint_follower/src/waypoint_follower.cpp#L126

It should be pretty easy to add a check for the number of goals in the array here. We do assume later in the code non-0 number of waypoints, but that could be gotten around by checking for the size early & terminating the action if no goals to visit.
