### ISSUE TITLE
TF_OLD_DATA warning is displayed.

### ISSUE THREAD

**Issue by hiroyuki-s1** [ros-planning/navigation2#2065]
TF_OLD_DATA warning is displayed.

Follow these steps to install navigation2 in the dashing environment and use.
https://navigation.ros.org/getting_started/index.html

I have tried running the simulation, but I get the following error.
Why?

And when I set up Navigaton2 Goal, it doesn't work.

"""
[rviz2-3] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-3]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[rviz2-3] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.23000 according to authority Authority undetectable
[rviz2-3] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-3]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] Detected jump back in time. Clearing TF buffer.[INFO] [global_costmap.global_costmap]: Timed out waiting for transform from base_link to map to become available, tf error: Could not find a connection between 'map' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after -14848.5 timeout was 1.
[amcl-6] Detected jump back in time. Clearing TF buffer.[INFO] [amcl_rclcpp_node]: [signalFailure] Drop message: frame 'base_scan' at time 14932.229 for reason(0)
[world_model-7] [INFO] [global_costmap.global_costmap_rclcpp_node]: [signalFailure] Drop message: frame 'base_scan' at time 14927.426 for reason(0)
[rviz2-3] [ERROR] [rviz2]: Lookup would require extrapolation into the future.  Requested time 14936.83000 but the latest data is at time 14936.77800, when looking up transform from frame [base_scan] to frame [map]
[recoveries_node-11] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.26400 according to authority Authority undetectable
[recoveries_node-11] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[recoveries_node-11]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[amcl-6] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.26400 according to authority Authority undetectable
[amcl-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[amcl-6]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.26400 according to authority Authority undetectable
[world_model-7] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[world_model-7]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[navfn_planner-9] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.26400 according to authority Authority undetectable
[navfn_planner-9] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[navfn_planner-9]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[navfn_planner-9] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_left_link at time 88.26400 according to authority Authority undetectable
[navfn_planner-9] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[navfn_planner-9]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[navfn_planner-9] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.26400 according to authority Authority undetectable
[navfn_planner-9] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[navfn_planner-9]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_left_link at time 88.26400 according to authority Authority undetectable
[world_model-7] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[world_model-7]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.26400 according to authority Authority undetectable
[world_model-7] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[world_model-7]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[recoveries_node-11] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_left_link at time 88.26400 according to authority Authority undetectable
[recoveries_node-11] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[recoveries_node-11]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[recoveries_node-11] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.26400 according to authority Authority undetectable
[recoveries_node-11] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[recoveries_node-11]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[amcl-6] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_left_link at time 88.26400 according to authority Authority undetectable
[amcl-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[amcl-6]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[amcl-6] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.26400 according to authority Authority undetectable
[amcl-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[amcl-6]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] [INFO] [global_costmap.global_costmap_rclcpp_node]: [signalFailure] Drop message: frame 'base_scan' at time 87.817 for reason(0)
[world_model-7] [INFO] [global_costmap.global_costmap_rclcpp_node]: [signalFailure] Drop message: frame 'base_scan' at time 88.217 for reason(0)
[world_model-7] [INFO] [global_costmap.global_costmap_rclcpp_node]: [signalFailure] Drop message: frame 'base_scan' at time 88.017 for reason(0)
[rviz2-3] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.26400 according to authority Authority undetectable
[rviz2-3] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-3]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[rviz2-3] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_left_link at time 88.26400 according to authority Authority undetectable
[rviz2-3] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-3]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[rviz2-3] Warning: TF_OLD_DATA ignoring data from the past for frame wheel_right_link at time 88.26400 according to authority Authority undetectable
[rviz2-3] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[rviz2-3]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[world_model-7] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.29800 according to authority Authority undetectable
[world_model-7] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[world_model-7]          at line 292 in /tmp/binarydeb/ros-dashing-tf2-0.11.6/src/buffer_core.cpp
[amcl-6] Warning: TF_OLD_DATA ignoring data from the past for frame base_footprint at time 88.29800 according to authority Authority undetectable
[amcl-6] Possible reasons are listed at http://wiki.ros.org/tf/Errors%20explained
[amcl-6]          at line 292 in /tmp/binar

"""

**Comment by SteveMacenski** [comment]
> world_model recoveries_node navfn_planner

Some of this looked fishy so I had to go back through the git logs. It looks like you're using an ancient version of navigation2 we do not offer support for. So much of the code has changed since then (like, really substantially) that I cannot reasonable back track that many massive changes to try to debug.
