### ISSUE TITLE
Add "nav2_" prefix to smac_planner

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2092]
Whoops, that was an oversight from my end. I wasn't  trying to make a statement by having it non-"nav2_" :smile:

**Comment by tonynajjar** [comment]
Can I take this? I'm looking for a simple first task to go over the contribution process once. This looks simple enough

**Comment by SteveMacenski** [comment]
Sure thing!

**Comment by SteveMacenski** [comment]
Thanks! Great starting ticket :-)
