### ISSUE TITLE
navigate_to_pose action is not preempted cleanly with different BT pending

### ISSUE THREAD

**Issue by tal-grossman** [ros-planning/navigation2#2095]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 20.04
- ROS2 Version:
  Foxy binaries
- Version or commit hash:
 0.4.3-1focal.20201103.171126
- DDS implementation:
Fast-RTPS

#### Steps to reproduce issue
Using CLI call /navigate_to_pose action with specific behvior tree for example: _"navigate_w_replanning_and_recovery.xml"_. goal pose does not matter as long as it is far enough to not complete immediately 
```
ros2 action send_goal /navigate_to_pose nav2_msgs/action/NavigateToPose '{behavior_tree: "FULL_PATH_TO/navigate_w_replanning_and_recovery.xml"}'
```
then, during the navigation in another terminal call for a for the same /navigate_to_pose action but with different BT, for example _"follow_point.xml"_
```
ros2 action send_goal /navigate_to_pose nav2_msgs/action/NavigateToPose '{behavior_tree: "FULL_PATH_TO/follow_point.xml"}'
```
#### Expected behavior
1. the previous action is preempted and all the action nodes from the previous BT are cancelled. 
2. the new BT  is loaded.
3. the new BT starts and executed cleanly
#### Actual behavior
1. the previous action is preempted with "Received goal preemption request" logged (aslo terminal showing it was ABORTED). but still nodes from previous BT are running.
2. the new BT is not loaded so the active BT is the previous one.
3. the new action starts but the old BT nodes are running - so in practice we have nodes running from 2 different actions. 
#### Additional information
If the plan is to have the bt_navigator as the main application server but with the option to preempt an active action so the pending one will take charge, it needs to have a smooth transition from one to another.

Another point to think about is if we have 2 application servers like [nav2_behavior_tree::BtActionServer PR](https://github.com/ros-planning/navigation2/pull/2010) suggesting. do we want to have them running in the same time? if not, it needs to be implemented as well.

**Comment by SteveMacenski** [comment]
#1971 covers, please search for existing tickets before opening your own
