### ISSUE TITLE
Port Costmaps to ROS2

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#21]

**Comment by mkhansen-intel** [comment]
As part of this work, the existing costmap placeholder code should either be removed or replaced. 
src/libs/nav2_util/src/costmap.cpp

**Comment by bpwilcox** [comment]
We can port in smaller chunks from the existing ROS1 costmap_2d code in #86

**Comment by SteveMacenski** [comment]
As part of this work, it might be good to keep in the back of your mind how you'd want to remove having 2 costmaps (one for controller another for planner) as that duplication of work accounts for a good amount of resource usage when using plugins for the 3D world.

**Comment by mjeronimo** [comment]
@SteveMacenski  Yes, definitely. We plan to factor out the duplication, were possible.

**Comment by mkhansen-intel** [comment]
Still need to port voxel layer (#193) and obstacle layer (#192), those are covered in their own issues, so closing this issue.
