### ISSUE TITLE
add smac planner to apt binaries

### ISSUE THREAD

**Issue by MoritzWillmann** [ros-planning/navigation2#2116]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy
- Version or commit hash:
  - ros-foxy-navigation2	0.4.3-1focal.20201104.092143

#### Steps to reproduce issue
```
sudo apt install ros-foxy-smac-planner
```
as in [nav2_smac_planner-->install](https://github.com/ros-planning/navigation2/tree/main/nav2_smac_planner#install)
#### Expected behavior
install smac planner
#### Actual behavior
E: Unable to locate package ros-foxy-smac-planner
#### Additional information
tried ros-foxy-nav2-smac-planner and similar, too. Also did apt search smac which didn't yield the expected package

**Comment by SteveMacenski** [comment]
It will be available in the next sync

**Comment by MoritzWillmann** [comment]
thanks!
