### ISSUE TITLE
[error] when run ros2 launch nav2_bringup tb3_simulation_launch.py, errors occur

### ISSUE THREAD

**Issue by JetBelson** [ros-planning/navigation2#2125]
## Bug report

**Required Info:**

- Operating System:
  -  macosbig sur->parallel desktop-> ubuntu-20.04.1-desktop-amd64
- ROS2 Version:
  -  ros2 foxy, Debian
- Version or commit hash:
  - 1. sudo apt install ros-<ros2-distro>-navigation2   2. sudo apt install ros-<ros2-distro>-nav2-bringup    3. follow official turtlebot3 installation guide (https://emanual.robotis.com/docs/en/platform/turtlebot3/ros2_setup/)
- DDS implementation:
  - 

#### Steps to reproduce issue
 source /opt/ros/<ros2-distro>/setup.bash
export TURTLEBOT3_MODEL=waffle
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/<ros2-distro>/share/turtlebot3_gazebo/models
ros2 launch nav2_bringup tb3_simulation_launch.py

```

```

#### Expected behavior
work as tutorial shows
#### Actual behavior
crash, rviz and gazebo do not response

[INFO] [launch]: All log files can be found below /home/zzj/.ros/log/2020-12-16-00-34-20-464761-ubuntu-2688
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [gzserver-1]: process started with pid [2693]
[INFO] [gzclient-2]: process started with pid [2695]
[INFO] [robot_state_publisher-3]: process started with pid [2697]
[INFO] [rviz2-4]: process started with pid [2699]
[INFO] [map_server-5]: process started with pid [2701]
[INFO] [amcl-6]: process started with pid [2703]
[INFO] [lifecycle_manager-7]: process started with pid [2705]
[INFO] [controller_server-8]: process started with pid [2707]
[INFO] [planner_server-9]: process started with pid [2709]
[INFO] [recoveries_server-10]: process started with pid [2711]
[INFO] [bt_navigator-11]: process started with pid [2713]
[INFO] [waypoint_follower-12]: process started with pid [2727]
[INFO] [lifecycle_manager-13]: process started with pid [2755]
[lifecycle_manager-7] [INFO] [1608050061.325737057] [lifecycle_manager_localization]: Creating
[robot_state_publisher-3] [WARN] [1608050061.382189164] [robot_state_publisher]: No robot_description parameter, but command-line argument available.  Assuming argument is name of URDF file.  This backwards compatibility fallback will be removed in the future.
[map_server-5] [INFO] [1608050061.406850868] [map_server]: 
[map_server-5] 	map_server lifecycle node launched. 
[map_server-5] 	Waiting on external lifecycle transitions to activate
[map_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-5] [INFO] [1608050061.409146710] [map_server]: Creating
[controller_server-8] [INFO] [1608050061.417495858] [controller_server]: 
[controller_server-8] 	controller_server lifecycle node launched. 
[controller_server-8] 	Waiting on external lifecycle transitions to activate
[controller_server-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[robot_state_publisher-3] Parsing robot urdf xml string.
[lifecycle_manager-7] [INFO] [1608050061.461041630] [lifecycle_manager_localization]: Creating and initializing lifecycle service clients
[robot_state_publisher-3] Link base_link had 7 children
[robot_state_publisher-3] Link camera_link had 2 children
[robot_state_publisher-3] Link camera_depth_frame had 1 children
[robot_state_publisher-3] Link camera_depth_optical_frame had 0 children
[robot_state_publisher-3] Link camera_rgb_frame had 1 children
[robot_state_publisher-3] Link camera_rgb_optical_frame had 0 children
[robot_state_publisher-3] Link caster_back_left_link had 0 children
[robot_state_publisher-3] Link caster_back_right_link had 0 children
[robot_state_publisher-3] Link imu_link had 0 children
[robot_state_publisher-3] Link base_scan had 0 children
[robot_state_publisher-3] Link wheel_left_link had 0 children
[robot_state_publisher-3] Link wheel_right_link had 0 children
[robot_state_publisher-3] [INFO] [1608050061.470566826] [robot_state_publisher]: got segment base_footprint
[robot_state_publisher-3] [INFO] [1608050061.475828243] [robot_state_publisher]: got segment base_link
[robot_state_publisher-3] [INFO] [1608050061.475837896] [robot_state_publisher]: got segment base_scan
[robot_state_publisher-3] [INFO] [1608050061.475844336] [robot_state_publisher]: got segment camera_depth_frame
[robot_state_publisher-3] [INFO] [1608050061.475850801] [robot_state_publisher]: got segment camera_depth_optical_frame
[robot_state_publisher-3] [INFO] [1608050061.475857595] [robot_state_publisher]: got segment camera_link
[robot_state_publisher-3] [INFO] [1608050061.475864008] [robot_state_publisher]: got segment camera_rgb_frame
[robot_state_publisher-3] [INFO] [1608050061.475870445] [robot_state_publisher]: got segment camera_rgb_optical_frame
[robot_state_publisher-3] [INFO] [1608050061.475876774] [robot_state_publisher]: got segment caster_back_left_link
[robot_state_publisher-3] [INFO] [1608050061.475883025] [robot_state_publisher]: got segment caster_back_right_link
[robot_state_publisher-3] [INFO] [1608050061.475963840] [robot_state_publisher]: got segment imu_link
[robot_state_publisher-3] [INFO] [1608050061.475971704] [robot_state_publisher]: got segment wheel_left_link
[robot_state_publisher-3] [INFO] [1608050061.475978095] [robot_state_publisher]: got segment wheel_right_link
[lifecycle_manager-7] [INFO] [1608050061.491903117] [lifecycle_manager_localization]: Starting managed nodes bringup...
[lifecycle_manager-7] [INFO] [1608050061.491948941] [lifecycle_manager_localization]: Configuring map_server
[map_server-5] [INFO] [1608050061.492284116] [map_server]: Configuring
[map_server-5] [INFO] [map_io]: Loading yaml file: /opt/ros/foxy/share/nav2_bringup/maps/turtlebot3_world.yaml
[map_server-5] [DEBUG] [map_io]: resolution: 0.05
[map_server-5] [DEBUG] [map_io]: origin[0]: -10
[map_server-5] [DEBUG] [map_io]: origin[1]: -10
[map_server-5] [DEBUG] [map_io]: origin[2]: 0
[map_server-5] [DEBUG] [map_io]: free_thresh: 0.196
[map_server-5] [DEBUG] [map_io]: occupied_thresh: 0.65
[map_server-5] [DEBUG] [map_io]: mode: trinary
[map_server-5] [DEBUG] [map_io]: negate: 0
[map_server-5] [INFO] [map_io]: Loading image_file: /opt/ros/foxy/share/nav2_bringup/maps/turtlebot3_world.pgm
[controller_server-8] [INFO] [1608050061.547182346] [controller_server]: Creating controller server
[amcl-6] [INFO] [1608050061.641094970] [amcl]: 
[amcl-6] 	amcl lifecycle node launched. 
[amcl-6] 	Waiting on external lifecycle transitions to activate
[amcl-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[amcl-6] [INFO] [1608050061.641303584] [amcl]: Creating
[map_server-5] [DEBUG] [map_io]: Read map /opt/ros/foxy/share/nav2_bringup/maps/turtlebot3_world.pgm: 384 X 384 map @ 0.05 m/cell
[waypoint_follower-12] [INFO] [1608050061.718731058] [waypoint_follower]: 
[waypoint_follower-12] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-12] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-12] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-12] [INFO] [1608050061.720307640] [waypoint_follower]: Creating
[planner_server-9] [INFO] [1608050061.812412899] [planner_server]: 
[planner_server-9] 	planner_server lifecycle node launched. 
[planner_server-9] 	Waiting on external lifecycle transitions to activate
[planner_server-9] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-9] [INFO] [1608050061.814677255] [planner_server]: Creating
[lifecycle_manager-13] [INFO] [1608050061.813813527] [lifecycle_manager_navigation]: Creating
[lifecycle_manager-7] [INFO] [1608050061.819266129] [lifecycle_manager_localization]: Configuring amcl
[amcl-6] [INFO] [1608050061.819556170] [amcl]: Configuring
[amcl-6] [INFO] [1608050061.819632642] [amcl]: initTransforms
[amcl-6] [INFO] [1608050061.825412783] [amcl]: initPubSub
[amcl-6] [INFO] [1608050061.830123144] [amcl]: Subscribed to map topic.
[controller_server-8] [INFO] [1608050061.833960393] [local_costmap.local_costmap]: 
[controller_server-8] 	local_costmap lifecycle node launched. 
[controller_server-8] 	Waiting on external lifecycle transitions to activate
[controller_server-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-8] [INFO] [1608050061.856762726] [local_costmap.local_costmap]: Creating Costmap
[bt_navigator-11] [INFO] [1608050061.897580094] [bt_navigator]: 
[bt_navigator-11] 	bt_navigator lifecycle node launched. 
[bt_navigator-11] 	Waiting on external lifecycle transitions to activate
[bt_navigator-11] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-11] [INFO] [1608050061.897702107] [bt_navigator]: Creating
[lifecycle_manager-7] [INFO] [1608050061.908409446] [lifecycle_manager_localization]: Activating map_server
[map_server-5] [INFO] [1608050061.908728644] [map_server]: Activating
[lifecycle_manager-7] [INFO] [1608050061.910351747] [lifecycle_manager_localization]: Activating amcl
[amcl-6] [INFO] [1608050061.912922190] [amcl]: Received a 384 X 384 map @ 0.050 m/pix
[recoveries_server-10] [INFO] [1608050061.916444460] [recoveries_server]: 
[recoveries_server-10] 	recoveries_server lifecycle node launched. 
[recoveries_server-10] 	Waiting on external lifecycle transitions to activate
[recoveries_server-10] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-13] [INFO] [1608050062.016722875] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[amcl-6] [INFO] [1608050062.035442098] [amcl]: Activating
[amcl-6] [WARN] [1608050062.037399612] [amcl]: Publishing the particle cloud as geometry_msgs/PoseArray msg is deprecated, will be published as nav2_msgs/ParticleCloud in the future
[lifecycle_manager-7] [INFO] [1608050062.042728906] [lifecycle_manager_localization]: Managed nodes are active
[lifecycle_manager-13] [INFO] [1608050062.106405746] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-13] [INFO] [1608050062.106877750] [lifecycle_manager_navigation]: Configuring controller_server
[controller_server-8] [INFO] [1608050062.107640568] [controller_server]: Configuring controller interface
[controller_server-8] [INFO] [1608050062.107728560] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-8] [INFO] [1608050062.107745817] [local_costmap.local_costmap]: Configuring
[controller_server-8] [INFO] [1608050062.116989022] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-8] [INFO] [1608050062.163741902] [local_costmap.local_costmap]: Subscribed to Topics: scan
[controller_server-8] [INFO] [1608050062.210712032] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-8] [INFO] [1608050062.210768444] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-8] [INFO] [1608050062.217880628] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[planner_server-9] [INFO] [1608050062.238655882] [global_costmap.global_costmap]: 
[planner_server-9] 	global_costmap lifecycle node launched. 
[planner_server-9] 	Waiting on external lifecycle transitions to activate
[planner_server-9] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-9] [INFO] [1608050062.242028739] [global_costmap.global_costmap]: Creating Costmap
[controller_server-8] [INFO] [1608050062.311420091] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-8] [INFO] [1608050062.316854281] [controller_server]: Created goal_checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-8] [INFO] [1608050062.348818584] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-8] [INFO] [1608050062.353897843] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-8] [INFO] [1608050062.467035804] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-8] [INFO] [1608050062.470343201] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.471368148] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-8] [INFO] [1608050062.474272209] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.475006974] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-8] [INFO] [1608050062.475793531] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.477584569] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-8] [INFO] [1608050062.482344518] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.483422787] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-8] [INFO] [1608050062.486121644] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.486200725] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-8] [INFO] [1608050062.486343563] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.488598963] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-8] [INFO] [1608050062.490266776] [controller_server]: Critic plugin initialized
[controller_server-8] [INFO] [1608050062.490300680] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-13] [INFO] [1608050062.532554955] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-9] [INFO] [1608050062.532906638] [planner_server]: Configuring
[planner_server-9] [INFO] [1608050062.532937158] [global_costmap.global_costmap]: Configuring
[planner_server-9] [INFO] [1608050062.548409481] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-9] [INFO] [1608050062.561909540] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-9] [INFO] [1608050062.566416670] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-9] [INFO] [1608050062.566467798] [global_costmap.global_costmap]: Using plugin "obstacle_layer"
[planner_server-9] [INFO] [1608050062.570298813] [global_costmap.global_costmap]: Subscribed to Topics: scan
[planner_server-9] [INFO] [1608050062.577589767] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 384 X 384 at 0.050000 m/pix
[planner_server-9] [INFO] [1608050062.585597313] [global_costmap.global_costmap]: Initialized plugin "obstacle_layer"
[planner_server-9] [INFO] [1608050062.585640596] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-9] [INFO] [1608050062.594158313] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-9] [INFO] [1608050062.651752371] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-9] [INFO] [1608050062.651837708] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-9] [INFO] [1608050062.659137614] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-13] [INFO] [1608050062.685492287] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-10] [INFO] [1608050062.686293058] [recoveries_server]: Configuring
[recoveries_server-10] [INFO] [1608050062.713188676] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-10] [INFO] [1608050062.718567479] [recoveries_server]: Configuring spin
[recoveries_server-10] [INFO] [1608050062.752538426] [recoveries_server]: Creating recovery plugin backup of type nav2_recoveries/BackUp
[recoveries_server-10] [INFO] [1608050062.755844012] [recoveries_server]: Configuring backup
[recoveries_server-10] [INFO] [1608050062.789038929] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-10] [INFO] [1608050062.793103832] [recoveries_server]: Configuring wait
[lifecycle_manager-13] [INFO] [1608050062.827832063] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-11] [INFO] [1608050062.828956726] [bt_navigator]: Configuring
[bt_navigator-11] [INFO] [1608050063.046330765] [bt_navigator_rclcpp_node]: Waiting for "compute_path_to_pose" action server
[bt_navigator-11] [INFO] [1608050063.046656192] [bt_navigator_rclcpp_node]: "ComputePathToPose" BtActionNode initialized
[bt_navigator-11] [INFO] [1608050063.054493693] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-11] [INFO] [1608050063.054639657] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Context" BtServiceNode initialized
[bt_navigator-11] [INFO] [1608050063.076555974] [bt_navigator_rclcpp_node]: Waiting for "follow_path" action server
[bt_navigator-11] [INFO] [1608050063.076717412] [bt_navigator_rclcpp_node]: "FollowPath" BtActionNode initialized
[bt_navigator-11] [INFO] [1608050063.081837453] [bt_navigator_rclcpp_node]: Waiting for "local_costmap/clear_entirely_local_costmap" service
[bt_navigator-11] [INFO] [1608050063.082548818] [bt_navigator_rclcpp_node]: "ClearLocalCostmap-Context" BtServiceNode initialized
[bt_navigator-11] [INFO] [1608050063.087583650] [bt_navigator_rclcpp_node]: Waiting for "local_costmap/clear_entirely_local_costmap" service
[bt_navigator-11] [INFO] [1608050063.088211586] [bt_navigator_rclcpp_node]: "ClearLocalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-11] [INFO] [1608050063.093498462] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-11] [INFO] [1608050063.093643696] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Subtree" BtServiceNode initialized
[bt_navigator-11] [INFO] [1608050063.118104077] [bt_navigator_rclcpp_node]: Waiting for "spin" action server
[bt_navigator-11] [INFO] [1608050063.118304204] [bt_navigator_rclcpp_node]: "Spin" BtActionNode initialized
[bt_navigator-11] [INFO] [1608050063.144191856] [bt_navigator_rclcpp_node]: Waiting for "wait" action server
[bt_navigator-11] [INFO] [1608050063.144341819] [bt_navigator_rclcpp_node]: "Wait" BtActionNode initialized
[lifecycle_manager-13] [INFO] [1608050063.147718407] [lifecycle_manager_navigation]: Configuring waypoint_follower
[waypoint_follower-12] [INFO] [1608050063.148531644] [waypoint_follower]: Configuring
[lifecycle_manager-13] [INFO] [1608050063.300841694] [lifecycle_manager_navigation]: Activating controller_server
[controller_server-8] [INFO] [1608050063.301425664] [controller_server]: Activating
[controller_server-8] [INFO] [1608050063.301459222] [local_costmap.local_costmap]: Activating
[controller_server-8] [INFO] [1608050063.301471237] [local_costmap.local_costmap]: Checking transform
[controller_server-8] [INFO] [1608050063.301498980] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[rviz2-4] libGL error: No matching fbConfigs or visuals found
[rviz2-4] libGL error: failed to load driver: swrast
[rviz2-4] libGL error: No matching fbConfigs or visuals found
[rviz2-4] libGL error: failed to load driver: swrast
[rviz2-4] rviz2: /tmp/binarydeb/ros-foxy-rviz-ogre-vendor-8.2.1/obj-x86_64-linux-gnu/ogre-v1.12.1-prefix/src/ogre-v1.12.1/RenderSystems/GL/src/OgreGLRenderSystem.cpp:3468: void Ogre::GLRenderSystem::initialiseExtensions(): Assertion `pcVer && "Problems getting GL version string using glGetString"' failed.
[controller_server-8] [INFO] [1608050063.801689881] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[controller_server-8] [INFO] [1608050064.301592312] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[ERROR] [rviz2-4]: process has died [pid 2699, exit code -6, cmd '/opt/ros/foxy/lib/rviz2/rviz2 -d /opt/ros/foxy/share/nav2_bringup/rviz/nav2_default_view.rviz --ros-args -r __node:=rviz2'].
[INFO] [lifecycle_manager-13]: sending signal 'SIGINT' to process[lifecycle_manager-13]
[INFO] [waypoint_follower-12]: sending signal 'SIGINT' to process[waypoint_follower-12]
[INFO] [bt_navigator-11]: sending signal 'SIGINT' to process[bt_navigator-11]
[INFO] [recoveries_server-10]: sending signal 'SIGINT' to process[recoveries_server-10]
[INFO] [planner_server-9]: sending signal 'SIGINT' to process[planner_server-9]
[INFO] [controller_server-8]: sending signal 'SIGINT' to process[controller_server-8]
[INFO] [waypoint_follower-12]: process has finished cleanly [pid 2727]
[INFO] [recoveries_server-10]: process has finished cleanly [pid 2711]
[INFO] [planner_server-9]: process has finished cleanly [pid 2709]
[INFO] [lifecycle_manager-7]: sending signal 'SIGINT' to process[lifecycle_manager-7]
[INFO] [bt_navigator-11]: process has finished cleanly [pid 2713]
[INFO] [amcl-6]: sending signal 'SIGINT' to process[amcl-6]
[INFO] [map_server-5]: sending signal 'SIGINT' to process[map_server-5]
[INFO] [robot_state_publisher-3]: sending signal 'SIGINT' to process[robot_state_publisher-3]
[INFO] [gzclient-2]: sending signal 'SIGINT' to process[gzclient-2]
[INFO] [controller_server-8]: process has finished cleanly [pid 2707]
[INFO] [lifecycle_manager-7]: process has finished cleanly [pid 2705]
[INFO] [map_server-5]: process has finished cleanly [pid 2701]
[INFO] [gzserver-1]: sending signal 'SIGINT' to process[gzserver-1]
[INFO] [amcl-6]: process has finished cleanly [pid 2703]
[INFO] [robot_state_publisher-3]: process has finished cleanly [pid 2697]
[lifecycle_manager-13] [INFO] [1608050064.375168179] [rclcpp]: signal_handler(signal_value=2)
[lifecycle_manager-13] [ERROR] [1608050064.379541403] [lifecycle_manager_navigation]: Failed to change state for node: controller_server
[lifecycle_manager-13] [ERROR] [1608050064.379608120] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[lifecycle_manager-13] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[lifecycle_manager-13]   what():  Failed to create interrupt guard condition in Executor constructor: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/guard_condition.c:67
[waypoint_follower-12] [INFO] [1608050064.382569933] [rclcpp]: signal_handler(signal_value=2)
[waypoint_follower-12] [INFO] [1608050064.383895994] [waypoint_follower]: Destroying
[waypoint_follower-12] [ERROR] [1608050064.388148848] [rclcpp_action]: Error in destruction of rcl action client handle: the Node Handle was destructed too early. You will leak memory
[bt_navigator-11] [INFO] [1608050064.390962317] [rclcpp]: signal_handler(signal_value=2)
[bt_navigator-11] [INFO] [1608050064.394214989] [bt_navigator]: Destroying
[recoveries_server-10] [INFO] [1608050064.435996287] [rclcpp]: signal_handler(signal_value=2)
[planner_server-9] [INFO] [1608050064.510542355] [rclcpp]: signal_handler(signal_value=2)
[controller_server-8] [INFO] [1608050064.539664764] [rclcpp]: signal_handler(signal_value=2)
[controller_server-8] [INFO] [1608050064.540056141] [local_costmap.local_costmap]: start
[controller_server-8] Failed to publish log message to rosout: publisher's context is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/publisher.c:423
[controller_server-8] [ERROR] [1608050064.540400970] []: Caught exception in callback for transition 13
[controller_server-8] [ERROR] [1608050064.540417017] []: Original error: could not create subscription: rcl node's context is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:441
[controller_server-8] [ERROR] [1608050064.540435094] []: Failed to finish transition 3. Current state is now: errorprocessing (Could not publish transition: publisher's context is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/publisher.c:423, at /tmp/binarydeb/ros-foxy-rcl-lifecycle-1.1.10/src/rcl_lifecycle.c:367)
[lifecycle_manager-7] [INFO] [1608050064.544870982] [rclcpp]: signal_handler(signal_value=2)
[lifecycle_manager-7] [INFO] [1608050064.546421526] [lifecycle_manager_localization]: Destroying
[amcl-6] [INFO] [1608050064.555497473] [rclcpp]: signal_handler(signal_value=2)
[amcl-6] [INFO] [1608050064.557326759] [amcl]: Destroying
[map_server-5] [INFO] [1608050064.585537831] [rclcpp]: signal_handler(signal_value=2)
[map_server-5] [INFO] [1608050064.588540228] [map_server]: Destroying
[robot_state_publisher-3] [INFO] [1608050064.595052591] [rclcpp]: signal_handler(signal_value=2)
[gzserver-1] [INFO] [1608050064.631555773] [rclcpp]: signal_handler(signal_value=2)
[ERROR] [gzclient-2]: process has died [pid 2695, exit code -2, cmd 'gzclient'].
[ERROR] [lifecycle_manager-13]: process has died [pid 2755, exit code -6, cmd '/opt/ros/foxy/lib/nav2_lifecycle_manager/lifecycle_manager --ros-args -r __node:=lifecycle_manager_navigation --params-file /tmp/launch_params_3io3ho87 --params-file /tmp/launch_params_mrhfrnuv --params-file /tmp/launch_params_n9c_ojsy'].
[gzserver-1] terminate called after throwing an instance of 'rclcpp::exceptions::RCLError'
[gzserver-1]   what():  could not create service: rcl node's context is invalid, at /tmp/binarydeb/ros-foxy-rcl-1.1.10/src/rcl/node.c:441
[ERROR] [gzserver-1]: process[gzserver-1] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [gzserver-1]: sending signal 'SIGTERM' to process[gzserver-1]
[ERROR] [gzserver-1]: process has died [pid 2693, exit code -6, cmd 'gzserver -s libgazebo_ros_init.so /opt/ros/foxy/share/nav2_bringup/worlds/waffle.model'].
#### Additional information
tutorials examples offered by turtlebot3 works well, e.g. turtlebot3_house.launch.py.

**Comment by SteveMacenski** [comment]
‘’’
[rviz2-4] libGL error: No matching fbConfigs or visuals found
[rviz2-4] libGL error: failed to load driver: swrast
[rviz2-4] libGL error: No matching fbConfigs or visuals found
[rviz2-4] libGL error: failed to load driver: swrast
‘’’

this is clearly an rviz issue, closing.
