### ISSUE TITLE
allow_unknown can't configure on dashing-devel branch

### ISSUE THREAD

**Issue by drtritmwin** [ros-planning/navigation2#2134]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 
- ROS2 Version:
  - Dashing binary

#### Expected behavior
The "allow_unknown" parameter should be configurable
#### Actual behavior
The "allow_unknown" parameter cannot be configurable
#### Additional information
**the parameter "allow_unknown" has been set as const in navfn_planner packages in ROS dashing branch**

----

As I mentioned, I can see that the variable  ""allown_unknown_" in only dashing branch has been set as
 
"const bool allow_unknown_{true};"

That variable is in /navigation2/nav2_navfn_planner/include/nav2_navfn_planner/navfn_planner.hpp, line number 147
So I can't configue that parameter

**Comment by SteveMacenski** [comment]
Please submit a PR to add that parameter, thanks!

**Comment by SteveMacenski** [comment]
Merged!
