### ISSUE TITLE
groot real-time monitoring

### ISSUE THREAD

**Issue by linuxsocke** [ros-planning/navigation2#2141]
Hi, 
I tried to get the groot real-time monitoring running in the foxy branch but I get the following error: 

`terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at`
  
So far I just copied the required lines (in the main branch) into the bt_navigator and behavior_tree_engine (foxy branch). 
  
Are there some ideas what causes this crash of groot when trying to connect to real time monitoring?  

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy

**Comment by SteveMacenski** [comment]
It sounds like you’ve made custom modifications to the codebase. Unfortunately you may have caused that crash and without further evidence (like a traceback) that this issue is caused by code as it exists in main or foxy-devel, we cannot assist.
