### ISSUE TITLE
Improve NavigateToPose Action Feedback

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2154]
CC @timple 

Distance to goal integrating path points rather than just L2 distance. 

ETA based on some conservative metrics (max speed or min speed, current speed?)

**Comment by deepaktalwardt** [comment]
I will be taking a crack at this issue over the next few days :)

**Comment by deepaktalwardt** [comment]
PR for this feature is up here https://github.com/ros-planning/navigation2/pull/2194

**Comment by SteveMacenski** [comment]
Merging imminent after CI passes
