### ISSUE TITLE
Add doxygen for all files

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2155]
We have pretty good coverage on this already, but there are a couple of packages missing doxygen in the headers

**Comment by SteveMacenski** [comment]
A good first time issue user might want to just add these for a couple of header files missing them! You don't have to do everything at once, even a little bit at a time is super helpful

**Comment by SteveMacenski** [comment]
From a survey, these are the packages needed doxygen
- [ ] AMCL
- [ ] behavior tree
- [ ] costmap 2d
- [ ] navfn
- [ ] recoveries
- [ ] utils

**Comment by mlsdpk** [comment]
@SteveMacenski this is my first time contributing to the project, I would like to take navfn first if possible.

**Comment by SteveMacenski** [comment]
That would be greatly helpful, thanks @mlsdpk!

**Comment by SteveMacenski** [comment]
I did utils and recoveries

**Comment by SteveMacenski** [comment]
Phew.... 2,000 lines later, finally complete!
