### ISSUE TITLE
Ability to get a path from the planner from any 2 poses (start_pose and goal) 

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#2178]
## Feature request
Add `use_start_pose` and `start_pose` to `ComputePathToPose`
#### Feature description
The current `ComputePathToPose` action exposed by the planner interface uses the current robot pose as a start pose to compute a path. It would be useful to be able to override the current robot pose with a provided `start_pose` so one could get a path from any 2 poses of the costmap.

#### Implementation considerations
Current behavior should be maintained as default one. Quite straightforward since the `global_planer` interface already implements:
```
nav_msgs::msg::Path createPlan(
    const geometry_msgs::msg::PoseStamped & start,
    const geometry_msgs::msg::PoseStamped & goal)
```
 Simple implementation in this draft PR : https://github.com/ros-planning/navigation2/pull/2179

**Comment by SteveMacenski** [comment]
merged
