### ISSUE TITLE
DWB missing parameter to expose

### ISSUE THREAD

**Issue by simutisernestas** [ros-planning/navigation2#2185]
https://github.com/ros-planning/navigation2/blob/4e52bad8d7b8add98291472c114ea0ec054bcd1b/nav2_dwb_controller/dwb_core/src/dwb_local_planner.cpp#L482-L492

Seems like ```shorten_transformed_plan``` is always true.

**Comment by SteveMacenski** [comment]
Its a parameter that should be exposed, but I don't think its redundant

**Comment by SteveMacenski** [comment]
Merged!
