### ISSUE TITLE
[BT plugin node] Only trigger underlying subtree / node once time 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2197]
In case you want to do something like "no replanning" so you place the planner BT node under this "only once" so that its skipped for all over traversals of the tree during a particular run.

**Comment by Opletts** [comment]
I'd like to give this a shot, if that's alright?

**Comment by SteveMacenski** [comment]
That would be more than alright! :smile:

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/2236 completes, @Opletts apologies, I needed this done for a demo :(
