### ISSUE TITLE
Update BT nodes to use callback groups / executors to process

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2251]
For example: https://github.com/ros-planning/navigation2/blob/main/nav2_util/include/nav2_util/service_client.hpp#L43

Subs:
- [x] Battery low
- [x] Goal updater
- [x] planner / controller / goal checker selectors 

Actions:
- [x] recoveries (spin, wait, backup)
- [x] follow path
- [x] compute path
- [x] NavigateToPose

Services:
- [x] clear all
- [x] clear region
- [x] clear except
- [x] relocalize global (does this even work anymore?)

**Comment by SteveMacenski** [comment]
It's come to my attention that the executors might be creating a new context remapping to a new DDS participant. This would not be good if we had each BT node creating a new participant to process separately. Some more research has to be done to figure out if this is workable before we jump into it.

Figure out if this does indeed add more participants to the network, if so, if there's a workable way around it so we can process callbacks uniquely in our BT nodes with little overhead.

If not, leave as is.

**Comment by BriceRenaudeau** [comment]
Right now, BT nodes are using there parent node("_rclcpp_node") to create subscriber/service/action so there are not creating new context.
May be we can also pass a multi Threaded executor create and spin in the parent node through the blackboard to attach callback groups. 
It will still create a new context but only one for all the BT node and remove the client_node.

**Comment by SteveMacenski** [comment]
> BT nodes are using there parent node("_rclcpp_node") to create subscriber/service/action so there are not creating new context

Correct @BriceRenaudeau , but this ticket was considering adding the same logic as you introduced in the simple service client. From the design document I linked to above and a little digging, the impression I'm under is that a new DDS participant is made in each new context. The constructor of the `executor` creates a new context object by default when none is given. 

Therefore, I think that we're actually creating a new network participant in the simple service client, which is probably worse for performance than before. It may be fixable, but I haven't had cycles to look into it.

This ticket is wanting to use that same design with a sub/pub/etc made from `node` but added to a local BT-node specific executor. I don't think we can do this due to the fact that it would create a new context, ergo a new DDS participant.

**Comment by SteveMacenski** [comment]
I spoke with Chris from OR and he gave me the key to my understanding on this -- while a new context is constructed on a new executor, when none is given as an input, it uses the default context which stores a static variable to use https://github.com/ros2/rclcpp/blob/master/rclcpp/src/rclcpp/contexts/default_context.cpp#L23. Therefore, any new executor, node, etc will use that same context regardless, unless you give a context to the object on construction.

Thusly, we can continue with this work one the model of the `ServiceClient` where each BT node can have its own executor for spinning to only receive its isolated messages!

**Comment by SteveMacenski** [comment]
merged!
