### ISSUE TITLE
[Eloquent] Caught exception in callback for transition 10

### ISSUE THREAD

**Issue by Repp-cattt** [ros-planning/navigation2#2275]
## Bug report

**Required Info:**

- Operating System:
ubuntu18.04
- ROS2 Version:
eloquent
- Version or commit hash:
  ros-eloquent-navigation2  0.3.5-1bionic.20201208.102351

#### Steps to reproduce issue

```
1、Download the source code of the eloquent branch of navigation2
https://github.com/ros-planning/navigation2/tree/eloquent-devel
2、Build code
source /opt/ros/eloquent/setup.bash
colcon build 
3、Bringup navigation
ros2 launch nav2_bringup nav2_bringup_launch.py use_sim_time:=true map:=/home/maps/map.yaml
4、You will see the error messages as below: 
```
`[bt_navigator-7] [ERROR] []: Caught exception in callback for transition 10
[bt_navigator-7] [ERROR] []: Original error: Could not load library: /opt/ros/eloquent/lib/libnav2_compute_path_to_pose_action_bt_node.so: undefined symbol: _ZTIN2BT14CoroActionNodeE
[bt_navigator-7] [WARN] []: Error occurred while doing error handling.
[bt_navigator-7] [FATAL] [bt_navigator]: Lifecycle node entered error state
[lifecycle_manager-1] [ERROR] [lifecycle_manager]: Failed to change state for node: bt_navigator
[lifecycle_manager-1] [ERROR] [lifecycle_manager]: Failed to bring up nodes: aborting bringup`

#### Implementation considerations
I want to use the function of 2D navigation, but I can't execute the program properly. I didn't see my map on time in rviz. Is there any way to solve this error?

**Comment by SteveMacenski** [comment]
Eloquent is EOL, we do not offer any support for it, try on ROS Answers for other eloquent users.
