### ISSUE TITLE
The robot cannot avoid obstacles and replan its route in the process of navigation.

### ISSUE THREAD

**Issue by miku54** [ros-planning/navigation2#2285]
## Bug report
In the process of navigation, the robot can not avoid obstacles and replan the route, there are display lines of global planning path and local planning path, and the map is refreshed, but the route cannot be re-planned.
**Required Info:**

- Operating System:
ubuntu18.04 /ubuntu20.04
- ROS2 Version:
Eloquent /foxy
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```
launch navigation2
set 2D Pose Estimate A 
set goal B
set obstacle on A to B path
```

#### Expected behavior
ROS2 navigation can avoid obstacles while set goal from A to B.

#### Actual behavior
ROS2 navigation cannot avoid obstacles while set goal from A to B.
And stopped when he encountered an obstacle.
#### Additional information

----

**Comment by SteveMacenski** [comment]
Please file a question on ROS Answers with about 10x more details, configuration guides, log files, and information.

**Comment by miku54** [comment]
Thank you. I've taken care of it.

Steve Macenski ***@***.***> 于2021年4月2日周五 上午2:42写道：
