### ISSUE TITLE
Port robot_navigation changes

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#229]
It looks like David updated the package with a bunch of bug fixes and such for DWB
https://github.com/locusrobotics/robot_navigation/pull/15

**Comment by mkhansen-intel** [comment]
Looks like these are the changes he was describing during his ROSCon talk.

A very large change overall.

**Comment by SteveMacenski** [comment]
Indeed. This would be good to make a talking point of this week's meeting

**Comment by crdelsey** [comment]
Looks like he has added a new plugin based global planner with plugins to replicate the Dijkstra and A* planner functionality.

The other big change is an overhaul/replacement of costmap.

**Comment by SteveMacenski** [comment]
For some of this depending on how we want to format things, we could actually just have a git submodule to his code so its all in 1 place but linked when someone clones. 

We'd need to get DLu on board with a ros2 branch

**Comment by crdelsey** [comment]
I guess the other possibility is that we port base_local_planner and/or dwa_local_planner over to ROS 2 and leave Dlu's repo as an optional planner.

**Comment by SteveMacenski** [comment]
One thing I'd like to see (and open to injecting myself into) is some homologation between the stack Locus has been working on and this `ros-planning` repo. The worst case scenario is we see a split in the community with one camp utilizing one framework and the other camp using the other. There's always people swapping out major components but generally people respect `navigation` framework even if they completely gut move_base. (i.e. plugins, nav_core, msgs). 

Especially since `robot_navigation` is ROS1, there's an opportunity to port into ROS2 as part of this project and ensure that all the tools and infrastructure for both are treated as first-class citizens (i.e. porting their eventual-released locomotion package as a `task` to ROS2 to fit in the framework or rethink things in light of it, etc). Things like the local/global planners fit easily into this. The world models and higher level logic not as easily. 

It appears to all be of very good quality and would seriously suck if in the ROS2 transition the navigation community fractured. Thoughts?

**Comment by DLu** [comment]
I acknowledge that I'm way behind in keeping up to date with what's going on in this repo. My apologies for that. 

The biggest discrepancy between the way `navigation2` and `robot_navigation` does things is the core interfaces. `navigation2` has Tasks, and `robot_navigation` has the `nav_core2` interfaces. 

There is a certain elegance to Tasks in that you can just say "Do This" without the clunkiness of additional details, but I worry that that limits the communication between Tasks too much. I remember @mikeferguson raised the question of setups where the global planner constantly replans. Can you remind me what the workaround is for that? i.e. would there just constantly be new `FollowPathTask`s?

**Comment by DLu** [comment]
@mkhansen-intel Is there something that provides that line of communication from GlobalPlanner to LocalPlanner?

**Comment by crdelsey** [comment]
@DLu I was cleaning up the old issues and saw this question was never answered. Sorry about that.

> would there just constantly be new FollowPathTasks?

Yes. That is how it currently works. 

The top level `bt_navigator` (the `move base` equivalent) has the possibility to cancel the current task, causing the robot to stop, and then send a new command. Or it can just issue new tasks, causing the previous one to be replaced without stopping.

**Comment by mkhansen-intel** [comment]
I don't believe there's any action to be taken here, we now support plugin interfaces for planners, controllers and recoveries. I think we're good. If we decide to port anything from robot_navigation later, we could open a ticket for each functional change we want to make.

**Comment by SteveMacenski** [comment]
This is still active. 

DLu pushed a bunch of DWB updates that we dont have reflected. I have to imagine there are bug patches

**Comment by shivaang12** [comment]
What are we aiming for here? transferring his repo or making update to our existing repo?

**Comment by DLu** [comment]
Updating the existing repo. Original repo is ROS1.

**Comment by shivaang12** [comment]
okay cool! I will start porting these changes!

**Comment by shivaang12** [comment]
@DLu I was just curious to know the reason behind change of "addGridScore" to "addCriticVisualization".

**Comment by DLu** [comment]
@shivaang12 I felt like the latter was a bit more descriptive of what was going on, since it doesn't actually change the scores, but just generates visualization information.
