### ISSUE TITLE
[Question] Plan for connenting with other powerful simlator

### ISSUE THREAD

**Issue by harderthan** [ros-planning/navigation2#2307]
## Feature request
Do you have a plan to connect with other powerful simulator, not gazebo?

#### Feature description
To development and test more complicated robots, simulator need more performance and functions like high definition render, multi robot clients, traffic scenarios simulation with maps.
There are already powerful simulators for them like **Airsim, CARLA and LGSVL**.
Do you have any plans to develop interfaces or bridges that can be used with these and Navigation2?

**Comment by SteveMacenski** [comment]
You're welcome to use any simulator you would like, there's no reason it should largely impact things. But we use gazebo as our default choice. We have no plans to migrate to others.
