### ISSUE TITLE
This model has not been registered: RemovePassedGoals

### ISSUE THREAD

**Issue by AustinDeric** [ros-planning/navigation2#2312]
## Bug report
- Operating System: Ubuntu 20.04
- ROS2 Version: Foxy binaries
- Version or commit hash: https://github.com/ros-planning/navigation2/commit/f28951048dc67f1e8a7b1b7cf450195e53a80ee6
- DDS implementation: Fast-RTPS

#### Steps to reproduce issue
1. ./Groot (implies cmake build as per https://github.com/BehaviorTree/Groot/blob/fae38066a61068c966eefd4c825738bb650413cc/README.md)
2. Load pallet: https://github.com/ros-planning/navigation2/blob/f28951048dc67f1e8a7b1b7cf450195e53a80ee6/nav2_behavior_tree/nav2_tree_nodes.xml
3. load tree: https://github.com/ros-planning/navigation2/blob/f28951048dc67f1e8a7b1b7cf450195e53a80ee6/nav2_bt_navigator/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml

#### Expected behavior
The tree loads in groot

#### Actual behavior
![image](https://user-images.githubusercontent.com/5349043/114815162-49d27680-9d7b-11eb-8779-200f4b12afe8.png)
```
It was not possible to parse the file. Error:

This model has not been registered: RemovePassedGoals
```

**Comment by SteveMacenski** [comment]
Merged, thanks!
