### ISSUE TITLE
costmap_filter_info_server cannot be found in the foxy-devel branch

### ISSUE THREAD

**Issue by JetBelson** [ros-planning/navigation2#2317]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 20.04
- ROS2 Version:
  -  Foxy binaries
- Version or commit hash:
  -   git clone https://github.com/ros-planning/navigation2.git --branch foxy-devel

- DDS implementation:
  -  Fast-RTPS

#### Steps to reproduce issue
 Follow the Navigating with Keepout Zones example (https://navigation.ros.org/tutorials/index.html)

```

```

#### Actual behavior
executable 'costmap_filter_info_server' not found on the libexec directory

I checked the CmakeLists in the directory of src/navigation2/nav2_map_server in the foxy-dev branch, found that the costmap_filter_info_server part is missing compared with the main branch.
 
#### Implementation considerations

Update the Build and Install part or  Navigating with Keepout Zones part of the Documentation.

**Comment by SteveMacenski** [comment]
It is only available in main and future distributions. Please check the source code. It is not ABI compatible for foxy release.
