### ISSUE TITLE
How to adopt the Smac Planner for path planning only?

### ISSUE THREAD

**Issue by LionelZheng** [ros-planning/navigation2#2319]
I want to use the Hybrid A* as a benchmark, especially its optimization part. 

First, I followed the original paper and reproduced my implementation, but it never worked.

Then I searched its implementations on the Internet and reproduced several versions,  but their implementations are all slightly different on the Differentiation Formulas implementations, and none of them can converge stably. 

Finally, I came to this project... 

I spent one week reading the Documentation and now has an initial idea to adopt the Smac Planner for path planning? As I only have some basics knowledge about the ROS, so before coding, I hope to share my idea and get some suggestion from your expert knowledge.

1. Set up the kinematics of my robot via the URDF file;
2. Set up an environment via the world pgm file and its params yaml file.
3. Set up params file for selecting the SMac Planner, etc..
4. Set up a BT tree for my simple path planning purpose.
5. Prepare a launch file...

Any suggestion to my initial idea?

Many thanks!

**Comment by SteveMacenski** [comment]
This isn't the right forum for this type of question - please ask on ROS Answers and potentially someone can assist.
