### ISSUE TITLE
Move CI, developer instructions, and workflows from ROS2 master to Rolling

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2337]
- [x] change dockerhub base image to rolling
- [x] change CI to use rolling
- [x] Release OMPL to Rolling to complete dependency chain in rolling
- [x] Update build / install instructions to use Rolling https://github.com/ros-planning/navigation.ros.org/pull/203
- [x] Update developer workflows to use Rolling and no longer master ROS2 builds + underlay/dependencies workspace https://github.com/ros-planning/navigation2/pull/2532
- [ ] Announce on discourse

CC @ruffsl

**Comment by SteveMacenski** [comment]
@ruffsl would I be correct in saying CI / all the docker images use rolling now? If so, I can update all of the documentation in Nav2 website to point to Rolling instead and then close this ticket out (maybe delete some of the tools in `tools`)

**Comment by SteveMacenski** [comment]
Did a quick review, found https://navigation.ros.org/build_instructions/index.html as the only page going into install methods to master. I'll update this and control+F on the rest of it to update any other references for master.

**Comment by ruffsl** [comment]
> would I be correct in saying CI / all the docker images use rolling now?

Yep, evening should be using the rolling release now.

**Comment by SteveMacenski** [comment]
Done!
