### ISSUE TITLE
cannot compile nav2 on ros2 foxy on jetson xaiver

### ISSUE THREAD

**Issue by cchantra** [ros-planning/navigation2#2359]
I am manually building nav2 on jetson xaiver for ros2 foxy.

mine is one  ubuntu 18.04. I followed the page https://navigation.ros.org/build_instructions/index.html

When I did,
colcon build --symlink-install

I am new to ros, ros2. There are lots of dependencies required here. I am not sure is it because of gcc version.
Mine is gcc 7.4.0

I got the following error:
=========================

In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/node_utils.cpp:15:0:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp: In function ‘std::__cxx11::string nav2_util::get_plugin_type_param(NodeT, const string&)’:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp:148:32: error: ‘ParameterUninitializedException’ in namespace ‘rclcpp::exceptions’ does not name a type
   } catch (rclcpp::exceptions::ParameterUninitializedException & ex) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_utils.cpp:22:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp: In constructor ‘nav2_util::ServiceClient<ServiceT>::ServiceClient(const string&, const SharedPtr&)’:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:45:12: error: no matching function for call to ‘rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType, bool)’
       false);
            ^
In file included from /opt/ros/foxy/install/rclcpp/include/rclcpp/executors/single_threaded_executor.hpp:28:0,
                 from /opt/ros/foxy/install/rclcpp/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/install/rclcpp/include/rclcpp/rclcpp.hpp:146,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:20,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_utils.cpp:22:
/opt/ros/foxy/install/rclcpp/include/rclcpp/node.hpp:144:3: note: candidate: rclcpp::CallbackGroup::SharedPtr rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType)
   create_callback_group(rclcpp::CallbackGroupType group_type);
   ^~~~~~~~~~~~~~~~~~~~~
/opt/ros/foxy/install/rclcpp/include/rclcpp/node.hpp:144:3: note:   candidate expects 1 argument, 2 provided
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_utils.cpp:22:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:46:30: error: ‘class rclcpp::executors::SingleThreadedExecutor’ has no member named ‘add_callback_group’
     callback_group_executor_.add_callback_group(callback_group_, node_->get_node_base_interface());
                              ^~~~~~~~~~~~~~~~~~
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:25:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_utils.cpp:22:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp: In function ‘std::__cxx11::string nav2_util::get_plugin_type_param(NodeT, const string&)’:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp:148:32: error: ‘ParameterUninitializedException’ in namespace ‘rclcpp::exceptions’ does not name a type
   } catch (rclcpp::exceptions::ParameterUninitializedException & ex) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_service_client.cpp:15:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp: In constructor ‘nav2_util::ServiceClient<ServiceT>::ServiceClient(const string&, const SharedPtr&)’:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:45:12: error: no matching function for call to ‘rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType, bool)’
       false);
            ^
In file included from /opt/ros/foxy/install/rclcpp/include/rclcpp/executors/single_threaded_executor.hpp:28:0,
                 from /opt/ros/foxy/install/rclcpp/include/rclcpp/executors.hpp:22,
                 from /opt/ros/foxy/install/rclcpp/include/rclcpp/rclcpp.hpp:146,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:20,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_service_client.cpp:15:
/opt/ros/foxy/install/rclcpp/include/rclcpp/node.hpp:144:3: note: candidate: rclcpp::CallbackGroup::SharedPtr rclcpp::Node::create_callback_group(rclcpp::CallbackGroupType)
   create_callback_group(rclcpp::CallbackGroupType group_type);
   ^~~~~~~~~~~~~~~~~~~~~
/opt/ros/foxy/install/rclcpp/include/rclcpp/node.hpp:144:3: note:   candidate expects 1 argument, 2 provided
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:24:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_service_client.cpp:15:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/service_client.hpp:46:30: error: ‘class rclcpp::executors::SingleThreadedExecutor’ has no member named ‘add_callback_group’
     callback_group_executor_.add_callback_group(callback_group_, node_->get_node_base_interface());
                              ^~~~~~~~~~~~~~~~~~
In file included from /home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/lifecycle_service_client.hpp:25:0,
                 from /home/nvidia/nav2_ws/src/navigation2/nav2_util/src/lifecycle_service_client.cpp:15:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp: In function ‘std::__cxx11::string nav2_util::get_plugin_type_param(NodeT, const string&)’:
/home/nvidia/nav2_ws/src/navigation2/nav2_util/include/nav2_util/node_utils.hpp:148:32: error: ‘ParameterUninitializedException’ in namespace ‘rclcpp::exceptions’ does not name a type
   } catch (rclcpp::exceptions::ParameterUninitializedException & ex) {
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/nav2_util_core.dir/node_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/CMakeFiles/nav2_util_core.dir/lifecycle_utils.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/nav2_util_core.dir/lifecycle_service_client.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/nav2_util_core.dir/all] Error 2
make: *** [all] Error 2
---
Failed   <<< nav2_util [19.0s, exited with code 2]

====
Please suggest the solution. 

Thanks 
cc

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers
