### ISSUE TITLE
rviz2 crash during use -- investigate

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2367]
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Node has already been added to an executor.
```

Is this an rviz2 issue? Is it a nav2 rviz plugin issue? This has been pretty long-standing since Crystal days

**Comment by AlexeyMerzlyakov** [comment]
The problem appears even if all Nav2-related stuff disabled. Submitted a new bug on rviz: https://github.com/ros-visualization/rviz/issues/1633

**Comment by SteveMacenski** [comment]
Closing since redirected to Rviz2.
