### ISSUE TITLE
Moving fixes from PR #2083 into foxy-devel

### ISSUE THREAD

**Issue by nkalupahana** [ros-planning/navigation2#2368]
## Bug report

**Required Info:**

- Operating System:
  - macOS 11
- ROS2 Version:
  - Foxy, from source
- Version or commit hash:
  - latest on `foxy-devel`
- DDS implementation:
  - Fast-DDS

Building on macOS was fixed by PR #2083 -- but those changes haven't gotten added to the foxy-devel branch, which is the branch people building for Foxy are expected to build off of. Is there a reason those changes haven't been cherry-picked over? I'd be happy to do it otherwise.

**Comment by SteveMacenski** [comment]
It was not migrated because it changed function signatures in `ObservationBuffer`. Other than that, all of the other changes could be made and I'd be happy to merge a PR into Foxy to resolve that for you as long as it doesn't modify any function signatures

**Comment by SteveMacenski** [comment]
@nkalupahana any progress? Currently blocked on the unique pointer, as far as I can tell from looking the move is still required by best practices to give up the ownership rights on the unique pointer to the middleware to reduce jitter

**Comment by nkalupahana** [comment]
I'm a bit tied up with work at the moment, but I should get some spare time in the next week to figure out what's going on and finish off the PR.

**Comment by SteveMacenski** [comment]
OK, thanks for the update

**Comment by SteveMacenski** [comment]
Merging imminent
