### ISSUE TITLE
Proper use of Gazebo / model spawner for more modular model / world use

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2389]
Right now, we have the model and the world all in 1 world file, rather than having a world file that we spawn a gazebo model into.

There's a `spawn_entity.py` and a multirobot version in Nav2 that we should be using instead to spawn robots within a world so that these things are not tied together. This would let someone change the robot or world more easily to spawn (different robots, in different places in the world, or in different worlds).

I think the gazebo gzserver needs to be the ros factory so file instead to use the model spawner, and any other things required (separate URDF file with gazebo plugins from the .world file)

**Comment by sathak93** [comment]
hi steve

i have manually input world file and spawned robot model sdf file and changed gazebo state to factory.
![Screenshot from 2021-07-16 16-40-31](https://user-images.githubusercontent.com/57533054/125938978-6977242a-459b-4fbe-ac22-95ca34d3900c.png)
i debugged it  to  some extent.
the only difference between the launch file with spawn entity and combined model + world is 
the layered  costmaps  are not published 
the if block in 
https://github.com/ros-planning/navigation2/blob/5a7027536068183602f10b419bd711fafdad6784/nav2_costmap_2d/src/costmap_2d_ros.cpp#L422 is always becomes false as the current time is always zero
![Screenshot from 2021-07-16 16-47-28](https://user-images.githubusercontent.com/57533054/125940897-466fbe16-5b05-4e55-aeda-2182e397b4e6.png)
![Screenshot from 2021-07-16 16-49-46](https://user-images.githubusercontent.com/57533054/125940926-7ebd84c1-959a-44fc-ab81-5b78cb03bfe1.png)

can you comment on  why auto current_time = now ()  is not updated or anything i did wrong?

**Comment by sathak93** [comment]
making the if block  true publishes global and local costmaps

**Comment by SteveMacenski** [comment]
I'm not sure, did it work before you changed the model spawning / gazebo? These seem unrelated but clearly must be somehow... maybe the gazebo .so file isn't publishing the clock in the same way?

**Comment by sathak93** [comment]
@SteveMacenski  i found  the problem it seems that libgazebo_ros_factory.so  should be used in addition to libgazebo_ros_init.so instead of replacing it. 
this also need to be changed to fix multi robot simulation not working https://github.com/ros-planning/navigation2/blob/5a7027536068183602f10b419bd711fafdad6784/nav2_bringup/bringup/launch/multi_tb3_simulation_launch.py#L105
it may also solves issues #2446

**Comment by SteveMacenski** [comment]
Oh really— interesting find! Thanks!!

**Comment by SteveMacenski** [comment]
What's the status of this?

**Comment by sathak93** [comment]
sorry i was busy 
i will create PR today

**Comment by SteveMacenski** [comment]
Merging imminent
