### ISSUE TITLE
bt_navigator: Multiple action nodes are started with the same names and parameters (pose, poses)

### ISSUE THREAD

**Issue by jonatanolofsson** [ros-planning/navigation2#2408]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Galactic binaries
- Version or commit hash:
  - 1.0.6
- DDS implementation:
  - 

#### Steps to reproduce issue
Start nav2 with bt_navigator
```
ros2 node list
```

#### Expected behavior
All nodes have separate names

#### Actual behavior
Two nodes named /bt_navigator_rclcpp_node are started

**Comment by SteveMacenski** [comment]
Please add much more detail to this ticket, I don't understand the issue at all you're reporting and you're using ambiguous language
