### ISSUE TITLE
Release AWS warehouse world to foxy/rolling/galactic + readd dep for nav2-simple-commander

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2414]

**Comment by joe28965** [comment]
question about the first part of this issue. There IS a AWS warehouse foxy version. I know, I created it, and made a pull request to the repo for it. So it would only be galactic/rolling right? Also, did that branch break for galactic/rolling?

**Comment by SteveMacenski** [comment]
There is a foxy branch that works fine across the board (because model files dont really change), but they're not released so there are no binaries and its not rosdep installable, so we can't release Nav2 to a new distro until that is released because now we have a dependency on it

**Comment by joe28965** [comment]
oh, you're talking about a binary release. My bad, I misunderstood. I was also curious what could change in a model file that would break it for other branches. Makes sense that it still works.

**Comment by SteveMacenski** [comment]
They are going to release it themselves now, closing here.
