### ISSUE TITLE
Path generation time question?

### ISSUE THREAD

**Issue by JackRen88** [ros-planning/navigation2#2435]
Hello,navi2 team!
I really appreciate your work.When I try the smac planner to generat a path,it takes more time than stated in the documentation,As shown below：
![smooth_!](https://user-images.githubusercontent.com/42662403/124537595-c6419680-de4c-11eb-8fda-5d71f13bcc70.png)
the red path represents unsmoothed path,the green path represents smoothed path, it takes about 500ms with 51292 iterations to generate path which is higher than 30-120ms stated in the documentation,so I want to know why the time difference is so big.
map resolution is 5cm.
The following are the algorithm parameters:
![hybrid para](https://user-images.githubusercontent.com/42662403/124540978-158ac580-de53-11eb-98d8-a64169e3c8da.png)

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers. The ticketing system is for bugs and features only. Please read the community guidelines before opening tickets. Questions belong on ROS Answers
