### ISSUE TITLE
[Smac Smoother] handle reverse direction reeds sheep models as individual segments

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2442]
Right now the smoother will smooth the entire path, meaning that it will smooth the cusp in direction changes. That probably isn't good. Instead we should be treating each segment in a velocity direction separately to retain the cusp and directional changes.

**Comment by dpm-seasony** [comment]
Could you confirm that the PR  #2660 solves this issue?

**Comment by salmagro** [comment]
I have experienced a similar effect, and I would like to clarify if it corresponds to the same issue treated here.

The function `updateApproximatePathOrientations` recalculate the heading based on the order of the XY coordinates without considering the driving direction.

This generates a continuous path to drive forward, provoking the misbehavior of the local planner.

![example1](https://user-images.githubusercontent.com/52298571/142390772-ffc33f1a-5254-4873-924c-5fcf7ce3c885.png)
![example2](https://user-images.githubusercontent.com/52298571/142390775-f4331ff3-8101-4f77-991c-b3df8f2b0990.png)

**Comment by SteveMacenski** [comment]
@salmagro try testing the PR #2660. It should work, I've asked for more programming style updates. Let us know if that fixes your issue

**Comment by salmagro** [comment]
@SteveMacenski thank you for the information. Yes, PR #2660 solved the problem with the wrong heading. However, I have experienced a bug described in https://github.com/ros-planning/navigation2/pull/2660#issuecomment-974087387 .

**Comment by SteveMacenski** [comment]
It's my intention to address this tomorrow and get something merged in hopefully before the end of the week. The issue with the smoother making the plans potentially no longer kinematically feasible remains, but at least reversing will not be negatively impacted anymore (e.g. I can stop commenting out the smoother when I do tests in reverse).

 I'll plan on addressing, or asking someone else to address, the issue with feasibility as a separate topic covered in #2690. I want to start working on these problems as individuals so we can make incremental progress.

**Comment by SteveMacenski** [comment]
I have a working solution to this, but discovered some quirks with the State Lattice planner that need to be resolved before I can merge it. We need the primitive markers to be some distance apart so I can use the dot product to discover cusps. Right now, it over-fires on some situations that I'm trying to fully analyze so that I can fix them all.

For now since I'm in a bit of a waiting cycle, I'm also going to try and tackle the smoother feasibility challenge, which might also encompass re-adding the parameter for smoothing or not so that it can be disabled.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/2727

**Comment by SteveMacenski** [comment]
Merging shortly
