### ISSUE TITLE
Do we have same kind of implimentation for ROS1

### ISSUE THREAD

**Issue by RamanaBotta** [ros-planning/navigation2#2458]
## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by padhupradheep** [comment]
Issues in this repo are used for feature requests or bugs. Also, I see that your question does not have much information. With the context I feel that this question is better for [https://answers.ros.org/](https://answers.ros.org/ )
