### ISSUE TITLE
Nav2 BT Navigator misses / cant find .so libs

### ISSUE THREAD

**Issue by marcomasa** [ros-planning/navigation2#2468]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04.2 LTS, AMD Ryzen 3600
- ROS2 Version:
  - Foxy Debian
- Version or commit hash:
ros-foxy-nav2-amcl	0.4.7-1focal.20210513.213303
ros-foxy-nav2-behavior-tree	0.4.7-1focal.20210513.213233
ros-foxy-nav2-bringup	0.4.7-1focal.20210619.024606
ros-foxy-nav2-bt-navigator	0.4.7-1focal.20210513.214421
ros-foxy-nav2-common	0.4.7-1focal.20210513.203711
ros-foxy-nav2-controller	0.4.7-1focal.20210513.214739
ros-foxy-nav2-core	0.4.7-1focal.20210513.214550
ros-foxy-nav2-costmap-2d	0.4.7-1focal.20210513.213728
ros-foxy-nav2-dwb-controller	0.4.7-1focal.20210513.215352
ros-foxy-nav2-lifecycle-manager	0.4.7-1focal.20210513.213306
ros-foxy-nav2-map-server	0.4.7-1focal.20210513.213306
ros-foxy-nav2-msgs	0.4.7-1focal.20210513.205442
ros-foxy-nav2-navfn-planner	0.4.7-1focal.20210513.214739
ros-foxy-nav2-planner	0.4.7-1focal.20210513.214742
ros-foxy-nav2-recoveries	0.4.7-1focal.20210513.214741
ros-foxy-nav2-regulated-pure-pursuit-controller	0.4.7-1focal.20210513.214745
ros-foxy-nav2-rviz-plugins	0.4.7-1focal.20210619.022344
ros-foxy-nav2-util	0.4.7-1focal.20210513.212614
ros-foxy-nav2-voxel-grid	0.4.7-1focal.20210513.210024
ros-foxy-nav2-waypoint-follower	0.4.7-1focal.20210513.213311

- DDS implementation:
  - Default (Fast-RTPS)

#### Steps to reproduce issue
https://navigation.ros.org/getting_started/index.html

#### Expected behavior
Working bringup ?

#### Actual behavior
```
[bt_navigator-4] [INFO] [1626782356.339201751] [bt_navigator]: Configuring
[bt_navigator-4] [ERROR] [1626782356.351797948] []: Caught exception in callback for transition 10
[bt_navigator-4] [ERROR] [1626782356.351841079] []: Original error: Could not load library: libnav2_navigate_through_poses_action_bt_node.so: cannot open shared object file: No such file or directory
[bt_navigator-4] [WARN] [1626782356.351880653] []: Error occurred while doing error handling.
[bt_navigator-4] [FATAL] [1626782356.351894459] [bt_navigator]: Lifecycle node bt_navigator does not have error state implemented
```

#### Additional information

So, coming from ROS1, i am trying to play a bit around with the new nav2 to test the new features.
I installed everything like 3 Weeks ago and it worked more or less out of the box (gazebo issues, maybe add install instructions for that).

But now i cannot start the behaviour tree again, as it crashes reporting that it cannot find the missing libs.
I also created a custom package where i change parameters, and if i change the parameters for the BT to not include the "nav2_compute_path_through_poses_action_bt_node"  (# it out), i get the following:

```
[bt_navigator-4] [INFO] [1626860792.139532918] [bt_navigator]: Configuring
[bt_navigator-4] [ERROR] [1626860792.151284676] []: Caught exception in callback for transition 10
[bt_navigator-4] [ERROR] [1626860792.151303141] []: Original error: Could not load library: libnav2_single_trigger_bt_node.so: cannot open shared object file: No such file or directory
[bt_navigator-4] [WARN] [1626860792.151320964] []: Error occurred while doing error handling.
[bt_navigator-4] [FATAL] [1626860792.151326635] [bt_navigator]: Lifecycle node bt_navigator does not have error state implemented
```

I saw some commits in the git regarding BT lines, did something happen there by mistake?
I also found this: https://answers.ros.org/question/344030/nav2_bt_navigator-exception-in-callback/
But as not even the tutorial launchfile work without the error above, i suspect there is something else missing here..

It stopped working after a colleague of mine made some "sudo apt update && upgrade" commands to fix something else while i was on vacation..
I dont want to reinstall ROS2, do you have a suggestion?

**Comment by SteveMacenski** [comment]
> libnav2_navigate_through_poses_action_bt_node.so

Where did you get that from? That isn't available in Foxy. It shouldn't be anywhere in the Foxy branch.

**Comment by marcomasa** [comment]
Tbh i dont know. I think i never had it, but it is now requested by the bt_navigator package, as shown above.

**Comment by SteveMacenski** [comment]
Please try to find where that is specified. Your options are: behavior tree, configuration file, or bt_navigator.cpp defaults. Its not in the defaults https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_bt_navigator/src/bt_navigator.cpp#L40-L67. So that means either you're trying to use a behavior tree containing that node or your configuration file is calling out to pick that library up that doesn't exist.

**Comment by marcomasa** [comment]
You are right, it should not be included in the launchfile.
I cloned the main branch to copy the existing nav2_bringup files and modify them:
https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/bringup/params/nav2_params.yaml

Apparently they are not on foxy-devel state but rather on galactic?
Idk which one should be on the master in your opinion, 
maybe update this to foxy? Its kinda unintuitive to have the previous ones as master.

Anyways, adjusting this params in the launchfile did the job. Thank you for your help!
