### ISSUE TITLE
Costmap stays empty: Sensor origin out of map bounds. The costmap can't raytrace for it.

### ISSUE THREAD

**Issue by mkep-dev** [ros-planning/navigation2#2537]
## Bug report

At first I like to underline that I have tried everything for 2 weeks to get my robot running and I failed so far.
I already tried to change any parameter that seemed to be related regarding the tutorial and the documentation.
Furthermore as far as I understand parts of the costmap are a port from move_base. That's why I have looked on the Internet for related problems but without any success.

**Required Info:**

- Operating System: 
  - Docker ROS foxy image
- ROS2 Version: 
  - Docker ROS foxy
- Version or commit hash: 
  - ros-foxy-navigation2	0.4.7-1focal.20210701.142448
- DDS implementation:
  - cyclon dds

#### Steps to reproduce issue

```
I am running on a real self build robot (students project)
1. Start the base nodes of my robot
    - Listener for /cmd_vel (=motor controller)
    - RP_lidar Node
    - Laser scan matcher (odometry replacement)
    - robot_state_publisher
    - joint_state_publisher
2. Slam toolbox
3. Navigation: ros2 launch nav2_bringup navigation_launch.py use_sim_time:=False params_file:=/home/config/nav2_params.yaml
4. Rviz2

```

The used configuration is identical to the example from nav2_bringup, only I set "use_sime_time" to "false" everywhere and I changed the size parameters regarding my robot.

The SLAM works fine, I get a perfect map of my environment and the global map is filled.

#### Expected behavior

The local costmap is "filled" and the robot can navigate

#### Actual behavior

The local costmap is empty and the robot won't move on any Goal Poses.

![Screenshot 2021-08-23 175349](https://user-images.githubusercontent.com/64690473/130918718-001da156-4531-4cbe-a3b2-71ef61574818.png)

Fruthermore the following line is printed:

[controller_server-1] [WARN] [1629735747.578710511] [local_costmap.local_costmap]: Sensor origin: (-0.01, -0.04, 0.80), out of map bounds. The costmap can't raytrace for it.

![Screenshot 2021-08-23 175307](https://user-images.githubusercontent.com/64690473/130918688-bb285cc5-b544-4991-9c63-6d05e97cbff2.png)

#### Additional information

The urdf etc are correct because they are mainly a port to ros2 foxy and in the past everything worked with hector slam.
Besides I already managed to let the robot move by triggering a recovering behaviour and the robot started turning -> communication is working.

Thank you very much for your help.

**Comment by JianchouBai** [comment]
> 没有错误
> 
> 完全是我的错误。感谢您极快的帮助
> 
> 编辑：查看 ros 答案以获取解决方案

excuse me . i met the same problem,could i ask you about the method what you use to fix the problem?
