### ISSUE TITLE
Migrate Recovery Server to Behavior Server

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2549]
After some thought around behavior primitives and actions, I think we should rename (and thusly update docs, package names, etc) for the recovery server to become the **behavior server**. At the end of the day, a recovery is simply a primitive behavior to get the robot out of a jam. As we're increasing the capabilities of Nav2 through behaviors and behavior trees, it doesn't make sense to restrict the recovery server to recoveries only. In particular, as we're creating capabilities like assisted teleop and docking, it makes sense to have these located in the same server for mental grouping and computational efficiency reasons.

The recovery server is uniquely designed to have many different action servers hosted within in (e.g. wait, spin, backup, etc) with their own action APIs to allow for customized plugin behaviors. But they are able to share some important information that is somewhat high overhead (e.g. TF buffers, costmap subscribers, footprints, etc) so that each behavior won't need to mimic much of the same information.

- Update docs to remove recovery -> behavior
- Update server and package names to behavior
- Update navigation concepts to have a discussion on behavior primitives 
- Update plugin API to behaviors rather than recoveries
- Think about what additional primitive behaviors might be nice to add (e.g. dock, assisted teleop, make a random move, follow the leader, etc) and file tickets to accomplish
- Remove recovery.hpp and have each recovery implement its own simple action server, this cycle frequency thing doesn't make sense for most behaviors.  

Perhaps provide some basic behaviors like 
- [ ] rotate to sp. heading
- [ ] Drive on heading for X distance (recommission backup plugin)
- [ ] assisted teleop
- [ ] "dance" or some example HRI behavior
- [ ] Back out of recent buffer of commands bc bad situation as recovery, then retry with another algo

**Comment by MOLOCH-dev** [comment]
@SteveMacenski With your guidance, I have tried to do something similar for Assisted  Teleop [PR #2575](https://github.com/ros-planning/navigation2/pull/2575)
Does that seems like a reasonable approach for a behaviour server? I could get started on this
