### ISSUE TITLE
Create bot for backporting PRs to released distributions on maintainer request, other automation needs

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2593]
I've seen this in action in other ROS 2 core repos, I'd like to see if that would make sense here as well to make maintenance of this repo easier for N distributions at once. 

Potentially also a bot for incrementing up the package.xml files and blooming it up?

**Comment by SteveMacenski** [comment]
https://github.com/ros2/ros2_documentation/blob/rolling/.mergify.yml

https://docs.mergify.io/

https://mergify.io/features/backports

**Comment by tylerjw** [comment]
Cool.  I will look into using some of these with MoveIt ( I might just copy some of what you are already doing, they look really nice ).
