### ISSUE TITLE
h => hpp conversion

### ISSUE THREAD

**Issue by Nickolaim** [ros-planning/navigation2#260]
While running `colcon test` I've noticed that for many packages `cppcheck` fails with error like below

```
[include/<file>.h:<line>]: (error: syntaxError) Code '<c++ code, like namespace declaration>' is invalid C code. Use --std or --language to configure the language.
```
The solution I propose is to rename `.h` files to `.hpp` files and update the references.

If you agree on the approach I can do the change.

This is the list of affected packages:
```
$ grep -R -F "is invalid C code" --include=stdout.log | sed -e 's/\/.*$//' | sort -u
costmap_queue
dwb_core
dwb_critics
dwb_plugins
nav2_costmap_2d
nav_2d_utils
nav2_util
nav2_voxel_grid
```

**Comment by crdelsey** [comment]
That looks like new behavior with the latest versions of `cppcheck` Your approach makes sense to me. Go ahead and submit a PR when you are ready.

Thanks for the help!
