### ISSUE TITLE
Re-enable costmap parameter to choose layers

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#262]
PR #235 disabled the parameters to select which costmap layers are to be loaded.

The implementation used to set the parameters to a default value on the node and then read them later in the code. Frequently, the parameters were not finished being set by the time they were to be read, resulting in exceptions being thrown, or no layers being loaded.

The race condition needs to be fixed and the change PR #235 made to costmap_2d_ros.cpp needs to be undone.

**Comment by bpwilcox** [comment]
Resolved with #302
