### ISSUE TITLE
Delete nav2_controller_example

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#263]
Now that the DWB controller is working, we can delete nav2_controller_example.

When this is done, the reference to the controller should also be deleted from nav2_bringup/launch/core.launch.py

This example controller will eventually be replaced by a functional carrot controller as mentioned in #202

**Comment by SteveMacenski** [comment]
I'm fairly certain this was done already in a recently merged PR

**Comment by crdelsey** [comment]
You're right! I think that was the next commit after I submitted this :-)
