### ISSUE TITLE
Change the timeout parameter in map_saver

### ISSUE THREAD

**Issue by olmerg** [ros-planning/navigation2#2637]
## Bug report

**Required Info:**

- Operating System:
Ubuntu 20.04
- ROS2 Version:
foxy binaries

- DDS implementation:
  - ciclone

#### Steps to reproduce issue
running slam_toolbox write the command to save the map changind the timeout parameter

```
ros2 run nav2_map_server map_saver_cli -f ~/lma_ws/map --ros-args -p save_map_timeout:=5
```
This command return timeout immediately. The expected command that should work( duration from second expect double) 

```
ros2 run nav2_map_server map_saver_cli -f ~/lma_ws/map --ros-args -p save_map_timeout:=5.0
[INFO] [1634752426.881060327] [map_saver]: 
        map_saver lifecycle node launched. 
        Waiting on external lifecycle transitions to activate
        See https://design.ros2.org/articles/node_lifecycle.html for more information.
[INFO] [1634752426.881210272] [map_saver]: Creating
[ERROR] [1634752427.100389722] [map_saver_cli]: Unexpected problem appear: expected [integer] got [double]
```

#### Expected behavior
Increase the timeout of save a map
#### Actual behavior
The timeout can not be changed, I think that is the type of data in the moment to create the parameter in [constructor](https://github.com/ros-planning/navigation2/blob/main/nav2_map_server/src/map_saver/map_saver.cpp#L50)

**Comment by SteveMacenski** [comment]
@AlexeyMerzlyakov please address
