### ISSUE TITLE
GoalUpdater missing in behavior tree palette for Groot in Foxy

### ISSUE THREAD

**Issue by Kaetera** [ros-planning/navigation2#2643]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04
- ROS2 Version:   - 
- Version or commit hash:  ros-foxy-nav2-bt-navigator  0.4.7-1focal.20211005.233007
- DDS implementation: CycloneDDS

This prevents to display in Groot any behavior tree that use a GoalUpdater node.

#### Steps to reproduce issue
0. Create a BTree with a GoalUpdater node:
```
<root main_tree_to_execute="MainTree">
  <BehaviorTree ID="MainTree">  
      <GoalUpdater input_goal="{goal}" output_goal="{updated_goal}"/>
  </BehaviorTree>
</root>
```
1. Install Groot from source (classic non-ROS version: https://github.com/BehaviorTree/Groot)
2. Run Groot app
3. Load the above tree following the instructions at https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_behavior_tree/groot_instructions.md
    3a. Load the default behavior tree palette that is shipped in navigation2 (https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_behavior_tree/nav2_tree_nodes.xml)
    3b. Import the minimal BTree above

#### Expected behavior
The import succeed and the tree is displayed in Groot:
![image](https://user-images.githubusercontent.com/17005540/138491932-1a69c203-1163-49f6-a44b-9efd69c78ccb.png)

#### Actual behavior
The import of the tree fails with the following message:
![image](https://user-images.githubusercontent.com/17005540/138491601-cf5cf8f8-e4e9-444a-88c1-a14b90cbc3b7.png)

#### Additional information
The import fails because this node is note listed in the palette shipped for Foxy.
A simple fix is to add it in https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_behavior_tree/nav2_tree_nodes.xml as it has already been done in the `main `branch :) 

```
    <Decorator ID="GoalUpdater">
      <input_port name="input_goal">Original goal in</input_port>
      <output_port name="output_goal">Output goal set by subscription</output_port>
    </Decorator>

```

**Comment by WinstonHChou** [comment]
Was the dpkg of nav2-behavior-tree containing this commit released?

**Comment by SteveMacenski** [comment]
Foxy is no longer a supported distribution.
