### ISSUE TITLE
Navigation2 codestyle

### ISSUE THREAD

**Issue by pschalkwijk** [ros-planning/navigation2#2647]
I'm working with the navigation2 package, and am interested in using the same codestyle.
Can you share the clang format you are using, or the codestyle rules so I can create my own?

**Comment by Ryanf55** [comment]
PS: `/opt/ros/rolling/bin/ament_uncrustify src/navigation2 --reformat` in your workspace to format all your changes. 
If anyone has recommendations to get this integrated to editor like vscode, it would be nice to add it to Nav2's contributing guidelines.
