### ISSUE TITLE
SmacPlanner Plugins not being correctly exported

### ISSUE THREAD

**Issue by musamarcusso** [ros-planning/navigation2#2650]
Hi,

when using the Debian package for `galactic` we noticed that the `nav2_smac_planner` plugins (like the `nav2_smac_planner/SmacPlannerHybrid`) could not be loaded or found. 
I have an impression it may have to do with this [line](https://github.com/ros-planning/navigation2/blob/0f6f49a3633de66db7cdf5f60ecbb951fea5883f/nav2_smac_planner/package.xml#L37) on the `package.xml` file.

Instead of 
```xml
<export>
    <build_type>ament_cmake</build_type>
    <nav2_core plugin="${prefix}/global_planner_plugin.xml" />
</export>
```

it should probably be

```xml
<export>
    <build_type>ament_cmake</build_type>
    <nav2_core plugin="${prefix}/smac_plugin.xml" />
    <nav2_core plugin="${prefix}/smac_plugin_2d.xml" />
</export>
```

right?

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/2582/commits/4c2b5ae82ebd04a0ca2ba3d5ae326885e66967bc This will be merged into master shortly. Then will backport and release to distributions with a larger sync
