### ISSUE TITLE
[Turtlebot3] Wrong Visualization in RViz and Nav2 doesn't work

### ISSUE THREAD

**Issue by Niitoge** [ros-planning/navigation2#2651]
**Required Info:**

- Operating System:
  - Ubuntu 20.04.3
- Installation type:
  - binaries (apt)
- ROS Version
  - ROS2 Foxy Fitzroy
- Version or commit hash:
  - Patch Release 6.1 (commit ID 3934568d4c50aebe186d7bac101e5b4686f16ce2)
- Laser unit:
  - 360 Laser Distance Sensor LDS-01 (ROBOTIS/Turtlebot3)
  
#### Steps to reproduce issue
* Installed ROS2 according to the [setup by ROBOTIS](https://emanual.robotis.com/docs/en/platform/turtlebot3/sbc_setup/#sbc-setup)
* Updated and upgrade everything (to get the Foxy Patch 6.1 because Foxy 6.0 had [issues](https://github.com/ros2/rviz/issues/782) with some topics in RViz)
* Install Nav2 via *apt* following the tutorial on the [Nav2 Wiki](https://navigation.ros.org/build_instructions/index.html)
* Install the slam_toolbox via *apt* following the tutorial on the [Nav2 Wiki](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html)
* Commands entered: 
```
source /opt/ros/foxy/setup.bash # in every terminal
export TURTLEBOT3_MODEL=burger
ros2 launch turtlebot3_bringup robot.launch.py 
ros2 launch nav2_bringup navigation_launch.py
ros2 launch slam_toolbox online_async_launch.py
ros2 launch nav2_bringup rviz_launch.py    # from remote PC
```

#### Expected behavior

Getting a live map feed as well as odometry and tf data in RViz2 

#### Actual behavior

When entering:
```
ros2 launch nav2_bringup rviz_launch.py
```
I receive this all the time
![](https://i.imgur.com/yXr4lGA.png)

And the RViz looks like this:
![](https://i.imgur.com/dUeTD8r.png)

Although the map updates, the visualization is wrong and Nav2 doesn't seem to work (see RViz pic below left)

#### Additional information

When entering:
```
ros2 launch nav2_bringup navigation_launch.py
```
I receive this messages all the time:
![](https://i.imgur.com/33pljpp.png)

And when entering:
```
ros2 launch slam_toolbox online_async_launch.py
# or
ros2 launch slam_toolbox online_sync_launch.py
```
![](https://i.imgur.com/484aW2P.png)

I hope you can help me, thanks in advance :)

https://github.com/SteveMacenski/slam_toolbox/issues/447

**Comment by SteveMacenski** [comment]
OK, let me know

**Comment by SteveMacenski** [comment]
Any update?

**Comment by Niitoge** [comment]
Unfortunately I was unable to continue my work until now.
I recently tried to [Build and Install Nav2](https://navigation.ros.org/build_instructions/index.html#build-instructions) but it didn't help.
Currently I'm working on the [ROS 2 binary packages](https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Binary.html).

**Comment by SteveMacenski** [comment]
You're going to need to provide much more detailed information then, I don't see this on my side and I haven't heard anyone else running into similar issues. It's almost certainly setup related, but there's not much I can do with vague descriptions

**Comment by Gianstiff** [comment]
Hi!
I'm following [this tutorial](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html) and I can confirm that with a similar setup (on a turtlebot3) I'm having the same issue when executing:

`ros2 launch nav2_bringup navigation_launch.py`

![image](https://user-images.githubusercontent.com/47113861/153008834-6cf56ed8-848f-43e5-8c06-9e36f103ecf0.png)
