### ISSUE TITLE
Error with NavFn Planner and DWB Planner in Navigation 2

### ISSUE THREAD

**Issue by staredeath** [ros-planning/navigation2#2655]
I have a project with Nav2. When I run file Navigation in Nav2 on my AGV. The Agv has problem such as Video: [https://youtu.be/ximboAbydjE](url) 
I using ROS2 Foxy with Ubuntu 20.04
Can you help me ??? I thick It is a problem with DWB planner but I don't know how to fix it. Anyone has experiences with the same problem before???

**Comment by SteveMacenski** [comment]
Ask on ros answers
