### ISSUE TITLE
Error when implement others planner with Nav2

### ISSUE THREAD

**Issue by staredeath** [ros-planning/navigation2#2656]
- Operating System: 20.04 LTS
- ROS2 Version: ROS2 Foxy

When I try to implement nav2_sbpl_lattice_planner with Nav2. I have a error:

`[planner_server-2] [INFO] [1635821905.645509150] [planner_server]: Created global planner plugin GridBased of type nav2_sbpl_lattice_planner/SBPLLatticePlanner
[planner_server-2] [INFO] [1635821905.645612056] [planner_server]: Name is GridBased
[planner_server-2] [ERROR] [1635821905.648488535] []: Caught exception in callback for transition 10
[planner_server-2] [ERROR] [1635821905.648516306] []: Original error: ERROR: unable to open 
[planner_server-2] [WARN] [1635821905.648541357] []: Error occurred while doing error handling.
[planner_server-2] [FATAL] [1635821905.648551020] [planner_server]: Lifecycle node planner_server does not have error state implemented
[lifecycle_manager-6] [ERROR] [1635821905.649321741] [lifecycle_manager_navigation]: Failed to change state for node: planner_server
[lifecycle_manager-6] [ERROR] [1635821905.649381940] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
`
Can you help me to solve this problem ??? Is a problem with Nav2, right ???

**Comment by SteveMacenski** [comment]
@staredeath please do not file superfluous tickets on projects implementing plugins for specific uses. ROS Answers is the appropriate venue for questions. Nav2 repo is for Nav2 development and maintenance only.
