### ISSUE TITLE
Error when build Navigation2 from source

### ISSUE THREAD

**Issue by staredeath** [ros-planning/navigation2#2657]
- Operating System: Ubuntu 20.04
- ROS2 Version: Foxy

When I build Navigation2 main branch from Github to my computer and build it, It have a error:
[https://i0.wp.com/s1.uphinh.org/2021/11/02/Screenshot-from-2021-11-02-16-06-23.png](https://i0.wp.com/s1.uphinh.org/2021/11/02/Screenshot-from-2021-11-02-16-06-23.png)

Can anyone help me ???

`

**Comment by padhupradheep** [comment]
Did you follow the [build instructions](https://navigation.ros.org/build_instructions/index.html)?

Could you please ask this question in answers.ros.org ? This is more relevant there!
