### ISSUE TITLE
nav2 and waypoint node stops when reached the second goal in rviz

### ISSUE THREAD

**Issue by raidhu** [ros-planning/navigation2#2685]
what will be the reason for this issue.

bot doesn't complete more than 2 goals what would be the reason.

**Comment by SteveMacenski** [comment]
You will need to include much more detailed information and properly fill in the issue template.

**Comment by SteveMacenski** [comment]
Any update?

**Comment by SteveMacenski** [comment]
Closing after 2 weeks of nonresponsiveness. If you feel like providing more detail, we can reopen and discuss
