### ISSUE TITLE
Turning radius gets downsampled/adapted  even when "downsample_costmap" param is deactivated.

### ISSUE THREAD

**Issue by salmagro** [ros-planning/navigation2#2686]
## Bug report

**Required Info:**
- Operating System:
  - Debian GNU/Linux 10 (buster)
- ROS2 Version:
  - `Rolling`
- Version or commit hash:
  - Branch `main`: `c65532f7e537c05c8d02c45099c42cf7ed8954bb`

#### Steps to reproduce the issue

Assign parameters to:
```
/planner_server:
    GridBased:
      downsample_costmap: false
      downsampling_factor: 4
```
The `downsampling_factor` is applied even though the `downsample_costmap` is set on  `False`. 
See: https://github.com/ros-planning/navigation2/blob/0abd2699e86fc27ed8d1c56931f3441c2208da12/nav2_smac_planner/src/smac_planner_hybrid.cpp#L134-L140

#### Actual behavior
For testing, I am changing the `downsampling_factor` while `downsample_costmap` is disabled. As can be seen in the images, the factor affects the turning radius.

![2021-11-17_16-53_ex1](https://user-images.githubusercontent.com/52298571/142389884-782090ef-f383-455b-a80a-721d72324f5f.png)
![2021-11-17_17-03_ex2](https://user-images.githubusercontent.com/52298571/142389880-e7778058-043f-4c90-9437-873e08950910.png)
![2021-11-17_17-09_ex3](https://user-images.githubusercontent.com/52298571/142389873-33e2a7c0-04ff-4485-84b7-e3a6acdb26b5.png)

#### Feature description

Check the parameter flag `downsample_costmap` in L134-L140. Proposed solution:

```cpp
  // convert to grid coordinates
  const double minimum_turning_radius_global_coords = _search_info.minimum_turning_radius;
  if (!_downsample_costmap)
  {
	  _downsampling_factor = 1;
  }
  _search_info.minimum_turning_radius =
		  _search_info.minimum_turning_radius / (_costmap->getResolution() * _downsampling_factor);
  _lookup_table_dim = static_cast<float>(_lookup_table_size)
		  / static_cast<float>(_costmap->getResolution() * _downsampling_factor);
`

```

**Comment by SteveMacenski** [comment]
Indeed, though if you specify a parameter that is actively incorrect for your situation, that is not good either. But I can see the point of doing some casual testing you'd get funky results. I'd love a PR to fix that. 

You could set it to `1` in `on_configure()` if the downsampler parameter is `false` so that even if you did set it to something else, it would be thrown out and be OK. You'd have to add that same logic in the dyanamic parameters callback.

**Comment by SteveMacenski** [comment]
Merging shortly
