### ISSUE TITLE
Implement Keepout Zone and Speed Limit TOGETHER

### ISSUE THREAD

**Issue by staredeath** [ros-planning/navigation2#2702]
**Required Info:**
- Operating System:
  - Ubuntu 20.04 LTS
- ROS2 Version:
  - ROS2 Galactic

Hello, Could any ways to implement keepout zone and speed limit together in ROS2 Galactic? If have, can you show me or give me some instructions ???

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers, but you should be able to at the same time using the 2 tutorials together
