### ISSUE TITLE
Can't open gazebo11,in tb3_simulation_launch.py

### ISSUE THREAD

**Issue by fantasyplus** [ros-planning/navigation2#2730]
**operating system:** Ubuntu20.04
**ros disto:** rolling
**nav version:** main branch

![Screenshot from 2021-12-07 15-11-37](https://user-images.githubusercontent.com/34959626/144983204-d8da3458-cfa0-4e6c-8861-727f71f49980.png)

![Screenshot from 2021-12-07 15-11-34](https://user-images.githubusercontent.com/34959626/144983212-e0c5cf87-8e97-4320-ae3e-9302df015a90.png)

I tried this demo with the virtual machine yesterday and encountered the same problem. I thought it's the virtual machine reason.

Today, I install the 20.04 physically. 

The result is the same,Gazebo can't be opened.

 And error is same,**[composed_bringup-9] [INFO] [1638861125.504970819] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist**

Can someone tell me why?

**Comment by SteveMacenski** [comment]
I don't see this on my side. Search up your log files and see what's missing, my guess there's something else going on there, like Gazebo had other errors or wasn't able to load the robot into simulation. Do you see the TB3 and data being produced by it in Gazebo, irregardless of Nav2? You could very well just be missing the TB3 package / gazebo model paths.

**Comment by SteveMacenski** [comment]
Have you figured out your issue?

**Comment by SteveMacenski** [comment]
Closing from lack of response and not able to reproduce locally or in CI. Happy to discuss if the user comes back or on ROS Answers. Sounds like its a gazebo issue that is hasn't totally spawned or the something is crashing. Logging would indicate the second, seeing teh gazebo world would indicate the first

**Comment by Nathan24zz** [comment]
I also got the same error (the gazebo can't be opened when running **ros2 launch nav2_bringup tb3_simulation_launch.py**).
Error that show in terminal like **[local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist**.

**OS**: Ubuntu 20.04
**ros distro**: foxy

**Comment by vaibhavkad-peppermint** [comment]
**I got the same error** 
Gazebo does not open when 
`run ros2 launch nav2_bringup tb3_simulation_launch.py`
**Error**: [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist

When opened separately Gazebo starts quickly

OS: Ubuntu 20.04
ros distro: foxy

![image](https://user-images.githubusercontent.com/87687973/150629812-70751568-7ead-426c-a354-97c32c6847c5.png)

**Comment by irfanbadshah** [comment]
I have the same issue.. 

Any idea on how to fix it?
ros distro: galactic

**Comment by Ryujiyasu** [comment]
Hi @miku54 you should check GAZEBO_MODEL_PATH, 
I checked below
GAZEBO_MODEL_PATH ☓ -> no working
GAZEBO_MODEL_PATH ○ -> working 

Ex.My Env
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/home/ubuntu/data/nav2_ws/src/turtlebot3_simulations/turtlebot3_gazebo/models

Thank you!!

**Comment by Ryujiyasu** [comment]
OS: Ubuntu 20.04
ros distribution: galactic

**Comment by Ryujiyasu** [comment]
https://github.com/ros-planning/navigation2/issues/2757

**Comment by miku54** [comment]
> #2757

I tried doing this, but still can't start gazebo from the command line in the terminal.       ><

**Comment by miku54** [comment]
> #2757

Solved! I added an extra '--verbose' thanks! ありがとう！

**Comment by KennySoh** [comment]
I had the same issue. I was trying to run the turtlebot3 simualtion with foxy. 
Seems like there something wrong with gazebo 

I managed to fix it by following the instruction below.

https://classic.gazebosim.org/tutorials?tut=ros2_installing&cat=connect_ros
```
source /usr/share/gazebo/setup.sh.  #this seems to fix gazebo
killall gzserver 
ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py. #Able to start gazebo!
```

**Comment by cliffe10086** [comment]
may you can check if the gzserver is already running,
$ ps aux | grep gzserver
if there are 2 msg(indicating there is already running)
$ pkill -f gzserver
then all right ,try run nav2 again
