### ISSUE TITLE
[CostmapLayer] clearArea inverted param seems... inverted

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#2770]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04
- ROS2 Version: Galactic
- Version or commit hash: last galactic sync
- DDS implementation: Cyclone

#### Steps to reproduce issue

Call `CostmapLayer::clearArea`
https://github.com/ros-planning/navigation2/blob/b201d058a7b15f1786c57afe69d079ac5d502018/nav2_costmap_2d/src/costmap_layer.cpp#L64-L81

#### Expected behavior
https://github.com/ros-planning/navigation2/blob/b201d058a7b15f1786c57afe69d079ac5d502018/nav2_costmap_2d/include/nav2_costmap_2d/costmap_layer.hpp#L78-L81

#### Actual behavior
The opposite!

#### Additional information
Propably this line should have `==` instead of `!=`
https://github.com/ros-planning/navigation2/blob/b201d058a7b15f1786c57afe69d079ac5d502018/nav2_costmap_2d/src/costmap_layer.cpp#L72

----

**Comment by SteveMacenski** [comment]
Agreed, please submit a PR and a website migration guide update explaining the inversion
