### ISSUE TITLE
namespaces and costmaps in multirobot scenarios

### ISSUE THREAD

**Issue by hndr-k** [ros-planning/navigation2#2793]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy and Galactic binaries 
- Version or commit hash:
  - apt binaries
- DDS implementation:
  - FastRTPS and CycloneDDS
#### Steps to reproduce issue

```
Start the multirobot launchfile in the nav2_bringup package
```

#### Expected behavior
Two fully functioning Navigation2 instances running with corresponding costmaps.
#### Actual behavior
It seems like the costmap server (local and global) does not function with namespaces since they dont receive a map.
The map server only publishes the map once and does not publish the map again so the costmap doesn't receive a map and can not be published. Also the path planning is very off and mostly works on one robot while the other one can not be navigated while using the default parameter set.
#### Additional information
I am currently writing my bachelor thesis about multi-robot pathplanning in ros2 and I am intending to use costmaps and navigation2 as the underlying framework, so I would really appreciate any help I can get because it seems like i can not resolve this issue on my own. I looked for possible reasons within the source code but thusfas I could not find any. My last ressort would be trying to launch a self written map_server for each robot.

----

**Comment by SteveMacenski** [comment]
See https://github.com/ros-planning/navigation2/issues/2719 there is some already noted issues with this we haven't started looking at yet.
