### ISSUE TITLE
Not able to execute navigation2 launch file

### ISSUE THREAD

**Issue by Gianstiff** [ros-planning/navigation2#2810]
I'm following [this tutorial](https://navigation.ros.org/tutorials/docs/navigation2_with_slam.html) and I can confirm that with a similar setup (on a turtlebot3) such as [this](https://github.com/ros-planning/navigation2/issues/2651) closed issue and I'm having the same problem when executing:

`ros2 launch nav2_bringup navigation_launch.py`

![image](https://user-images.githubusercontent.com/47113861/153013445-472697ae-b2b6-4b27-bf42-8c0efd543d4d.png)

**Comment by SteveMacenski** [comment]
Ask on ROS Answers

**Comment by Gianstiff** [comment]
> Ask on ROS Answers

Ok

> but looks like gazebo isn't up / happy with the tree you're using. That means the nothing is publishing the odom->base_link which comes from gazebo / RL

@SteveMacenski thanks for the feedback, but actually I'm working with a physical robot, not the simulated one
