### ISSUE TITLE
Nav2 Fails / Weird behaviour when trying to navigate the robot to a point that is not in front

### ISSUE THREAD

**Issue by rjrs23** [ros-planning/navigation2#2846]
Hello, 

I have managed to bring up my robot on ROS2 as per the requirements of the nav2 stack.

**Observed Behaviour**
- Robot navigates fine when the point to navigate is in front of the robot
- Robot tries to take a weird path / and tries to keep circling the goal poin if the new goal point is beind the robot

**Expected Behaviour**
- Robot should be able to navigate to the nav2 goal published either in front or behind the robot

**What I have checked**
- Accuracy of odometry data: The odometry data generated by my drive is accurate and as per ros standards
- Lidar data: I am using an existing ros2 drive for the lidar
- Nav 2 Configuration: I have not edited any Nav2 params except the robot_radius and max/min velocities

**Where I need help:**
- I am unable to understand the reason behind the behaviour being observed and need help to isolate the issue

**My Config**
- Nav2 installed using ubuntu 20.04 via apt
- Robot: custom robot base
- Lidar: RpLidar A2M8
- Robot runs on a Intel NUC (Quad core Atom Processor, 4GB RAM)

Please find attached below a screengrab of rviz and a video of the actual robot. 

https://user-images.githubusercontent.com/100414238/158054415-9b0ef6d8-31ea-4af0-a329-ce3fa1291159.mp4

https://user-images.githubusercontent.com/100414238/158054419-47e726d2-c6bc-4243-a906-5be20cae09cb.mp4

**Comment by SteveMacenski** [comment]
Please ask on ROS Answers, this is not the right forum for configuration help.
