### ISSUE TITLE
Cannot implement Speed Limit like Navigation2 Tutorials

### ISSUE THREAD

**Issue by staredeath** [ros-planning/navigation2#2849]
I'm using this project in my real robot. unfortunately I can't use the speed limit zone. I followed the instructions [here](https://navigation.ros.org/tutorials/docs/navigation2_with_speed_filter.html)
Here is my yaml file:
`               amcl:
                ros__parameters:
                  use_sim_time: True
                  alpha1: 0.2
                  alpha2: 0.2
                  alpha3: 0.2
                  alpha4: 0.2
                  alpha5: 0.2
                  base_frame_id: "base_footprint"
                  beam_skip_distance: 0.5
                  beam_skip_error_threshold: 0.9
                  beam_skip_threshold: 0.3
                  do_beamskip: false
                  global_frame_id: "map"
                  lambda_short: 0.1
                  laser_likelihood_max_dist: 2.0
                  laser_max_range: 100.0
                  laser_min_range: -1.0
                  laser_model_type: "likelihood_field"
                  max_beams: 60
                  max_particles: 4000
                  min_particles: 500
                  odom_frame_id: "odom"
                  pf_err: 0.05
                  pf_z: 0.99
                  recovery_alpha_fast: 0.0
                  recovery_alpha_slow: 0.0
                  resample_interval: 1
                  robot_model_type: "differential"
                  save_pose_rate: 0.5
                  sigma_hit: 0.2
                  tf_broadcast: true
                  transform_tolerance: 1.0
                  update_min_a: 0.05
                  update_min_d: 0.05
                  z_hit: 0.5
                  z_max: 0.05
                  z_rand: 0.5
                  z_short: 0.05
                  scan_topic: scan
              
              amcl_map_client:
                ros__parameters:
                  use_sim_time: True
              
              amcl_rclcpp_node:
                ros__parameters:
                  use_sim_time: True
              
              bt_navigator:
                ros__parameters:
                  use_sim_time: True
                  global_frame: map
                  robot_base_frame: base_link
                  odom_topic: /odom
                  bt_loop_duration: 10
                  default_server_timeout: 20
                  enable_groot_monitoring: True
                  groot_zmq_publisher_port: 1666
                  groot_zmq_server_port: 1667
                  # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
                  # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
                  # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
                  # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
                  plugin_lib_names:
                  - nav2_compute_path_to_pose_action_bt_node
                  - nav2_compute_path_through_poses_action_bt_node
                  - nav2_follow_path_action_bt_node
                  - nav2_back_up_action_bt_node
                  - nav2_spin_action_bt_node
                  - nav2_wait_action_bt_node
                  - nav2_clear_costmap_service_bt_node
                  - nav2_is_stuck_condition_bt_node
                  - nav2_goal_reached_condition_bt_node
                  - nav2_goal_updated_condition_bt_node
                  - nav2_initial_pose_received_condition_bt_node
                  - nav2_reinitialize_global_localization_service_bt_node
                  - nav2_rate_controller_bt_node
                  - nav2_distance_controller_bt_node
                  - nav2_speed_controller_bt_node
                  - nav2_truncate_path_action_bt_node
                  - nav2_goal_updater_node_bt_node
                  - nav2_recovery_node_bt_node
                  - nav2_pipeline_sequence_bt_node
                  - nav2_round_robin_node_bt_node
                  - nav2_transform_available_condition_bt_node
                  - nav2_time_expired_condition_bt_node
                  - nav2_distance_traveled_condition_bt_node
                  - nav2_single_trigger_bt_node
                  - nav2_is_battery_low_condition_bt_node
                  - nav2_navigate_through_poses_action_bt_node
                  - nav2_navigate_to_pose_action_bt_node
                  - nav2_remove_passed_goals_action_bt_node
                  - nav2_planner_selector_bt_node
                  - nav2_controller_selector_bt_node
                  - nav2_goal_checker_selector_bt_node
              
              bt_navigator_rclcpp_node:
                ros__parameters:
                  use_sim_time: True
              
              controller_server:
                ros__parameters:
                  use_sim_time: True
                  controller_frequency: 20.0
                  min_x_velocity_threshold: 0.001
                  min_y_velocity_threshold: 0.5
                  min_theta_velocity_threshold: 0.001
                  progress_checker_plugin: "progress_checker"
                  goal_checker_plugin: "goal_checker"
                  controller_plugins: ["FollowPath"]
                  speed_limit_topic: "/speed_limit"
              
                  progress_checker:
                    plugin: "nav2_controller::SimpleProgressChecker"
                    required_movement_radius: 0.5
                    movement_time_allowance: 10.0
                  goal_checker:
                    plugin: "nav2_controller::SimpleGoalChecker"
                    xy_goal_tolerance: 0.25
                    yaw_goal_tolerance: 0.25
                    stateful: True
                  FollowPath:
                    plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
                    desired_linear_vel: 0.5
                    max_linear_accel: 2.5
                    max_linear_decel: 2.5
                    lookahead_dist: 0.6
                    min_lookahead_dist: 0.3
                    max_lookahead_dist: 0.9
                    lookahead_time: 1.5
                    rotate_to_heading_angular_vel: 1.8
                    transform_tolerance: 0.1
                    use_velocity_scaled_lookahead_dist: false
                    min_approach_linear_velocity: 0.05
                    use_approach_linear_velocity_scaling: true
                    max_allowed_time_to_collision: 1.0
                    use_regulated_linear_velocity_scaling: true
                    use_cost_regulated_linear_velocity_scaling: false
                    regulated_linear_scaling_min_radius: 0.9
                    regulated_linear_scaling_min_speed: 0.25
                    use_rotate_to_heading: true
                    rotate_to_heading_min_angle: 0.785
                    max_angular_accel: 3.2
                    cost_scaling_dist: 0.3
                    cost_scaling_gain: 1.0
                    inflation_cost_scaling_factor: 3.0
                    
              controller_server_rclcpp_node:
                ros__parameters:
                  use_sim_time: True
              
              local_costmap:
                local_costmap:
                  ros__parameters:
                    update_frequency: 5.0
                    publish_frequency: 2.0
                    global_frame: odom
                    robot_base_frame: base_link
                    use_sim_time: True
                    rolling_window: true
                    width: 6
                    height: 6
                    resolution: 0.05
                    robot_radius: 0.5
                    footprint: "[[-0.45,-0.28],[-0.45,0.28],[0.45,0.28],[0.45,-0.28]]"
                    footprint_padding: 0.01
                    plugins: ["voxel_layer", "inflation_layer"]
                    filters: ["keepout_filter"]
                    inflation_layer:
                      plugin: "nav2_costmap_2d::InflationLayer"
                      cost_scaling_factor: 30.0
                      inflation_radius: 1.5
                    voxel_layer:
                      plugin: "nav2_costmap_2d::VoxelLayer"
                      enabled: True
                      publish_voxel_map: True
                      origin_z: 0.0
                      z_resolution: 0.05
                      z_voxels: 16
                      max_obstacle_height: 1.0
                      mark_threshold: 0
                      observation_sources: scan_marking scan_clearing scan_cam_1_marking scan_cam_1_clearing scan_cam_2_marking scan_cam_2_clearing
                      scan_marking:
                        topic: /scan
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 3.0
                        raytrace_min_range: 0.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_clearing:
                        topic: /scan
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 3.0
                        raytrace_min_range: 0.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_1_clearing:
                        topic: /scan_cam_1
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_1_marking:
                        topic: /scan_cam_1
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_2_clearing:
                        topic: /scan_cam_2
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_2_marking:
                        topic: /scan_cam_2
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                    static_layer:
                      map_subscribe_transient_local: True
                    keepout_filter:
                      plugin: "nav2_costmap_2d::KeepoutFilter"
                      enabled: True
                      filter_info_topic: "/costmap_filter_info"
                    always_send_full_costmap: True
                local_costmap_client:
                  ros__parameters:
                    use_sim_time: True
                local_costmap_rclcpp_node:
                  ros__parameters:
                    use_sim_time: True
              
              global_costmap:
                global_costmap:
                  ros__parameters:
                    update_frequency: 1.0
                    publish_frequency: 1.0
                    global_frame: map
                    robot_base_frame: base_link
                    use_sim_time: True
                    footprint: "[[-0.45,-0.28],[-0.45,0.28],[0.45,0.28],[0.45,-0.28]]"
                    footprint_padding: 0.01
                    robot_radius: 0.5
                    resolution: 0.025
                    track_unknown_space: true
                    plugins: ["static_layer", "obstacle_layer", "inflation_layer", "keepout_filter"]
                    filters: ["speed_filter"]
                    filters: ["keepout_filter"]
                    obstacle_layer:
                      plugin: "nav2_costmap_2d::ObstacleLayer"
                      enabled: True
                      observation_sources: scan_marking scan_clearing scan_cam_1_marking scan_cam_1_clearing scan_cam_2_marking scan_cam_2_clearing
                      scan_marking:
                        topic: /scan
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 3.0
                        raytrace_min_range: 0.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_clearing:
                        topic: /scan
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 3.0
                        raytrace_min_range: 0.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_1_clearing:
                        topic: /scan_cam_1
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_1_marking:
                        topic: /scan_cam_1
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_2_clearing:
                        topic: /scan_cam_2
                        max_obstacle_height: 1.0
                        clearing: True
                        marking: False
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                      scan_cam_2_marking:
                        topic: /scan_cam_2
                        max_obstacle_height: 1.0
                        clearing: False
                        marking: True
                        data_type: "LaserScan"
                        raytrace_max_range: 6.0
                        raytrace_min_range: 4.0
                        obstacle_max_range: 2.5
                        obstacle_min_range: 0.0
                    static_layer:
                      plugin: "nav2_costmap_2d::StaticLayer"
                      map_subscribe_transient_local: True
                    inflation_layer:
                      plugin: "nav2_costmap_2d::InflationLayer"
                      cost_scaling_factor: 5.0
                      inflation_radius: 0.55
                    speed_filter:
                      plugin: "nav2_costmap_2d::SpeedFilter"
                      enabled: True
                      filter_info_topic: "/costmap_filter_info"
                      speed_limit_topic: "/speed_limit"
                      transform_tolerance: 0.1
                    keepout_filter:
                      plugin: "nav2_costmap_2d::KeepoutFilter"
                      enabled: True
                      filter_info_topic: "/costmap_filter_info"
                    always_send_full_costmap: True
                    
                global_costmap_client:
                  ros__parameters:
                    use_sim_time: True
                global_costmap_rclcpp_node:
                  ros__parameters:
                    use_sim_time: True
              
              map_server:
                ros__parameters:
                  use_sim_time: True
                  yaml_filename: "/home/agvteam/robot_ws/src/navigation2/nav2_bringup/bringup/map_rtc.yaml"
              
              map_saver:
                ros__parameters:
                  use_sim_time: True
                  save_map_timeout: 10.0
                  free_thresh_default: 0.25
                  occupied_thresh_default: 0.65
                  map_subscribe_transient_local: True
              
              planner_server:
                ros__parameters:
                  planner_plugins: ["GridBased"]
                  use_sim_time: True
              
                  GridBased:
                    plugin: "nav2_smac_planner/SmacPlannerHybrid"
                    downsample_costmap: false           # whether or not to downsample the map
                    downsampling_factor: 1              # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
                    allow_unknown: true                 # allow traveling in unknown space
                    max_iterations: 1000000             # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
                    max_planning_time: 3.0              # max time in s for planner to plan, smooth
                    motion_model_for_search: "DUBIN"    # Hybrid-A* Dubin, Redds-Shepp
                    angle_quantization_bins: 72         # Number of angle bins for search
                    analytic_expansion_ratio: 3.5       # The ratio to attempt analytic expansions during search for final approach.
                    minimum_turning_radius: 0.30        # minimum turning radius in m of path / vehicle
                    reverse_penalty: 2.0                # Penalty to apply if motion is reversing, must be => 1
                    change_penalty: 1.25                 # Penalty to apply if motion is changing directions (L to R), must be >= 0
                    non_straight_penalty: 3.25          # Penalty to apply if motion is non-straight, must be => 1
                    cost_penalty: 3.5                   # Penalty to apply to higher cost areas when adding into the obstacle map dynamic programming distance expansion heuristic. This drives the robot more towards the center of passages. A value between 1.3 - 3.5 is reasonable.
                    lookup_table_size: 20.0             # Size of the dubin/reeds-sheep distance window to cache, in meters.
                    cache_obstacle_heuristic: true     # Cache the obstacle map dynamic programming distance expansion heuristic between subsiquent replannings of the same goal location. Dramatically speeds up replanning performance (40x) if costmap is largely static.
              
                    smoother:
                      max_iterations: 1000
                      w_smooth: 0.3
                      w_data: 0.2
                      tolerance: 1e-10
                      
              planner_server_rclcpp_node:
                ros__parameters:
                  use_sim_time: True
              
              recoveries_server:
                ros__parameters:
                  costmap_topic: local_costmap/costmap_raw
                  footprint_topic: local_costmap/published_footprint
                  cycle_frequency: 10.0
                  recovery_plugins: ["spin", "backup", "wait"]
                  spin:
                    plugin: "nav2_recoveries/Spin"
                  backup:
                    plugin: "nav2_recoveries/BackUp"
                  wait:
                    plugin: "nav2_recoveries/Wait"
                  global_frame: odom
                  robot_base_frame: base_link
                  transform_timeout: 0.1
                  use_sim_time: true
                  simulate_ahead_time: 2.0
                  max_rotational_vel: 1.0
                  min_rotational_vel: 0.4
                  rotational_acc_lim: 3.2
              
              robot_state_publisher:
                ros__parameters:
                  use_sim_time: True
              
              waypoint_follower:
                ros__parameters:
                  loop_rate: 20
                  stop_on_failure: false
                  waypoint_task_executor_plugin: "wait_at_waypoint"   
                  wait_at_waypoint:
                    plugin: "nav2_waypoint_follower::WaitAtWaypoint"
                    enabled: True
                    waypoint_pause_duration: 2000
`

When I run  the speed limit zone still display but the robot robot does not decelerate.
[image](https://i.imgur.com/zD1H2Rw.pngl)

The terminal is:
`
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [lifecycle_manager-1]: process started with pid [113972]
[INFO] [map_server-2]: process started with pid [113974]
[INFO] [costmap_filter_info_server-3]: process started with pid [113976]
[costmap_filter_info_server-3] [INFO] [1647491552.085614341] [costmap_filter_info_server]: This is costmap filter info publisher
[costmap_filter_info_server-3] [INFO] [1647491552.162655955] [costmap_filter_info_server]: 
[costmap_filter_info_server-3] 	costmap_filter_info_server lifecycle node launched. 
[costmap_filter_info_server-3] 	Waiting on external lifecycle transitions to activate
[costmap_filter_info_server-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-2] [INFO] [1647491552.162908733] [filter_mask_server]: 
[map_server-2] 	filter_mask_server lifecycle node launched. 
[map_server-2] 	Waiting on external lifecycle transitions to activate
[map_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-2] [INFO] [1647491552.163024209] [filter_mask_server]: Creating
[lifecycle_manager-1] [INFO] [1647491552.178695189] [lifecycle_manager_costmap_filters]: Creating
[lifecycle_manager-1] [INFO] [1647491552.182421705] [lifecycle_manager_costmap_filters]: Creating and initializing lifecycle service clients
[lifecycle_manager-1] [INFO] [1647491552.185740930] [lifecycle_manager_costmap_filters]: Starting managed nodes bringup...
[lifecycle_manager-1] [INFO] [1647491552.185814261] [lifecycle_manager_costmap_filters]: Configuring filter_mask_server
[map_server-2] [INFO] [1647491552.198378561] [filter_mask_server]: Configuring
[map_server-2] [INFO] [map_io]: Loading yaml file: /home/agvteam/robot_ws/install/rtcrobot_navigation/share/rtcrobot_navigation/maps/speed_mask.yaml
[map_server-2] [DEBUG] [map_io]: resolution: 0.05
[map_server-2] [DEBUG] [map_io]: origin[0]: -14.8
[map_server-2] [DEBUG] [map_io]: origin[1]: -10.1
[map_server-2] [DEBUG] [map_io]: origin[2]: 0
[map_server-2] [DEBUG] [map_io]: free_thresh: 0
[map_server-2] [DEBUG] [map_io]: occupied_thresh: 1
[map_server-2] [DEBUG] [map_io]: mode: scale
[map_server-2] [DEBUG] [map_io]: negate: 0
[map_server-2] [INFO] [map_io]: Loading image_file: /home/agvteam/robot_ws/install/rtcrobot_navigation/share/rtcrobot_navigation/maps/speed_mask_2.pgm
[map_server-2] [DEBUG] [map_io]: Read map /home/agvteam/robot_ws/install/rtcrobot_navigation/share/rtcrobot_navigation/maps/speed_mask_2.pgm: 488 X 454 map @ 0.05 m/cell
[lifecycle_manager-1] [INFO] [1647491552.228204277] [lifecycle_manager_costmap_filters]: Configuring costmap_filter_info_server
[costmap_filter_info_server-3] [INFO] [1647491552.228471637] [costmap_filter_info_server]: Configuring
[lifecycle_manager-1] [INFO] [1647491552.230381698] [lifecycle_manager_costmap_filters]: Activating filter_mask_server
[map_server-2] [INFO] [1647491552.230527683] [filter_mask_server]: Activating
[map_server-2] [INFO] [1647491552.239366071] [filter_mask_server]: Creating bond (filter_mask_server) to lifecycle manager.
[lifecycle_manager-1] [INFO] [1647491552.344438019] [lifecycle_manager_costmap_filters]: Server filter_mask_server connected with bond.
[lifecycle_manager-1] [INFO] [1647491552.344519840] [lifecycle_manager_costmap_filters]: Activating costmap_filter_info_server
[costmap_filter_info_server-3] [INFO] [1647491552.345066573] [costmap_filter_info_server]: Activating
[costmap_filter_info_server-3] [INFO] [1647491552.345337963] [costmap_filter_info_server]: Creating bond (costmap_filter_info_server) to lifecycle manager.
[lifecycle_manager-1] [INFO] [1647491552.451354948] [lifecycle_manager_costmap_filters]: Server costmap_filter_info_server connected with bond.
[lifecycle_manager-1] [INFO] [1647491552.451424550] [lifecycle_manager_costmap_filters]: Managed nodes are active
[lifecycle_manager-1] [INFO] [1647491552.451454552] [lifecycle_manager_costmap_filters]: Creating bond timer...
`

**Comment by Kaiser-Wang** [comment]
Hi @staredeath, did you figure out why it didn't work? I ran into the same issue in humble. I added speed filter in global costmap but the robot didn't slow down in the speed zone. Then I tried to add speed filter in local costmap and the robot slowed down in the speed zone. Does the speed filter in global costmap only affect global planner but not affect local controller?
