### ISSUE TITLE
Remove dependency on custom ros2/launch

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#285]
#### Summary
The nav2_bringup repo uses TimerActions in the launch file to slow down the process and bring everything up reliably. Unfortunately, TimerActions are not supported yet in the official ros2/launch repo, so we are using a custom version of Launch.

Before we can go into the crystal release and before the ROS build farm can build our stack, this dependency needs to be removed, and the launch files need to work with the official launch tool

**Comment by mkhansen-intel** [comment]
@crdelsey - since we're not using TimerActions, I think we can do this now, correct?

**Comment by crdelsey** [comment]
Yes. I'll do this now.
