### ISSUE TITLE
Add plugins for Quadrotor

### ISSUE THREAD

**Issue by brunopinto900** [ros-planning/navigation2#2876]
Hello all,

Can i add plugins for planners and controlelrs in 3D for quadrotors? How hard it would be given this stack is for 2D navigation.

Thank you.

**Comment by SteveMacenski** [comment]
Can you? Yes, almost definitely, but you're likely to run into some integration challenges. Particularly as it relates to the costmap environmental model. The actual control / planning APIs though are perfectly capable of handling 3D poses / orientations 

Closing ticket, as this is not the current intent / direction of the project. Happy to consider it in the future, but it would have to be matched with a sustained and professional-level development effort.
