### ISSUE TITLE
Multi tb3 simulation not using LiDAR data

### ISSUE THREAD

**Issue by ccpjboss** [ros-planning/navigation2#2883]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Galactic
- Version or commit hash:
  - ros-galactic-navigation2	1.0.8-1focal.20220211.200406
- DDS implementation:
  - 

#### Steps to reproduce issue
Run the `multi_tb3_simulation_launch.py` example from `nav2_bringup` package and proceed to add an obstacle to the gazebo world.

`ros2 launch nav2_bringup multi_tb3_simulation_launch.py  `

#### Expected behavior
The newly added obstacle should be represented in the global costmap, just like in the single turtlebot simulation provided by the launch file `tb3_simulation_launch.py`. (see screenshot below)

![Screenshot from 2022-04-01 12-42-56](https://user-images.githubusercontent.com/33908859/161257026-500527be-3fa4-45fe-82a3-33728f01cf97.png)

#### Actual behavior

When the obstacle is added in the multi robot world, none of the robots can "reflect" the obstacle in the costmap. (see screenshot below).

![Screenshot from 2022-04-01 12-35-53](https://user-images.githubusercontent.com/33908859/161257234-334d3771-ddea-4dad-91b7-25c4f5b7ffc1.png)

#### Additional information

I had already asked a similar [question](https://answers.ros.org/question/398333/detected-object-not-appearing-in-costmap-navigation2/) on ROS Answers, but upon further investigation found the same problem in the  `multi_tb3_simulation_launch.py` so I decided to post here.

**Comment by SteveMacenski** [comment]
Do not cross post, I commented on the thread on ROS Answers and will continue to do so.
