### ISSUE TITLE
the navigator circle around in front of a width wall and stuck there

### ISSUE THREAD

**Issue by yuan-ge** [ros-planning/navigation2#2885]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy source
- Version or commit hash:
  -  foxy-devel
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue

this is my [nav2_params.yaml](https://pastebin.com/FUWQ6C5T)

and this is the rviz of my navigating, as the picture shows, it stuck in front of the wall and circle around.
![image](https://user-images.githubusercontent.com/61228924/161423259-26feb11c-7ab0-4755-b043-802458b2a4cf.png)
more surprising, after some turns of spinning, waiting, running. It just stop in situ and report that navigation is completed!
![image](https://user-images.githubusercontent.com/61228924/161423399-b91a20dc-7f59-413a-8142-b48ff7c40767.png)

#### Expected behavior
the robot should follow the global planner way
#### Actual behavior
getting stuck

**Comment by SteveMacenski** [comment]
Please ask for configuration help on ROS Answers and review the configuration guides on navigation.ros.org
