### ISSUE TITLE
Costmaps header stamps are set to 0

### ISSUE THREAD

**Issue by charlielito** [ros-planning/navigation2#2897]
## Bug report
`/local_costmap/costmap` or `/global_costmap/costmap` topics header stamps are set to 0. Is this somehow intentional?

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Galactic binaries
- Version or commit hash:
  - Galactic binaries 1.0.8-1focal.20220211
- DDS implementation:
  - Cyclone

#### Steps to reproduce issue
Launch the nav2 stack as usual then see `/local_costmap/costmap` or `/global_costmap/costmap` topics header and note that they are set to 0.

#### Expected behavior
Header stamps consistent with system time

#### Actual behavior
Header stamps set to 0

#### Additional information
I see that the header stamp is set [here](https://github.com/ros-planning/navigation2/blob/30b405c58e6d53ba8c96381416bc4679d35a1483/nav2_costmap_2d/src/costmap_2d_publisher.cpp#L129) to 

```c++
  grid_->header.stamp = rclcpp::Time();
```
which AFAIK is the reason it is set to 0.

**Comment by SteveMacenski** [comment]
I don't think it is intentional to be `0`, please submit a PR to implement with the real time!

**Comment by charlielito** [comment]
Done https://github.com/ros-planning/navigation2/pull/2899

**Comment by Jos-Meran** [comment]
Hi there, I have the same problem in ROS2 Foxy. Saw what you did to fix it  (from grid_->header.stamp = rclcpp::Time(); to grid_->header.stamp = clock_->now();), but I can't seem to find the file (costmap_2d_publisher.cpp) where the header stamp is defined. I don't know much about this stuff, but is this something that I can't do locally and has to be fixed directly in the foxy-devel branch of the nav2 package? If so, how could I push this change?

**Comment by SteveMacenski** [comment]
Foxy is EOL and has not receive updates for some time

**Comment by Jos-Meran** [comment]
Oh, so should I install the package from source and use the main branch?
