### ISSUE TITLE
Enabling persistent robot pose across node restarts

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#290]
----
## Feature request
Enabling parameter server

#### Feature description

We need to enable parameter server so that we can save robot states during shutdown.  This is important in many applications.  For example: in AMCL, robot may start from a known location (i.e. docking station) which we can use to initializes the filter.   Later before shutting down we can save the last location either on a file or parameter server.  This way when we start AMCL, the algorithm will know it's initial location.

**Comment by mkhansen-intel** [comment]
@mhpanah - can you implement this? Is there anything blocking you at this point?

**Comment by mhpanah** [comment]
> @mhpanah - can you implement this? Is there anything blocking you at this point?

We need to figure out how we want to save/load robot states.

**Comment by SteveMacenski** [comment]
@mkhansen-intel @mhpanah now that AMCL has the parameters for set pose on bringup and the parameters to set a pose, this is my in large done. It's up to an application level to cache and bringup using those params. 

Do you think that's a sufficient solution or should we support the caching / reload here as well?

**Comment by crdelsey** [comment]
> It's up to an application level to cache and bringup

I vote for leaving it up to the application ... at least until somebody comes up with a use case where it would be best to integrate it into AMCL.

**Comment by SteveMacenski** [comment]
Agreed, it should be easy enough for folks with parameterized bringup. Closing then.
