### ISSUE TITLE
DWB parameter helper doesn't work with strings

### ISSUE THREAD

**Issue by roncapat** [ros-planning/navigation2#2916]
https://github.com/ros-planning/navigation2/blob/21a146a97c0d400eb9bdaeaf31bb9dfb536cf00b/nav2_dwb_controller/nav_2d_utils/include/nav_2d_utils/parameters.hpp#L75

Writing new DWB critics and noticed that 'searchAndGetParam<>()' compiles for strings but then fails during execution, since `value` is 0-initialized and there is a [run time error](https://stackoverflow.com/questions/33706112/setting-stdstring-to-0-during-definition-vs-setting-stdstring-to-0).

A solution would be to remove the initialization of the variable, since it is overwritten a few lines later.

**Comment by SteveMacenski** [comment]
Hi,

thanks for the interest! Can you submit a PR with that? Happy to review / merge.
