### ISSUE TITLE
Adding a method to access costmap in goal_checker

### ISSUE THREAD

**Issue by hardesh** [ros-planning/navigation2#2939]
Can we also have a method to access local costmap in the goal checker? In the current implementation, it's possible to access the goal checker in the controller. we're not passing the costmap pointer to that class. In some applications, this can be very useful. 

Ideally, I think goal checking (whether it's occupied or not) should be done in the behavior tree. But if we check the goal directly in the goal checker/controller the logic in the BT can be bypassed

**Comment by padhupradheep** [comment]
> Can we also have a method to access local costmap in the goal checker?

I believe you want to reject the goal if the space is occupied?

**Comment by SteveMacenski** [comment]
That's not what the goal checker is for, its for checking if the goal has been achieved yet or not. It's a binary yes/no for 
- Yes: We have reached the goal pose and can stop navigating 
- No: We have not yet reached the goal pose and must been navigating

If there was something that the costmap would be useful to you for in that context, then I would be OK adding a costmap pointer to this plugin type. However, what you're proposing is checking the status of the costmap at the goal pose, either way, that responses that the Goal Checker plugin have available wouldn't be particularly useful, if I'm understanding you use-case properly.

Even if you knew it was occupied in the Goal Checker, there wouldn't be anything it could do. It's just returning "yes I'm done navigating in my goal tolerance" or "no keep going".

I suppose though you could check if its occupied and then preemptively say "yes I'm done" regardless of the set goal tolerances / pose constraints. Is that what you had in mind? 

---

Separately, if you guys are open to donating a BT node for checking if a goal / pose / footprint is occupied, I think that would be a useful BT primitive to have available. Always happy to have more generic BT nodes that would be useful for navigation system developers (and less you need to maintain long term).

**Comment by hardesh** [comment]
> Even if you knew it was occupied in the Goal Checker, there wouldn't be anything it could do. It's just returning "yes I'm done navigating in my goal tolerance" or "no keep going".

Yes this is exactly what we want to do. 


In navigation (ROS1), move_base/move_base_flex both have `isGoalReached` function directly in the controller plugin. So we do not worry about this. But in nav2 since the controller and the goal checker are separated there's no way for the goal_checker to influence the controller or vice versa.

**Comment by SteveMacenski** [comment]
While we could add it, within the controller you can always throw an exception that it can't follow due to a collision. But that would return a failed status rather than a succeeded status, but have the same otherwise termination condition. I suppose it matters more semantically what you want to have happen in that situation (e.g. stop as success or start enacting failure conditions).

If you want the positive situation, please submit a PR making the change to the goal checker plugin ID and update the corresponding goal checkers to use it (so it builds)

**Comment by SteveMacenski** [comment]
Any update?

**Comment by hardesh** [comment]
It's on my TODO list. I'll try to open up a PR of the BT plugin this weekend

**Comment by hardesh** [comment]
https://github.com/ros-planning/navigation2/pull/2965 Adds costmap_ros pointer in the goal_checker plugin. I do plan to add a separate BT plugin as well. Will try to open a PR in the next 2-3 weeks since it does not introduce any breaking changes for Humble release

**Comment by SteveMacenski** [comment]
Awesome! I look forward to it!

**Comment by mini-1235** [comment]
Found this issue when refactoring the controller server

> Separately, if you guys are open to donating a BT node for checking if a goal / pose / footprint is occupied, I think that would be a useful BT primitive to have available.

So we actually don't have something like `IsPoseOccupied` in the BTNode? I think it can be very useful for https://github.com/ros-navigation/navigation2/issues/2599, for example if start/goal is occupied then we enter different behaviors in the recovery subtree

**Comment by SteveMacenski** [comment]
I believe we do now, this ticket is very old 😉 https://github.com/ros-navigation/navigation2/blob/main/nav2_msgs/srv/IsPathValid.srv https://github.com/ros-navigation/navigation2/blob/main/nav2_msgs/srv/GetCosts.srv

**Comment by mini-1235** [comment]
They have different use cases, I think

Imagine if we are sending the goal that is already occupied, then the planner server should fails, by default it should clear the entire costmap, if it doesn't help, it finally enters the recovery behavior. The `isPathValid` service / BT Node cannot be used here as the planner server throws and never generates a path.


When it enters the recovery subtree, it tries `Backup`, `Wait` and `Spin` in a round robin fashion. Inspired by this ticket, I think we can have a "smarter" recovery here, for example, if the goal is occupied, I think it doesn't make sense for the robot to `Backup`, `Wait` and `Spin` (Or at least not in this order) it doesn't help the robot to reach the goal, so I was thinking about using this api [navigation/navigation2/blob/main/nav2_msgs/srv/GetCosts.srv](https://github.com/ros-navigation/navigation2/blob/main/nav2_msgs/srv/GetCosts.srv) to create a condition node. Then, we can probably do something like

```
if(isPoseOccupied(start)
   then Recovery A
else if(isPoseOccupied(goal)
   then Recovery B
else
  Recovery C
```

I think this gives the recovery subtree more information on which behavior to choose 

I also did a quick grep in `nav2_behavior_tree`, and I think 
> https://github.com/ros-navigation/navigation2/blob/main/nav2_msgs/srv/GetCosts.srv

is only used in `RemoveInCollisionGoals`

I haven’t worked with the BT nodes in a while, so please let me know if you have a better design approach or if I have misunderstood anything :grin:

**Comment by SteveMacenski** [comment]
I think we could use that service to make the feature you're asking for :-) I thought for some reason we had that already as a BT node to complement `RemoveInCollisionGoals` but that doesn't appear to be the case. Please contribute that (and can lift alot of the code from `RemoveInCollisionGoals` to boot 😆 )
