### ISSUE TITLE
Range sensor Plugin issue (Range sensor layer can't transform from odom to sonar0) 

### ISSUE THREAD

**Issue by debanik123** [ros-planning/navigation2#2957]
Though it has connected with nav2_costmap_2d. We put the tf between sonar0 frame and base_link frame but still got the following errors -->
[planner_server-5] [INFO] [1652950773.483920872] [global_costmap.global_costmap]: Range sensor layer can't transform from map to sonar0
[controller_server-4] [INFO] [1652950773.514802332] [local_costmap.local_costmap]: Range sensor layer can't transform from odom to sonar0

**Comment by SteveMacenski** [comment]
Agreed. Include the rqt tf tree graph
