### ISSUE TITLE
Apt is installing version 1.0.8 instead of 1.0.11 

### ISSUE THREAD

**Issue by omerts** [ros-planning/navigation2#2959]
- Operating System:
  - Ubuntu 20.04 
- ROS2 Version:
  - Galactic - binaries
- Version or commit hash:
```
ros-galactic-navigation2:
  Installed: 1.0.8-1focal.20220430.173751
  Candidate: 1.0.8-1focal.20220430.173751
  Version table:
 *** 1.0.8-1focal.20220430.173751 500
        500 http://packages.ros.org/ros2/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

- DDS implementation:
 Fast-RTPS

#### Steps to reproduce issue
```
sudo apt install ros-galactic-navigation2
```

#### Expected behavior
It should install latest 1.0.11 version

#### Actual behavior
It installs version 1.0.8

**Comment by padhupradheep** [comment]
We need to wait for it until the next Galactic sync

**Comment by omerts** [comment]
@padhupradheep Looking at the release notes 1.0.8 was released months ago:
![image](https://user-images.githubusercontent.com/4996164/169338391-dc3c97ff-c894-4dab-a902-e391b4d3b935.png)

**Comment by SteveMacenski** [comment]
It takes time to run release syncs at OSRF.
