### ISSUE TITLE
Ros2 AMCL problem   exit code -11

### ISSUE THREAD

**Issue by lunanueva** [ros-planning/navigation2#2963]
## Bug report
 Ros Navigation2  AMCL  process died with exit code -11

**Required Info:**

- Operating System:
  Ubuntu 20.04 in Host machine and Raspberry pi4
- ROS2 Version:
  -  ROS2  version Foxy  (host and Raspberry)
- Version or commit hash:
     Debian packages (host and raspi) 
- DDS implementation:
   DDS  cyclonedds

#### Steps to reproduce issue
Robot mecanum omnidirectional  4 wheels

Navigation config
amcl:
  ros__parameters:
    set_initial_pose: True
    initial_pose.x: 0.0
    initial_pose.y: 0.0
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 100.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: “nav2_amcl::OmniMotionModel" # "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001   # 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.35
      max_vel_y: 0.35 # 0.0
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.35
      min_speed_theta: 0.0
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 1.5 # 2.5
      acc_lim_y: 1.5 # 0.0
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_y: -2.5 # 0.0
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 20 # 5
      vtheta_samples: 20
      sim_time: 1.7
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.2
      xy_goal_tolerance: 0.25
      trans_stopped_velocity: 0.25
      short_circuit_trajectory_evaluation: True
      stateful: True
      # critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist", "Twirling"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      Twirling.scale: 0.0  

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22
      plugins: ["voxel2d_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55  
      voxel2d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan base_scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        base_scan:
          topic: /base/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      robot_radius: 0.22
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "voxel3d_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan base_scan
        scan:
          topic: /scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
        base_scan:
          topic: /base/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      voxel3d_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: False
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        mark_threshold: 1
        observation_sources: realsense zed
        min_obstacle_height: 0.00
        max_obstacle_height: 2.0 
        realsense:
          topic: /camera/depth/color/points
          raytrace_min_range: 0.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
        zed:
          topic: /zed/point_cloud/cloud_registered
          raytrace_min_range: 0.5
          min_obstacle_height: 0.0
          max_obstacle_height: 2.0 
          clearing: True
          marking: True
          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.55
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "playground.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 5000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: False

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "back_up", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    back_up:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.1
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2   

robot_state_publisher:
  ros__parameters:
    use_sim_time: False

navigation LOG

[INFO] [launch]: All log files can be found below /home/ubuntu/.ros/log/2022-05-22-12-27-55-776224-raspiagua-2381
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [map_server-1]: process started with pid [2383]
[INFO] [amcl-2]: process started with pid [2385]
[INFO] [lifecycle_manager-3]: process started with pid [2387]
[INFO] [controller_server-4]: process started with pid [2389]
[INFO] [planner_server-5]: process started with pid [2391]
[INFO] [recoveries_server-6]: process started with pid [2394]
[INFO] [bt_navigator-7]: process started with pid [2404]
[INFO] [waypoint_follower-8]: process started with pid [2423]
[INFO] [lifecycle_manager-9]: process started with pid [2430]
[lifecycle_manager-3] [INFO] [1653222477.395040377] [lifecycle_manager_localization]: Creating
[lifecycle_manager-3] [INFO] [1653222477.553102751] [lifecycle_manager_localization]: Creating and initializing lifecycle service clients
[map_server-1] [INFO] [1653222477.592422399] [map_server]: 
[map_server-1] 	map_server lifecycle node launched. 
[map_server-1] 	Waiting on external lifecycle transitions to activate
[map_server-1] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-1] [INFO] [1653222477.592747798] [map_server]: Creating
[lifecycle_manager-3] [INFO] [1653222477.616705929] [lifecycle_manager_localization]: Starting managed nodes bringup...
[lifecycle_manager-3] [INFO] [1653222477.616826969] [lifecycle_manager_localization]: Configuring map_server
[amcl-2] [INFO] [1653222477.668648264] [amcl]: 
[amcl-2] 	amcl lifecycle node launched. 
[amcl-2] 	Waiting on external lifecycle transitions to activate
[amcl-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[amcl-2] [INFO] [1653222477.669077870] [amcl]: Creating
[controller_server-4] [INFO] [1653222477.824652183] [controller_server]: 
[controller_server-4] 	controller_server lifecycle node launched. 
[controller_server-4] 	Waiting on external lifecycle transitions to activate
[controller_server-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-9] [INFO] [1653222478.141763216] [lifecycle_manager_navigation]: Creating
[planner_server-5] [INFO] [1653222478.187740459] [planner_server]: 
[planner_server-5] 	planner_server lifecycle node launched. 
[planner_server-5] 	Waiting on external lifecycle transitions to activate
[planner_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-4] [INFO] [1653222478.298940856] [controller_server]: Creating controller server
[planner_server-5] [INFO] [1653222478.343294381] [planner_server]: Creating
[waypoint_follower-8] [INFO] [1653222478.376151613] [waypoint_follower]: 
[waypoint_follower-8] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-8] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-8] [INFO] [1653222478.382197899] [waypoint_follower]: Creating
[bt_navigator-7] [INFO] [1653222478.559097834] [bt_navigator]: 
[bt_navigator-7] 	bt_navigator lifecycle node launched. 
[bt_navigator-7] 	Waiting on external lifecycle transitions to activate
[bt_navigator-7] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-7] [INFO] [1653222478.560311317] [bt_navigator]: Creating
[recoveries_server-6] [INFO] [1653222478.629365333] [recoveries_server]: 
[recoveries_server-6] 	recoveries_server lifecycle node launched. 
[recoveries_server-6] 	Waiting on external lifecycle transitions to activate
[recoveries_server-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-9] [INFO] [1653222478.715095862] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[lifecycle_manager-9] [INFO] [1653222479.129419848] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-9] [INFO] [1653222479.129676394] [lifecycle_manager_navigation]: Configuring controller_server
[planner_server-5] [INFO] [1653222479.468992138] [global_costmap.global_costmap]: 
[planner_server-5] 	global_costmap lifecycle node launched. 
[planner_server-5] 	Waiting on external lifecycle transitions to activate
[planner_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-5] [INFO] [1653222479.519645315] [global_costmap.global_costmap]: Creating Costmap
[controller_server-4] [INFO] [1653222479.593264600] [local_costmap.local_costmap]: 
[controller_server-4] 	local_costmap lifecycle node launched. 
[controller_server-4] 	Waiting on external lifecycle transitions to activate
[controller_server-4] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-4] [INFO] [1653222479.618658227] [local_costmap.local_costmap]: Creating Costmap
[map_server-1] [INFO] [1653222481.325088191] [map_server]: Configuring
[map_server-1] [INFO] [map_io]: Loading yaml file: casa.yaml
[map_server-1] [DEBUG] [map_io]: resolution: 0.05
[map_server-1] [DEBUG] [map_io]: origin[0]: -7.04
[map_server-1] [DEBUG] [map_io]: origin[1]: -7.81
[map_server-1] [DEBUG] [map_io]: origin[2]: 0
[map_server-1] [DEBUG] [map_io]: free_thresh: 0.25
[map_server-1] [DEBUG] [map_io]: occupied_thresh: 0.65
[map_server-1] [DEBUG] [map_io]: mode: trinary
[map_server-1] [DEBUG] [map_io]: negate: 0
[map_server-1] [INFO] [map_io]: Loading image_file: ./casa.pgm
[map_server-1] [DEBUG] [map_io]: Read map ./casa.pgm: 286 X 345 map @ 0.05 m/cell
[lifecycle_manager-3] [INFO] [1653222481.669121128] [lifecycle_manager_localization]: Configuring amcl
[amcl-2] [INFO] [1653222481.701470806] [amcl]: Configuring
[amcl-2] [INFO] [1653222481.702298738] [amcl]: initTransforms
[amcl-2] [INFO] [1653222482.040691652] [amcl]: initPubSub
[amcl-2] [INFO] [1653222482.254117367] [amcl]: Subscribed to map topic.
[lifecycle_manager-3] [INFO] [1653222482.459348951] [lifecycle_manager_localization]: Activating map_server
[map_server-1] [INFO] [1653222482.460629193] [map_server]: Activating
[lifecycle_manager-3] [INFO] [1653222482.556774868] [lifecycle_manager_localization]: Activating amcl
[amcl-2] [INFO] [1653222482.559743030] [amcl]: Activating
[amcl-2] [WARN] [1653222482.559969351] [amcl]: Publishing the particle cloud as geometry_msgs/PoseArray msg is deprecated, will be published as nav2_msgs/ParticleCloud in the future
[amcl-2] [INFO] [1653222482.560136467] [amcl]: initialPoseReceived
[amcl-2] [INFO] [1653222482.561743996] [amcl]: Setting pose (1653222482.561719): 0.000 0.000 0.000
[lifecycle_manager-3] [INFO] [1653222482.611940165] [lifecycle_manager_localization]: Managed nodes are active
[amcl-2] [INFO] [1653222482.712211721] [amcl]: Received a 286 X 345 map @ 0.050 m/pix
[amcl-2] [INFO] [1653222482.796729811] [amcl]: createLaserObject
[controller_server-4] [INFO] [1653222484.143870471] [controller_server]: Configuring controller interface
[controller_server-4] [INFO] [1653222484.147554390] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-4] [INFO] [1653222484.147819842] [local_costmap.local_costmap]: Configuring
[controller_server-4] [INFO] [1653222484.349802069] [local_costmap.local_costmap]: Using plugin "voxel2d_layer"
[controller_server-4] [INFO] [1653222484.471171837] [local_costmap.local_costmap]: Subscribed to Topics: scan base_scan
[controller_server-4] [INFO] [1653222484.740792970] [local_costmap.local_costmap]: Initialized plugin "voxel2d_layer"
[controller_server-4] [INFO] [1653222484.740967567] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-4] [INFO] [1653222484.754041921] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[controller_server-4] [INFO] [1653222484.826430221] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-4] [INFO] [1653222484.833315935] [controller_server]: Created goal_checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-4] [INFO] [1653222484.877854647] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-4] [INFO] [1653222484.909642144] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-4] [INFO] [1653222485.210464424] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-4] [INFO] [1653222485.250791697] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.256171292] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-4] [INFO] [1653222485.274328521] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.284171295] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-4] [INFO] [1653222485.291325903] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.294861872] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-4] [INFO] [1653222485.323071418] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.330013149] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-4] [INFO] [1653222485.344546369] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.349435395] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-4] [INFO] [1653222485.363071145] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.368808120] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-4] [INFO] [1653222485.380082268] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.386078380] [controller_server]: Using critic "Twirling" (dwb_critics::TwirlingCritic)
[controller_server-4] [INFO] [1653222485.392328073] [controller_server]: Critic plugin initialized
[controller_server-4] [INFO] [1653222485.392640934] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-9] [INFO] [1653222485.524145011] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-5] [INFO] [1653222485.528473391] [planner_server]: Configuring
[planner_server-5] [INFO] [1653222485.528752713] [global_costmap.global_costmap]: Configuring
[planner_server-5] [INFO] [1653222485.705245602] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-5] [INFO] [1653222485.808945292] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-5] [INFO] [1653222485.828934905] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-5] [INFO] [1653222485.829236988] [global_costmap.global_costmap]: Using plugin "obstacle_layer"
[planner_server-5] [INFO] [1653222485.847552740] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 286 X 345 at 0.050000 m/pix
[planner_server-5] [INFO] [1653222485.872199224] [global_costmap.global_costmap]: Subscribed to Topics: scan base_scan
[planner_server-5] [INFO] [1653222486.078324232] [global_costmap.global_costmap]: Initialized plugin "obstacle_layer"
[planner_server-5] [INFO] [1653222486.086307876] [global_costmap.global_costmap]: Using plugin "voxel3d_layer"
[planner_server-5] [INFO] [1653222486.124765040] [global_costmap.global_costmap]: Subscribed to Topics: realsense zed
[planner_server-5] [INFO] [1653222486.394128802] [global_costmap.global_costmap]: Initialized plugin "voxel3d_layer"
[planner_server-5] [INFO] [1653222486.398672390] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-5] [INFO] [1653222486.436991253] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-5] [INFO] [1653222486.618999088] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-5] [INFO] [1653222486.619360579] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-5] [INFO] [1653222486.768267229] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-9] [INFO] [1653222487.004653087] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-6] [INFO] [1653222487.006472951] [recoveries_server]: Configuring
[recoveries_server-6] [INFO] [1653222487.137011882] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-6] [INFO] [1653222487.149194802] [recoveries_server]: Configuring spin
[recoveries_server-6] [INFO] [1653222487.287777597] [recoveries_server]: Creating recovery plugin back_up of type nav2_recoveries/BackUp
[recoveries_server-6] [INFO] [1653222487.307423495] [recoveries_server]: Configuring back_up
[recoveries_server-6] [INFO] [1653222487.384254372] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-6] [INFO] [1653222487.394989772] [recoveries_server]: Configuring wait
[lifecycle_manager-9] [INFO] [1653222487.472520631] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-7] [INFO] [1653222487.474559908] [bt_navigator]: Configuring
[bt_navigator-7] [INFO] [1653222488.191143588] [bt_navigator_rclcpp_node]: Waiting for "compute_path_to_pose" action server
[bt_navigator-7] [INFO] [1653222488.192493216] [bt_navigator_rclcpp_node]: "ComputePathToPose" BtActionNode initialized
[bt_navigator-7] [INFO] [1653222488.213841204] [bt_navigator_rclcpp_node]: Waiting for "global_costmap/clear_entirely_global_costmap" service
[bt_navigator-7] [INFO] [1653222488.214752191] [bt_navigator_rclcpp_node]: "ClearGlobalCostmap-Context" BtServiceNode initialize
[ERROR] [amcl-2]: process has died [pid 2385, exit code -11, cmd '/opt/ros/f

**Comment by padhupradheep** [comment]
issue can be closed now..

**Comment by lunanueva** [comment]
Hi

After testing my robot,  I have noted that the problem is solved only if the goal is very close and in a straight line

It is posible that it could have erroneous parameters for  omnidirectional robot but they are according with the  ROS documentation.

Config AMCL
  robot_model_type: “omnidirectional”


Config Followpath
      min_vel_x: 0.0
      min_vel_y: 0.0
      max_vel_x: 0.35
      max_vel_y: 0.35
      max_vel_theta: 1.0
      min_speed_xy: 0.0
      max_speed_xy: 0.35
      min_speed_theta: 0.0
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist",   "GoalDist", "Twirling"]
      Twirling.scale: 0.0




Error in the log file

[ERROR] [amcl-2]: process has died [pid 2441, exit code -11, cmd '/opt/ros/foxy/lib/nav2_amcl/amcl --ros-args -r __node:=amcl --params-file /tmp/tmprh8h1bi6 -r /tf:=tf -r /tf_static:=tf_static'].


Many thanks for your help.

Florencio Garcia


Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: Pradheep ***@***.***>
Enviado: lunes, 23 de mayo de 2022 11:34
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [ros-planning/navigation2] Ros2 AMCL problem exit code -11 (Issue #2963)


issue can be closed now..
