### ISSUE TITLE
[Release] Release for Humble

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#2967]
Blockages today:
- CI is not up and running on 22.04
- Gazebo to ignition blockers since Gazebo is not longer supported

**Comment by vinnnyr** [comment]
Could Turtlebot4 (which supports Ignition) be used instead of TB3? https://github.com/turtlebot/turtlebot4_simulator 
Sorry if this issue is not the correct place to discuss the GZ -> Ign Gz issue

**Comment by SteveMacenski** [comment]
As fine of a place as any! Even in a nice demo room as well. I certainly wouldn't have any issues switching to the TB4, I'd even prefer it

**Comment by SteveMacenski** [comment]
It would be nice to break out the gazebo launching into its own launch file + add an ignition launch file and have it be a launch parameter in tb3_simulation_launch.py which to apply (or even have a new tb4_simulation_launch.py which is just using ignition)

**Comment by vinnnyr** [comment]
I might have gotten too excited to see the TB4 repo reference Ignition Gazeebo. 

It doesn't (or has dependencies that don't) build in Jammy / Humble.
https://github.com/turtlebot/turtlebot4_simulator/issues/16

**Comment by SteveMacenski** [comment]
It seems that gazebo might have been released recently and our issues were docker related, running some experiments now but we may be able to release to humble and deal with gazebo issues in a hot minute
