### ISSUE TITLE
Branch confusion

### ISSUE THREAD

**Issue by muttistefano** [ros-planning/navigation2#2970]
hi everyone,
i cannot understand which one is the development branch.
i can see galactic and main are the most developed one, is the main branch the one corresponding to ros2 rolling ?
Thanks

**Comment by automech-rb** [comment]
Yeah, the main branch corresponds to rolling. It is documented [here](https://navigation.ros.org/build_instructions/index.html)

_Build or install ROS 2 rolling using the [build instructions](https://docs.ros.org/en/rolling/Installation/Ubuntu-Development-Setup.html) provided in the ROS 2 documentation. All development is done using the rolling distribution on Nav2’s main  branch.._

**Comment by automech-rb** [comment]
Actually live Groot monitoring support was dropped as explained in the migration page [here](https://navigation.ros.org/migration/Galactic.html)

**Comment by muttistefano** [comment]
Thanks for the clarification
