### ISSUE TITLE
 Cannot locate rosdep definition for [slam_toolbox] for rolling

### ISSUE THREAD

**Issue by xianglunkai** [ros-planning/navigation2#2978]
For ros-rolling version, to resolve dependent Libraries:

rosdep install -y -r -q --from-paths src --ignore-src --rosdistro rolling

The following error will be printed:
nav2_bringup: Cannot locate rosdep definition for [slam_toolbox]

**Comment by SteveMacenski** [comment]
It is not released to rolling, nor Nav2 itself
