### ISSUE TITLE
Add diagnostics to Nav2?

### ISSUE THREAD

**Issue by tonynajjar** [ros-planning/navigation2#2984]
This is a question/feature request.

I'm in the process of adding [Diagnostics](http://wiki.ros.org/diagnostics) to my system. I'd like to add a diagnostic that tells me if Nav2 is healthy or not. This [service](https://github.com/ros-planning/navigation2/blob/80d7d0a080d7401607fd85216f9c450518e7ed42/nav2_lifecycle_manager/src/lifecycle_manager.cpp#L68) sounds like a good enough high-level check to me.

Do you think it would be useful to publish a health diagnostic from the lifecycle manager? Basically publish the value of `system_active_` to diagnostics. I can submit a PR.

**Comment by SteveMacenski** [comment]
Sure, why not! Feel free to submit a PR

**Comment by tonynajjar** [comment]
https://github.com/ros-planning/navigation2/pull/2986
