### ISSUE TITLE
Map saver without 'get_parameter'

### ISSUE THREAD

**Issue by MartiBolet** [ros-planning/navigation2#2985]
## Feature request
Hi, I see that the `map_saver.cpp` has the `declare_parameter` for `save_map_timeout`, `free_thresh_default`, `occupied_thresh_default` and `map_subscribe_transient_local` but doesn't get the value of the parameters anywhere.

#### Feature description
Add the `get_parameter(...)` inside `on_configure()` transition.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/main/nav2_map_server/src/map_saver/map_saver.cpp#L49-L54 They are gotten in the constructor. I'll admit that its not the best place for that kind of thing, but they are gotten.
