### ISSUE TITLE
Provide BT status to navigator in goalCompleted() function

### ISSUE THREAD

**Issue by mradams-bastian** [ros-planning/navigation2#2991]
#### Feature description
Each class that inherits from navigator.hpp has a chance to populate the result of its corresponding ROS action when the behavior tree finishes executing in the [goalCompleted()](https://github.com/ros-planning/navigation2/blob/bd31820efb5113cd9df43957b92ae7309e443580/nav2_bt_navigator/include/nav2_bt_navigator/navigator.hpp#L298) function. In many cases it could be nice to have some context around the final status of the behavior tree while populating this result.

#### Implementation considerations
The most straightforward implementation would be to add another parameter to goalCompleted() for the behavior tree status (nav2_behavior_tree::BtStatus). [The status is readily available where the completion callback is called](https://github.com/ros-planning/navigation2/blob/b5989fd8bf79464c86776a2d86c2c0937d6a41db/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp#L210-L219), so passing in that extra argument would be trivial.

**Comment by SteveMacenski** [comment]
Current all action result types are empty, but sure, feel free to submit a PR that sounds reasonable for future proofing

**Comment by SteveMacenski** [comment]
If you could do so in the next day, that would be appreciated, we're going to release to Humble this week and I'd like this in before that fork is made.

**Comment by mradams-bastian** [comment]
Sure, I'll do that

**Comment by SteveMacenski** [comment]
Merge imminent
