### ISSUE TITLE
Adding service for robot footprint collision check

### ISSUE THREAD

**Issue by andriimaistruk** [ros-planning/navigation2#3006]
#### Feature description

In the project I contribute to, there are action servers that need checking poses for robot collisions on local as well as on global costmap, and I couldn't find any service in nav2 that would allow to do that for the costmap. 

#### Implementation considerations

There is nav2_costmap_2d::CostmapTopicCollisionChecker class that might be useful. The service can be added as part of nav2_costmap_2d::Costmap2DROS.
If this feature is of interest, I or my colleagues would like to create pull request for it.

**Comment by SteveMacenski** [comment]
You can create an instance of the `CostmapTopicCollisionChecker` in your application - that's what its there for. Its not in `nav2_utils` mostly from dependency circular issues. You can see examples of its use in the behavior server https://github.com/ros-planning/navigation2/blob/30048b46bf02c6a60473b1dae6000e6eb2597056/nav2_behaviors/src/behavior_server.cpp#L90-L91 which uses the costmap topics and footprints published to check for collisions at certain poses for servers external to the planner/controller servers.

Note that costmap subscriptions are heavy, so its recommended that, whenever possible / useful, to use as few costmap subscribers as possible. This is why the `behavior` server exists; to host a number of behaviors that need common but heavy stuff like TF buffers and costmap subscriptions so they can all share those resources.

**Comment by andriimaistruk** [comment]
Thank you very much for a comprehensive answer.
