### ISSUE TITLE
Unable to reverse when navigating with Ackerman model robot

### ISSUE THREAD

**Issue by miku54** [ros-planning/navigation2#3011]
- Operating System:
  - ubuntu20.04
- ROS2 Version:
  - Galactic 
Based on this problem:  [#2983 ](https://github.com/ros-planning/navigation2/issues/2983) , I upgraded the ROS2 version and currently use the Galactic version for navigation testing. Strangely, when navigating with the nav2_regulated_pure_pursuit_controlle controller, my robot is still unable to reverse. On the contrary, when I use the DWBLocalPlanner controller, I can "occasionally" achieve the reverse effect, but it cannot always park accurately at the target point. Attaching my parameter file here, do I need to change those?

**Comment by padhupradheep** [comment]
what planner are you using? I see from the last issue, that it is an Ackermann drive. In that case, you have to use the smac_planner and use the reed-shepp motion model.

**Comment by miku54** [comment]
![Screenshot from 2022-06-09 20-38-08](https://user-images.githubusercontent.com/81612531/172852857-579742a5-d5ec-4397-8252-fec2f9bd9126.png)

**Comment by padhupradheep** [comment]
Please read the documentation for RPP. https://navigation.ros.org/configuration/packages/configuring-regulated-pp.html

There is a parameter called `allow_reversing` that needs to be set to true, combined with the changes I told you above. 

Note that this is a feature request or a bug tracker. I would suggest you to ask your configuration related questions in [answers.ros.org](https://answers.ros.org/)

I know that our contributors are pretty active over there.

**Comment by miku54** [comment]
> nav2_navfn_planner

Thanks for your reply, I use NavFn Planner, doesn't this match the Ackerman model?

**Comment by miku54** [comment]
> * nav2_regulation_pure_pursuit_controlle

But I didn't use the "allow_reversing" parameter.
According to your prompt, when adapting the nav2_regulation_pure_pursuit_controlle controller, it needs to be used with Smac Planner, right?

**Comment by padhupradheep** [comment]
>According to your prompt, when adapting the nav2_regulation_pure_pursuit_controlle controller, it needs to be used with Smac Planner, right?

For Ackermann! yes!

**Comment by miku54** [comment]
> > According to your prompt, when adapting the nav2_regulation_pure_pursuit_controlle controller, it needs to be used with Smac Planner, right?
> 
> For Ackermann! yes!

@Aposhian  thank you! I need to wait 12 hours before testing, can I close the problem if I fix it then? Have a great day!

**Comment by miku54** [comment]
> 我建议关闭这个问题！据我所知，该功能运行良好。如果您有任何配置问题，请将其发布在 answers.ros.org 上！

Can I close the question after my test is complete? thanks
