### ISSUE TITLE
Writing the behavior_tree file reports an error: Missing key [bt_loop_duration]

### ISSUE THREAD

**Issue by miku54** [ros-planning/navigation2#3020]
When I run this file with Ubuntu20.04-foxy, there is no exception. I have migrated the program to Galactic version. In this version, has the format of the behavior tree file changed?This is the error I have encountered in the content of my file
![image](https://user-images.githubusercontent.com/81612531/174054563-5813ab93-e3f2-4f4f-b9ee-8e8c29fd496f.png)
![image](https://user-images.githubusercontent.com/81612531/174054683-53f81e36-9010-4e21-88b6-2a9e6e0aec38.png)

**Comment by SteveMacenski** [comment]
Did you check and update all appropriate settings from the migration guides? https://navigation.ros.org/migration/index.html

**Comment by miku54** [comment]
Allow me to apologize for my lateness.
I checked my code and found that there is no variable bt_loop_duration_. I used std::chrono::milliseconds(1000) instead of bt_loop_duration_, which is the problem. After adding bt_loop_duration_, there is no error, but I don't Have run it in simulation, not sure if it will work. Anyway thank you!
