### ISSUE TITLE
Adjust getting started documentation

### ISSUE THREAD

**Issue by empirephoenix** [ros-planning/navigation2#3024]
#### Expected behavior
The documentation at https://navigation.ros.org/getting_started/index.html#navigating states that after running the following command "ros2 launch nav2_bringup tb3_simulation_launch.py" gazebo and RVis should be started.

#### Actual behavior
Gzclient is not started, because headless defaults to True (perhaps it did default to false in the past?)

#### Additional information
This causes some confusion, eg. see https://github.com/ros-planning/navigation2/issues/3013

## Feature request

Please adjust the documentation to the command "ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False" so that it matches the screenshots.

If you can point me to the right location, I would also try my hands on a pull request

**Comment by SteveMacenski** [comment]
Hi,

Good point, here is the documentation! https://github.com/ros-planning/navigation.ros.org/blob/master/getting_started/index.rst I look forward to the pull request :smile:

**Comment by empirephoenix** [comment]
Hi,

is this adequate? https://github.com/ros-planning/navigation.ros.org/pull/326

**Comment by SteveMacenski** [comment]
LGTM!
