### ISSUE TITLE
[map_saver]: Failed to spin map subscription

### ISSUE THREAD

**Issue by miku54** [ros-planning/navigation2#3048]
Hello, I am using Ubuntu20.04 Galactic system to debug the following.
When I use gmapping to build the map, there is an error saving the map, the save instruction is:
ros2 run nav2_map_server map_saver_cli -f /ros2_ws/src/maps/map
output:
```

[INFO] [1656406101.802655809] [map_saver]:
        map_saver lifecycle node launched.
        Waiting on external lifecycle transitions to activate
        See https://design.ros2.org/articles/node_lifecycle.html for more information.
[INFO] [1656406101.803415447] [map_saver]: Creating
[INFO] [1656406101.804794775] [map_saver]: Saving map from 'map' topic to 'WHEELTEC' file
[WARN] [1656406101.805103318] [map_saver]: Free threshold unspecified. Setting it to default value: 0.250000
[WARN] [1656406101.805368892] [map_saver]: Occupied threshold unspecified. Setting it to default value: 0.650000
[WARN] [1656406101.811595060] [map_saver]: New publisher discovered on topic '/map', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY
[ERROR] [1656406103.811321118] [map_saver]: Failed to spin map subscription
[INFO] [1656406103.815013579] [map_saver]: Destroying
```

But when I try to save with the directive after building the map using slam_toolbox, everything works fine,
and when I run in foxy everything works fine
Please how can I solve this problem?

I found this issue: https://github.com/ros-planning/navigation2/issues/2637, but I still haven't solved it

**Comment by SteveMacenski** [comment]
> New publisher discovered on topic '/map', offering incompatible QoS. No messages will be sent to it. Last incompatible policy: DURABILITY_QOS_POLICY

That seems pretty clear to me. In the future, please direct questions to ROS Answers, this is not the appropriate forum for configuration help.

**Comment by HUANG-Haolun** [comment]
I just solved it by download the source code and add the `map_qos.durability_volatile();` below https://github.com/ros-planning/navigation2/blob/98af3b9a28d9180ba22b17573f01cccaf7cbe04b/nav2_map_server/src/map_saver/map_saver.cpp#L192
