### ISSUE TITLE
Obstacle layer don't subscribe laser scans

### ISSUE THREAD

**Issue by PSotiriadis** [ros-planning/navigation2#3059]
Hi
I want to report an issue with nav2_costmap_2d package. Using navigation2 with ROS2 Humble, local costmap is not indicated in RViz, like in screenshot below:

<img width="1785" alt="ObstacleLayerproblem" src="https://user-images.githubusercontent.com/47846833/177132559-2b949e5c-55c7-4547-91f3-3c243fd20572.PNG">

However, global costmap is working properly:

<img width="1690" alt="StaticLayerOK" src="https://user-images.githubusercontent.com/47846833/177132707-25be659f-cd43-4a2f-8f8e-41c2e492778d.PNG">

So I thought that problem can be in obstacle layer and I took a look in navigation2->nav2_costmap_2d->plugins->obstacle_layer.cpp. I realized, that in line 226, we unsubscribe the laser scan subscriber, which is subscribed above in lines 224,225. I comment line 226 and local costmap is working now fine for me and is indicated in RViz normally:

<img width="1704" alt="ObstacleLayerOK" src="https://user-images.githubusercontent.com/47846833/177133313-b6a09ac4-5a17-4695-80e7-3d2b47b5ce12.PNG">

This is logical for me, but I don't know if it is desired from the authors of navigation2 (maybe it is desired to unsubscribe in this position, but forgot to subscribe later). I want only to highlight the problem!!!

PS: Same happens also later  in line 255, where PointCloud2 subscriber is unsubscribed, but I didn't check if works or not. Please see also this position, because it can also produce a problem.

**Comment by padhupradheep** [comment]
Already reported https://github.com/ros-planning/navigation2/issues/3014 ! More info https://github.com/ros-planning/navigation2/pull/3018

**Comment by SteveMacenski** [comment]
Indeed, working through it with Fast-DDS, but there’s the temp PR patch that can be applied to work with Fast-DDS if absolutely required, but I’d recommend just using Cyclone

**Comment by PSotiriadis** [comment]
First, @SteveMacenski & @padhupradheep thanks a lot for the very fast response and sorry for the repetition of this issue. I switch to cyclone dds and everything works!!!
