### ISSUE TITLE
Feature: Get a generic navigation status

### ISSUE THREAD

**Issue by DatSpace** [ros-planning/navigation2#3060]
#### Feature description

I have been trying for several hours to find a way to get the navigation status similarly to the ROS1 stack.
My understanding is that due to nav2 not being a state machine, they current status of navigation is not strictly defined at any point.

Non the less it would be super useful to have a simplified version of a status that tells us if the robot is idle, thinking, moving, recovering or aborted.

I checked all the current published topics and there doesn't seem to be a topic or service for that. On that note, the simple commander could be a solution but as far I know it is currently restricted to only python.

Thank you.

**Comment by SteveMacenski** [comment]
If you use the action server (which you should always be doing), then you should know when the robot is idle, completed/aborted, or in execution.

Within execution, the [Navigation action feedback](https://github.com/ros-planning/navigation2/blob/main/nav2_msgs/action/NavigateToPose.action) also shows things like ETA, distance remaining to goal, and the number of executed recovery behaviors for the request. That can be used to track recoveries if you like. 

Also within execution, https://github.com/ros-planning/navigation2/blob/bccf6d680b47d06680e4b18be1b7d87656bbe0d7/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_server_impl.hpp#L182 publishes to a topic the current status of the behavior tree nodes, so you could get some context about when events occur there (but are obviously subject to the specific BT XML you're using). 

In terms of hyperstates like "thinking" "moving" are not really well defined and I don't think that would be sensible to add. I think what's provided already is sufficient but if there are some generalizable states that could be published, I'd be open to that, but "thinking" is not a good example of such a state. 

> On that note, the simple commander could be a solution but as far I know it is currently restricted to only python.

There's nothing special about that API, it can be trivially replicated in C++, though that won't help you much in what you're asking for.

**Comment by DatSpace** [comment]
Thank you for your answer.

Indeed in the documentation in the Navigation contexts page, the Action Server is the first topic to be discussed. Nonetheless, even if it is an obvious move from ROS1 actions to only using ROS2 action server for monitoring the status, I would recommend that it is made clear in the documentation. I suspect much of ROS1 user base was using the topics instead.

Your explanation above is exactly what I was asking for and I hope it helps other users with the same question.

I did try the bt logger yesterday before posting but as you mentioned it was kinda messy. As it should, it logs all the BT changes per root node tick, which is helpful for debugging the BT but not for determining the navigation status.

Regarding the hyperstates the idea was founded from the ROS1 feedback were we would get goal status like: PENDING, ACTIVE, ABORTED, SUCCEEDED. It was meant to abstract from the 10 (guess) possible statuses and instead have 4 more generic ones. But indeed as you mentioned the status from the action server is enough.

Thanks again for explanation

**Comment by SteveMacenski** [comment]
Awesome! Glad to have it resolved. Even in ROS 1, most users use the action server, **not** the topic. The topic is a good place for students to start, but the action server is the only reliable way so you can cancel / preempt goals and track statuses. Definitely should always be what's used :+1:
