### ISSUE TITLE
nav2_util::get_node_options_default is dead code

### ISSUE THREAD

**Issue by Aposhian** [ros-planning/navigation2#3072]
#### Feature description
`get_node_options_default` is not used anywhere in Nav2. It was misleading me by thinking those default settings were being applied everywhere, when they are actually applied nowhere.

#### Implementation considerations
Some users may be using `nav2_util::get_node_options_default` in their own code. I don't know how we sunset it without breaking people's code. Add a compile time deprecation warning?

**Comment by SteveMacenski** [comment]
Removed
