### ISSUE TITLE
rclcpp for Simple Commander 

### ISSUE THREAD

**Issue by bekirbostanci** [ros-planning/navigation2#3079]
#### Feature description
Simple commander api is also developed for c++.

#### Implementation considerations
With the simple commander API, python developers can easily include nav2 in their projects but the same is not true for c++ developers. Is it possible to create an API for C++ too? Where should I start my research to help with this?

**Comment by SteveMacenski** [comment]
This is a wontfix ticket, we will not plan to offer a simplified C++ API since the APIs for ROS2 are already stylistically C++. The Python API was made differently to be more Pythonic to language styling.
