### ISSUE TITLE
Support lifecycle nodes in python 

### ISSUE THREAD

**Issue by nakai-omer** [ros-planning/navigation2#3080]
## Feature request
Allow for lifecycle nodes to be created in python.

#### Feature description
Currently the lifecycle manager is expecting a bond from its nodes. The problem is that it is impossible at the moment to create such a bond. `bondpy`, the bond port for python, is not being maintained for ROS 2, so it is currently impossible to create lifecyclen nodes in python. 

#### Implementation considerations
Drop `bond` usage in favor of a different hearbeat mechanism

**Comment by SteveMacenski** [comment]
This is a wontfix ticket, we offer the lifecycle manager paired with Nav2. That is the solution for this architecture. You’re welcome to create another lifecycle management solution if you like, but it’ll need to be in C++ if you want the benefits of bond. Though, bond is not strictly required.
