### ISSUE TITLE
Start not included in SmacPlanner path

### ISSUE THREAD

**Issue by mangoschorle** [ros-planning/navigation2#3085]
The path returned by smac planner doesn't explicitly include the start.

`bool NodeHybrid::backtracePath(CoordinateVector & path` will not add the start node (who's parrent I would assume is a nullptr). Whats the reasoning not to include the start. Is this on purpose or should there be a do while loop.

https://github.com/ros-planning/navigation2/blob/97068787fb35894a098f9c4600b5a06c7dddf43b/nav2_smac_planner/src/node_hybrid.cpp#L700

**Comment by SteveMacenski** [comment]
That was likely an oversight. Feel free to submit a PR and I'd be happy to merge it. Its likely that all 3 planners have this issue, so fixing them across the board would be appreciated.
