### ISSUE TITLE
Missing commas in default plugin names

### ISSUE THREAD

**Issue by aaronchongth** [ros-planning/navigation2#3092]
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04
- ROS2 Version: Humble
- Version or commit hash: `main`
- DDS implementation: Fast-RTPS

#### Steps to reproduce issue

Missing commas in https://github.com/ros-planning/navigation2/blob/main/nav2_bt_navigator/src/bt_navigator.cpp#L76 and https://github.com/ros-planning/navigation2/blob/main/nav2_bt_navigator/src/bt_navigator.cpp#L79, causes search for plugins named `nav2_path_longer_on_approach_bt_nodenav2_wait_cancel_bt_node` and `nav2_back_up_cancel_bt_nodenav2_drive_on_heading_cancel_bt_node`. This happens when the parameter `plugin_lib_names` is not available.

**Comment by jwallace42** [comment]
If you could add a pr with the fix and tag me that would be great!
