### ISSUE TITLE
3d navigation stack for drones

### ISSUE THREAD

**Issue by stevedanomodolor** [ros-planning/navigation2#3095]
## Feature request
I would love to see an implementation of 3d navigation for drones in the navigation stack.  It would be nice to discuss with @SteveMacenski as mentioned in the link `https://answers.ros.org/question/341594/navigation2-support-for-3d-navigation-drones/` to see the possibilities.

**Comment by jwallace42** [comment]
I would join the slack https://navigation.ros.org/about/index.html?highlight=slack.

**Comment by Stevedan-robotics** [comment]
I am not able to join the slack with my personal email, because i need an invitation @SteveMacenski. @jwallace42 can you assist me with that

**Comment by stevedanomodolor** [comment]
I cannot seem to enter the slack group with my personal email, i require a special invitation, @SteveMacenski. @jwallace42 can you help me with that

**Comment by jwallace42** [comment]
Sure, what is your email?

**Comment by Stevedan-robotics** [comment]
stevedan.robotic@gmail.com

**Comment by stevedanomodolor** [comment]
stevedan.o.omodolor@gmail.com

**Comment by jwallace42** [comment]
Just send you a invite. Let me know if that works.

**Comment by stevedanomodolor** [comment]
Received thank you

**Comment by yrik** [comment]
how it's going with drone/plane nav support?

**Comment by songanz** [comment]
Also want follow-ups here

**Comment by stevedanomodolor** [comment]
My response when i asked was that there wasn't a specific plan to implement this in the near future although it is possible to contribute to nav2 because the base architecture of nav2 can support this. Another alternative is px4
