### ISSUE TITLE
Unable to load my own map with Galactic Nav2 (No map is received)

### ISSUE THREAD

**Issue by jackykwok2002** [ros-planning/navigation2#3103]
## Bug report

**Required Info:**
- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - ROS2 Galactic
- Version or commit hash:
  - 104bdc51fb72e05af4ccb4fb96a2fd421239f016
- DDS implementation:
  - Fast-RTPS (default)

#### Steps to reproduce issue

```
sudo apt install ros-galactic-navigation2 -y
sudo apt install ros-galactic-nav2-bringup
**ros2 launch nav2_bringup bringup_launch.py use_sim_time:=False autostart:=True map:= Path to Map**
```

#### Expected behavior
Navigation stack should be launched and the map should be updated and displayed in RVIZ

#### Actual behavior
- Map is not received/updated 
- Frozen on **[local_costmap.local_costmap]: Creating local_costmap**

----

**Comment by padhupradheep** [comment]
are you sure, you installed turtlebot3 packages? 

please follow the instructions given here: https://navigation.ros.org/getting_started/index.html

**Comment by SteveMacenski** [comment]
And are you sure that your path to the map is absolute? What other errors do you see, if any?  Does it work fine if you don't specify the map path and uses the default? There are a number of questions here we need answers to to help :smile:

**Comment by SteveMacenski** [comment]
Closing due to lack of response and cannot reproduce. If you continue to have a problem, feel free to comment back here or file on ROS Answers.
