### ISSUE TITLE
ClearCostmapAroundRobot not in Groot

### ISSUE THREAD

**Issue by MrOCW** [ros-planning/navigation2#3105]
## Bug report

**Required Info:**

- Operating System:
  - Jetpack 4.6.1 (Ubuntu 18.04) running Ubuntu 22.04 docker container
- ROS2 Version:
  - Humble binaries
- Version or commit hash:
  - latest apt
- DDS implementation:
  - CycloneDDS

#### Steps to reproduce issue
Import node palette into Groot from /opt/ros/humble/nav2_behaviour_tree/nav2_tree_nodes.xml

#### Expected behavior
ClearCostmapAroundRobot to appear in the palette
#### Actual behavior
Only ClearEntireCostmap is available
#### Additional information
During contextual recovery, clear entire costmap is used but it takes a very long time for the global costmap to appear again after being cleared, likely due to a large static map, which almost caused a collision as there is no global costmap for the global planner to identify obstacles. Will using ClearCostmapAroundRobot speed up the time needed for the global costmap to appear again?

Replacing ClearEntireCostmap with ClearCostmapAroundRobot manually in the xml file does not produce errors but the costmap doesnt clear around the robot anyways. Manually calling the service doesnt clear it as well. I get this message whenever contextual recovery or recovery subtree gets ticked.
[bt_navigator-11] [WARN] [1660115595.034508823] [bt_navigatornavigate_to_pose_rclcpp_node]: Node timed out while executing service call to global_costmap/clear_around_global_costmap

**Comment by SteveMacenski** [comment]
It can be added to https://github.com/ros-planning/navigation2/blob/main/nav2_behavior_tree/nav2_tree_nodes.xml, would you mind submitting a PR to add this missing BT node so you can use it in groot? I'd be happy to merge it.

**Comment by enesbedir1** [comment]
Hİ @SteveMacenski I created a pr #3155  for the issue 
I would be appreciated if you consider reviewing it.

**Comment by SteveMacenski** [comment]
Merged!
