### ISSUE TITLE
AMCL integration test

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#312]
- To run AMCL integration test Gazebo needs to be launched. 

- Update `test_localization_launch.py` file to launch gazebo.

**Comment by mkhansen-intel** [comment]
@mhpanah - Actually, we can create a new test_amcl_launch.py and have it include the needed launch files. I'll post the system test which is doing this.

**Comment by mkhansen-intel** [comment]
Here's a branch with the gazebo_launch.py file.

**Comment by mhpanah** [comment]
Addressed in PR #388.
