### ISSUE TITLE
Unable to trigger minimum speed condition in xy_theta_iterator due to always False theta speed condition (min_speed_theta = 0.0)

### ISSUE THREAD

**Issue by smkyle90** [ros-planning/navigation2#3134]
https://github.com/ros-planning/navigation2/blob/1421f17bd033b7c76affb655885a9f44904e1ecf/nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp#L102

I have been trying to configure the `dwb_core::DWBLocalPlanner` to generate valid twists with a linear speed range of [0.5, 1.0], however, the minimum speed condition in [xy_theta_iterator.cpp](https://github.com/ros-planning/navigation2/blob/1421f17bd033b7c76affb655885a9f44904e1ecf/nav2_dwb_controller/dwb_plugins/src/xy_theta_iterator.cpp#L102) has an `&&` condition that is always false for my application.

Thus, even if my minimum speed condition is true and renders the speed invalid (desired behaviour), the `&&` condition on the theta velocity is always false (since `minimum_theta_speed: 0.0`) and the logic of `fabs(theta) + EPSILON < kinematics.getMinSpeedTheta()` is necessarily `false`, returning false for the whole statement, and therefore, all speeds in the range [0.0, 1.0] are deemed to be valid.

Is there a reason the condition that checks the `min_speed_xy` configuration is coupled with the `min_speed_theta` logic? 

If this is a one-off for my application, I am happy to fork and carry on. Otherwise, I can submit a PR de-coupling these checks. See code snippet below that is now giving the expected outcome. 

```C++
bool XYThetaIterator::isValidSpeed(double x, double y, double theta)
{
  KinematicParameters kinematics = kinematics_handler_->getKinematics();
  double vmag_sq = x * x + y * y;
  if (kinematics.getMaxSpeedXY() >= 0.0 && vmag_sq > kinematics.getMaxSpeedXY_SQ() + EPSILON) {
    return false;
  }
  // separate linear and rotational min speeds as they are not really dependent on each other.
  if (kinematics.getMinSpeedXY() >= 0.0 && vmag_sq + EPSILON < kinematics.getMinSpeedXY_SQ()) {
    return false;
  }
  if (kinematics.getMinSpeedTheta() >= 0.0 && fabs(theta) + EPSILON < kinematics.getMinSpeedTheta()) {
    return false;
  }
  if (vmag_sq == 0.0 && th_it_->getVelocity() == 0.0) {
    return false;
  }
  return true;
}
```

**Comment by SteveMacenski** [comment]
That seems reasonable to me. @DLu given this is your logic from the ROS 1 version, do you agree that this is a sensible change?

@smkyle90 please open the PR
