### ISSUE TITLE
nav2_bringup: Multi robot sim - goal_checker_plugins parameters have wrong format

### ISSUE THREAD

**Issue by ipa-kut** [ros-planning/navigation2#3136]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04/Ubuntu 20.04
- ROS2 Version:
  - Humble/Rolling/Galactic/
- Version or commit hash:
  - 10cd1a118b3e679cbbcb1edc9109e1ac102f4a76
- DDS implementation:
  - Default of ROS2

#### Steps to reproduce issue

```
ros2 launch nav2_bringup multi_tb3_simulation_launch.py
```

#### Expected behavior

Multi robot simulation launches properly without errors

#### Actual behavior

Everything else starts up, but the controllers crash and navigation does not work. The exact failure messages are:

```
[controller_server-8]   what():  parameter 'goal_checker_plugins' has invalid type: Wrong parameter type, parameter {goal_checker_plugins} is of type {string_array}, setting it to {string} is not allowed.
...
[ERROR] [controller_server-8]: process has died [pid 132737, exit code -6,
```
This is repeated for every robot launched.

#### Additional information

As the message reports, the `goal_checker_plugins` should be declared as a list of strings in the param files [here](https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/params/nav2_multirobot_params_1.yaml#L116) and [here](https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/params/nav2_multirobot_params_2.yaml#L116), but are declared as single strings only. 

The fix is to enclose the string values in square brackets. If this solution is acceptable, I can make PRs.

**Comment by SteveMacenski** [comment]
LGTM
