### ISSUE TITLE
[Eloquent] Malloc Error when Launching Bt Navigator

### ISSUE THREAD

**Issue by dverstandig** [ros-planning/navigation2#3143]
Hello,

I am trying to run navigation2 on eloquent and running into several issues when launching the BT navigator.

The first one being:
`[bt_navigator-7] [ERROR] []: Could not load library: /opt/ros/eloquent/lib/libnav2_compute_path_to_pose_action_bt_node.so: undefined symbol: _ZTIN2BT14CoroActionNodeE`

This was fixed by building BehaviorTreeCPP from source as suggested here: https://github.com/ros-planning/navigation2/issues/1948

When building from source, I know get a malloc error when launching the BT navigator:
`[bt_navigator-4] malloc(): memory corruption`

- Operating System:
  -  Ubuntu 18.04
- ROS2 Version:
  - Eloquent
- Version or commit hash:
  - ros-eloquent-navigation2
  -  BehaviorTree.cpp 3.7.0 (commit 8db5593a880c60211a8871bfe4da5b2507f726b3)
- DDS implementation:
  - Default DDS for Eloquent

Any idea what the issue could be?
Thanks!

**Comment by SteveMacenski** [comment]
Unfortunately, Eloquent has been ended of life about 2 years ago and won't receive further support. The best I can give you is to properly follow the dependencies of the distribution you're using - according to our records the BT.CPP should not be 3.7.0 but rather 3.5.3

https://github.com/ros-planning/navigation2/blob/eloquent-devel/tools/ros2_dependencies.repos
