### ISSUE TITLE
Use SetParameter Launch API to set the yaml filename for map_server

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#3149]
Would let us remove the RewrittenYaml remappings entirely and let us remove the requirement of a bogus `yaml_filename` entry in the yaml file to be overwritten. Now, it could just not be present at all and that would be fine. Just need to make sure that this is set only for the `map_server` node, which should be straight forward. 

See https://github.com/ros-planning/navigation2/pull/3131 for a motivating example and fixes https://github.com/ros-planning/navigation2/issues/3111 to be less quirky @superseppl. Thanks @tonynajjar once again for a timely PR that helps fix another problem

Note that we should also remove the `note` I added to the navigation.ros.org configuration for map server explaining that `yaml_filename` is strictly required.

**Comment by stevedanomodolor** [comment]
@SteveMacenski I can try it this weekend

**Comment by stevedanomodolor** [comment]
This might sound like a silly question but just to confirm. When you mean by

> Just need to make sure that this is set only for the `map_server` node, which should be straight forward.

If the set parameter is set for only the map_server node, what about other node that takes uses the params. For example the following launch file from the localization launch file 

```
load_nodes = GroupAction(
        condition=IfCondition(PythonExpression(['not ', use_composition])),
        actions=[
            SetParameter("use_sim_time", use_sim_time),
Node(
                package='nav2_map_server',
                executable='map_server',
                name='map_server',
                output='screen',
                respawn=use_respawn,
                respawn_delay=2.0,
                parameters=[configured_params],
                arguments=['--ros-args', '--log-level', log_level],
                remappings=remappings),
            Node(
                package='nav2_amcl',
                executable='amcl',
                name='amcl',
                output='screen',
                respawn=use_respawn,
                respawn_delay=2.0,
                parameters=[configured_params],
                arguments=['--ros-args', '--log-level', log_level],
                remappings=remappings),
            Node(
                package='nav2_lifecycle_manager',
                executable='lifecycle_manager',
                name='lifecycle_manager_localization',
                output='screen',
                arguments=['--ros-args', '--log-level', log_level],
                parameters=[{'autostart': autostart},
                            {'node_names': lifecycle_nodes}])
```
Similar to https://github.com/ros-planning/navigation2/pull/3131, would it not be also effective to set the yaml filename similarly as the  use_sim_time is set?

**Comment by SteveMacenski** [comment]
Awesome!
