### ISSUE TITLE
RegulatedPurePursuitController:: getCostmapMaxExtent() is incorrectly written

### ISSUE THREAD

**Issue by xianglunkai** [ros-planning/navigation2#3152]
double RegulatedPurePursuitController::getCostmapMaxExtent() const
{
  const double max_costmap_dim_meters = std::max(
    costmap_->getSizeInMetersX(), costmap_->getSizeInMetersY());
  return max_costmap_dim_meters / 2.0;
}

**Comment by SteveMacenski** [comment]
Thanks!
