### ISSUE TITLE
where to find OpenVSLAM integration?

### ISSUE THREAD

**Issue by LangDaoAI** [ros-planning/navigation2#3170]
Hi Team,

I want to know where to find OpenVSLAM integration and how to config/use such integration?

Thanks!

**Comment by SteveMacenski** [comment]
There is no integration at this time. We did not feel it was suitably robust to provide as a default option and have the high-quality user experience we want Nav2 to be known for. 

It is obviously not hard to implement to replace AMCL or SLAM Toolbox via map->odom transform, but we don’t offer OpenVSLAM as a default integration
