### ISSUE TITLE
Simple Commander API foxy support

### ISSUE THREAD

**Issue by sreesms** [ros-planning/navigation2#3176]
I am trying to implement simple goal navigation in nav2. I have checked  the Simple Commander API, (https://navigation.ros.org/commander_api/index.html#simple-commander-api). But I have found no modules in foxy-devel for the same. Can anyone suggest how to use the Simple commander API in ROS foxy?

**Comment by SteveMacenski** [comment]
There is no support for this in Foxy. Please use Galactic or newer for Simple Commander API.

**Comment by emiraykin** [comment]
This could help for goal sending : https://github.com/emiraykin/Nav2-Simple-Commander-for-Foxy-and-below
