### ISSUE TITLE
Topic subscription in nav2_simple_commander not working

### ISSUE THREAD

**Issue by MrOCW** [ros-planning/navigation2#3187]
## Bug report

**Required Info:**

- Operating System:
  - Jetpack 4.6.1 
- ROS2 Version:
  - Humble
- Version or commit hash:
  - source, commit: 34ecee20a1913a71bc345b0438a0081b73159458
- DDS implementation:
  - CycloneDDS -->

#### Steps to reproduce issue
In robot_navigator.py, add these lines:

IN THE CONSTRUCTOR
```
self.odom = Odometry()
self.odometry_sub = self.create_subscription(Odometry,
                                                    'odometry_filtered',
                                                    self._odometryCallback,
                                                    1)
self.global_costmap = PyCostmap2D(OccupancyGrid())
self.global_costmap_sub = self.create_subscription(OccupancyGrid,
                                                              'global_costmap/costmap',
                                                              self._costmapCallback,
                                                             10)  
```
SEPARATE CALLBACK FUNCTIONS
```
def _costmapCallback(self,msg):
        self.global_costmap = PyCostmap2D(msg)
        self.info("Global Costmap has been updated")
        return


def _odometryCallback(self, msg):
        self.odom.pose.pose.position.x = msg.pose.pose.position.x
        self.odom.pose.pose.position.y = msg.pose.pose.position.y
        self.odom.pose.pose.orientation.z = msg.pose.pose.orientation.z
        self.odom.pose.pose.orientation.w = msg.pose.pose.orientation.w
        return
```
printing navigator.odom and navigator.global_costmap.getCost(int(mx),int(my)) returns 0 every time in another script which is running followWaypoints

Also, I'm pretty sure I'm not using PyCostmap2D correctly as I am creating new instances of PyCostmap2D at each callback...
Are there any example showing the correct way of initializing and updating a PyCostmap2D object during runtime?

#### Expected behavior
Print the odometry of the robot and the cost in the global costmap every second
#### Actual behavior
Both returns 0,0 and 0 every second

**Comment by SteveMacenski** [comment]
Ask on ros answers, this not the right place for application assistance. If all of your subscription objects are wrong, its likely nothing to do with this project.
