### ISSUE TITLE
Request to support additional sensors in collision monitor

### ISSUE THREAD

**Issue by automech-rb** [ros-planning/navigation2#3225]
#### Feature description

Add support for RGBD sensor (`sensor_msgs/Image`) for collision monitor.

#### Implementation considerations

Similar to sensor described at : https://navigation.ros.org/setup_guides/sensors/setup_sensors.html

**Comment by SteveMacenski** [comment]
A depth image can be easily converted into a PointCloud2 for use via a depth image proc pipeline instance.

**Comment by automech-rb** [comment]
My mindset was to not increase one more topic as `sensor_msgs/Image` type is supported in Costmap2D. But what you say makes sense too.

Closing the issue.

**Comment by SteveMacenski** [comment]
Images are not supporting costmap 2D. That section is going over types of gazebo sensors for simulation
