### ISSUE TITLE
Add Savitzky–Golay Path Smoother

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#3246]
I did some quick prototypes and pretty happy with the results of applying SG filters to the problem of path smoothing. Unlike the simple smoother, this won't deviate from the path much, so no need to collision check. Its also analytical so no numerous iterations to converge.

I found the [7-point quadratic formulation](https://en.wikipedia.org/wiki/Savitzky%E2%80%93Golay_filter) to work quite well. 5 point did OK if we did so iteratively, but 7 point was actually good alone. 

Task: take R&D code below to clean up and add into a new path smoother algorithm.

Questions / features:
- Include refinement option (e.g. run recursively a few times)
- Add in orientation vectors
- Support for reverse segmentation 
- Does this maintain turning boundary conditions on minimum curvature? -- Seems so
- Default include in NavFn to remove odd artifacts?

```
  // std::array<double, 5> filter{-3.0/35.0, 12.0/35.0, 17.0/35.0, 12.0/35.0, -3.0/35.0};
  std::array<double, 7> filter{-2.0/21.0, 3.0/21.0, 6.0/21.0, 7.0/21.0, 6.0/21.0, 3.0/21.0, -2.0/21.0};
  const unsigned int & num_sequences = plan.poses.size();

  auto applyFilter = [&](const std::vector<double> & data) -> float {
      float val = 0.0;
      for (unsigned int i = 0; i != filter.size(); i++) {
        val += filter[i] * data[i];
      }

      return val;
    };

  auto applyFilterOverX =
    [&](nav_msgs::msg::Path & path) -> void
    {
      unsigned int idx = 0;
      // TODO update for 7 pt
      // path.poses[0].pose.position.x = applyFilter({
      //   path.poses[0].pose.position.x,
      //   path.poses[0].pose.position.x,
      //   path.poses[0].pose.position.x,
      //   path.poses[1].pose.position.x,
      //   path.poses[2].pose.position.x});

      // idx++;
      // path.poses[1].pose.position.x = applyFilter({
      //   path.poses[0].pose.position.x,
      //   path.poses[1].pose.position.x,
      //   path.poses[1].pose.position.x,
      //   path.poses[2].pose.position.x,
      //   path.poses[3].pose.position.x});

      for (unsigned int idx = 3; idx != num_sequences - 3; idx++) {
        path.poses[idx].pose.position.x = applyFilter({
          path.poses[idx - 3].pose.position.x,
          path.poses[idx - 2].pose.position.x,
          path.poses[idx - 1].pose.position.x,
          path.poses[idx].pose.position.x,
          path.poses[idx + 1].pose.position.x,
          path.poses[idx + 2].pose.position.x,
          path.poses[idx + 3].pose.position.x});
      }

      // idx++;
      // path.poses[idx].pose.position.x = applyFilter({
      //     path.poses[idx - 2].pose.position.x,
      //     path.poses[idx - 1].pose.position.x,
      //     path.poses[idx].pose.position.x,
      //     path.poses[idx + 1].pose.position.x,
      //     path.poses[idx + 1].pose.position.x});

      // idx++;
      // path.poses[idx].pose.position.x = applyFilter({
      //    path.poses[idx - 2].pose.position.x,
      //     path.poses[idx - 1].pose.position.x,
      //     path.poses[idx].pose.position.x,
      //     path.poses[idx].pose.position.x,
      //     path.poses[idx].pose.position.x});
    };

  auto applyFilterOverY =
    [&](nav_msgs::msg::Path & path) -> void
    {
      // TODO update for 7 pt
      // unsigned int idx = 0;
      // path.poses[0].pose.position.y = applyFilter({
      //   path.poses[0].pose.position.y,
      //   path.poses[0].pose.position.y,
      //   path.poses[0].pose.position.y,
      //   path.poses[1].pose.position.y,
      //   path.poses[2].pose.position.y});

      // idx++;
      // path.poses[1].pose.position.y = applyFilter({
      //   path.poses[0].pose.position.y,
      //   path.poses[1].pose.position.y,
      //   path.poses[1].pose.position.y,
      //   path.poses[2].pose.position.y,
      //   path.poses[3].pose.position.y});

      for (unsigned int idx = 3; idx != num_sequences - 3; idx++) {
        path.poses[idx].pose.position.y = applyFilter({
          path.poses[idx - 3].pose.position.y,
          path.poses[idx - 2].pose.position.y,
          path.poses[idx - 1].pose.position.y,
          path.poses[idx].pose.position.y,
          path.poses[idx + 1].pose.position.y,
          path.poses[idx + 2].pose.position.y,
          path.poses[idx + 3].pose.position.y});
      }

      // idx++;
      // path.poses[idx].pose.position.y = applyFilter({
      //     path.poses[idx - 2].pose.position.y,
      //     path.poses[idx - 1].pose.position.y,
      //     path.poses[idx].pose.position.y,
      //     path.poses[idx + 1].pose.position.y,
      //     path.poses[idx + 1].pose.position.y});

      // idx++;
      // path.poses[idx].pose.position.y = applyFilter({
      //    path.poses[idx - 2].pose.position.y,
      //     path.poses[idx - 1].pose.position.y,
      //     path.poses[idx].pose.position.y,
      //     path.poses[idx].pose.position.y,
      //     path.poses[idx].pose.position.y});
    };

  applyFilterOverX(plan2);
  applyFilterOverY(plan2);
```

**Comment by SteveMacenski** [comment]
This branch as the work: https://github.com/ros-planning/navigation2/tree/sgf_smoother

Still needs unit tests and general testing that it works as expected, but mostly ready to go

**Comment by AlexeyMerzlyakov** [comment]
Duplicating the Slack, just for the case:
The SGF smoother was estimated with SmacHybrid and default NavFn path planner. On both, it produces pretty aligned smoothed path, except of its goal. At the end of path, SGF smoother every time makes incorrect movements, as shown at the attached pictures below (for SmacHybrid planner):
![Screenshot from 2022-10-28 11-39-33](https://user-images.githubusercontent.com/60094858/198552945-df73d551-78da-4114-87be-b72c8b96a3a3.png)
![Screenshot from 2022-10-28 11-40-45](https://user-images.githubusercontent.com/60094858/198552980-3ffc2c79-2e7d-4fcc-8604-7813b2716609.png)
![Screenshot from 2022-10-28 11-42-06](https://user-images.githubusercontent.com/60094858/198553131-6d03e2c1-bb01-4f4f-98b0-5dd44c26f46d.png)

Similar situation for NavFn planner, but unlike SHA* planner, the goal to be reached in this case:
![Screenshot from 2022-10-28 11-49-22](https://user-images.githubusercontent.com/60094858/198553425-a3b98e90-822c-4265-b839-11c73c0edd7b.png)
![Screenshot from 2022-10-28 11-49-32](https://user-images.githubusercontent.com/60094858/198553435-cc968d56-6f97-4dc8-aaf9-80ba5a61d963.png)
From the testing sight, it seems that final direction is being to be correct, while the smoothed poses coordinates near the goal are walking around.

**Comment by SteveMacenski** [comment]
Pushed branch resolves!

**Comment by SteveMacenski** [comment]
I hope tomorrow to get on unit tests & doc updates. I'd like this pushed before week's end so I can focus on the EOY tasks (Nav Algo paper + MPPI)

**Comment by AlexeyMerzlyakov** [comment]
I've verified the path smoother with NavFn, ThetaStar and Smac-HybridA* (DUBIN).
Now all cases are working pretty well, smoothing the local factured paths, produced by path planners.
Here is the examples for NavFn (high resolution collage, best to click):
![NavFn](https://user-images.githubusercontent.com/60094858/199442376-63150550-0ed3-494a-bbe1-74e9927b8451.png)
... and for ThetaStar:
![theta_star](https://user-images.githubusercontent.com/60094858/199442432-5f653a5d-820c-4888-996f-1baa5c9182d0.png)

For SmacHybridA*, the following metrics (collected by [smoother_benchmarking](https://github.com/ros-planning/navigation2/tree/main/tools/smoother_benchmarking), and compared with SS and CS) were obtained:
```
--------------------  --------------------  ------------------  ------------------  --------  ----------------------  -----------------------
Planner               Time (s)              Path length (m)     Average cost        Max cost  Path smoothness (x100)  Average turning rad (m)
SmacHybrid            0.11719178941200001   11.504739520948565  12.258683968318367  129.462   1.586654909354627       0.7057524803168388
simple_smoother       0.001119348878        11.002066883616866  18.05353044518565   127.16    0.4624616549599383      3.102313187507408
constrained_smoother  0.022246623292000004  11.493715590115078  6.881435517035139   103.975   1.314291295118698       2.5888961854885775
sgf_smoother          5.5814876e-05         11.467456502405593  12.181844171244819  127.762   1.2115300728553242      2.2909156972353713
--------------------  --------------------  ------------------  ------------------  --------  ----------------------  -----------------------
```

**Comment by SteveMacenski** [comment]
Sweet - you already knew what I was thinking too. Needed metrics for it to add to the paper :wink: 

Thanks for doing the real-world tests. I plan to write the unit tests tomorrow which should button up this topic then beyond documentation!

**Comment by SteveMacenski** [comment]
Merging imminent
