### ISSUE TITLE
Port costmap_2d_markers and costmap_2d _cloud visualization tools

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#326]
There are two costmap_2d executables ([costmap_2d_markers](https://github.com/ros-planning/navigation2/blob/master/nav2_costmap_2d/src/costmap_2d_markers.cpp) and [costmap_2d_cloud](https://github.com/ros-planning/navigation2/blob/master/nav2_costmap_2d/src/costmap_2d_cloud.cpp)) which have yet to be ported. They are not part of the critical navigation path, but  (to my knowledge) provides publishers for voxel grid visualization.

**Comment by SteveMacenski** [comment]
Thoughts on just including them in the voxel layer itself? The cloud uses a `sensor_msgs::PointCloud` which has long been replaced by most folks with `sensor_msgs::PointCloud2`. Markers could be reused elsewhere though I dont know that anyone actually is

**Comment by crdelsey** [comment]
This is done now.
