### ISSUE TITLE
Node and parameter namespaces

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#327]
In ROS1, parameters were scoped under the node (i.e. parameter 'foo' on node 'node' would be /node/foo) in the parameter server. In ROS2, parameters are hosted on the node itself with no such fully qualified scope. A prefix parameter namespace is allowed via ROS2 (see [rcl_yaml_param_parser](https://github.com/ros2/rcl/tree/master/rcl_yaml_param_parser)), however. This is useful to distinguish between parameters which live on the same node or namespace. In the navigation2 code, there are instances where we should establish convention on which parameters should receive a prefix, if not all parameters. 

On node namespaces, this issue affects parameter events and whether nodes on the same namespace have duplicate parameter names or receive callbacks from other nodes on its namespace. I am proposing some upstream changes to resolve the event's source node, but for now it is not case.

Some options:
- We could have all parameters be prefixed with its host node
- For dynamic parameters (i.e. can change during run-time), if duplicate parameters exist across nodes in same namespace, we could either create a separate namespace for each node or create a prefix for those parameters
- Any duplicate parameters existing on the same node should be given unique prefix
- example parameter namespace: '_node.prefix.param_'

**Comment by mkhansen-intel** [comment]
We discussed with @gbiggs and @mikeferguson during the Nav2 WG and I think we came to the conclusion that yes we need a convention everywhere that includes a prefix as in the example given above: node.name.param. 

Others please feel free to comment here.
