### ISSUE TITLE
cannot use other built-in behavior tree xml

### ISSUE THREAD

**Issue by foxydevelby** [ros-planning/navigation2#3295]
- Operating System:
      Ubuntu 20.04
- ROS2 Version:
      ROS2 Galactic

#### Steps to reproduce issue
      added line in nav2_params.yaml to change the default behavior tree

    bt_navigator:
       ros__parameters:
         use_sim_time: True
         global_frame: map
         robot_base_frame: base_link
         odom_topic: /odom
         bt_loop_duration: 10
         default_server_timeout: 20
         enable_groot_monitoring: True
         groot_zmq_publisher_port: 2000
         groot_zmq_server_port: 2001
         # 'default_nav_through_poses_bt_xml' and 'default_nav_to_pose_bt_xml' are use defaults:
         # nav2_bt_navigator/navigate_to_pose_w_replanning_and_recovery.xml
        # nav2_bt_navigator/navigate_through_poses_w_replanning_and_recovery.xml
        # They can be set here or via a RewrittenYaml remap from a parent launch file to Nav2.
       **default_bt_xml_filename: "follow_point.xml"
       default_nav_to_pose_bt_xml: "follow_point.xml"
       default_nav_through_poses_bt_xml: "follow_point.xml"**
#### Expected behavior
      will load the configured behavior tree
#### Actual behavior
[bt_navigator-11] [INFO] [1669006996.718676261] [bt_navigator]: Activating
[bt_ [ERROR] [1669006996.718738750] [bt_navigator]: Couldn't open input XML file: follow_point.xml
[bt_navigator-11] [ERROR] [1669006996.718759869] [bt_navigator]: Error loading XML file: follow_point.xml
[lifecycle_manager-13] [ERROR] [1669006996.719096599] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator

**Comment by SteveMacenski** [comment]
Provide the full file path. The param file has no concept of where that could be located in your filesystem.
