### ISSUE TITLE
AMCL hangs on GetMap service during constructor

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#330]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - source
- Version or commit hash:
  - master branch
- DDS implementation:
  - default (FastRTPS)
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```
ros2 launch nav2_bringup nav2_bringup_lauch.py map:=<path to map.yaml> use_sim_time:=True

```
In a 2nd window:
```
ros2 param set /static_transform_publisher use_sim_time True
```
When using the GetMap service, the AMCL will hang in the constructor.

**Comment by mkhansen-intel** [comment]
Labeling as medium since we have a working way of doing this, so this isn't currently gating release. We should still root cause and fix as soon as we can.

**Comment by crdelsey** [comment]
This problem is no longer present
