### ISSUE TITLE
Necessary ompl includes are not exported by nav2_smac_planner

### ISSUE THREAD

**Issue by malban** [ros-planning/navigation2#3357]
## Bug report

Necessary ompl includes are not exported by nav2_smac_planner

**Required Info:**

- Operating System:
Ubuntu 22.04

- ROS2 Version:
  - humble binaries
- Version or commit hash:
  - 1.1.3-1jammy.20221207.052822
- DDS implementation:
  - cycloneDDS

#### Steps to reproduce issue

include `#include <nav2_smac_planner/smac_planner_lattice.hpp>` in a source file in a ROS package that has included `nav2_smac_planner` as a dependency and try to build it.

Unless the ompl include directories have been exported by some other dependency of the package, they won't be found causing the build to fail.

#### Expected behavior

ompl includes are found and the build succeeds

#### Actual behavior

```
In file included from /opt/ros/humble/include/nav2_smac_planner/node_2d.hpp:30,
                 from /opt/ros/humble/include/nav2_smac_planner/analytic_expansion.hpp:23,
                 from /opt/ros/humble/include/nav2_smac_planner/a_star.hpp:30,
                 from /opt/ros/humble/include/nav2_smac_planner/smac_planner_lattice.hpp:22,
...

/opt/ros/humble/include/nav2_smac_planner/node_hybrid.hpp:28:10: fatal error: ompl/base/StateSpace.h: No such file or directory
   28 | #include "ompl/base/StateSpace.h"
```

**Comment by SteveMacenski** [comment]
Thanks! Will review PR shortly
