### ISSUE TITLE
Build warning: easy_install and setup.py install are deprecated

### ISSUE THREAD

**Issue by AndyZe** [ros-planning/navigation2#3363]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22
- ROS2 Version:
  - Rolling, building from source
- Version or commit hash:
  - latest commit on main (c841417)
- DDS implementation:
  - Cyclone

When building from source, I get these warnings:

```
#0 46.17 --- stderr: nav2_simple_commander
#0 46.17 /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
#0 46.17   warnings.warn(
#0 46.17 /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
```

I think the docker commands I'm using to build are pretty straight forward:

```
FROM ros:rolling

SHELL [ "/bin/bash", "-c" ]

# Install dependencies
# Note the ros-rolling-gazebo-ros* packages are needed here as they are 
# not captured by the package dependencies when running rosdep install.
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        bash-completion \
        openssh-client \
        python3-pip \
        ros-rolling-gazebo-ros*

# Set up CycloneDDS as ROS 2 middleware
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        ros-rolling-rmw-cyclonedds-cpp
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# Create Underlay workspace
ARG UNDERLAY_WS=/opt/underlay_ws
ENV UNDERLAY_WS=${UNDERLAY_WS}
WORKDIR ${UNDERLAY_WS}/src
COPY ./tiago_simulation.repos ../
RUN vcs import < ../tiago_simulation.repos
RUN source /opt/ros/rolling/setup.bash && \
    rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y
WORKDIR ${UNDERLAY_WS}
RUN source /opt/ros/rolling/setup.bash && \
    colcon build --symlink-install --packages-skip nav2_system_tests
```

**Comment by SteveMacenski** [comment]
Does that not happen for all python ROS 2 packages? The last my understanding was, this wasn't something we could migrate away from (yet?) out of our control. If that's changed, it would be good to know and happy to have fixed in Nav2!

**Comment by AlexeyMerzlyakov** [comment]
I have the same issue on Jammy and ROS2 Rolling built from sources. No problems on Focal with the same ROS2 sources. 
There are also lots of same messages during ROS2 build process itself. Seems to have the same problems described in https://github.com/colcon/colcon-core/issues/454 and https://github.com/ament/ament_cmake/issues/382. Both tickets are open, as a workaround they are suggesting to downgrade the `setuptools` python package version (although did not checked yet locally w/a).

**Comment by SteveMacenski** [comment]
Until there's a real ROS-2-wide solution, I'm going to close this since its not actionable.
