### ISSUE TITLE
Can not correctly read YAML parameters for multi-components node on non-root namespace

### ISSUE THREAD

**Issue by AlexeyMerzlyakov** [ros-planning/navigation2#3376]
The bug discovered during fix developing for #3182.
When running two or more component nodes inside one container with some non-empty root namespace, composable nodes inside this container can not read ROS-parameters from YAML correctly.

## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04, 22.04
- ROS2 Version:
  - ROS2 Rolling built from sources (check-up date 2023.01.10)
- Version or commit hash:
  - 9e070b7e
- DDS implementation:
  - CycloneDDS

#### Steps to reproduce issue
Consider the attached example package: [nav2_pkg.zip](https://github.com/ros-planning/navigation2/files/10457658/nav2_pkg.zip)
This example contains two lifecycle nodes, exported as composable nodes, that are reading `node_param` parameter from input YAML-file (by-default parameter's value is `UNDEFINED`):
```
node1:
  ros__parameters:
    node_param: "PASS"
node2:
  ros__parameters:
    node_param: "PASS"
```

Unpack it in `navigation2` source directory and build it:
```
 colcon build --symlink-install --packages-select nav2_pkg
```

Then run the example with some root namespace (e.g. `robot1`):
```
ros2 launch nav2_pkg test_launch.py namespace:=robot1 use_composition:=True 
```
Here the launch-file - is a simplified `localization_launch.py` from nav2_bringup.

#### Expected behavior
Both parameters to be set to `PASS` value, that could be observed from logs.

#### Actual behavior
In case of composable node on `robot1` root namespace and we could observe some kind of undefined behavior: for the first initialized node this parameter to be read from input YAML, while for other ones it can not and to be left to default:
```
ros2 launch nav2_pkg test_launch.py namespace:=robot1 use_composition:=True
...
[component_container_isolated-1] [INFO] [1674138269.616420930] [robot1.lifecycle_manager_localization]: Configuring node1
[component_container_isolated-1] [INFO] [1674138269.616951726] [robot1.node1]: Configuring
[component_container_isolated-1] [INFO] [1674138269.617034718] [robot1.node1]: NODE1 name = node1, namespace = /robot1
[component_container_isolated-1] [INFO] [1674138269.617052866] [robot1.node1]: node_param = PASS
[component_container_isolated-1] [INFO] [1674138269.617675336] [robot1.lifecycle_manager_localization]: Configuring node2
[component_container_isolated-1] [INFO] [1674138269.617915953] [robot1.node2]: Configuring
[component_container_isolated-1] [INFO] [1674138269.617993659] [robot1.node2]: NODE2 name = node2, namespace = /robot1
[component_container_isolated-1] [INFO] [1674138269.618012148] [robot1.node2]: node_param = UNDEFINED
```

Running the same example, but with conventional separate nodes will give correct result:
```
ros2 launch nav2_pkg test_launch.py namespace:=robot1 use_composition:=False
...
[lifecycle_manager-3] [INFO] [1674138305.137439608] [robot1.lifecycle_manager_localization]: Configuring node1
[node1-1] [INFO] [1674138305.138322511] [robot1.node1]: Configuring
[node1-1] [INFO] [1674138305.138406182] [robot1.node1]: NODE1 name = node1, namespace = /robot1
[node1-1] [INFO] [1674138305.138425920] [robot1.node1]: node_param = PASS
[lifecycle_manager-3] [INFO] [1674138305.139189646] [robot1.lifecycle_manager_localization]: Configuring node2
[node2-2] [INFO] [1674138305.139818653] [robot1.node2]: Configuring
[node2-2] [INFO] [1674138305.139908128] [robot1.node2]: NODE2 name = node2, namespace = /robot1
[node2-2] [INFO] [1674138305.139929253] [robot1.node2]: node_param = PASS
```

Moreover, if remove root-namespace (leave it empty), both composition nodes will work correctly:
```
ros2 launch nav2_pkg test_launch.py use_composition:=True
...
[component_container_isolated-1] [INFO] [1674138331.440440362] [lifecycle_manager_localization]: Configuring node1
[component_container_isolated-1] [INFO] [1674138331.440878937] [node1]: Configuring
[component_container_isolated-1] [INFO] [1674138331.440951747] [node1]: NODE1 name = node1, namespace = /
[component_container_isolated-1] [INFO] [1674138331.440970335] [node1]: node_param = PASS
[component_container_isolated-1] [INFO] [1674138331.441564540] [lifecycle_manager_localization]: Configuring node2
[component_container_isolated-1] [INFO] [1674138331.441749216] [node2]: Configuring
[component_container_isolated-1] [INFO] [1674138331.441810231] [node2]: NODE2 name = node2, namespace = /
[component_container_isolated-1] [INFO] [1674138331.441827782] [node2]: node_param = PASS
```

#### Additional information

The fact that undefined behavior appears only for composable nodes with non-empty root namespace leads to thought that the problem might be in composable node running mechanism, or RewrittenYAML parser. Needs an additional investigation.

**Comment by SteveMacenski** [comment]
Please move this discussion back to the other ticket, that's all related to the same issue.

But I also don't see an issue here. The parameter values in the parameter file must also be under the namespace. If you want to use non-namespaced node yaml names, that's why we have that rewritten yaml script in the launch system.
