### ISSUE TITLE
Local planner failing with new obstacle and stopping navigation completely

### ISSUE THREAD

**Issue by brean** [ros-planning/navigation2#3392]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04, Ubuntu 22.04
- ROS2 Version:
  - ROS2 foxy binaries, ROS2 humble binaries
- Version or commit hash:
  - ros-foxy-navigation2	0.4.7-1focal.20221104.131617
  - ros-humble-navigation2	1.1.3-1jammy.20221207.081347
- DDS implementation:
  - Fast-RTPS, CyclonDDS (for humble)

#### Steps to reproduce issue
1. start the default ROS2 turtlebot simulation environment with rviz:
  - `ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py`(for gazebo or the bringup script on your turtlebot if you use real hardware)
  - `ros2 launch turtlebot3_navigation2 navigation2.launch.py map:=/opt/ros/foxy/share/nav2_bringup/maps/turtlebot3_world.yaml`
2. set the robot pose in rviz
3. set a goal somewhere on the map 
4. add an obstacle very close to the robot in Gazebo or walk in front of the real robot.

#### Expected behavior
The robot should move and follow the global plan.

#### Actual behavior
A new global path is shown in rviz but the robot just wiggles on the spot and does not move anymore. Even when given a new goal position it just stays on its spot and does not follow the global plan.

#### Additional information
No errors are shown in the log, no information that any node has stopped, the system just seems to continue but the robot does not move.
The behavior can be reproduced in simulation and on real hardware.
The obstacle has to be quite close, ~5 cm in front while the robot is moving. If the obstacle is further away the robot will just navigate around it (I assume the global planner works fine).
You can use my Docker setup to reproduce both cases for FastDDS [foxy](https://github.com/brean/ros2-turtlebot3-gazebo-docker/tree/foxy-gazebo-classic) and [humble](https://github.com/brean/ros2-turtlebot3-gazebo-docker/tree/humble-gazebo-classic) and [humble](https://github.com/brean/ros2-turtlebot3-gazebo-docker/tree/humble-gazebo-classic-cyclonedds) for CyclonDDS.

**Comment by SteveMacenski** [comment]
Ask on ROS Answers with a video or image. We're not responsible for the configurations in the TB3 repositories.
