### ISSUE TITLE
Galactic nav2_msgs.action for SmoothPath not found 

### ISSUE THREAD

**Issue by francescacavicchi** [ros-planning/navigation2#3394]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 20.04
- ROS2 Version:
 ROS2 Galactic 

#### Steps to reproduce issue
in the python cli:
from nav2_msgs.action import SmoothPath

#### Expected behavior
import successful

#### Actual behavior
SmoothPath not imported (not found in /opt/ros/galactic/lib/python3.8/site-packages/nav2_msgs/action/__init___.py)

#### Additional information
I searched in /opt/ros/galactic/lib/python3.8/site-packages/nav2_msgs/action/ and I am missing the file for it

**Comment by SteveMacenski** [comment]
Smoothers are not available in Galactic, see the repository, the smoother server was not added until humble.
