### ISSUE TITLE
Enable failing BT nodes from on_tick()

### ISSUE THREAD

**Issue by tonynajjar** [ros-planning/navigation2#3429]
#### Feature description
In my BT action and service nodes I do some input validation and would like to fail the node directly, without sending any goal, if the validation fails. I tried calling `halt()` and `setStatus(BT::NodeStatus::FAILURE)` but the goal was still sent. Is there another way I missed or is this just currently not possible?

**Comment by SteveMacenski** [comment]
I believe you may already for action: https://github.com/ros-planning/navigation2/blob/main/nav2_behavior_tree/include/nav2_behavior_tree/bt_action_node.hpp#L196-L201

But you're right services don't have the same param that an `on_tick()` can set to not do. A contribution to add that analog to the Action server node would be a great contribution!

**Comment by tonynajjar** [comment]
Ah nice I was on Humble, didn't see that this is already implemented on master. I backported to my branch :+1: 
I opened a draft PR for BTServiceNode

**Comment by SteveMacenski** [comment]
OK. I think your other ticket + the PR cover the scope of this ticket, so I'm just going to close it and continue the subconversations in those respective places.
