### ISSUE TITLE
Crash when setting should_send_goal_= false in BTActionNode

### ISSUE THREAD

**Issue by tonynajjar** [ros-planning/navigation2#3434]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22
- ROS2 Version:
  - rolling
- Version or commit hash:
  - main
- DDS implementation:
  - default

#### Steps to reproduce issue

- Checkout https://github.com/tonynajjar/navigation2/tree/test-should-send-goal 
- run: `ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False use_composition:=False` (same with composition but logs are clearer)
- send a navigate goal from rviz

result:

```
[rviz2-5] Start navigation
[rviz2-5] [INFO] [1677608877.168918659] [_]: NavigateToPose will be called using the BT Navigator's default behavior tree.
[bt_navigator-13] [INFO] [1677608877.170131589] [bt_navigator]: Begin navigating from current location to (-0.98, -0.64)
[ERROR] [bt_navigator-13]: process has died [pid 77169, exit code -11, cmd '/root/ros2_ws/install/nav2_bt_navigator/lib/nav2_bt_navigator/bt_navigator --ros-args --log-level info --ros-args -r __node:=bt_navigator -p use_sim_time:=True --params-file /tmp/tmp7t00bd9a -r /tf:=tf -r /tf_static:=tf_static'].
[lifecycle_manager-16] [INFO] [1677608881.198937704] [lifecycle_manager_navigation]: Have not received a heartbeat from bt_navigator.
[lifecycle_manager-16] [ERROR] [1677608881.198974694] [lifecycle_manager_navigation]: CRITICAL FAILURE: SERVER bt_navigator IS DOWN after not receiving a heartbeat for 4000 ms. Shutting down related nodes.
[lifecycle_manager-16] [INFO] [1677608881.198994855] [lifecycle_manager_navigation]: Terminating bond timer...
[lifecycle_manager-16] [INFO] [1677608881.198999375] [lifecycle_manager_navigation]: Resetting managed nodes...
[lifecycle_manager-16] [INFO] [1677608881.199003463] [lifecycle_manager_navigation]: Deactivating velocity_smoother
[velocity_smoother-15] [INFO] [1677608881.199244084] [velocity_smoother]: Deactivating
[velocity_smoother-15] [INFO] [1677608881.199288283] [velocity_smoother]: Destroying bond (velocity_smoother) to lifecycle manager.
[lifecycle_manager-16] [INFO] [1677608881.310584027] [lifecycle_manager_navigation]: Deactivating waypoint_follower
[waypoint_follower-14] [INFO] [1677608881.310874224] [waypoint_follower]: Deactivating
[waypoint_follower-14] [INFO] [1677608881.310964174] [waypoint_follower]: Destroying bond (waypoint_follower) to lifecycle manager.
[lifecycle_manager-16] [INFO] [1677608881.422289915] [lifecycle_manager_navigation]: Deactivating bt_navigator
```

My branch contain very minimal changes that use this [feature](https://github.com/ros-planning/navigation2/pull/3293), see the diff [here](https://github.com/ros-planning/navigation2/compare/main...tonynajjar:navigation2:test-should-send-goal?expand=1)

#### Expected behavior

No crash

#### Actual behavior

crash

#### Additional information

----

**Comment by SteveMacenski** [comment]
Thats not the actual crash report. That’s just map server crashing with your other caused crash. Please provide a traceback

**Comment by tonynajjar** [comment]
Edited

**Comment by SteveMacenski** [comment]
As a general FYI, if you see that map server lib crash, its almost never that. That's just crashing because something before it crashed. Its a signal to me to look up the log files more. 

I still need a traceback - this is just the logs. This doesn't indicate to me what is wrong.

**Comment by tonynajjar** [comment]
> I still need a traceback - this is just the logs. This doesn't indicate to me what is wrong.

Do you mean with backward_ros or gdb? If so, I didn't think that you normally require this as many bug reporters don't know how to get you that.

**Comment by SteveMacenski** [comment]
Either or, I even wrote a tutorial about it https://navigation.ros.org/tutorials/docs/get_backtrace.html. I do require it for things that I cannot look at and know the reason (and I don't have the cycles to fish for the problem).

But, as discussed above, its probably due to the fact that the goal wasn't sent so later stuff in the node is assuming some shared pointers are valid when they're not. I think discussing the question about what we would expect to have happen when `should_send_goal_` is `false` sheds some light to the degree at which we need to look into it. If we just return FAILURE, then largely this issue is probably moot

**Comment by tonynajjar** [comment]
Hey, sorry this will be delayed a little bit; I did create an internal ticket to tackle this though
