### ISSUE TITLE
build error about cv_bridge in humble

### ISSUE THREAD

**Issue by dujeong** [ros-planning/navigation2#3455]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble binaries
- Version or commit hash:
  - d40099811f62aafb4f4d16de92fbe5ddbba6009e
- DDS implementation:
  - cyclonedds

#### Steps to reproduce issue
I received the navigation2 humble branch and built the source. Dependencies were also installed through `rosdep`. However, the following error occurs when building(`colcon build --symlink-install`).

```bash
--- stderr: nav2_waypoint_follower                                                                                                                                      
In file included from /home/dujeong/nav2_ws/src/nav2_waypoint_follower/plugins/photo_at_waypoint.cpp:15:
/home/dujeong/nav2_ws/src/nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp:37:10: fatal error: cv_bridge/cv_bridge.hpp: No such file or directory
   37 | #include "cv_bridge/cv_bridge.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~

```

So I checked if the cv_bridge was installed, and it was installed.
```bash
ros-humble-cv-bridge/jammy,now 3.2.1-1jammy.20230112.154415 amd64 [installed]
```

Please let me know if anyone know about the problem.

#### Additional information

----

**Comment by SteveMacenski** [comment]
Did you pull the changes from earlier today fixing a backport error?

**Comment by TZECHIN6** [comment]
@SteveMacenski Yes, I have just clean up the src directory and pull the humble bench again, and this error occurs.

**Comment by dujeong** [comment]
@SteveMacenski Yes, I git clone today 3 hours ago.

**Comment by SteveMacenski** [comment]
Ah I see, we didn't change the `hpp` back to `h` in the header include. That's a simple fix if that resolves your issues (let me know, I'll update it in Humble)

Sorry about this - our CI in humble is out of date (well technically _forward_ dated with Rolling) so I requested these changes to get CI to turn over from other project.

**Comment by TZECHIN6** [comment]
@SteveMacenski I changed to `h` as suggested, now the error is gone, however, another similar issue pop up:
```
Finished <<< nav2_dwb_controller [0.17s]
--- stderr: nav2_waypoint_follower     
/home/thomasluk/nav2_ws/src/navigation2/nav2_waypoint_follower/plugins/photo_at_waypoint.cpp:22:10: fatal error: nav2_util/node_utils.h: No such file or directory
   22 | #include "nav2_util/node_utils.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/photo_at_waypoint.dir/build.make:76: CMakeFiles/photo_at_waypoint.dir/plugins/photo_at_waypoint.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:260: CMakeFiles/photo_at_waypoint.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< nav2_waypoint_follower [3.17s, exited with code 2]
Aborted  <<< nav2_rotation_shim_controller [22.7s]
```

Should I change it to `hpp` this time ?

**Comment by TZECHIN6** [comment]
After successful build, I tried to run the demo in the tutorial, however an error occur:

### Reproduce step
1. cd nav2_ws
2. source install/setup.bash
3. export TURTLEBOT3_MODEL=waffle
4. export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
5. ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False

```
~/nav2_ws$ ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False
[INFO] [launch]: All log files can be found below /home/thomasluk/.ros/log/2023-03-08-15-10-05-460598-apas-thomasluk-ubuntu22-78812
[INFO] [launch]: Default logging verbosity is set to INFO
1678259406.151483 [0]       ros2: config: //CycloneDDS/Domain/Internal/MinimumSocketReceiveBufferSize: setting moved to //CycloneDDS/Domain/Internal/SocketReceiveBufferSize[@min] (file:///opt/autoware/cyclonedds_config.xml line 6)
1678259406.152205 [0]       ros2: failed to increase socket receive buffer size to at least 10485760 bytes, current is 425984 bytes
[ERROR] [1678259406.152260261] [rmw_cyclonedds_cpp]: rmw_create_node: failed to create domain, error Error

>>> [rcutils|error_handling.c:108] rcutils_set_error_state()
This error state is being overwritten:

  'error not set, at ./src/rcl/node.c:263'

with this new error message:

  'rcl node's rmw handle is invalid, at ./src/rcl/node.c:415'

rcutils_reset_error() should be called after error handling to avoid this.
<<<
[ERROR] [1678259406.152281599] [rcl]: Failed to fini publisher for node: 1
[ERROR] [launch]: Caught exception in launch (see debug for traceback): error creating node: rcl node's rmw handle is invalid, at ./src/rcl/node.c:415
```

**Comment by dujeong** [comment]
> @SteveMacenski I changed to `h` as suggested, now the error is gone, however, another similar issue pop up:
> 
> ```
> Finished <<< nav2_dwb_controller [0.17s]
> --- stderr: nav2_waypoint_follower     
> /home/thomasluk/nav2_ws/src/navigation2/nav2_waypoint_follower/plugins/photo_at_waypoint.cpp:22:10: fatal error: nav2_util/node_utils.h: No such file or directory
>    22 | #include "nav2_util/node_utils.h"
>       |          ^~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> gmake[2]: *** [CMakeFiles/photo_at_waypoint.dir/build.make:76: CMakeFiles/photo_at_waypoint.dir/plugins/photo_at_waypoint.cpp.o] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:260: CMakeFiles/photo_at_waypoint.dir/all] Error 2
> gmake[1]: *** Waiting for unfinished jobs....
> gmake: *** [Makefile:146: all] Error 2
> ---
> Failed   <<< nav2_waypoint_follower [3.17s, exited with code 2]
> Aborted  <<< nav2_rotation_shim_controller [22.7s]
> ```
> 
> Should I change it to `hpp` this time ?
> 
> **Update** Making below changes at commit [7d04c8e](https://github.com/ros-planning/navigation2/commit/7d04c8ef7e2edf6815e9cd0a77635f06c81f495f) successfully build the workspace:
> 
> 1. changing `.hpp` to `.h` at line 37 | #include "cv_bridge/cv_bridge.hpp" nav2_waypoint_follower/include/nav2_waypoint_follower/plugins/photo_at_waypoint.hpp
> 2. changing `.h` to `.hpp` at 22 | #include "nav2_util/node_utils.h" navigation2/nav2_waypoint_follower/plugins/photo_at_waypoint.cpp

after updating, build succeeded!! Thanks a lot!!! @SteveMacenski @TZECHIN6

**Comment by TZECHIN6** [comment]
@dujeong Have you successfully run the example demo after the build? I encounter an issue which the error message is a bit hard to trace what is the problem...

**Comment by SteveMacenski** [comment]
OK updates made. Ugh, it looks like a user trying to fix the service QOS issue introduced the hpp -> h in the node utils include for no reason I can discern. 

The runtime error you see is something to do with your configuration of ROS 2, not nav2. The path clearly points to some autoware config.

**Comment by dujeong** [comment]
> @dujeong Have you successfully run the example demo after the build? I encounter an issue which the error message is a bit hard to trace what is the problem...
> 
> I found someone said that `export ROS_LOCALHOST_ONLY=1` in bashrc would cause issue, I will test this in tmr and update it in here. Seem nothing done with the nav2 slack at all.

@TZECHIN6 When I launch the file by `ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False`, the error you encountered did not occur.
I didn't even do any `export ~~` what you did. I just do `export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp`.

**Comment by TZECHIN6** [comment]
@SteveMacenski yes, I have a DDS tuning config for autoware project, and I put it down on my bashrc which cause this issue. I would call now its a case-close.
