### ISSUE TITLE
Ros2-Foxy not supported nav2_smac_planner and ThetaStartPlanner

### ISSUE THREAD

**Issue by MehmetKUTAN** [ros-planning/navigation2#3473]
## Bug report

**Required Info:**

- Operating System:
  Ubuntu 20.04
- ROS2 Version:
  Foxy
- Version or commit hash:
 Ros2-Foxy-devel

I have a question? I work a project and I wanna use  for planner ->plugin: "nav2_smac_planner/SmacPlannerHybrid"
But i am getting error. This error is:  [planner_server-15] [FATAL] [1678714672.029638203] [planner_server]: Failed to create global planner. Exception: According to the loaded plugin descriptions the class smac_planner/SmacPlannerHybrid with base class type nav2_core::GlobalPlanner does not exist. Declared types are  nav2_navfn_planner/NavfnPlanner smac_planner/SmacPlanner smac_planner/SmacPlanner2D

so I just using nav2_navfn_planner/NavfnPlanner smac_planner/SmacPlanner smac_planner/SmacPlanner2D

Why ı cant use nav2_smac_planner/SmacPlannerHybrid, nav2_smac_planner/SmacPlannerLattice and Theta Star Planner.

Please help me?

**Comment by SteveMacenski** [comment]
Theta* is not available in Foxy, its only in Galactic and newer. Smac Planner was originally backported to Foxy, but before the State Lattice Planner so the naming is a little different. See the migration guides: https://navigation.ros.org/migration/index.html. Note that the Foxy version of Smac is somewhat out of date, so some bug fixes or new features have been added that are only available in more recent distributions. 

The Hybrid planner is the just `SmacPlanner` in Foxy. Ther is no Lattice or Theta*
