### ISSUE TITLE
[velocity smoother] Deceleration limit not applied when command timeout

### ISSUE THREAD

**Issue by BriceRenaudeau** [ros-planning/navigation2#3481]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble
- Version or commit hash:
  - last release
- DDS implementation:
  - cycloneDDS 

#### Steps to reproduce issue
```

```

#### Expected behavior
When the command timeout, the smoother sends a deceleration slope using the deceleration limit.

#### Actual behavior
When the command timeout, the smoother sends a 0 velocity command.

#### Additional information
Tested on real robot using this config:
```
{"smoothing_frequency": 20.0},
{"scale_velocities": False},
{"feedback": "OPEN_LOOP"},
{"max_velocity": [0.5, 0.0, 0.8]},
{"min_velocity": [-0.5, 0.0, -0.8]},
{"velocity_timeout": 0.5},
{"max_accel": [1.0, 0.0, 1.2]},
{"max_decel": [-1.0, 0.0, -1.2]}
```
![nav2_smoother_no_decel_timeout](https://user-images.githubusercontent.com/48433002/225652813-8a57ef14-fdc1-4b40-aba1-3dda0086f83d.png)

**Comment by BriceRenaudeau** [comment]
I think I see how to do it cleanly.
I will take some time to do a PR.

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/3512 Imminently to be merged.
