### ISSUE TITLE
[Collision monitor] max_points should be called min_points

### ISSUE THREAD

**Issue by tonynajjar** [ros-planning/navigation2#3499]
Just a nitpick issue. The max_points parameter would be more intuitive if called min_points

![image](https://user-images.githubusercontent.com/14879660/226908050-40c82bde-b2b8-4782-92f8-016ee0d915bd.png)

becomes: "Minimum number of data readings within a zone to trigger the action. "  

The way it's used [here](https://github.com/ros-planning/navigation2/blob/0822a14b34c412cc4f8e5f2d8486d1bb2aa28fb1/nav2_collision_monitor/src/collision_monitor_node.cpp#LL404C2-L404C2) also sounds better with min_points (check if the collision points are more that the minimum number of points required -> if yes, trigger action)

**Comment by AlexeyMerzlyakov** [comment]
Agree, `min_points` sounds more reasonable. I'll prepare the PR on the days

**Comment by SteveMacenski** [comment]
Renamed!
