### ISSUE TITLE
[Collision monitor] Slowdown field that limit speed, not reduce it

### ISSUE THREAD

**Issue by BriceRenaudeau** [ros-planning/navigation2#3514]
## Feature request
We would like a zone that clamps the command if there is an obstacle inside.
In our use case, we prefer to have a slowdown field that limits the speed to a fixed value. Now it is multiplying it with a coef.

Now, if there is an obstacle in the field and I send a small command the output will be even slower.

#### Feature description
We would like a field that limits the command to a fixed value.

That's the behavior of a real low-level safety field. 

#### Implementation considerations
What about robots with different min(-) and max(+) velocities? Use a single value with a *-1 or add a parameter for min_vel?

It can be another model `Limit model` or a parameter to change the behavior of the `slowdown model`.

**Comment by BriceRenaudeau** [comment]
Thanks, we will make it soon.

**Comment by BriceRenaudeau** [comment]
While implementing the new mode for the slowdown, I encountered an issue. It's pretty sure we will want to have no one limit for the 3 components (x, y, tw) but 3 different limits. Also `Action robot_action` doesn't have a place for a different mode of slowdown.

Hence I think it's better to add a new type (LIMIT) than to add several parameters to the slowdown type.

**Comment by SteveMacenski** [comment]
How we've done this in the speed limiting costmap filter is to use the transitional velocity absolute limit and then scale back the angular velocity proportional to it (e.g. if the max is 1m/s and you set it to 0.5m/s via absolute, we calculate the percentage reduction that represents and apply it to the angular velocity).

Would that be sufficient? If not, then having separate values is sensible.

**Comment by SteveMacenski** [comment]
PR imminently to be merged
