### ISSUE TITLE
[nav2_msgs] Nav2 master build fails after ros rolling update

### ISSUE THREAD

**Issue by ehiker** [ros-planning/navigation2#3533]
## Bug report

- Operating System:
  - Ubuntu Jammy 22.04
- ROS2 Version:
  - ROS 2 Rolling
- Version or commit hash:
  - nav2 from source, master, SHA ff4fd54076c64f6782b821c60319686413f2551b
  - ros2 rolling apt update & upgrade from 2023-04-17
- DDS implementation:
  - fastrtps and cyclondds

Package nav2_msgs building fails due to strict warning policy in navigation2/nav2_common/cmake/nav2_package.cmake and long-term issue with a redundant declaration in rosidl generation. I reported the issue in more detail in rosidl_typesupport_fastrtps issue, please see https://github.com/ros2/rosidl_typesupport_fastrtps/issues/28

**Comment by SteveMacenski** [comment]
What's the error?

**Comment by SteveMacenski** [comment]
Huh, neat. I see that as well even after a clean rebuild which usually resolves those kinds of issues after a breaking update.

**Comment by ehiker** [comment]
Hi, I can confirm the current master [1cdc277b84115ee97c94b60b2a14630d097c6975](https://github.com/ros-planning/navigation2/commit/1cdc277b84115ee97c94b60b2a14630d097c6975) fixed the issue. I can build nav2_msgs package locally against current ros rolling from APT packages without any workaround.

Thank you.

**Comment by SteveMacenski** [comment]
Leaving open since that's a temporary fix, we need to fix rosidl

**Comment by ehiker** [comment]
Ok. I am sorry.

**Comment by SteveMacenski** [comment]
No need to be sorry :smile:

**Comment by SteveMacenski** [comment]
:heart: to @emersonknapp for debugging https://github.com/ros2/rosidl/issues/743#issuecomment-1577716426
