### ISSUE TITLE
how can i decrease calculate time on Embedded Chips when use theta star planner

### ISSUE THREAD

**Issue by dahuacai** [ros-planning/navigation2#3535]
**Issuse:**
I use the theta star algorithm on rockchip 3308 embedded chip(the IoT processor is based on ARM quad-core 64-bit Cortex-A35 kernel with 4cpu 255M RAM 512M ROM).when i plan a path with map w,h=(192,254) res=0.05, it wasters near 90ms to get a 15m path.when i use navfn_planner, it only waster 9ms. the 90ms is not acceptable.how can i optimize the code to decrease calculate time.I guess the time was wasted on the "loscheck" function.Could you give me some suggestions for revision
**(we want the output path is  as far away obstacle as possible  and as smooth as possible)**

**plan map:**
![theta](https://user-images.githubusercontent.com/7418674/233032192-78d1cf94-a772-4463-8e48-faa122db0bf7.png)

**CPU INFO:**
![cpu](https://user-images.githubusercontent.com/7418674/233034865-0a854cf5-ce1e-4dae-858e-73dc8bed3353.png)

**Comment by dahuacai** [comment]
@SteveMacenski

**Comment by dahuacai** [comment]
that's ok. I will further test and give some feedback

**Comment by SteveMacenski** [comment]
@dahuacai any feedback :smile:

**Comment by SteveMacenski** [comment]
Closing - happy to reopen or have a PR if you find a way to speed things up! But for now, it meets our requirements on performance. Improvements always welcome, but if there's not a tangible suggestion or actionable change, I don't think we need to have a performance ticket open for every algorithm 'to make it faster'. Obviously, we'd be happy if any algorithm was made faster :smile: 

If you find a potential improvement, I'd love to know!
