### ISSUE TITLE
how can i let astar use 8 neighbourhood search?

### ISSUE THREAD

**Issue by dahuacai** [ros-planning/navigation2#3538]
**Issue:**
some times if i use navfn_planner to plan a path ,it will plan failed when only Diagonal grid is free and other neighbourhoods is obs.
we known that navfn_planner  is 4 neighbourhood search, so how can i mod the code to enable 8 neighbourhood search.

such as following example. we can not plan a path following the arrow :

![企业微信截图_16823446833031](https://user-images.githubusercontent.com/7418674/234019579-2225b21a-0462-44bf-a335-cfecacea5bfa.png)

**fullmap:**

![costmap_explore(1)](https://user-images.githubusercontent.com/7418674/234019337-d13d0cc6-2c8b-4bfd-8029-2a3c7049ccef.png)

**Comment by dahuacai** [comment]
the map is just inflated map.but navfn_planer can not plan a path following the red arrow.I will also seek ROS Answer.Our robots often encounter narrow situations,they will get stuck if they don't plan out.

**Comment by SteveMacenski** [comment]
It looks like you should definitely consider a higher-resolution costmap if you really have things that close together with that narrow of a passage way. That seems to be unacceptably coarse for that situation
