### ISSUE TITLE
An error was reported while running the foxy-devel branch code

### ISSUE THREAD

**Issue by SenHe524** [ros-planning/navigation2#3540]
## Bug report
I tried navigation2 by doing the following:
   1.mkdir -p nav2_foxy/src
   2.cd nav2_foxy/src
   3.git clone https://github.com/ros-planning/navigation2.git -b foxy-devel
   4.cd ..
   5.rosdep install --from-paths src --ignore-src -r -y
   6.colcon build --packages-up-to navigation2 --symlink-install --continue-on-error
   7.source install/setup.bash
   8.ros2 launch agv_nav2 agv_nav2.launch.py
      The agv_nav2.launch.py file is as follows:
![image](https://user-images.githubusercontent.com/99389099/234208211-939b65cb-68ea-4c34-ad13-1b4f8156855b.png)
   9.The end result is as follows:
[INFO] [launch]: All log files can be found below /home/sen/.ros/log/2023-04-25-15-28-49-234074-ubuntu-196101
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [196106]
[INFO] [map_server-2]: process started with pid [196108]
[INFO] [amcl-3]: process started with pid [196110]
[INFO] [lifecycle_manager-4]: process started with pid [196112]
[INFO] [controller_server-5]: process started with pid [196114]
[INFO] [planner_server-6]: process started with pid [196116]
[INFO] [recoveries_server-7]: process started with pid [196118]
[INFO] [bt_navigator-8]: process started with pid [196143]
[INFO] [waypoint_follower-9]: process started with pid [196162]
[INFO] [lifecycle_manager-10]: process started with pid [196166]
[map_server-2] [INFO] [1682407729.759946865] [map_server]: 
[map_server-2] 	map_server lifecycle node launched. 
[map_server-2] 	Waiting on external lifecycle transitions to activate
[map_server-2] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-2] [INFO] [1682407729.760039840] [map_server]: Creating
[amcl-3] [INFO] [1682407729.733463562] [amcl]: 
[amcl-3] 	amcl lifecycle node launched. 
[amcl-3] 	Waiting on external lifecycle transitions to activate
[amcl-3] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[amcl-3] [INFO] [1682407729.733603926] [amcl]: Creating
[controller_server-5] [INFO] [1682407729.740267506] [controller_server]: 
[controller_server-5] 	controller_server lifecycle node launched. 
[controller_server-5] 	Waiting on external lifecycle transitions to activate
[controller_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1682407729.747837880] [controller_server]: Creating controller server
[controller_server-5] [INFO] [1682407729.766808774] [local_costmap.local_costmap]: 
[controller_server-5] 	local_costmap lifecycle node launched. 
[controller_server-5] 	Waiting on external lifecycle transitions to activate
[controller_server-5] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[controller_server-5] [INFO] [1682407729.767922347] [local_costmap.local_costmap]: Creating Costmap
[lifecycle_manager-4] [INFO] [1682407729.795385991] [lifecycle_manager_localization]: Creating
[waypoint_follower-9] [INFO] [1682407729.806895284] [waypoint_follower]: 
[waypoint_follower-9] 	waypoint_follower lifecycle node launched. 
[waypoint_follower-9] 	Waiting on external lifecycle transitions to activate
[waypoint_follower-9] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[waypoint_follower-9] [INFO] [1682407729.807046370] [waypoint_follower]: Creating
[bt_navigator-8] [INFO] [1682407729.809162048] [bt_navigator]: 
[bt_navigator-8] 	bt_navigator lifecycle node launched. 
[bt_navigator-8] 	Waiting on external lifecycle transitions to activate
[bt_navigator-8] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[bt_navigator-8] [INFO] [1682407729.809304746] [bt_navigator]: Creating
[lifecycle_manager-10] [INFO] [1682407729.815506392] [lifecycle_manager_navigation]: Creating
[planner_server-6] [INFO] [1682407729.820709179] [planner_server]: 
[planner_server-6] 	planner_server lifecycle node launched. 
[planner_server-6] 	Waiting on external lifecycle transitions to activate
[planner_server-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[lifecycle_manager-4] [INFO] [1682407729.822313892] [lifecycle_manager_localization]: Creating and initializing lifecycle service clients
[planner_server-6] [INFO] [1682407729.824257214] [planner_server]: Creating
[lifecycle_manager-10] [INFO] [1682407729.825371948] [lifecycle_manager_navigation]: Creating and initializing lifecycle service clients
[lifecycle_manager-4] [INFO] [1682407729.830127739] [lifecycle_manager_localization]: Starting managed nodes bringup...
[lifecycle_manager-4] [INFO] [1682407729.830268625] [lifecycle_manager_localization]: Configuring map_server
[lifecycle_manager-10] [INFO] [1682407729.847300428] [lifecycle_manager_navigation]: Starting managed nodes bringup...
[lifecycle_manager-10] [INFO] [1682407729.847361427] [lifecycle_manager_navigation]: Configuring controller_server
[recoveries_server-7] [INFO] [1682407729.853645877] [recoveries_server]: 
[recoveries_server-7] 	recoveries_server lifecycle node launched. 
[recoveries_server-7] 	Waiting on external lifecycle transitions to activate
[recoveries_server-7] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[map_server-2] [INFO] [1682407729.860088342] [map_server]: Configuring
[map_server-2] [INFO] [map_io]: Loading yaml file: /home/sen/Desktop/AGV_1/src/agv_nav2/maps/map1.yaml
[map_server-2] [DEBUG] [map_io]: resolution: 0.05
[map_server-2] [DEBUG] [map_io]: origin[0]: -2.51243
[map_server-2] [DEBUG] [map_io]: origin[1]: -3.66716
[map_server-2] [DEBUG] [map_io]: origin[2]: 0
[map_server-2] [DEBUG] [map_io]: free_thresh: 0.196
[map_server-2] [DEBUG] [map_io]: occupied_thresh: 0.65
[map_server-2] [DEBUG] [map_io]: mode: trinary
[map_server-2] [DEBUG] [map_io]: negate: 0
[planner_server-6] [INFO] [1682407729.870138224] [global_costmap.global_costmap]: 
[planner_server-6] 	global_costmap lifecycle node launched. 
[planner_server-6] 	Waiting on external lifecycle transitions to activate
[planner_server-6] 	See https://design.ros2.org/articles/node_lifecycle.html for more information.
[planner_server-6] [INFO] [1682407729.872047487] [global_costmap.global_costmap]: Creating Costmap
[map_server-2] [INFO] [map_io]: Loading image_file: /home/sen/Desktop/AGV_1/src/agv_nav2/maps/map1.pgm
[map_server-2] [DEBUG] [map_io]: Read map /home/sen/Desktop/AGV_1/src/agv_nav2/maps/map1.pgm: 192 X 329 map @ 0.05 m/cell
[lifecycle_manager-4] [INFO] [1682407729.888064258] [lifecycle_manager_localization]: Configuring amcl
[amcl-3] [INFO] [1682407729.888525840] [amcl]: Configuring
[amcl-3] [INFO] [1682407729.888603260] [amcl]: initTransforms
[amcl-3] [INFO] [1682407729.894223117] [amcl]: initPubSub
[amcl-3] [INFO] [1682407729.902743388] [amcl]: Subscribed to map topic.
[controller_server-5] [INFO] [1682407729.917554930] [controller_server]: Configuring controller interface
[controller_server-5] [INFO] [1682407729.917696240] [controller_server]: Controller frequency set to 20.0000Hz
[controller_server-5] [INFO] [1682407729.917722114] [local_costmap.local_costmap]: Configuring
[controller_server-5] [INFO] [1682407729.922121591] [local_costmap.local_costmap]: Using plugin "voxel_layer"
[controller_server-5] [INFO] [1682407729.925160208] [local_costmap.local_costmap]: Subscribed to Topics: scan
[lifecycle_manager-4] [INFO] [1682407729.927228365] [lifecycle_manager_localization]: Activating map_server
[map_server-2] [INFO] [1682407729.928067856] [map_server]: Activating
[lifecycle_manager-4] [INFO] [1682407729.930512445] [lifecycle_manager_localization]: Activating amcl
[amcl-3] [INFO] [1682407729.931064779] [amcl]: Received a 192 X 329 map @ 0.050 m/pix
[controller_server-5] [INFO] [1682407729.933398890] [local_costmap.local_costmap]: Initialized plugin "voxel_layer"
[controller_server-5] [INFO] [1682407729.933685246] [local_costmap.local_costmap]: Using plugin "inflation_layer"
[controller_server-5] [INFO] [1682407729.934084616] [local_costmap.local_costmap]: Initialized plugin "inflation_layer"
[amcl-3] [INFO] [1682407729.941234792] [amcl]: Activating
[amcl-3] [WARN] [1682407729.941323253] [amcl]: Publishing the particle cloud as geometry_msgs/PoseArray msg is deprecated, will be published as nav2_msgs/ParticleCloud in the future
[lifecycle_manager-4] [INFO] [1682407729.942660970] [lifecycle_manager_localization]: Managed nodes are active
[controller_server-5] [INFO] [1682407729.943713314] [controller_server]: Created progress_checker : progress_checker of type nav2_controller::SimpleProgressChecker
[controller_server-5] [INFO] [1682407729.944335067] [controller_server]: Created goal_checker : goal_checker of type nav2_controller::SimpleGoalChecker
[controller_server-5] [INFO] [1682407729.949310051] [controller_server]: Created controller : FollowPath of type dwb_core::DWBLocalPlanner
[controller_server-5] [INFO] [1682407729.949460082] [controller_server]: Setting transform_tolerance to 0.200000
[controller_server-5] [INFO] [1682407729.971353885] [controller_server]: Using critic "RotateToGoal" (dwb_critics::RotateToGoalCritic)
[controller_server-5] [INFO] [1682407729.973272289] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.974470703] [controller_server]: Using critic "Oscillation" (dwb_critics::OscillationCritic)
[controller_server-5] [INFO] [1682407729.976457672] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.977003619] [controller_server]: Using critic "BaseObstacle" (dwb_critics::BaseObstacleCritic)
[controller_server-5] [INFO] [1682407729.977853267] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.978528450] [controller_server]: Using critic "GoalAlign" (dwb_critics::GoalAlignCritic)
[controller_server-5] [INFO] [1682407729.980118427] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.980804832] [controller_server]: Using critic "PathAlign" (dwb_critics::PathAlignCritic)
[controller_server-5] [INFO] [1682407729.981931858] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.982481755] [controller_server]: Using critic "PathDist" (dwb_critics::PathDistCritic)
[controller_server-5] [INFO] [1682407729.983531545] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.984124661] [controller_server]: Using critic "GoalDist" (dwb_critics::GoalDistCritic)
[controller_server-5] [INFO] [1682407729.985084536] [controller_server]: Critic plugin initialized
[controller_server-5] [INFO] [1682407729.985122659] [controller_server]: Controller Server has FollowPath  controllers available.
[lifecycle_manager-10] [INFO] [1682407729.998746404] [lifecycle_manager_navigation]: Configuring planner_server
[planner_server-6] [INFO] [1682407729.999202652] [planner_server]: Configuring
[planner_server-6] [INFO] [1682407729.999236478] [global_costmap.global_costmap]: Configuring
[planner_server-6] [INFO] [1682407730.004935981] [global_costmap.global_costmap]: Using plugin "static_layer"
[planner_server-6] [INFO] [1682407730.007835704] [global_costmap.global_costmap]: Subscribing to the map topic (/map) with transient local durability
[planner_server-6] [INFO] [1682407730.009265140] [global_costmap.global_costmap]: Initialized plugin "static_layer"
[planner_server-6] [INFO] [1682407730.009290626] [global_costmap.global_costmap]: Using plugin "obstacle_layer"
[planner_server-6] [INFO] [1682407730.009374102] [global_costmap.global_costmap]: Subscribed to Topics: scan
[planner_server-6] [INFO] [1682407730.011650028] [global_costmap.global_costmap]: Initialized plugin "obstacle_layer"
[planner_server-6] [INFO] [1682407730.011673096] [global_costmap.global_costmap]: Using plugin "inflation_layer"
[planner_server-6] [INFO] [1682407730.011882387] [global_costmap.global_costmap]: Initialized plugin "inflation_layer"
[planner_server-6] [INFO] [1682407730.020586026] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 192 X 329 at 0.050000 m/pix
[planner_server-6] [INFO] [1682407730.020768588] [planner_server]: Created global planner plugin GridBased of type nav2_navfn_planner/NavfnPlanner
[planner_server-6] [INFO] [1682407730.020795507] [planner_server]: Configuring plugin GridBased of type NavfnPlanner
[planner_server-6] [INFO] [1682407730.032745443] [planner_server]: Planner Server has GridBased  planners available.
[lifecycle_manager-10] [INFO] [1682407730.038980196] [lifecycle_manager_navigation]: Configuring recoveries_server
[recoveries_server-7] [INFO] [1682407730.039372851] [recoveries_server]: Configuring
[recoveries_server-7] [INFO] [1682407730.046840169] [recoveries_server]: Creating recovery plugin spin of type nav2_recoveries/Spin
[recoveries_server-7] [INFO] [1682407730.049059438] [recoveries_server]: Configuring spin
[recoveries_server-7] [INFO] [1682407730.061306460] [recoveries_server]: Creating recovery plugin backup of type nav2_recoveries/BackUp
[recoveries_server-7] [INFO] [1682407730.063842783] [recoveries_server]: Configuring backup
[recoveries_server-7] [INFO] [1682407730.079228714] [recoveries_server]: Creating recovery plugin wait of type nav2_recoveries/Wait
[recoveries_server-7] [INFO] [1682407730.081739981] [recoveries_server]: Configuring wait
[lifecycle_manager-10] [INFO] [1682407730.095028324] [lifecycle_manager_navigation]: Configuring bt_navigator
[bt_navigator-8] [INFO] [1682407730.095570098] [bt_navigator]: Configuring
[bt_navigator-8] [ERROR] [1682407730.131709560] []: Caught exception in callback for transition 10
[bt_navigator-8] [ERROR] [1682407730.131752370] []: Original error: Could not load library: libnav2_compute_path_through_poses_action_bt_node.so: cannot open shared object file: No such file or directory
[bt_navigator-8] [WARN] [1682407730.131778670] []: Error occurred while doing error handling.
[bt_navigator-8] [FATAL] [1682407730.131789775] [bt_navigator]: Lifecycle node bt_navigator does not have error state implemented
[lifecycle_manager-10] [ERROR] [1682407730.133851729] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator
[lifecycle_manager-10] [ERROR] [1682407730.133899427] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
[rviz2-1] [INFO] [1682407731.033091158] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1682407731.034057899] [rviz2]: OpenGl version: 4.1 (GLSL 4.1)
[rviz2-1] [INFO] [1682407731.080847533] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [WARN] [1682407731.344320297] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1682407731.367532531] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [WARN] [1682407731.392433696] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rviz2-1] [INFO] [1682407731.438793880] [rviz2]: Waiting for the lifecycle_manager_navigation/is_active service...
[rviz2-1] [INFO] [1682407731.439020252] [rviz2]: Sending lifecycle_manager_navigation/is_active request
[rviz2-1] [INFO] [1682407731.439684248] [rviz2]: Waiting for the lifecycle_manager_localization/is_active service...
[rviz2-1] [INFO] [1682407731.439767533] [rviz2]: Sending lifecycle_manager_localization/is_active request
[rviz2-1] [INFO] [1682407731.440999009] [rviz2]: Trying to create a map of size 192 x 329 using 1 swatches
[rviz2-1] [ERROR] [1682407731.445770051] [rviz2]: Vertex Program:rviz/glsl120/indexed_8bit_image.vert Fragment Program:rviz/glsl120/indexed_8bit_image.frag GLSL link result : 
[rviz2-1] active samplers with a different type refer to the same texture image unit

   10.Among the notable ones:
![image](https://user-images.githubusercontent.com/99389099/234208609-74ec20ca-bc79-4ad7-a3e3-a30514fd627d.png)

   11.I wonder if this is due to a bug in the source code of the foxy-devel branch that prevents me from running navigation2 correctly

**Required Info:**

- Operating System:
   Ubuntu20.04
- ROS2 Version:
  Foxy binaries
- Version or commit hash:
 foxy-devel

**Comment by SteveMacenski** [comment]
>  [bt_navigator-8] [ERROR] [1682407730.131752370] []: Original error: Could not load library: libnav2_compute_path_through_poses_action_bt_node.so: cannot open shared object file: No such file or directory

This is pretty clear, you have the `nav2_compute_path_through_poses_action_bt_node` in your configuration file. Since I can't see your actual yaml file since that's not a public page, I can't point specifically at it. You probably took the yaml file from a more recent branch as your base for use locally when you needed to have taken the one from `foxy-devel`'s branch. You can note in the [foxy branch's file](https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_bringup/bringup/params/nav2_params.yaml#L60) there is no compute path through poses BT node in that parameterization, nor set [as a default](https://github.com/ros-planning/navigation2/blob/foxy-devel/nav2_bt_navigator/src/bt_navigator.cpp#L40) in Foxy's params.   

This seems like a clearcut case of user error, most likely :smile:

**Comment by SenHe524** [comment]
Thank you very much for your reply. @SteveMacenski

**Comment by ibrahimqazi** [comment]
Hello all, I have the same issue but it reports another node `libnav2_compute_path_through_poses_action_bt_node.so`, it's strange that I installed the Nav2 package from binary not from source which is different than mate @SenHe524 but still this library does not exist. I used the following command to install it.
`sudo apt install ros-foxy-navigation2 ros-foxy-nav2-bringup ros-foxy-turtlebot3*`

@SteveMacenski, do you have any comments on this, please ? Since I am following a book, so at the moment its not possible for me to switch to another distro, it will be time consuming.
