### ISSUE TITLE
Simple Commander API - BasicNavigator - GetPath | planner_id and use_start get overriden

### ISSUE THREAD

**Issue by nakai-omer** [ros-planning/navigation2#3558]
**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Humble     
- Version or commit hash:
  - ros-humble-navigation2	1.1.6-1jammy.20230327.054544
- DDS implementation:
  - cyclone-dds

#### Steps to reproduce issue
https://github.com/ros-planning/navigation2/blob/9b56556dfd9c50f4046d253317cd0949a4f34583/nav2_simple_commander/nav2_simple_commander/robot_navigator.py#L353

You can see in above line that parameters are being overridden by default values, causing planner_id and use_start to get the default values.

#### Expected behavior
`getPath` should use the parameters

#### Actual behavior
`getPath` overrides them with default values

**Comment by nakai-omer** [comment]
Added a PR to fix this and a couple of more places with the same bug

**Comment by SteveMacenski** [comment]
Will merge shortly!

**Comment by nakai-omer** [comment]
@SteveMacenski Also added a PR for humble branch #3562
