### ISSUE TITLE
Final orientation cannot be reached for Ackermann vehicles

### ISSUE THREAD

**Issue by HarunTeper** [ros-planning/navigation2#3573]
Hello,

I am currently configuring the Nav2 stack for an ackermann vehicle and I am having issues with the planner and controller for the final orientation. Specifically, the planner always recreates a new circular path around the goal pose, while the controller is not able to reach the final goal pose orientation.

My nav2 configuration can be found here: https://github.com/HarunTeper/AuNa/blob/main/src/auna_nav2/config/nav2_params/nav2_params.yaml
I'm using Ubuntu 20.04 and ROS2-Galactic.

I am using the nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitControllerand the nav2_smac_planner/SmacPlannerHybrid for the navigation.

What should I change to prevent this behavior?

**Comment by Rodrag** [comment]
Hi there, did you find a fix for this, working on the same issue atm

**Comment by HarunTeper** [comment]
@Rodrag I changed the global planner to SmacPlannerHybrid, to make the car plan according to its kinematic constraints. You may also change the local planner to RegulatedPurePursuit, and add a converter node to change the output from unicycle to bicycle or Ackermann model as well.
