### ISSUE TITLE
Add component for costmap_filter_info_server 

### ISSUE THREAD

**Issue by FiIipe** [ros-planning/navigation2#3589]
#### Feature description
Currently, there is no possibility to use the costmap_filter_info_server as a component. 

Upon reviewing the recent [commit](https://github.com/ros-planning/navigation2/commit/420a6ffd3c6b154c4aec2c5f2a24e4af4bd971a9), I noticed that the map_saver and map_server components were added, but the costmap_filter_info_server was not included as a component.

Therefore, I would like to request the addition of the costmap_filter_info_server as a component in the Navigation2 package, if possible. 

#### Implementation considerations
No special considerations for the implementation. 

Thank you for considering my feature request. I appreciate your dedication and efforts in continually enhancing the Nav2 package.

**Comment by SteveMacenski** [comment]
That seems reasonable enough to me - I'm surprised we overlooked that. @AlexeyMerzlyakov I think that's in your maintainer bin - can you make it a component + update tutorial to use in that way?

**Comment by FiIipe** [comment]
Sure, I would love to contribute to the Nav2 project! 
I will start by reading the development guidelines for the Nav2 project and then I will implement the costmap_filter_info_server as a component. 

Thank you!

**Comment by SteveMacenski** [comment]
I think broadly you should only need to register it as a component + cmake to support and it should be good to go with documentation updates. @AlexeyMerzlyakov, anything else you think @FiIipe would need to do?

**Comment by FiIipe** [comment]
@SteveMacenski @AlexeyMerzlyakov I created two PR. One is already mentioned in this ticket and the other is for the navigation_tutorials package. The PR can be found here: https://github.com/ros-planning/navigation2_tutorials/pull/67

If my changes are approved, then it would be important to update also the documentation here: https://navigation.ros.org/tutorials/docs/navigation2_with_keepout_filter.html#configure-costmap-filter-info-publisher-server

Thank you :robot:

**Comment by alejama** [comment]
Hi! 
I'm trying to use nav2_costmap_filters_demo, but when I'm running shows me next problem:
launch.substitutions.substitution_failure.SubstitutionFailure: executable 'costmap_filter_info_server' not found on the libexec directory '/opt/ros/foxy/lib/nav2_map_server'

**Comment by SteveMacenski** [comment]
Foxy Is EOL and is no longer supported. It does not contain the costmap filter features.

**Comment by FiIipe** [comment]
@SteveMacenski @AlexeyMerzlyakov I will look into it now, hopefully it will be merged soon :) 

Thank you

**Comment by SteveMacenski** [comment]
@FiIipe any update? I'd like this squared away ASAP so we can get this off the issue tracker

**Comment by FiIipe** [comment]
@SteveMacenski I'm waiting Alexey's review, he was on vacation. I'm not sure he is back

**Comment by SteveMacenski** [comment]
Got it, thanks!

**Comment by AlexeyMerzlyakov** [comment]
Apologies for late review: hot season after vacation today. Tutorial update is almost done. Please submit a new PR to documentation updates describing the switchin of CostmapFilterInfoServer to using Composable mode.

**Comment by SteveMacenski** [comment]
@FiIipe @AlexeyMerzlyakov can we try to get this done shortly? The actual code change is done and its a bad spot to be in without the docs
