### ISSUE TITLE
Unable to use Nav2 for multi-robot system (multi_tb3_simulation.launch.py)

### ISSUE THREAD

**Issue by AryanArora12** [ros-planning/navigation2#3592]
## Bug report

**Required Info:**

- Operating System:
  -  Ubuntu 20.04.06 LTS
- ROS2 Version:
  -  Foxy

#### Steps to reproduce issue
 I am trying to create an environment with two robots and I want to navigate them via NAV2. I already have a custom world and a custom map built for the robots. I tried using the multi_tb3_simulation.launch.py for my purposes, by changing the initial spawning positions of the robot as well as adding my own custom gazebo world and map. 
The robots spawn at the correct location in gazebo, however, in RVIZ, the robot is not detecting any obstacles. 

#### Expected behavior

Expect to see obstacles detection in RVIZ

#### Actual behavior
Gazebo works well, with robots being spawned at the correct location, while no map is detected in RVIZ.
<img width="803" alt="image" src="https://github.com/ros-planning/navigation2/assets/100324494/6b28585f-3ea1-405e-80a1-5ca8fa8dcbcc">

<img width="824" alt="image" src="https://github.com/ros-planning/navigation2/assets/100324494/3bfc8acd-e060-4918-b6cc-1fd7bb8c7aa8">

**Comment by SteveMacenski** [comment]
Foxy is EOL and will not receive support.
