### ISSUE TITLE
High level block diagram of intended workflow

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#36]
Coming from the standard nav stack and having built a few alternatives over time, I dont look at this project and have a good understand what's happening or how the elements interact.

Is there a plan to make a block diagram much like the move_base one to clear up your architectural intentions? It's challenging to get involved or track without it.

**Comment by SteveMacenski** [comment]
I see this guy (https://github.com/ros-planning/navigation2/blob/master/doc/design/Navigation_2_Overview.pdf) but that's not really a full block diagram of what you're trying to accomplish here with navigation2 restructuring instead of starting with navigation stack and building on top of it

**Comment by mkhansen-intel** [comment]
@SteveMacenski - Steve I've added this to our TO DO. We'll create a better diagram or two and put it in a more obvious place, like the top-level README. Thanks for your feedback.

**Comment by SteveMacenski** [comment]
More generally speaking, I'd like to be involved in this effort as well. Having a good briefing about the thought process and what's being rebuilt vs. ported over would be good!
