### ISSUE TITLE
TB3 Simulation launch spawn_entity crash

### ISSUE THREAD

**Issue by xkaraman** [ros-planning/navigation2#3601]
## Bug report

**Required Info:**

- Operating System:
  - Docker based on Jammy 22.04
- ROS2 Version:
  - Docker based on Jammy 22.04 and ros:humble image 
- Version or commit hash:
  - `ros-humble-navigation2  1.1.6-1jammy.20230426.153445`
- DDS implementation:
  -  Default (Fast-RTPS)

I am trying to launch the `tb3_simulation_launch.py` but gazebo fails to load both the world and the waffle but opens a new empty world containing nothing (Rviz and map loads). Launching the relative launch file from `turtlebot3_gazebo` `ros2 launch turtlebot3_gazebo turtlebot3_word.launch.py` package though seems to load everything successfully.

#### Steps to reproduce issue

```
source /opt/ros/hubmle/setup.bash
# Install various missing packages in order to properly launch packages
sudo apt update # (W: http://packages.ros.org/ros2/ubuntu/dists/jammy/InRelease: Key is stored in legacy trusted.gpg keyring 
                           # (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.)
sudo apt install ros-humble-nav2-bringup
# (should't the following be installed with nav2-bringup? since it is required for the tb_launch_file?)
sudo apt install ros-humble-gazebo-ros 
sudo apt install ros-humble-rviz2
# Also installed everything turtlebot3 related
sudo apt install ros-humble-turtlebot3*

export TURTLEBOT3_MODEL=waffle
ros2 launch nav2_bringup tb3_simulation_launch.py
```

#### Expected behavior
I am expecting the gazebo server to load successfully and spawning the robot and the world. If i also add `headless:=False`, so gazebo client (GUI) load, i expect the `turtlebot3_world.world` to appear.

#### Actual behavior
Gazebo server fails to load the world and robot successfully and gazebo client show nothing but an empty world.
The error occuring is the following. I believe the `local_costmap` info are due to not a successful bringup, waiting on the frames to be populated.
```
[spawn_entity.py-3] [ERROR] [1686047965.672993729] [spawn_entity]: Service %s/spawn_entity unavailable. Was Gazebo started with GazeboRosFactory?
[spawn_entity.py-3] [ERROR] [1686047965.675367425] [spawn_entity]: Spawn service failed. Exiting.
[component_container_isolated-6] [INFO] [1686047965.810357036] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[ERROR] [spawn_entity.py-3]: process has died [pid 5367, exit code 1, cmd '/opt/ros/humble/lib/gazebo_ros/spawn_entity.py -entity turtlebot3_waffle -file /opt/ros/humble/share/nav2_bringup/worlds/waffle.model -robot_namespace -x -2.00 -y -0.50 -z 0.01 -R 0.00 -P 0.00 -Y 0.00 --ros-args'].
```
#### Additional information
As i said earlier launching `ros2 launch turtlebot3_gazebo turtlebot3_word.launch.py` will correctly start both `gzserver` and `gzclient`. (Note on the first run, probably due to loading the world, spawning fails exactly as on the `nav2_bringup`, yet the world loads succesful. On the second run, where world is now download and ready to use, spawing also completes.)

Having said that, i copied the nav2 launch file into a new package and tried some things. Changing `start_gazebo_server_cmd` from
```
    ...
    declare_world_cmd = DeclareLaunchArgument(
        'world',
        # TODO(orduno) Switch back once ROS argument passing has been fixed upstream
        #              https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/91
        # default_value=os.path.join(get_package_share_directory('turtlebot3_gazebo'),'worlds','turtlebot3_world.world'),
        default_value=os.path.join(bringup_dir, 'worlds', 'world_only.model'),
        description='Full path to world model file to load')
    ...
    
   # Specify the actions
    start_gazebo_server_cmd = ExecuteProcess(
        condition=IfCondition(use_simulator),
        cmd=['gzserver', '-s', 'libgazebo_ros_init.so',
             '-s', 'libgazebo_ros_factory.so', world],
        cwd=[launch_dir], output='screen')

    start_gazebo_client_cmd = ExecuteProcess(
        condition=IfCondition(PythonExpression(
            [use_simulator, ' and not ', headless])),
        cmd=['gzclient'],
        cwd=[launch_dir], output='screen')

```
to and use the launch from `gazebo_ros` package
```
    pkg_gazebo_ros = get_package_share_directory('gazebo_ros')

    declare_world_cmd = DeclareLaunchArgument(
        'world',
        # TODO(orduno) Switch back once ROS argument passing has been fixed upstream
        #              https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/91
        default_value=os.path.join(get_package_share_directory('turtlebot3_gazebo'),'worlds','turtlebot3_world.world'),
        # default_value=os.path.join(bringup_dir, 'worlds', 'world_only.model'),
        description='Full path to world model file to load')

    start_gazebo_server_cmd = IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(pkg_gazebo_ros, 'launch', 'gzserver.launch.py')
            ),
            launch_arguments={'world': world}.items()
        )

    start_gazebo_client_cmd= IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(pkg_gazebo_ros, 'launch', 'gzclient.launch.py')
            )
        )
```

I haven't investigated how this affect other worlds or tb3 models but now after cliclick 2D Pose Estimation in Rviz, i can use nav2 and send goals.

**Comment by SteveMacenski** [comment]
Its almost certainly to do with lack of exporting of the gazebo model paths properly as the documentation outlines: https://navigation.ros.org/getting_started/index.html

**Comment by xkaraman** [comment]
Indeed that was it, i don't see how i missed that part. 
After I was checking this [tutorial](https://navigation.ros.org/tutorials/docs/navigation2_dynamic_point_following.html). Is `default_bt_xml_filename:=/path/to/bt.xml` argument still valid? I can't seem to find it in the launch file.

**Comment by zhangpeng66** [comment]
how to solve it?who know?
