### ISSUE TITLE
ObstacleLayer above StaticLayer always overrides unknown parts

### ISSUE THREAD

**Issue by RBT22** [ros-planning/navigation2#3603]
#### Feature description
If I'm not mistaken currently there is no easy way to prevent the planner generating a path through areas that are not on a static map if there is an obstacle layer above it. When the obstacle layer updates the costmap's values in `ObstacleLayer::updateCosts` with both combination_method parameter options the unknown parts are overriden with new values.
```
  switch (combination_method_) {
    case 0:  // Overwrite
      updateWithOverwrite(master_grid, min_i, min_j, max_i, max_j);
      break;
    case 1:  // Maximum
      updateWithMax(master_grid, min_i, min_j, max_i, max_j);
      break;
    default:  // Nothing
      break;
  }
```
"If the master value is NO_INFORMATION, it is overwritten." says the docs about CostmapLayer::updateWithMax.

#### Implementation considerations
Our team wrote an ObstacleLayer::updateWithMaxWithoutUnknownOverride method to address this issue. Is this something that could be supported, or there is a better way to achive this behavior?

**Comment by SteveMacenski** [comment]
> If I'm not mistaken currently there is no easy way to prevent the planner generating a path through areas that are not on a static map if there is an obstacle layer above it

Why would you require an obstacle layer before a static layer? I'm trying to understand the situation where that's a semantically different situation that requires you to do that (e.g. versus a misconfiguration).

**Comment by RBT22** [comment]
Thank you for the quick response! Sorry if it was a bit confusing, exactly the last sentence you wrote. 

The supported way of using our robot is to create a map first about the environment you want to use it in, and then you can start the navigation. In this case, it is better to avoid situations where the robot is going through places that are not on the map, even if the current sensor measurements says they are clear.
