### ISSUE TITLE
Local costmap not update, and the timestamp of the received footprint is the previous time point.malloc(): unsorted double linked list corrupted

### ISSUE THREAD

**Issue by lizhao112396** [ros-planning/navigation2#3608]
## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by SteveMacenski** [comment]
@lizhao112396 please fill in the issue template with all of the requested information, its important if you want assistance.

**Comment by lizhao112396** [comment]
Ok, thank you for your reply.
Add an planner_costmap  in the controller_ server , used for local path planning, and planner_costmap is also a separate thread. Occasional planner_ Costmap or local_ Costmap is not updated and footprint remains unchanged.
The location of the problem is as follows:
void
Costmap2DROS::updateMap()
{
  RCLCPP_DEBUG(get_logger(), "Updating map...");

  if (!stop_updates_) {
    // get global pose
    geometry_msgs::msg::PoseStamped pose;
    if (getRobotPose(pose)) {
      const double & x = pose.pose.position.x;
      const double & y = pose.pose.position.y;
      const double yaw = tf2::getYaw(pose.pose.orientation);
      layered_costmap_->updateMap(x, y, yaw);

      auto footprint = std::make_unique<geometry_msgs::msg::PolygonStamped>();
      footprint->header = pose.header;
      transformFootprint(x, y, yaw, padded_footprint_, *footprint);

      RCLCPP_DEBUG(get_logger(), "Publishing footprint");
      footprint_pub_->publish(std::move(footprint));
      initialized_ = true;
    }
  }
}
In fact, the problem with calling getRobotPose() is essentially caused by the received '/tf' not being updated, but the specific reason has not been found.

**Comment by SteveMacenski** [comment]
Are you saying that you modified the code and the issues are w.r.t. the modifications of your version of the code? I'm not clear what you mean here or what the specific problem is.

**Comment by SteveMacenski** [comment]
@lizhao112396 any info?

**Comment by SteveMacenski** [comment]
No response + lack of actionable information.
