### ISSUE TITLE
[collision monitor] How to handle .nan (and .inf) commands ?

### ISSUE THREAD

**Issue by doisyg** [ros-planning/navigation2#3628]
## Feature request
Linked to https://github.com/ros-planning/navigation2/issues/3627
It is not a bug, but currently the collision monitor is not filtering out invalid input commands. We probably want to implement the same logic as discussed in https://github.com/ros-planning/navigation2/issues/3627, i.e. reject and log invalid ones (.nan and .inf)

**Comment by SteveMacenski** [comment]
I'll make a comment to roll that in to the same ticket
