### ISSUE TITLE
Ros2 navigation2 can not load map in RVIZ2

### ISSUE THREAD

**Issue by congliu0913** [ros-planning/navigation2#363]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - initial_ros_setup.sh
- Version or commit hash:
  - nav2_bringup_readme branch
- DDS implementation:
  - default
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
As we follow https://github.com/ros-planning/navigation2/tree/nav2_bringup_readme/nav2_bringup to load map by ros2 navigation, the map not show in rviz2. 
```
$ ros2 launch nav2_bringup nav2_bringup_1st_launch.py map:=/home/intel/Documents/map/cartographer_40hz_default_speed_1.yaml 
```
```
$ ros2 run rviz2 rviz2 
```
We no show map topic in ros2 topic list.
```
$ ros2 topic list 
/amcl_pose
/initialpose
/occ_grid
/parameter_events
/particlecloud
/scan
/tf
/tf_static

$ ros2 node list
ros2 node  list
/launch_ros
/map_server
/amcl
/amcl
/amcl
/rviz
```
#### Expected behavior
Can display map in RVIZ2.
#### Actual behavior
Unable to display map in RVIZ2.
#### Additional information
![1st_launch_to_load_local_map](https://user-images.githubusercontent.com/30585576/49065537-3e895980-f259-11e8-862a-63e530d937e4.png)
![2nd_launch](https://user-images.githubusercontent.com/30585576/49065564-52cd5680-f259-11e8-95bb-b8282e609ecd.png)
![rviz2](https://user-images.githubusercontent.com/30585576/49065571-595bce00-f259-11e8-8f34-c16c8f2288d5.png)
![ros2_topic_list](https://user-images.githubusercontent.com/30585576/49065583-5e208200-f259-11e8-9556-d513d1a7f732.png)
![show_in_rviz2](https://user-images.githubusercontent.com/30585576/49065586-624c9f80-f259-11e8-8675-be30e738be8f.png)

**Comment by mkhansen-intel** [comment]
The map is published on the /occ_grid topic since the type is /occ_grid. We have an issue #197 to change this.

**Comment by congliu0913** [comment]
After change topic from /map to /occ_grid, we can show loaded map in rviz2.
![show_map_in_rviz2_of_ubuntu_18 04](https://user-images.githubusercontent.com/30585576/49127617-03dbfb80-f303-11e8-9b1d-591302d7685d.png)
