### ISSUE TITLE
Humble nav2_bringup parameter file includes bt node that doesn't exist in humble

### ISSUE THREAD

**Issue by Nate711** [ros-planning/navigation2#3636]
I was trying to make my own version of nav2_bringup on humble but the stack would crash on startup. I traced it to https://github.com/ros-planning/navigation2/pull/3616, in particular to the fact that `nav2_are_error_codes_active_condition_bt_node` is not in humble but it's referenced in the parameter file for nav2_bringup. https://github.com/ros-planning/navigation2/blob/395b9cd8f424203d8ac88ea01ce29a8b550ec602/nav2_bringup/params/nav2_params.yaml#L70

Reverting the params file to 0d86469f1c31708117e68f3f44ad5392347e9a5d  seems to have made it work

**Comment by SteveMacenski** [comment]
Fixing now

**Comment by Nate711** [comment]
Thanks!
