### ISSUE TITLE
CMake: Deprecated CMAKE_COMPILER_IS_GNUCXX variable

### ISSUE THREAD

**Issue by Ryanf55** [ros-planning/navigation2#3646]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04
- ROS2 Version:
  - Rolling
- Version or commit hash:
  - N/A

#### Steps to reproduce issue

Just reading the NAV2 CMake source code and NAV2 source code, this variable is deprecated:

https://cmake.org/cmake/help/latest/variable/CMAKE_COMPILER_IS_GNUCXX.html

#### Expected behavior

Using non-deprecated CMake

#### Actual behavior

NAV2 is using deprecated variables

#### Additional information

This should be a quick swap.

**Comment by SteveMacenski** [comment]
A PR would be appreciated :smile:

**Comment by Ryanf55** [comment]
You got it
