### ISSUE TITLE
nav2_mppi_controller is necessary?

### ISSUE THREAD

**Issue by Autostone-c** [ros-planning/navigation2#3664]
hi，I compiled and built autoware (the humble branch) on ubuntu20.04, and because rely on navigation2, I downloaded the source code for compilation, but nav2_mppi_controller relies on the “xtensor” library, which I found difficult to compile on Ubuntu 20.04. Additionally, I have checked navigation2 and autoware, but there are no feature packages used for nav2_mppi_controller, so I want to ask if this must be compiled? Or can we ignore it

**Comment by SteveMacenski** [comment]
If you want  to use the most advanced predictive trajectory planner in the stack: then yes. Otherwise, then no, you could skip it and you'd be none the worse.
