### ISSUE TITLE
How to create subscription/publisher from custom costmap plugin?

### ISSUE THREAD

**Issue by pky404** [ros-planning/navigation2#3665]
ROS 2 Humble

Ubuntu 22.04

How to create a subscription while creating a custom costmap plugin?

The plugin is able to load and updateCosts functions are getting called with no error . The subscription topic is not listed on " ros2 topic list" , same thing happening with publisher.

Using:
`class PolyLayer : public nav2_costmap_2d::CostmapLayer`

Subscriber created in the onInitialize().

```

void PolyLayer::onInitialize()
{
    auto node = node_.lock();
    if (!node)
    {
        throw std::runtime_error{"Failed to lock node"};
    }
    declareParameter("enabled", rclcpp::ParameterValue(true));
    node->get_parameter(name_ + "." + "enabled", enabled_);

    rolling_window_ = layered_costmap_->isRolling();

    RCLCPP_INFO(logger_, "check:[%d]", node_.expired());

    this->poly_vertices_sub_ = node->create_subscription<geometry_msgs::msg::PolygonStamped>("poly_shape", rclcpp::QoS(rclcpp::KeepLast(1)).reliable(), std::bind(&PolyLayer::poly_vertices_cb, this, std::placeholders::_1));

    current_ = true;
    default_value_ = NO_INFORMATION;
    matchSize();

    RCLCPP_INFO(logger_, "Polygon Layer Initialized.");
}
```

**Comment by SteveMacenski** [comment]
This is not a feature or bug with nav2, so please ask on Robotics Stack Exchange or other ‘ask’ forums or look into basic ROS tutorials on subscriptions
