### ISSUE TITLE
Using Simple Commander API for multi robot systems

### ISSUE THREAD

**Issue by AryanArora12** [ros-planning/navigation2#3668]
----
## Feature request
Using [Simple Commander API](https://navigation.ros.org/commander_api/index.html) for multi robot systems. This is in continuation to [this](https://github.com/ros-planning/navigation2/issues/2415) post.  

#### Feature description
I am making a multi-robot simulation and for my purposes, I want to use the Python API to send navigation goals to different robots. As of now, I cannot see how to do that with two robots(that is add a namespace and setting up goal poses as well as set initial poses individually for each robot). Any guidance on how to do this would be helpful. 

#### Implementation considerations

I think the solution proposed in the [post](https://github.com/ros-planning/navigation2/issues/2415) mentioned earlier sounds good, if not implemented yet.

**Comment by SteveMacenski** [comment]
That was outside of the scope of the original "simple" nature of the commander, but it shouldn't be prohibitively difficult to make work and it would be a great contribution back!

I'd add the namespace support and than have a different simple commander object for each of the robots. That should separate them from each other and namespaced by the appropriate services and such.

**Comment by AryanArora12** [comment]
Cool! I thought about the same thing but was struggling in adding the namespace functionality. I'll work on it over the next few days and provide an update if I get any progress/or am able to implement that successfully.

**Comment by SteveMacenski** [comment]
I think its mostly just adding the namespace when we create all the clients in the python API's constructor! 

OK!

**Comment by SteveMacenski** [comment]
Whoops wrong button. Can you open a PR? Happy to merge it so others can use!

**Comment by AryanArora12** [comment]
Yeah sure. I'll try and do a few more tests for sanity check and then open a PR by this week.

**Comment by ipa-rar** [comment]
@SteveMacenski Can you check this PR #3701

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/main/nav2_simple_commander/nav2_simple_commander/robot_navigator.py#L50  https://docs.ros2.org/latest/api/rclpy/api/node.html. That might just do everything for us automatically. Can you try that instead?

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/3803 implements + tested
