### ISSUE TITLE
nav2_params.yaml from nav2_bringup contains unknown library

### ISSUE THREAD

**Issue by cocodmdr** [ros-planning/navigation2#3671]
## Bug report

**Required Info:**

- Operating System:
  - ubunut 22.04
- ROS2 Version:
  - ROS2 Humble 
- Version or commit hash:
  - latest debian packages
- DDS implementation:
  - 

#### Steps to reproduce issue
- replace nav2_params.yaml from /opt/ros/humble/share/nav2_bringup/params/nav2_params.yaml by the one from the repo (https://github.com/ros-planning/navigation2/blob/humble/nav2_bringup/params/nav2_params.yaml)
```
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/humble/share/turtlebot3_gazebo/models
export TURTLEBOT3_MODEL=waffle
ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False
```

#### Expected behavior
 - working navigation
 
#### Actual behavior

`
[component_container_isolated-6] [ERROR] [1688139916.451750453] []: Original error: Could not load library: libnav2_is_battery_charging_condition_bt_node.so: cannot open shared object file: No such file or directory
[component_container_isolated-6] [WARN] [1688139916.451769935] []: Error occurred while doing error handling.
[component_container_isolated-6] [FATAL] [1688139916.451777604] [bt_navigator]: Lifecycle node bt_navigator does not have error state implemented
[component_container_isolated-6] [ERROR] [1688139916.452150036] [lifecycle_manager_navigation]: Failed to change state for node: bt_navigator
[component_container_isolated-6] [ERROR] [1688139916.452170551] [lifecycle_manager_navigation]: Failed to bring up all requested nodes. Aborting bringup.
`
#### Additional information

By removing the line 101 in the file nav2_params.yaml(https://github.com/ros-planning/navigation2/blob/humble/nav2_bringup/params/nav2_params.yaml#L101) everything runs fine.

**Comment by SteveMacenski** [comment]
This has already been addressed as you mention, just wanting on a Humble sync to update the version in binaries.
