### ISSUE TITLE
MPPI Controller Implementation issues for local and global cost map

### ISSUE THREAD

**Issue by Kazimbalti** [ros-planning/navigation2#3678]
[config folder](https://drive.google.com/drive/folders/1U6v9h8MYsgemMfUX7Um3pibFhfhWeBGL?usp=drive_link)

Hello,
Please check the config folder, inside the config folder there is tb3_nav_params.yaml file,
I did copy and past the controller_server from here [MPPI](https://navigation.ros.org/configuration/packages/configuring-mppic.html) 
Now the global and local map doesn't appear.
Please guide me in this regard.
thank you

**Comment by SteveMacenski** [comment]
Ask on ROS Answers
