### ISSUE TITLE
Create a global plan between any 2 poses with nav2

### ISSUE THREAD

**Issue by ipa-rar** [ros-planning/navigation2#3686]
## Question

**Required Info:**
- ROS2 Version:
  - humble
- Version or commit hash:
  - binary

#### Steps to reproduce issue
I am trying to create a path between 2 poses using nav2_simple_commander. However nav2_simple_commander rely on AMCL when creating path. Is there a way to generate a global plan between two poses in a map without relying on AMCL. 

#### Additional information
https://answers.ros.org/question/417326/create-a-global-plan-between-any-2-poses-with-nav2/

**Comment by SteveMacenski** [comment]
Glad you found something, our nav2 benchmarking scripts should provide you an example of how to do it!

**Comment by SteveMacenski** [comment]
In /tools
