### ISSUE TITLE
Delay in Response and Collision Handling of Robots when Faced with Dynamic Obstacles

### ISSUE THREAD

**Issue by osama-z-salah** [ros-planning/navigation2#3695]
Required Info:

**Operating System:**
-Ubuntu 22.04.2
ROS2 Version:
Humble binaries

**Steps to reproduce issue:**

I am using teb local planner
The planner exhibits a slightly delayed response when encountering dynamic obstacles. If an obstacle suddenly appears within approximately 0.2 meters in front of my robot, it won't come to an immediate halt. Instead, it will continue moving for a short duration before eventually stopping, sometimes making contact with the obstacle before coming to a complete stop.

**Expected behavior**

immediate halt

**Actual behavior**

continue moving for a short duration before eventually stopping, sometimes making contact with the obstacle before coming to a complete stop

**Here is my controller parameter**
controller_server:
  ros__parameters:
    odom_topic: /diffbot_base_controller/odom
    use_sim_time: True
    controller_frequency: 5.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: teb_local_planner::TebLocalPlannerROS

      teb_autosize: 1.0
      dt_ref: 0.2
      dt_hysteresis: 0.07
      max_samples: 500
      global_plan_overwrite_orientation: False
      allow_init_with_backwards_motion: False
      max_global_plan_lookahead_dist: 3.0
      global_plan_viapoint_sep: 0.3
      global_plan_prune_distance: 1.0
      exact_arc_length: False
      feasibility_check_no_poses: 5
      publish_feedback: False
          
      # Robot
              
      max_vel_x: 0.3
      max_vel_theta: 0.25 
      acc_lim_x: 0.2
      acc_lim_theta: 0.2

      footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "line"
        line_start : [-0.1775, 0.0]
        line_end : [0.1775, 0.0]

      # GoalTolerance
              
      free_goal_vel: False
          
      # Obstacles
          
      min_obstacle_dist: 0.5
      inflation_dist: 1.0
      include_costmap_obstacles: True
      costmap_obstacles_behind_robot_dist: 1.5
      obstacle_poses_affected: 30

      dynamic_obstacle_inflation_dist: 1.0
      include_dynamic_obstacles: True 

      costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
      costmap_converter_spin_thread: True
      costmap_converter_rate: 5

      # Optimization
          
      no_inner_iterations: 5
      no_outer_iterations: 4
      optimization_activate: True
      optimization_verbose: False
      penalty_epsilon: 0.1
      obstacle_cost_exponent: 4.0
      weight_max_vel_x: 2.0
      weight_max_vel_theta: 1.0
      weight_acc_lim_x: 1.0
      weight_acc_lim_theta: 1.0
      weight_kinematics_nh: 1000.0
      weight_kinematics_forward_drive: 70.0
      weight_kinematics_turning_radius: 1.0
      weight_optimaltime: 1.0 # must be > 0
      weight_shortest_path: 0.0
      weight_obstacle: 100.0
      weight_inflation: 0.2
      weight_dynamic_obstacle: 10.0 # not in use yet
      weight_dynamic_obstacle_inflation: 0.2
      weight_viapoint: 1.0
      weight_adapt_factor: 2.0

      # Homotopy Class Planner

      enable_homotopy_class_planning: True
      enable_multithreading: True
      max_number_classes: 4
      selection_cost_hysteresis: 1.0
      selection_prefer_initial_plan: 0.9
      selection_obst_cost_scale: 100.0
      selection_alternative_time_cost: False

      roadmap_graph_no_samples: 15
      roadmap_graph_area_width: 5.0
      roadmap_graph_area_length_scale: 1.0
      h_signature_prescaler: 0.5
      h_signature_threshold: 0.1
      obstacle_heading_threshold: 0.45
      switching_blocking_period: 0.0
      viapoints_all_candidates: True
      delete_detours_backwards: True
      max_ratio_detours_duration_best_duration: 3.0
      visualize_hc_graph: False
      visualize_with_time_as_z_axis_scale: 0.0

      # Recovery
      
      shrink_horizon_backup: True
      shrink_horizon_min_duration: 10.0
      oscillation_recovery: True
      oscillation_v_eps: 0.1
      oscillation_omega_eps: 0.1
      oscillation_recovery_min_duration: 10.0
      oscillation_filter_duration: 10.0

**Comment by SteveMacenski** [comment]
Take it up with TEB. We didn’t make nor directly support it
