### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by makarandmandolkar** [ros-planning/navigation2#3705]
I am trying to build nav2 in ros galactic, but encountering the following error:

Starting >>> nav2_amcl                                                                                                                        
**--- stderr: nav2_map_server                                                                                                                               
/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(convert.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN4YAML23RepresentationExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status**
make[2]: *** [CMakeFiles/map_io.dir/build.make:278: libmap_io.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:347: CMakeFiles/map_io.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:146: all] Error 2

Can someone please guide on how to fix this?
I am building using this:"
colcon build \
  --symlink-install
  
I am following this page: 
https://navigation.ros.org/development_guides/build_docs/index.html

**Comment by SteveMacenski** [comment]
galactic is EOL and will not receive support.
