### ISSUE TITLE
How to improve the consistency of adjacent frame decision results in path planning?

### ISSUE THREAD

**Issue by xianglunkai** [ros-planning/navigation2#3707]
I think this is very important. Currently, navigation systems have inconsistent output paths when making path decisions, which is very detrimental to controller execution. My initial idea is to change the planning starting point to the projection of the previous planned path, or to add continuous constraints between adjacent paths; Alternatively, use trajectory trees for planning instead of the current trajectory chain

**Comment by SteveMacenski** [comment]
Certainly all of which are possible. Choosing how and when you plan is one key thing you can control in the behavior tree. If you would like to use a planning method with some memory of previous paths, that’s also easy to customize using the planner plugin APIs. I’m sure such methods would also make good open source contributions!

**Comment by SteveMacenski** [comment]
Happy to keep chatting on this, but I think my explanation above gives some clear direction on the BT how to address this concern that is probably best and doesn't require follow up here in terms of code changes or new features in nav2.
