### ISSUE TITLE
Handling Emergency Stop Button for Differential Mobile Robot using Nav2

### ISSUE THREAD

**Issue by osama-z-salah** [ros-planning/navigation2#3709]
I am facing an issue with handling the emergency stop button for a differential mobile robot that utilizes Nav2 for navigation. The problem arises when the emergency button is pressed, cutting power to the motors. Upon releasing the button, a new odometry transformation (tf) is being created, which differs from the one that was existing before the emergency button was clicked. As a result, the robot loses its localization in the map.

**Required Info:**

- Operating System:
  -Ubuntu 22.04.2
- ROS2 Version:
  -Humble binaries

#### Steps to reproduce issue

1. Start the robot and enable navigation with Nav2.
2. Drive the robot around the environment to establish a proper odometry transformation (tf).
3. Press the emergency stop button to cut power to the motors.
4. Release the emergency button to restore power to the motors.
5. Observe that a new odometry transformation (tf) is created, which differs from the previous one.
6. As a result, the robot loses its localization in the map.

#### Expected behavior

When the emergency stop button is pressed and then released, the robot should maintain its original odometry transformation (tf) without any significant deviation from the previous state. This will ensure that the robot can resume navigation without losing its localization in the map.

#### Actual behavior

Upon releasing the emergency stop button, a new odometry transformation (tf) is created, which differs from the previous one. This deviation in odometry causes the robot to lose its localization in the map, leading to navigation inaccuracies and potentially unsafe behavior.

**Comment by SteveMacenski** [comment]
Hi,

This seems like more of an application specific problem for how you create the e-stop behavior. It sounds like this is a trivial solution is **not** to reset the TF tree and continue to track odometry even if the motors' are not being actuated. The steps for reproduction you list in 3-5 seem like a self inflicted wound that has to do with your robot specifics more than anything to do with Nav2 or the software stack. 

> When the emergency stop button is pressed and then released, the robot should maintain its original odometry transformation (tf) 

Precisely, you should set up your robot that way, that's not something we provided, that something your robot implements.
