### ISSUE TITLE
Talk to existing non-nav2 maintainers carried over and ask their interest in continuing to maintain their packages in navigation2

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#372]
Looks like
- [ ] Aaron Hoy @aaronhoy 
- [ ] Fergs @mikeferguson 
- [ ] David V. Lu!! (on dwb metapackage) @DLu

**Comment by mkhansen-intel** [comment]
I'm hoping they will at least be part-time contributors :)

**Comment by crdelsey** [comment]
ROS 1 maintainers are welcome and encouraged to be ROS 2 maintainers as they see fit. Closing this issue for now.

**Comment by SteveMacenski** [comment]
@crdelsey the reason I opened the ticket is because their names are still in the package XML file, and therefore they are receiving failures of packages for building they "maintain", which is unfair to spam people uninvolved with our work.

I'm reopening this ticket, and from the lack of motion from any of the maintainers, I propose that we remove them from their respective package.xml files. @crdelsey thoughts?

**Comment by crdelsey** [comment]
I agree that makes sense.
