### ISSUE TITLE
Update costmap publisher and subscriber to allow for 'update' messages in raw costmaps

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#3732]
Currently, all costmap publisher / subscription when using raw messages (e.g. costmap messages containing the raw costmap from 0-255 rather than the occupancy grid message of 0-100 for internal use by the task servers such as behavior and smoother) send the full costmap each time. This is unideal, even though we compose all our nodes into the same process, which does help greatly with compute time.

It would be better if we mirrored the Update methods from the OccupancyGrid publication to minimize the number of times a full, raw, costmap is sent over the network and only publish the updated regions. This would decrease compute resources and latency for the behavior and smoother server (or other servers for client applications using the raw costmaps).

This is a great first issue for a new contributor! Just make sure to look over the code and make sure that all instances of costmap pub/sub are using these classes to make sure that everyone can properly handle the updates (which I believe they all should be, minus some unit tests)

**Comment by Relativiteit** [comment]
@SteveMacenski I would like to contribute to this as one of my first contributions!

**Comment by SteveMacenski** [comment]
Great! Any questions you might have :-) The file I point to should pretty much have the "core basics" of demonstration of how such a feature could work using the OccupancyGrid update logic. Its mostly mirroring that for the nav2_msgs/Costmap message type and updating the publisher and subscriber to work with it. Then, checking uses of the Costmap message to make sure everyone is using the pub/sub objects to get those updates -- in case there are some raw publishers / subscribers hanging around!

Thanks and I look forward!

**Comment by SteveMacenski** [comment]
@Relativiteit any update? :-)

**Comment by emSko** [comment]
I would like to take over this issue.

Just to recap, you think about mimicking this behaviour [costmap_update_pub_](https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/src/costmap_2d_publisher.cpp#L203-L222)  for _costmap_raw_pub__ . 

So creating CostmapUpdate message and adding proper publisher and subscriber.

**Comment by SteveMacenski** [comment]
And the counterpart in the costmap subscriber as well to take those published updates and populate the raw costmap!

**Comment by Relativiteit** [comment]
hey guys yes, I got a bit lost on how to do it please @emSko take it over this was a bit above my head. I would still like to try it this weekend. And make a PR but please take point on it.

**Comment by SteveMacenski** [comment]
@emSko any updates or thoughts? How's it going :smile:

**Comment by emSko** [comment]
@SteveMacenski I've implemented the publisher but have no good ideas for the subscriber's implementation. I would like to talk it over during tonight's meeting, is that ok?

**Comment by SteveMacenski** [comment]
OK!

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/plugins/static_layer.cpp#L290

https://github.com/ros-visualization/rviz/blob/noetic-devel/src/rviz/default_plugin/map_display.cpp#L570

**Comment by SteveMacenski** [comment]
Hi @emSko ! How are things going?

**Comment by SteveMacenski** [comment]
I took a brief look at it and from a first look, the publisher seems good. Some notes, but nothing huge! 

> but the size of an update of the global Costmap became 10 times smaller compared with the whole map

Assuming you're talking about the update: That's good news! That's exactly what it should be doing. This should be only publishing the part of the map that has changed from new sensor data processing rather than sending the full size every single time. The first map published (if the logic is right) on the main topic should be the full map, and subsequent updates on the `_update` topic should be much smaller!

This sounds like good news

For testing:

`colcon test --packages-select <your package>` and to see the results once complete `colcon test-result --verbose` to see the failed results.

**Comment by SteveMacenski** [comment]
Merging imminently! Thanks @emSko !
