### ISSUE TITLE
Obstacle avoidance question

### ISSUE THREAD

**Issue by abhinavsagar** [ros-planning/navigation2#3738]
Hi, I don't know if this is the correct place to ask so please excuse me if it is not. Nav2 automatically avoids obstacles. My goal is to make it work such that it avoids all obstacles except one like a person's face. I would like the robot to goal to that obstacle and stop at some threshold distance rather than avoid it. It would be great if anyone can guide me on how to solve this task.

**Comment by SteveMacenski** [comment]
Please ask application questions or help requests on ROS Answers, Slack, etc. This is not the appropriate place.
