### ISSUE TITLE
Setting map_url to a relative path

### ISSUE THREAD

**Issue by Juhyung-L** [ros-planning/navigation2#3742]
I am trying to save a costmap to a file using the map_saver service.

It says here that you can use either the absolute path or the relative path (relative to a ROS package) of the file: https://github.com/ros-planning/navigation2/blob/main/nav2_msgs/srv/SaveMap.srv

I was able to save the map using the absolute path.
```
SaveParameters save_parameters;
save_parameters.map_file_name = "/home/juhyung/Desktop/dev_ws/src/map_loader/map/map";

```
I want to save the map file to the map folder inside the map_loader ROS package using a path that is relative to the map_loader package. How can I do this?

**Comment by SteveMacenski** [comment]
The relative path is to the relative directory of execution of the server, not arbitrarily relative to anywhere in the filesystem. 

However, you can manipulate this one time at launch using the `cwd` launch argument for the directory that the node is launched within (ex https://github.com/ros-planning/navigation2/blob/main/nav2_bringup/launch/tb3_simulation_launch.py#L172). This can be arbitrary, but unchanging. 

A better way is whatever is saving the map, _that_ can find the relative path as an absolute path using the ament_cpp tools to find the shared directory path of a requested ROS package (or other ROS package directories, see the ament_cpp API) https://docs.ros2.org/latest/api/ament_index_cpp/index.html. Then, your request can just send that absolute path to the map saver.
