### ISSUE TITLE
planner server unstart and planner log empty(using nav2-galactic)

### ISSUE THREAD

**Issue by davidlmljll** [ros-planning/navigation2#3743]
After starting the navigator, the planner did not start after the initial pose was given on rviz2 (and the global cost map was not published), the planner log file (.ros/log) is empty without any content, what is the cause of this?

**Comment by SteveMacenski** [comment]
Galactic is EOL and does not receive support. Try updating to a modern version + check out our getting started guides at navigation.ros.org.
