### ISSUE TITLE
Can we use nav2_param.yaml for turtlebot4 for ignition world.

### ISSUE THREAD

**Issue by vamsi1961** [ros-planning/navigation2#3759]
## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by SteveMacenski** [comment]
@vamsi1961 its not calibrated specifically for the TB4, but might be a good starting point for adjustments for the TB4 platform. You may want to look at the TB4 navigation packages, they might contain parameters specific to the TB4.
