### ISSUE TITLE
Issues with Monitoring using Groot in ROS2 Navigation

### ISSUE THREAD

**Issue by pannatorn6395** [ros-planning/navigation2#3770]
Hello everyone,

I'm trying to use Groot to monitor the behavior tree in ROS2, but I'm encountering some challenges in setting it up and running it.

I've set the following in my yaml file:

enable_groot_monitoring: True
pose_groot_server_port: 1666
pose_groot_publisher_port: 1667

However, I'm still unable to monitor through Groot. I'm unsure if there are additional steps or configurations I need to consider. Has anyone faced this issue before or have any suggestions? Any guidance would be appreciated.

Thank you in advance!

**Comment by SteveMacenski** [comment]
We have dropped live groot BT monitoring some time ago due to challenges with dynamically switching BTs with the zeromq connection. It is not a feature we have anymore in Humble/Iron/Rolling
