### ISSUE TITLE
stop a nav2 navigation with a python node

### ISSUE THREAD

**Issue by kleanbotmk2** [ros-planning/navigation2#3783]
Ros2 foxy

Hi,

i'd like to know how could i stop a nav2 navigation with a python node ! I can't find the information on my own.

Thanks in advance,

Sacha

**Comment by SteveMacenski** [comment]
See the simple commander API https://navigation.ros.org/commander_api/index.html

If you have follow up questions, ask on Robotics Stack Exchange

**Comment by kleanbotmk2** [comment]
thanks for your awnser but i unable to find the ros-foxy-nav2-simple-commander package when i'm trying to install it. Any ideas ?

**Comment by kleanbotmk2** [comment]
@SteveMacenski any ideas ?
