### ISSUE TITLE
Obstacle heuristic admissibility

### ISSUE THREAD

**Issue by Nate711** [ros-planning/navigation2#3820]
Hi, I was wondering if the obstacle heuristic is admissible? I noticed it uses 8-way graph connectivity which would overestimate path lengths in comparison hybrid and lattice motions which cut across grid edges. For example going 2 cells up and 1 to the right with 8-way connectivity would have a distance of 2.414 vs a straight line cost of 2.23. Does the obstacle heuristic include some sort of scaling to account for this?

**Comment by SteveMacenski** [comment]
Good question, I'll start off with multiple claims from multiple robotics research experts that this is indeed admissible:
- https://ieeexplore.ieee.org/document/8702779
- http://www.cs.cmu.edu/~maxim/classes/robotplanning_grad_fall19/lectures/casestudy_autodriving_16782_fall19.pdf

In practice, I've actually had a similar suspicion so I took some metrics pre-planning on the heuristic value that the cost-aware obstacle heuristic computed the cost as and then the final cost over maps of varying size. Without going into the gruesome details (some partial summary is [here](https://github.com/ros-planning/navigation2/issues/3172#issuecomment-1684574569) or in the surrounding thread): it borders admissibility well within 1% of the true cost of travel (< 0.5%) --  but usually on the right side of it. That's pretty good as far as we're concerned in any functional aspect. We also post-process smooth lightly that would remove any such issues that it might create (which the main paper also does but far, far more intensively which would definitely remove any such admissibility issues in the base technique). Though, I did some experiments where I manually shot up the heuristic to be always admissible and I noticed no difference in path quality so I think there's not much reason to
