### ISSUE TITLE
nav2 go to pose python example using cartographer

### ISSUE THREAD

**Issue by altineller** [ros-planning/navigation2#3829]
Hello,

Referencing: https://github.com/ros-planning/navigation2/issues/2283#issuecomment-853456150

I am using nav2 in conjunction with cartographer. I wanted to use above example to submit a goal and wait for it, but it will naturally complain about amcl namely [INFO] [1695315958.261853669] [basic_navigator]: amcl/get_state service not available, waiting.

Since we are not using amcl, in both cartographer and slam mode, are we not able to take advantage of the navigator submitting goal poses, or is it generally a bad idea to submit goal poses in unnkown environments such as cartographer and slam.

Best Regards,
C.A.

**Comment by SteveMacenski** [comment]
Check out the documentation: https://navigation.ros.org/commander_api/index.html#id1

`waitUntilNav2Active( navigator=’bt_navigator’, localizer=’amcl’)` you need to set the proper localizer.
