### ISSUE TITLE
Can we running Regulated Pure Pursuit in ROS1?

### ISSUE THREAD

**Issue by DoongLi** [ros-planning/navigation2#3839]
Hi ,
Thanks advance, Just wanna know is there any chance to running Regulated Pure Pursuit  at ros1?

**Comment by SteveMacenski** [comment]
We do not support ros 1

**Comment by DoongLi** [comment]
Hi，Can you tell me how to modify it？

**Comment by asasine** [comment]
https://github.com/JohnTGZ/regulated_pure_pursuit_controller is a Noetic backport of regulated pure pursuit but is no longer maintained.

**Comment by DoongLi** [comment]
Thx! @asasine
