### ISSUE TITLE
local costmap is not running in nav2_simple_commander demos

### ISSUE THREAD

**Issue by altineller** [ros-planning/navigation2#3847]
ROS2 humble, Ubuntu 22, using humble branch from github

Hello,

When working with navigation2/nav2_simple_commander/launch/nav_through_poses_example_launch.py

I noticed no local costmap is generated.

Local costmap does not output error in the console but complains about:

[component_container_isolated-4] [INFO] [1695928844.435968060] [local_costmap.local_costmap]: Checking transform
[component_container_isolated-4] [INFO] [1695928844.435983233] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container_isolated-4] [INFO] [1695928844.936046615] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container_isolated-4] [INFO] [1695928845.436043341] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container_isolated-4] [INFO] [1695928845.936042666] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[component_container_isolated-4] [INFO] [1695928846.436082404] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
[gzserver-1] [INFO] [1695928846.800852636] [gazebo_ros_node]: ROS was initialized without arguments.
[component_container_isolated-4] [INFO] [1695928846.936063389] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist

Any ideas greatly appreciated.

-C

**Comment by SteveMacenski** [comment]
Ask on Robotics Stack Exchange but the error appears to be clear: odom isn't being published for the costmap to be valid. You should look into that.
