### ISSUE TITLE
[Smac planner: Lattice generator] Simplifying equation to get lattice outer edge point

### ISSUE THREAD

**Issue by akchobby** [ros-planning/navigation2#3858]
https://github.com/ros-planning/navigation2/blob/67bae86462e0242a48283c55f713ddb35861c98f/nav2_smac_planner/lattice_primitives/lattice_generator.py#L122

A simplification to this formula can be done theoretically and it would  allow others to clearly understand the code, the current formula is as follows
![image](https://github.com/ros-planning/navigation2/assets/44644339/0701fc8a-ed2c-4212-a080-08f45214af57)

where n = number of headings

it can be simplified to just 
![image](https://github.com/ros-planning/navigation2/assets/44644339/480a9578-97fb-4cb7-b28d-6c199cdf1a0c)

Note the equations match even when flooring (int) is applied.

**Comment by SteveMacenski** [comment]
That tracks for me too. Can you open a PR for that adjustment?
