### ISSUE TITLE
Unable to navigate using Realsense D455 camera due to bad costmap 

### ISSUE THREAD

**Issue by deepak-anzo** [ros-planning/navigation2#3865]
ROS2 Nav2 Humble

I am trying to navigate and avoid obstacles using Realsense D455 camera and lidar therefore added into the obstacle layers parameters. All the pointcloud is added into costmap and the robot is unable to move. I am not able to find out the problem. Please help.
The costmap in front of the camera looks like this.

![Screenshot from 2023-10-07 11-19-59](https://github.com/ros-planning/navigation2/assets/122998199/70a367e7-e306-4904-aa0c-a5bdba1e79f6)

the parameter file is given as - 
global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      footprint: "[ [0.80, 0.80], [0.80, -0.80], [-0.80, -0.80], [-0.80, 0.80] ]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "keepout_filter", "inflation_layer"]
      filters: ["speed_filter"]
      speed_filter:
        plugin: "nav2_costmap_2d::SpeedFilter"
        enabled: True
        filter_info_topic: "/speed_costmap_filter_info"
        speed_limit_topic: "/speed_limit"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_1 scan_2 points_1 points_2
        scan_1:
          topic: /front_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
        scan_2:
          topic: /rear_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
        points_1:
          topic: /camera/depth/color/points
          max_obstacle_height: 2.0
          min_obstacle_height: 0.30
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
          footprint_clearing_enabled: True
          sensor_frame:  camera_depth_optical_frame
          observation_persistence: 0.0
          mark_threshold: 5.0
        points_2:
          topic: /camera/depth/color/points
          max_obstacle_height: 0.30
          min_obstacle_height: 0.0
          clearing: True
          marking: False
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
          footprint_clearing_enabled: True
          sensor_frame:  camera_depth_optical_frame
          observation_persistence: 0.0
  static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.5

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"
    
  always_send_full_costmap: True

    global_costmap_client:
      ros__parameters:
        use_sim_time: False
    global_costmap_rclcpp_node:
      ros__parameters:
        use_sim_time: False

***************************************************************

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0 
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 10
      height: 10
      resolution: 0.05
      # robot_radius: 1.25
      footprint: "[ [0.80, 0.80], [0.80, -0.80], [-0.80, -0.80], [-0.80, 0.80] ]"
      plugins: ["voxel_layer", "denoise_layer","keepout_filter", "inflation_layer"]
      denoise_layer:
        plugin: "nav2_costmap_2d::DenoiseLayer"
        enabled: true
        minimal_group_size: 2
        group_connectivity_type: 8
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 1.5
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: scan_1 scan_2 points_1 points_2
        scan_1:
          topic: /front_lidar/scan
          max_obstacle_height: 2.0
          clearing: False
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
        scan_2:
          topic: /front_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: False
          data_type: "LaserScan"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
        points_1:
          topic: /camera/depth/color/points
          max_obstacle_height: 2.0
          min_obstacle_height: 0.150
          clearing: True
          marking: True
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
          footprint_clearing_enabled: True
          sensor_frame: camera_link
          observation_persistence: 0.0
          mark_threshold: 5.0
        points_2:
          topic: /camera/depth/color/points
          max_obstacle_height: 0.150
          min_obstacle_height: 0.0
          clearing: True
          marking: False
          data_type: "PointCloud2"
          raytrace_max_range: 10.0
          raytrace_min_range: 0.0
          obstacle_max_range: 9.5
          obstacle_min_range: 0.0
          footprint_clearing_enabled: True
          sensor_frame: camera_link
          observation_persistence: 0.0

      static_layer:
        map_subscribe_transient_local: True

      keepout_filter:
        plugin: "nav2_costmap_2d::KeepoutFilter"
        enabled: True
        filter_info_topic: "/costmap_filter_info"

      always_send_full_costmap: True

**Comment by SteveMacenski** [comment]
Ask on robotics stack exchange with an actual description of the bad behavior
