### ISSUE TITLE
 stack-buffer-overflow in behavior_tree

### ISSUE THREAD

**Issue by Rrooach** [ros-planning/navigation2#3884]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version: Humble
  - 
- Version or commit hash: 4b9bd8638de2cdd5bde363c84ecd4760105ec00e
  - 
- DDS implementation: FastRTPS
  - 

#### Steps to reproduce issue
Hi, when I fuzz test the Nav2, I encountered an ASAN report during testing, within the behavior tree module.

I build the project with AddressSanitizer:
```shell
 CC=clang CXX=clang++  colcon build --parallel-workers 3333  --cmake-args -DCMAKE_C_FLAGS=" -g  -w  -fsanitize=address " -DCMAKE_CXX_FLAGS="  -g  -w -fsanitize=address "
```
And then I start the fuzzing process, and I get the following error report:
https://pastebin.com/2MLhqdp8

It seems there is an illegal access at src/behaviortree-cpp-v3/src/xml_parsing.cpp
```cpp
  for (auto bt_root = xml_root->FirstChildElement("BehaviorTree"); bt_root != nullptr;
       bt_root = bt_root->NextSiblingElement("BehaviorTree"))
  {
    recursiveStep(bt_root);
  }
```
#### Expected behavior
The program execute without error

#### Actual behavior
The program crashed with ASAN report. 

It would be so nice of you to review this bug report. Thank you again for taking the time. Any suggestions or feedback you can provide would be very helpful.

**Comment by SteveMacenski** [comment]
Hi

>  src/behaviortree-cpp-v3/src/xml_parsing.cpp

You should file with BT.CPP then. We don't have that in our repo: https://github.com/BehaviorTree/BehaviorTree.CPP

]]
