### ISSUE TITLE
obstacle layer plugin and obstacle avoidance on Turtlebot4.

### ISSUE THREAD

**Issue by Akalpita30** [ros-planning/navigation2#3889]
## Bug report

**Required Info:**

OS: Ubuntu version 22.04
ROS Distro: Humble 
Built from source
Package version: H.2.2
DDS implementation: Fast-RTPS

#### Steps to reproduce issue
The turtlebot4 and the remote computer are connected to the WiFi. I tried implementing the solutions suggested by Hilary Lou but the issue still persists.

We are running nav2. Launch.py command using- ros2 launch turtlebot4_navigation nav2. launch.py params_file:=/home/nidiab2/turtlebot_ws/configs/nav2.yamL

We are running the localization command using- ros2 launch turtlebot4_navigation localization. launch_py map:=office-july13.yamL
We are using a custom code for ir_intensity. 
We run the custom code using the command - ros2 launch tb4_ir obstacles.launch.py.

I tried implementing the solutions suggested by Hilary Lou but the issue still persists.
After doing this we observed that the robot was updating the position of small obstacles (the pink-ish), but it kept on trying to navigate through it. There were instances where the robot would back up and try to navigate through the obstacle again. I am attaching the video below showing the collision. We are unsure if there is a parameter under Nav2 that we need to configure so it does not go through.

#### Expected behavior
Turtlebot4 navigate to points and avoid and reroute around the obstacles.

#### Actual behavior
The robot detects the obstacles but it does not avoid them, instead, it crashes into it.
#### Additional information

The video 

https://github.com/ros-planning/navigation2/assets/87574208/1006ecb3-14e8-418f-882c-a4454853cda0

This is the screen of Rviz.
![image](https://github.com/Fields2Cover/Fields2Cover/assets/87574208/cd2b3b58-68cd-4230-8736-050e3f15d0be)

![image](https://github.com/Fields2Cover/Fields2Cover/assets/87574208/a68c1547-98dc-4d87-a2d0-e70296eba7f9)

This is the custom code we are using
[tb4_ir.zip](https://github.com/turtlebot/turtlebot4/files/12899776/tb4_ir.zip)

This is the nav2.yaml file.
[nav2.zip](https://github.com/turtlebot/turtlebot4/files/12899779/nav2.zip)

**Comment by SteveMacenski** [comment]
We know nothing about the TB4, what you're working on, the TB4 packages your point to, or conversations with Hilary Lou. I have no relationship with any of this. I can't speak to your customizations, configuration, etc. Please follow up with relevant folks or ask on Robotics Stack Exchange. I'm definitely not  going to download random zip files from people I don't know and open files over the internet (that's security 101).
