### ISSUE TITLE
Wrong name in NavigateThroughPosesNavigator comment

### ISSUE THREAD

**Issue by Alexbeast-CN** [ros-planning/navigation2#3890]
in [https://github.com/ros-planning/navigation2/blob/main/nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_through_poses.hpp](https://github.com/ros-planning/navigation2/blob/main/nav2_bt_navigator/include/nav2_bt_navigator/navigators/navigate_through_poses.hpp)

```cpp
/**
 * @class NavigateToPoseNavigator
 * @brief A navigator for navigating to a a bunch of intermediary poses
 */
class NavigateThroughPosesNavigator
```

`@class NavigateToPoseNavigator` should be `@class NavigateThroughPosesNavigator`

**Comment by SteveMacenski** [comment]
Fixed - thanks! In general, you can just open PRs for things like this, you don't need to file a ticket!

**Comment by Alexbeast-CN** [comment]
I'll try to open a PR next time.

Cheers!
