### ISSUE TITLE
Limiting the Width and Height of the Global Costmap in NAV2

### ISSUE THREAD

**Issue by esamet** [ros-planning/navigation2#3906]
I'm currently working on a robot project using the NAV2 package of the ROS Navigation Stack. Since my map is large and the computational resources on my system are limited, I want to limit the global costmap area to 20 meters.

Is there a way to limit the global cost map to a specific area, such as a 20x20 meter region, rather than creating it for the entire map? I would greatly appreciate any feedback, suggestions or solutions you can provide.

I tried to add width and height to the global cost map properties but it didn't work.

always_send_full_costmap: false This option also did not reduce computer resource usage

Thank you from now!

**Comment by SteveMacenski** [comment]
Please ask on Robotics Stack Exchange.
