### ISSUE TITLE
How to add functionality to navigate through poses.

### ISSUE THREAD

**Issue by VineetTambe** [ros-planning/navigation2#3919]
I want to write a plugin for navigating through poses such that the robot executes certain actions after reaching the waypoints. 
From the information available on plugins for waypoint behaviour of nav2 on the [nav2 docs page](https://navigation.ros.org/configuration/packages/nav2_waypoint_follower-plugins/input_at_waypoint.html) - [this](https://github.com/DockDockGo/ddg_waitstep_at_waypoint) is what I came up with.

But from the looks of it this only works with WaypointFollower which is not the same as navigate_through_poses?
The documentation is a little unclear on what exactly to do. It looks like I was headed in some wrong direction and the documentation to add a waypoint behaviour is either outdated or obscured.

I am having a tough time figuring out what I need to modify/add in order for nav_through_poses to do certain behaviours on reaching waypoints.

Any help would be hugely appreciated :)

**Comment by SteveMacenski** [comment]
Please ask on Robotics Stack Exchange
