### ISSUE TITLE
mppi controller test build failed.

### ISSUE THREAD

**Issue by ladianchad** [ros-planning/navigation2#3926]
## Bug report

**Required Info:**

- Operating System:
  - ubuntu 22.04
- ROS2 Version:
  - apt : ros-humble-navigation2	1.1.12-1jammy.20231005.224358
  - git : humble branch / 95b2322
- DDS implementation:
  - rmw_cyclone_dds

#### Steps to reproduce issue
```bash
sudo apt install ros-humble-navigation -y
mkdir -p nav_ws/src
cd nav_ws/src
git clone -b humble git@github.com:ros-planning/navigation2.git
cd ..
source /opt/ros/humble/setup.bash
colcon build --merge-install

```

#### Expected behavior
build success

#### Actual behavior
mppi controller test build failed.
![Screenshot from 2023-11-01 23-00-59](https://github.com/ros-planning/navigation2/assets/60467877/b839f007-ff8f-4a32-a562-90813779187b)

#### Additional information

----

**Comment by SteveMacenski** [comment]
Thanks! Will merge after CI
