### ISSUE TITLE
navfn_planner GoalOccupied exception

### ISSUE THREAD

**Issue by ladianchad** [ros-planning/navigation2#3931]
## Bug report

**Required Info:**

- Operating System:
  - 22.04
- ROS2 Version:
  - humble
- Version or commit hash:
  - source da7f85d
- DDS implementation:
  - rmw_cyclone

#### Steps to reproduce issue
send goal like below image
![Frame 4 (2)](https://github.com/ros-planning/navigation2/assets/60467877/1b6f2f45-96a4-4031-babf-2dee46065913)

#### Expected behavior
navfn throw GoalOccupied

#### Actual behavior
navfn palnner not throw GoalOccupied
#### Additional information

----

**Comment by SteveMacenski** [comment]
I don't understand this ticket. Please provide detail about the error, what you expect to happen, what is happening, and what behavior you expect. This is not verbose enough for me to understand what the issue is.

**Comment by SteveMacenski** [comment]
Closing due to lack of response and PR doesn't seem to solve a problem that I can identify. Feel free to comment here or on the PR and we can continue.
