### ISSUE TITLE
remapping after adding namespace in arguments

### ISSUE THREAD

**Issue by ipa-rar-sy** [ros-planning/navigation2#3935]
## Bug report

**Required Info:**

- Operating System:
  - ubuntu 22.04
- ROS2 Version:
  - Humble
- Version or commit hash:
  - ros-humble-navigation2	1.1.12-1jammy.20231005.224358
- DDS implementation:
  - Fast rtps
 

I am using turtlebot4 navigation packages. I want navigate 4 robots simultaneously. These robots have namespaces. i am adding namespace through arguments while launching localization and nav2 launch files. I want to remap /agent/map topic to /map topic. So that all 4 robots listen to /map topic instead of /agent_0/map, /agent_1/map.. I tried giving argument to remap while launching but it didn't work. Map server gives tf error. Can someone please tell me a solution to do this. 
Thank you in advance.

**Comment by SteveMacenski** [comment]
Please ask on Robotics Stack Exchange -- but this is a remapping problem as you identify. The actual errors you're receiving and topics being published would help you debug the problem. This seems like a pretty tractable thing to do that might just involve a few param file updates. I know users using Nav2 on Humble with multirobot simulations fine, so I know you can do it :-)
