### ISSUE TITLE
Global costmap resizing and clearing

### ISSUE THREAD

**Issue by savalena** [ros-planning/navigation2#3961]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 20.04
- ROS2 Version:
  - Foxy source
- Version or commit hash:
  - [0.4.7](https://github.com/ros-planning/navigation2/releases/tag/0.4.7)
- DDS implementation:
  - Cyclone DDS  

#### Expected behavior
When the map is increased in size (e.g. in a SLAM mode), the obstacle layer of the costmap is resized accordingly **and** it is cleared. 

#### Actual behavior
From my perspective, the costmap should preserve the information about costs and change only the size. What is initial purpose to clear obstacle layer when it's resized?

**Comment by SteveMacenski** [comment]
Resizing doesn't necessarily promise that the `map` frame of the new static map is in the same place as it once was. As a result, data in the current costmap could be in the wrong location w.r.t. the old map frame. It could be translated if the costs were known to be exact multiples of costmap resolution away, but most mapping techniques are not based on grid maps (e.g. they generate grid maps for use, but underlying data structure is very different using pose graphs and such). In that case, we have aliasing that would occur which would be worse off in the local window of updated sensor readings than just taking new sensor reading with respect to the new coordinate system. 

While for any update, we know our map transform from the updated positioning, that is a continuous coordinate system whereas the costmaps are grid-based discrete. That can cause real headaches or not necessarily represent old costs accurately that can cause problems in narrow spaces and/or when using coarse resolutions.

Does that make sense? Once a map updates using the static layer, that breaks alot of the assumptions we make in data processing layers and its better to repopulate than try to utilize it. If you don't use the static layer forcing resizes, then it wouldn't have this behavior.
