### ISSUE TITLE
do not locate themselves after rotating near the target coordinates

### ISSUE THREAD

**Issue by jisu320** [ros-planning/navigation2#3964]
**Required Info:**

- Operating System:
Ubuntu 22.04

- ROS2 Version:
humble

- Version or commit hash:
nav2_simple_commander

- DDS implementation:
  - 

It's my first time asking a question on git, so I may lack explanation.

#### Steps to reproduce issue

Below is my code written by referring to nav2_to_pose.
(https://github.com/ros-planning/navigation2/blob/main/nav2_simple_commander/nav2_simple_commander/example_nav_to_pose.py)

`from geometry_msgs.msg import PoseStamped
from nav2_simple_commander.robot_navigator import BasicNavigator, TaskResult
import rclpy
from rclpy.duration import Duration
from std_msgs.msg import String
import pygame

class Goal:
    def __init__(self):
        self.node = rclpy.create_node('goal')
        pygame.mixer.init()
    def run(self):
        self.node.create_subscription(String, 'aruco_marker_id', self.aruco_callback, 10)
        self.node.create_subscription(String, 'stop', self.stop, 10)
        rclpy.spin(self.node)
    
    def aruco_callback(self, msg):
        alert1 = '/home/jisu/robotu/src/robotu/sound/alert.mp3'
        alert2 = '/home/jisu/robotu/src/robotu/sound/alert2.mp3'
        if msg.data == '1':
            pygame.mixer.music.load(alert1)
            pygame.mixer.music.play()
            self.send_goal(-0.5, 1.8, 0.211)
        elif msg.data == '2':
            pygame.mixer.music.load(alert2)
            pygame.mixer.music.play()
            self.send_goal(0.0, 0.0, 0.0) 
        else:
            # self.node.get_logger().info(f"marker_id: {msg.data}  \n -> 등록되지 않은 마커입니다.")
            self.stop()

    def stop(self, msg):
        navigator = BasicNavigator()
        navigator.cancelTask()
    def send_goal(self, goal_x, goal_y, goal_theta):
        navigator = BasicNavigator()

        goal_pose = PoseStamped()
        goal_pose.header.frame_id = 'map'
        goal_pose.header.stamp = navigator.get_clock().now().to_msg()
        goal_pose.pose.position.x = goal_x
        goal_pose.pose.position.y = goal_y
        goal_pose.pose.orientation.w = goal_theta
        navigator.goToPose(goal_pose)
        i = 0
        while not navigator.isTaskComplete():
            self.node.get_logger().info('whileStart.')
            i = i + 1
            feedback = navigator.getFeedback()
            if feedback and i % 5 == 0:
                print('Estimated time of arrival: ' + '{0:.0f}'.format(
                    Duration.from_msg(feedback.estimated_time_remaining).nanoseconds / 1e9)
                    + ' seconds.')

                if Duration.from_msg(feedback.navigation_time) > Duration(seconds=600.0):
                    navigator.cancelTask()

                # if Duration.from_msg(feedback.navigation_time) > Duration(seconds=18.0):
                #     # goal_pose.pose.position.x = -3.0
                #     navigator.goToPose(goal_pose)

        result = navigator.getResult()
        if result == TaskResult.SUCCEEDED:
            print('Goal succeeded!')
        elif result == TaskResult.CANCELED:
            print('Goal was canceled!')
        elif result == TaskResult.FAILED:
            print('Goal failed!')
        else:
            print('Goal has an invalid return status!')

        # navigator.lifecycleShutdown()

        # exit(0)

def main():
    rclpy.init()
    goal = Goal()
    goal.run()

if __name__ == '__main__':
    main()`

#### Expected behavior

When I put the aruco marker ID 1, it moves to a specific target coordinate and displays goal success.

#### Actual behavior

The robot moved to a certain coordinate. However, it loses its position within rivz2 as it spins after arriving.

#### Additional information

I'm currently adjusting the speed because I think it's a problem that occurs a little faster.
If it is a coordinate that does not rotate, the goal success appears well.
I may not understand well because it's my first time with ros.

----

**Comment by SteveMacenski** [comment]
Ask on Robotics stack exchange, this isn't the right place for application help.
