### ISSUE TITLE
[MPPI] Acceleration constraint

### ISSUE THREAD

**Issue by emilnovak** [ros-planning/navigation2#3985]
#### Feature description
Using MPPI we encountered an issue where our robot's wheels were slipping. Limiting acceleration with velocity_smoother resulted in oversteering.  After some testing and tuning we concluded that for robots using MPPI with relatively high speed and non-negligible inertia, respecting acceleration and deceleration limits would be beneficial. Is this conclusion reasonable?

#### Implementation considerations
As mentioned in [Issue #3351 Potential MPPI Controller Improvements](https://github.com/ros-planning/navigation2/issues/3351) a new constrained motion model is needed similar to the `AckermannMotionModel` where a filter would be applied to clamp extreme acceleration values.

@doisyg, since you were tagged in #3351 for this feature, I would like to ask if you are planning on implementing this feature? My team would be happy to help realizing this feature as soon as we can.

**Comment by SteveMacenski** [comment]
Dont duplicate file tickets. As you linked to, that task is in our issue tracker already. I agree acceleration constraints would be nice. If you’re open to contributing that, please follow up there!
