### ISSUE TITLE
Controller keeps publishing command velocities after it reaches goal pose

### ISSUE THREAD

**Issue by hjorthchristian** [ros-planning/navigation2#3993]
- Operating System:
  Ubuntu 22.04
- ROS2 Version:
 Humble

I've experienced an issue while using the nav2 controllers. Wen I set a goal pose and the robot moves to the pose and suceeds, the controller, whether it is DWB or MPPI etc, it still keeps publishing the same command velocity from the instance before it reached its goal position. It is basically locked in the same command and keeps publishing it,until I either kill the terminal with the navigation launch, or I set a new pose, in which case, it will do the same after reaching this new pose. This means that even if the robot receives a new pose, after it reaches it, it repeats the behavior of publishing the same velocities endlessly.  I've sudo apt update and upgrade and it does not change the behavior seen. Any help is welcomed! Thanks  beforehand!

**Comment by SteveMacenski** [comment]
> it still keeps publishing the same command velocity from the instance before it reached its goal position. 

How are you measuring this? 

Does your robot stop at the goal pose? If so, then clearly it does not continue to publish. We have a bunch of system tests that run over realistic environments and I would have received alot of panicked issues if this was actually occurring - so I'm a bit suspicious that this actually what is happening or perhaps something is incorrect on your side.

**Comment by hjorthchristian** [comment]
If you look at the  video, you can see in the terminal that the robot suceeds to reach the goal pose, however when i echo the cmd_vel topic it clealry still publishes, and then when I kill the nav2 launch terminal, it stops publishing to cmd_vel. I can provide more videos if you need, however I beilieve you will be able to see from this video
https://github.com/ros-planning/navigation2/assets/82757713/98e136e4-f3b9-4b2e-af99-ffc70bb7829a

**Comment by SteveMacenski** [comment]
I don't think that proves what you think it proves. The robot clearly stops which means that there aren't still cmd_vel's being published - but I suppose with those tiny velocities I could be wrong. Are you sure this isn't the result of something else on your side? Can you reproduce this using our TB3 simulation demo that is the default bringup? If so, that's something actionable we can work through.

Did you test to see if the cmd_vel_nav vs other cmd_vel topics are still publishing to see  what potential node is still triggering updates? Do you see any warnings or errors about service or action call failures?

**Comment by hjorthchristian** [comment]
@SteveMacenski 

I have tested with the Turtlebot3 simulation and it worked as it should. After reaching the goal position, it stopped sending cmd_vel commands. However, the issue still happens on my physical robot.  There are only 3  that are publsihing. Those are controller_server behavior_server and velocity_smoother. The cmd_vel_nav is remapped to cmd_vel in my case.  I've attached the parameter file as a txt, since I could not upload the yaml
[nav2_params.txt](https://github.com/ros-planning/navigation2/files/13601189/nav2_params.txt)

**Comment by SteveMacenski** [comment]
And which of them is publishing? Is your physical robot still actually moving by them or is it an aberration of the CLI tools?

**Comment by SteveMacenski** [comment]
Hi - any updates? Did you find your issue?

**Comment by SteveMacenski** [comment]
Closing from non-response and lack of reports over the last 3 months from other users. I expect that this user has found their error and that's why I'm not seeing responses, thus no action for us here. Happy to reopen if others find the same issue or more information is provided!

**Comment by hjorthchristian** [comment]
@SteveMacenski 
Sorry for the late response, the last time I published a message was also the last time I was at the laboratory facilities, so I have not been able to troubleshoot anymore. So I will write when I'm back at working with the robot. Thanks for your help until now and I apologize for the late response!

**Comment by corot** [comment]
Just in case it helps anyone, I found a related problem:   velocity_smoother keeps publishing zero-velocity Twist messages for `velocity_timeout` seconds after the navigation completes.
