### ISSUE TITLE
set size_x_ and size_y_ in method initMaps

### ISSUE THREAD

**Issue by Hao-Li-Bachelorarbeit** [ros-planning/navigation2#4014]
## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

in file costmap_2d.cpp
```
void Costmap2D::initMaps(unsigned int size_x, unsigned int size_y)
{
  std::unique_lock<mutex_t> lock(*access_);
  delete[] costmap_;
  costmap_ = new unsigned char[size_x * size_y];
}
```

#### Additional information

----
#### Feature description

set size_x_ and size_y_ in this method. Since these two attributes are always used to describe costmap_, I think this information should be synchronized when initializing the map, and setting them separately causes code redundancy.

**Comment by SteveMacenski** [comment]
All uses of it now either call it using the member sizes or set the new member sizes right before the call (e.g. resizeMap). You could do the same in your application of just setting those member sizes before you call `initMaps`. But, I have no objection to this, can you submit the PR?

**Comment by Hao-Li-Bachelorarbeit** [comment]
Already submitted a PR

**Comment by SteveMacenski** [comment]
I requested a quick change, otherwise LGTM

**Comment by Hao-Li-Bachelorarbeit** [comment]
Done, please notice the PR
