### ISSUE TITLE
DriveOnHeading in SimpleCommander

### ISSUE THREAD

**Issue by Vortex-TH** [ros-planning/navigation2#4018]
I am using the Simple Commander API for Python and I'm a bit confused about something. I would just like to move my robot forward by a relative distance and there seems to be an action server for that: [DriveOnHeading](
https://navigation.ros.org/configuration/packages/bt-plugins/actions/DriveOnHeading.html). But for Simple Commander there is only [BackUp and no DriveOnHeading](https://navigation.ros.org/commander_api/index.html#overview), or am I missing something? Is there a reason why there are only commands for spinning and driving backwards, but not forward? I tried using backup with negative values, but that doesn't work.

**Comment by SteveMacenski** [comment]
It appears to be an oversight when we did a migration to abstract out the DriveOnHeading behavior. Would you be open to contributing back to the project to add that capability? You could essentially mimick the [Backup python method](https://github.com/ros-planning/navigation2/blob/main/nav2_simple_commander/nav2_simple_commander/robot_navigator.py#L268-L289) using the DriveOnHeading server / message type. They are very similar :-)
