### ISSUE TITLE
[Question]  Is it possible access global cost map with a local planner? 

### ISSUE THREAD

**Issue by GPrathap** [ros-planning/navigation2#4054]
I can access local cost map layers using `costmap_ros->getLayeredCostmap()->getPlugins()` and work with them, however, I want to get information from the global cost map for some logic. Still, I could not find a way around it except to subscribe to the global cost map.  

Is there a way to access global cost map layers or the global master cost map within the local planner in ROS2 Humble?

**Comment by SteveMacenski** [comment]
Nope, you need to subscribe to it if you want it.
