### ISSUE TITLE
[Question] How to activate and deactive subscriber in side custom nav2_behavior_tree plugin? 

### ISSUE THREAD

**Issue by GPrathap** [ros-planning/navigation2#4075]
The goal is to build a custom **nav2_behavior_tree action plugin** that leverages external data to drive real-time decision-making. I can see we can access its node by  `node_ = config().blackboard->get<rclcpp::Node::SharedPtr>("node")`

Is it possible to create a subscriber inside the nav2_behavior_tree action plugin? And how to activate and deactivate the subscriber that was created? Or it is not necessary to deactivate? 

I can do reset `subscriber_.reset()` but not sure when I should do it?

**Comment by SteveMacenski** [comment]
Yes! See `isBatteryLow` condition node for an example of that in action: https://github.com/ros-planning/navigation2/blob/main/nav2_behavior_tree/plugins/condition/is_battery_low_condition.cpp

There are no (currently) lifecycle subscriptions, so once you create it on `initialize()`, you're good to go for the lifecycle of that BT instance.
