### ISSUE TITLE
Tuning assistance for SMAC Hybrid Planner

### ISSUE THREAD

**Issue by shannonwarren** [ros-planning/navigation2#4080]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 22.04.3 LTS
- ROS2 Version:
  - Humble
- Version or commit hash:
  - master
- DDS implementation:
  - Cyclone
  
#### Actual behavior
I'm using SmacHybridPlanner as my planner and RPP as my controller with the following configs which works great for us. 
Background: We have an omnidirectional robot but since we patrol long aisles and we don't want rotations in the aisle, I'm using a min turning radius of 0.3. 

The current issue we have is, occasionally the robot, even though it reached its goal pose it passes a new path to the controller (shown in the figure) which is feasible but not desirable. I used the smac lattice planner before and didn't have the issue. I suspect that either my goal tolerance is very fine and hence the robot needs to correct or there is something in the analytic expansion ratio I'm not tuning correctly? 

> plugin: "nav2_smac_planner/SmacPlannerHybrid"
      downsample_costmap: false           
      downsampling_factor: 1              
      tolerance: 0.25                    
      allow_unknown: False               
      max_iterations: 1000000             
      max_on_approach_iterations: 1000   
      max_planning_time: 5.0             
      motion_model_for_search: "DUBIN"    # Hybrid-A* Dubin, Redds-Shepp
      angle_quantization_bins: 72         
      analytic_expansion_ratio: 3.5       
      analytic_expansion_max_length: 2.0  
      minimum_turning_radius: 0.3         
      reverse_penalty: 2.0                
      change_penalty: 0.1                
      non_straight_penalty: 1.2          
      cost_penalty: 2.5                   
      retrospective_penalty: 0.015
      lookup_table_size: 20.0           
      cache_obstacle_heuristic: false     
      debug_visualizations: false       
      use_quadratic_cost_penalty: False
      downsample_obstacle_heuristic: True
      allow_primitive_interpolation: False
      smooth_path: True

  
---------------------------------------------

> course_navigation:
>       plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
>       #Base parameter 
>       use_velocity_scaled_lookahead_dist: true
>       desired_linear_vel: 0.25
>       lookahead_dist: 1.0
>       min_lookahead_dist: 0.6
>       max_lookahead_dist: 5.0
>       lookahead_time: 1.5
>       rotate_to_heading_angular_vel: 0.2
>       transform_tolerance: 0.1
>       min_approach_linear_velocity: 0.05
>       approach_velocity_scaling_dist: 0.6
>       use_collision_detection: true
>       max_allowed_time_to_collision_up_to_carrot: 1.5
>       use_regulated_linear_velocity_scaling: true
>       use_fixed_curvature_lookahead: true
>       curvature_lookahead_dist: 0.6
>       use_cost_regulated_linear_velocity_scaling: true
>       regulated_linear_scaling_min_radius: 0.3
>       regulated_linear_scaling_min_speed: 0.05
>       use_rotate_to_heading: false
>       allow_reversing: false
>       rotate_to_heading_min_angle: 0.785
>       max_angular_accel: 0.1
>       max_robot_pose_search_dist: 10.0
>       use_interpolation: false
>       cost_scaling_dist: 0.3
>       cost_scaling_gain: 1.0
>       inflation_cost_scaling_factor: 1.0

![Screenshot from 2024-01-27 12-03-03](https://github.com/ros-planning/navigation2/assets/46359438/313044f5-0cfb-4231-8ba6-3271470afbc5)

**Comment by SteveMacenski** [comment]
0.25/0.20 aren't that tight of goal criteria to be a contributor. 

I think perhaps we should move this discussion over to that ticket if we're going down that direction.  Thus closing this ticket and moving my response over there
