### ISSUE TITLE
Smac Planner Hybrid Issue

### ISSUE THREAD

**Issue by anath93** [ros-planning/navigation2#4104]
- Operating System: Ubuntu 20.04
- ROS2 Version: Galactic
- Version or commit hash: I saw an issue previously and built the Smac planner from main to galactic.

#### Steps to reproduce issue
![image](https://github.com/ros-planning/navigation2/assets/130472005/1743de78-1a1c-4e07-ab6b-38e339328ff5)

![image](https://github.com/ros-planning/navigation2/assets/130472005/f3c90889-7fdd-44b8-b3da-d7d2471b8fe2)

![image](https://github.com/ros-planning/navigation2/assets/130472005/ce8c6de4-9cf3-4414-bddf-23c1f037e0ad)

#### Expected behavior

The planner should re-route by seeing the obstacle when raytrace is in range. 

#### Actual behavior

It keeps computing ending up burning in the bin, its diff drive robot. But it does stop and says collision detected and goes in recovery mode.

**Comment by SteveMacenski** [comment]
Its unclear from your diagram: is that present in the global costmap used for planning or the local costmap used for control, or both? 

That's doesn't look like a lethal obstacle to me (yeah?), that's just a higher cost region as evidenced that there is no inflation around it. The cost functions weight distance with cost, so in this situation, it was better to go through 1-2 cells of higher cost than to diverge dozens.

**Comment by anath93** [comment]
Yes it is present in the global costmap, and its not lethal, as you said higher cost but shouldn't Smac Hybrid planner plan around it  based on the cost penalty with conjunction of global costmap ?
This is my below global and local costmap setup so far, 
![image](https://github.com/ros-planning/navigation2/assets/130472005/8d2d03b2-87af-4536-a861-fef2334d50a5)
![image](https://github.com/ros-planning/navigation2/assets/130472005/b673aed2-83dd-49af-b032-b676fd173e8b)
![image](https://github.com/ros-planning/navigation2/assets/130472005/1fb6b699-15f7-4eea-86be-ae25fd73a6ed)

**Comment by SteveMacenski** [comment]
> Yes it is present in the global costmap, and its not lethal, as you said higher cost but shouldn't Smac Hybrid planner plan around it based on the cost penalty with conjunction of global costmap ?

Not necessarily, there are trade offs beyond just cost, like shortest length. We couldn't want a robot necessarily to add 100m to a path to stay in `0` cost space over entering 1 cell that is `1` cost, right? So we need to decide on a trade off between minimum length and reasonable cost to travel. We do that with the traversal function of `cost_to_travel = cell_length * (1.0 + cost / 254 * weight)`. That makes us balance the cost to travel by both the length of the primitive with the normalized, weighted cost. A higher cost weight would make traveling in higher cost spaces more expensive. [Figure 5 of this paper](https://arxiv.org/pdf/2401.13078.pdf) highlights how the change in cost penalty changes behavior.

Looking at your example, it seems like the extra ~+2m to go around it isn't proportionate to the extra cost from such a small obstacle (its only 1-2 pixels thick). I might expect a different result if your virtual obstacle there was filled. What you show is more or less expected and good behavior. If you wanted that are to be not traversed at all, you should mark it with lethal cost via whatever custom mechanism you've added that with

Note: In general, please don't post pictures of parameters, include them as code snippets for the sections that are important. But also note that nothing you showed is really relevant.
