### ISSUE TITLE
Dev Docker Build - Package Not Found Error for ros-rolling-foxglove-bridge

### ISSUE THREAD

**Issue by alanxuefei** [ros-planning/navigation2#4120]
## Bug report
The ros-rolling-foxglove-bridge package does not exist. Therefore, the Docker build in the main (rolling) branch will fail. Should we append true at the end of the code as shown below?
```
# Install foxglove dependencies. If the package cannot be found or installed, the command will not fail due to the '|| true' at the end.
RUN apt-get update && \
    apt-get install -y --no-install-recommends ros-$ROS_DISTRO-foxglove-bridge || true
```

![Screenshot 2024-02-17 191415](https://github.com/ros-planning/navigation2/assets/7146994/2c0c885f-d3ee-4a15-b594-3398e1d156d8)

**Required Info:**

- Operating System:
  - VSCode is running an Ubuntu container on Windows
- ROS2 Version:
  - Rolling 
- Version or commit hash:
  - Unknown 
- DDS implementation:
  - Unknown 

#### Steps to reproduce issue
* Build the docker using master branch in VScode, 
* Or attempt to install the “ros-rolling-foxglove-bridge” package using the command “apt-get install -y --no-install-recommends ros-rolling-foxglove-bridge”.

#### Expected behavior
The "ros-rolling-foxglove-bridge" package should be installed successfully.

#### Actual behavior
The system is unable to locate the "ros-rolling-foxglove-bridge" package, resulting in an error.

#### Additional information
The error occurs during the execution of an "apt-get install" command in a Dockerfile.

**Comment by SteveMacenski** [comment]
Ask on Robotics Stack Exchange or Foxglove docs - sorry, just because we have the docker tutorial doesn't mean that we're going to be able to answer every question or fix every issue with all ROS related libraries and Docker.
