### ISSUE TITLE
No way of decreasing costmap costs over time?

### ISSUE THREAD

**Issue by Victorsoeby** [ros-planning/navigation2#4149]
I am playing with the costmap_2d package, where i am using the inflation and static layer to successfully create a costmap from various sensors, to see where i can drive my robot. I am not using a Lidar or depth-camera, and will therefore not be working with the raytracing algorithms. 

My question is: Is there really no way to have the costmap slowly decay the costs of every cell every x seconds? This means that i am currently unable to clear obstacles (and false sensor readings) that occur once in a while. I am thinking of modifying the source code, to have a timer proc at a fixed interval and substract 1 or 2 from the cost of every cell.

**Comment by SteveMacenski** [comment]
Its up to you to manage the costmap data; if you would like to temporally decay data, then your layer should do that.
