### ISSUE TITLE
Occasional BT Navigator segfault

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#417]
Seems to happen in the spin loop at shutdown, but more investigation needed to characterize the problem.

**Comment by orduno** [comment]
I had multiple segfaults yesterday, all pointing to the DDS layer. I wonder if it's an issue of the particular DDS implementation we're using (eProsima Fast RTPS).

At some point we should test [other implementations](https://index.ros.org/doc/ros2/DDS-and-ROS-middleware-implementations/). 

On a related topic, when debugging we can also use the [DDS tools and ecosystem](https://www.rti.com/blog/ros2-dds-when-ecosystems-merge).

**Comment by orduno** [comment]
Here's a different segfault.
![segfault6](https://user-images.githubusercontent.com/39749557/49691962-dc571100-fb02-11e8-869c-5f1725b6d69b.png)

**Comment by crdelsey** [comment]
Enable BT by default

**Comment by crdelsey** [comment]
This segfault doesn't seem to occur anymore. We'll close this after more testing.

**Comment by mkhansen-intel** [comment]
Can we close this now?
