### ISSUE TITLE
What is the purpose of using the 'next_to_last_length_ratio' in constarint smoother

### ISSUE THREAD

**Issue by Youhaochan** [ros-planning/navigation2#4201]
I was lookint at the code in the nav2 constraint smoother and had some questions about the "addSmoothingResidual" function. I noticed that , 'next_to_last_length_ratio_' muptiply the term (p_next - p_t). I'm unsure about the rationale behind this ratio
Additionally, I observed that while constraint smoother appears to be effective for paths with both forward and reverse segments, the smooth cost calculation using the equation fcost = (p_next - p_t) - (p_t - p_last) may not be suitable for cases where there are cusps, as it could result in a significant cost. Could you please elaborate on how your smoother handles such scenarios?

**Comment by SteveMacenski** [comment]
See where its populated: https://github.com/ros-planning/navigation2/blob/12292d17c5db73b1fb387d30c0c426415ff2defe/nav2_constrained_smoother/include/nav2_constrained_smoother/smoother.hpp#L227

It represents the cost with proximity to a cusp.
