### ISSUE TITLE
Use of Nav2 Stack and Commander API without AMCL , with just odometry data

### ISSUE THREAD

**Issue by alvikag** [ros-planning/navigation2#4208]
Hi,
I want to test Nav2 for teach and repeat with just odometry data without building a map. Basically, I want to collect a series of waypoints indoors using odometry data and then start from same position and traverse the waypoints autonomously as a test case without worrying about obstacles and map (just want to test the nav2 controller and different waypoint behaviours). Is it possible to use the commander API for this or does it expect to have  a map?
I am not sure what changes to make to nav2_params.yaml file and if it requires a lot of changes. I have a vehicle equipped with a zed camera to record odometry

## Bug report

**Required Info:**

- Operating System:
  - 
- ROS2 Version:
  - 
- Version or commit hash:
  - 
- DDS implementation:
  - 

#### Steps to reproduce issue

```

```

#### Additional information

----

**Comment by SteveMacenski** [comment]
This is not a bug or feature request, please ask on Robotics Stack Exchange.
