### ISSUE TITLE
[humble-MPPI] Bug in path align critic

### ISSUE THREAD

**Issue by Chortine** [ros-planning/navigation2#4230]
https://github.com/ros-planning/navigation2/blob/1ff1303537dfaceaa953faff7530febace585f83/nav2_mppi_controller/src/critics/path_align_critic.cpp#L97C1-L100C24

I think it misses a `path_pt = 0;` here.

**Comment by SteveMacenski** [comment]
Correct, I found and fixed that in my 45% performance boost PR but hasn't trickled down to Humble yet. If you file a PR for Humble to make that temp fix, happy to merge!

**Comment by SteveMacenski** [comment]
https://github.com/ros-planning/navigation2/pull/4272
