### ISSUE TITLE
BehaviorTreeEngine 

### ISSUE THREAD

**Issue by ajjaya18** [ros-planning/navigation2#4235]
[bt_navigator-53] [WARN] [1712092264.539138354] [BehaviorTreeEngine]: Behavior Tree tick rate 100.00 was exceeded!

Hi, I have this out in my terminal, can you help me please?
I have been workin with turtlebot4 simulator and I'm having this

**Comment by SteveMacenski** [comment]
Please ask on robotics stack exchange or properly file an issue with the provided template you deleted.
