### ISSUE TITLE
Robot stabilization on recovery behavior

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#425]
When the robot bumps into objects it might tilt or oscillate. For now, the `Stop` motion primitive waits for a fixed amount of time to allow for it to settle down, however, we might want to actively monitor this state and vary the wait time. Perhaps also do active stabilization.

**Comment by mkhansen-intel** [comment]
Most robots have an IMU so you can use the accelerometer and gyro to make sure the robot motion has stabilized. by subscribing to the IMU topic and looking at the acceleration values in linear and angular terms. If an IMU isn't available, then default to a time-delay as a backup case.

**Comment by crdelsey** [comment]
This could be a pause type BT node or a node that just waits for IMU stabilization

**Comment by SteveMacenski** [comment]
Is this still a ticket to review? The stop recovery is gone

**Comment by mkhansen-intel** [comment]
I think we should close it
