### ISSUE TITLE
[WIP] Add amcl's service request to robot class

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#427]
#### Feature description

Add global localization and no motion update service request to robot class.  This is the first step to create robot's selfLocalization method.

**Comment by mkhansen-intel** [comment]
Can you explain a little better what this means?  Why does the robot need a self.localization method?

**Comment by mkhansen-intel** [comment]
Labeling this medium priority for now but not clear to me what this will really do differently than what we have today.

**Comment by mhpanah** [comment]
Addressed in #503 #504.
