### ISSUE TITLE
Long delay between issuing goal pose and robot starting to move

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#446]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04 -->
- Installation type:
  - source (release and debug builds)
- Version or commit hash:
  - 5f6c2c41d4905f (Dec 7, 2018
- DDS implementation:
  - Fast RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue
Set a nav goal in RVIZ

#### Expected behavior
The robot moves to that location

#### Actual behavior
It can take up to 4 seconds on my computer before the robot starts to take action. No significant difference is seen between a debug vs a release version of the nav stack

### Additional Info
Test system:
4-Core  Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz Hyperthreading enabled
32 GB RAM
1Gbps ethernet

**Comment by mkhansen-intel** [comment]
Can you add what your hardware computer is? Are you running on an Atom or Core CPU? We need to ID what our standard minimum platform should be and benchmark performance issues on that. But for now, let's just document what platform we ran on for reproducing it.

**Comment by crdelsey** [comment]
I added the machine info. I probably had the static_transform_publishers running at the time, which could have taken up 2 cores worth of CPU.

**Comment by crdelsey** [comment]
I still see the delay without the static_transform_publishers running.

I think the delay happens at the planner stage. Might be because we Djikstra by default instead of A*

**Comment by crdelsey** [comment]
@orduno Has indicated that there is sometimes a long delay in Simple Navigator, so it could be the problem is there instead of in navfn.

**Comment by orduno** [comment]
As described in #540, I see the issue when using the `bt_navigator` and not with the default simple navigator. So the issue might be related to the creation of the behavior tree every time we send a goal pose.

**Comment by mkhansen-intel** [comment]
@crdelsey - do we still see this issue?

**Comment by crdelsey** [comment]
I don't know. I have no reason to believe it is fixed, though. If it still exists, it might be worth trying it with a release build. At the time I filed this, I think I was running debug builds mostly.

**Comment by crdelsey** [comment]
In my testing today, I still see this problem.

**Comment by crdelsey** [comment]
Problem has gone away
