### ISSUE TITLE
Change function name get_event_param() in DynamicParamsClient class

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#484]
Per discussion in PR #464, the function `get_event_param()` in the `DynamicParamsClient` class is a misnomer since the dynamic parameters are retrieved from the internal parameter map and not directly from the event message (though new events will replace values in internal map) and can be accessed outside of the an event & user callback. The name could be changed to `get_parameter()` to conform with the terminology in the node and parameter client classes.

**Comment by crdelsey** [comment]
No longer applicable
