### ISSUE TITLE
DWB trajectories are not properly aligned with robot

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#514]
## Bug report

**Required Info:**

- Operating System:
  - 
- Installation type:
  - 
- Version or commit hash:
  - Latest on master as of Jan 4, 2019
- DDS implementation:
  - 
- Client library (if applicable):
  - 

#### Steps to reproduce issue
Have robot navigating around map with local planner trajectories displayed.

#### Expected behavior
The fanout of trajectories should be front and back of the robot. Those are the only valid possibilities given the kinematic constraints of the turtlebot.

![image](https://user-images.githubusercontent.com/39749483/50716159-38934f00-1035-11e9-8dc6-5d03f7e0996e.png)

#### Actual behavior
Instead, sometimes the fanout of trajectories sticks out the side of the robot.

![image](https://user-images.githubusercontent.com/39749483/50716114-f0742c80-1034-11e9-9fbe-7aa10dee4b71.png)

**Comment by SteveMacenski** [comment]
That laser scan also looks suspect, from where the robot is shown to be located, the lasers arent where they should be (it's seeing part of the lower right pillar that is unviewable from its angle and missing huge amounts of things that are)

Might be a syncing issue

**Comment by crdelsey** [comment]
@SteveMacenski With the version of Rviz I'm using (latest as of a few weeks ago), laser scans mostly don't display properly due to lack of message filter support in Rviz; the same problem we had with AMCL originally.

99.9% of the laser scans fail to transform, so, if they manage to ever get displayed at all, they rapidly go out of date.

Hopefully, rviz re-enables message filters now that it is part of crystal.

**Comment by crdelsey** [comment]
It looks like the `odom` messages getting published by Gazebo are noisy. Frequently, the odom message has a `y` component to the velocity. That `y` component gets added in to all the possible trajectories DWB can achieve, because, as far as it is concerned, it is slipping sideways and those trajectories reflect its reality.

The result is that the trajectories all fan out to the side in the direction of that `y` component.

At times the `y` component published by Gazebo exceeds the maximum velocity of the robot, leaving no headroom for any remaining X velocity. When this happens, DWB cannot generate any trajectories and it fails with the error shown in #441.

I believe DWB is behaving properly and the real fix needs to be done in the gazebo code that generates `odom` messages.

**Comment by SteveMacenski** [comment]
Ah, I've seen that behavior before when I've messed up URDF/TF/frames when building custom robots before (simulation results for controllers using bad frames and then the calculated components are weird). make sure your navigation configurations are correct looking at the right frames and the URDF make sense

**Comment by crdelsey** [comment]
Thanks for the suggestion. I'll have to dig in to the turtlebot description to see exactly what is going on here, it seems.

**Comment by mkhansen-intel** [comment]
@crdelsey - are you still seeing this issue?

**Comment by crdelsey** [comment]
Yes. Still a problem. I have to put together some data again to file an issue upstream.

**Comment by mkhansen-intel** [comment]
Believe this to be a simulation only problem.

**Comment by crdelsey** [comment]
Upstream issue ROBOTIS-GIT/turtlebot3_simulations#75
