### ISSUE TITLE
Enable obtaining robot pose from TF tree

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#518]
In some situations we might need more often approximations of the robot pose (such as with `MotionPrimitives`, see #516) .

It's a bug (at least on the Primitives) since we see the following behavior:
- Send a request to backup *x* distance.
- The controller will compare the initial position with *x* and start moving the robot.
- The controller will run through several cycles of comparing the actual position with *x*.
  - However, since the pose is coming from AMCL, it might not be updated recently.
- After a few cycles, the pose is updated and possibly we overshoot the desired position.

**Comment by mkhansen-intel** [comment]
@orduno - is this a bug or an enhancement request? If it's a bug, can you explain what is failing?
