### ISSUE TITLE
Considerable delay from the time the goal provided to start of planning

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#540]
## Bug report

**Required Info:**

- Operating System: Ubuntu 16.04
- Installation type: from source
- Version or commit hash: head of master
- DDS implementation: Fast-RTPS

#### Steps to reproduce issue
- Launch gazebo, rviz and navstack (with bt_navigator)
- Provide robot initial pose in rviz
- Provide goal pose in rviz

#### Expected behavior
Once goal pose is provided, planning should happen almost immediately. 

#### Actual behavior
There is a considerable delay between the time the goal pose is sent and the time the `navfn_planner` starts planning.

#### Additional information
This could be related to the creation of the behavior tree since the delay is not noticable if using `nav2_simple_navigator`.

**Comment by crdelsey** [comment]
May be related to #446

**Comment by mkhansen-intel** [comment]
@orduno - do we have root cause on this issue yet?

**Comment by orduno** [comment]
Let's test it again once we get lifecycle in.

**Comment by crdelsey** [comment]
@orduno Do you still see this? I think it is gone now.

**Comment by SteveMacenski** [comment]
I dont think this has been an issue within recent memory (and my memory is bad)
