### ISSUE TITLE
Multi-layer maps: map server and data structures design

### ISSUE THREAD

**Issue by gbiggs** [ros-planning/navigation2#547]
Relates to #392.

Design a map server and the necessary data structures, APIs and messages to allow a single map server to provide multi-layered maps, with the maps overlaying each other in space and providing different information (one example given is traffic flows to allow robots to avoid crowded areas).

**Comment by SteveMacenski** [comment]
After discussions with Geoff, we decided this was out of scope for navigation. This was in reference to analogs in autoware for having multi-layered maps for things like stop signs, lane labeling, etc that we don't really use in this context. This isn't covering the use of sharded maps overlaying into 1 consistent map for navigation, which you can do right now with multiple static layer plugins for each exposed map.
