### ISSUE TITLE
Map server providing dynamically-generated maps

### ISSUE THREAD

**Issue by gbiggs** [ros-planning/navigation2#549]
Relates to #392.

Enhance the map server to allow it to dynamically generate maps at runtime and serve them. The map server may be merging multiple different map data sources into a single map (single- or multi-layer) based on processing the data when it is loaded and combining the results in some way, for example.

An example use case is a map that contains a traffic layer, where the traffic data is updated from an external source regularly.

Another example use case is the local cost map, which is an application of this idea. (Or, conversely, this idea is a generalisation of how the costmap currently works.)

The map server may need to announce changes in the map to other nodes using the data.

**Comment by SteveMacenski** [comment]
I think this is sufficiently covered by #547 and #548
