### ISSUE TITLE
Implement ROSRobot functionality

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#55]
Right now ROSRobot is an empty shell class with no functionality. It needs to be defined and implemented or the code should be removed.

**Comment by mjeronimo** [comment]
This is a duplicate of #22 "Define Robot class and interface"

**Comment by mkhansen-intel** [comment]
I thought the other one was definition / design and this is implementation, however I'm fine with closing if the other one will cover this.
