### ISSUE TITLE
Navfn planner might be backtracing the path twice.

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#573]
The `nav2_navfn_planner` is based on a wavefront planner that first calculates a potential (using the costmap) and then backtraces finding the lowest gradient to extract the path.

The backtracing of the path seems to be executed twice.

First here:
https://github.com/ros-planning/navigation2/blob/178c7c6ce4aa3ea58189302e1287d44f800543cd/nav2_navfn_planner/src/navfn_planner.cpp#L236

Then when actually retrieving the plan here:
https://github.com/ros-planning/navigation2/blob/178c7c6ce4aa3ea58189302e1287d44f800543cd/nav2_navfn_planner/src/navfn_planner.cpp#L363

Since `calcNavFnAstar()` calls `calcPath()` internally. However, it could be that most of the backtracking is skipped in `calcPath()` if we already have one, but it's not obvious on the code. 

In general, it seems we should make the following improvements:
1) Calculate the potential only when the (global) costmap is out of date, i.e. rarely if we are only using the costmap with only static map info, and sometimes for obstacle layer enabled costmap).

2) If costmap was not updated, then we only provide the new current location and backtrace the path from there (call `calcPath()`), otherwise compute the new potential and backrace (call `calcNavFnAstar()` only).

Lastly, this possible bug is also found on `move_base`.

Here:
https://github.com/ros-planning/navigation/blob/66fba702f6ac79ba9386f22d4bbc1e0f50afb5f6/navfn/src/navfn_ros.cpp#L264

and here:
https://github.com/ros-planning/navigation/blob/66fba702f6ac79ba9386f22d4bbc1e0f50afb5f6/navfn/src/navfn_ros.cpp#L399

**Comment by SteveMacenski** [comment]
@orduno can you elaborate on this? I can probably help out if we think this is an issue.

**Comment by orduno** [comment]
@SteveMacenski I've updated the issue description with more information about the possible bug.

**Comment by shivaang12** [comment]
@orduno is this still an issue? I can help if it is.

**Comment by SteveMacenski** [comment]
This is still an issue, we're not 100% sure that its happening but from glancing over again, I'm about 80% sure it is. 

Feel free to submit a PR
