### ISSUE TITLE
Remove `stop` motion primitive, make a method on the robot class

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#575]

**Comment by SteveMacenski** [comment]
@orduno given the robot class is now a util, do you think that should still apply? It could simply use the `PublishVelocity` util with an empty twist message, but I could wrap that if you like.

Else maybe this ticket is closed. Let me know :)

**Comment by crdelsey** [comment]
@SteveMacenski 
> but I could wrap that if you like

I like the idea of wrapping the stop command for code readability, but I think we can close this issue when your PR gets merged.

**Comment by orduno** [comment]
Closing this issue as #725 removes the `stop` motion primitive.

Basically, with the new ROS2 actions, the dwb controller will send a stop command whenever its action command is canceled. This occurs when the followPath bt action node is halted.
