### ISSUE TITLE
Create MissionPlan message type

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#58]
Right now the Mission Plan message is defined as a string.src/mission_execution/nav2_mission_execution_msgs/msg/MissionPlan.msg

We need a real Mission Plan, whether that is an array of actions or something else is not clear yet.

**Comment by mjeronimo** [comment]
We agreed in the Navigation WG meeting on 11/1/2018 that it is acceptable to continue to use a string for the mission plan message (which will be used to communicate from a client, like a BT GUI to the Mission Executor, both of which will be off of the robot).
