### ISSUE TITLE
Remove logger.h from dijkstra planner directory

### ISSUE THREAD

**Issue by mkhansen-intel** [ros-planning/navigation2#60]
We shouldn't need this file. Include rclcpp.hpp and use rclcpp::get_logger() instead
src/planning/nav2_dijkstra_planner/src/Logger.h

**Comment by mjeronimo** [comment]
Doesn't seem like a bug to me in that it doesn't affect the functionality of the program. Perhaps we could have a tag that specifies that something should be addressed before release (FixForRelease, or something). This could apply to bugs and non-bug items.

**Comment by mkhansen-intel** [comment]
I'll change it to a task instead.

**Comment by mkhansen-intel** [comment]
Mike thanks for doing this!

Fixed in PR #100
