### ISSUE TITLE
Update "Ignore Y oscillation on robots not capable of Y velocity"

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#603]
PR #588 has some unfinished work that needs to still be done

- [ ] Ensure default critic scale parameters are being set and used correctly in the code. We shouldn't need to set them in the params.yaml file unless we want to change it from the default.
- [ ] Work with upstream DWB to ensure the Y oscillation problem is fixed there as well
- [ ] Add parameters to the oscillation critic to allow the user to choose which axes will be considered for oscillation detection
- [ ] Generalize the existing mechanism to all axes.

**Comment by mkhansen-intel** [comment]
@crdelsey -Is this fixed by #674?

**Comment by crdelsey** [comment]
Not entirely. #674 would fix bullets 3 and 4 above but not 1 and 2.
