### ISSUE TITLE
Random Crawl

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#631]
## Feature request
Random Crawl
#### Feature description

Utilizes Reinforcement Learning to make turtlebot 3 to randomly crawl around without hitting any obstacles.

- Have already implemented this task internally. Will need to bring it out to our repo.

- Random Crawl can be used as:
   1. Map exploration
   2. Localization test
   3. System test
   4. Tutorial to enable RL for different tasks

**Comment by SteveMacenski** [comment]
Is this based on the turtlebot3 DQN tutorial? I had just run across that and seemed similar. If you hadn't seen it, another good reference implementation 

Link: http://emanual.robotis.com/docs/en/platform/turtlebot3/machine_learning/#machine-learning

**Comment by mhpanah** [comment]
> Is this based on the turtlebot3 DQN tutorial? I had just run across that and seemed similar. If you hadn't seen it, another good reference implementation
> 
> Link: http://emanual.robotis.com/docs/en/platform/turtlebot3/machine_learning/#machine-learning

Yes, I've seen this and it's a great tutorial.  The random crawl is currently also using DQN, however the implementation is slightly different.
