### ISSUE TITLE
ROS2 navigation cannot avoid obstacles while set goal from A to B.

### ISSUE THREAD

**Issue by rafaelhuang-intel** [ros-planning/navigation2#660]
## Bug report

**Required Info:**

- Operating System:
 Ubuntu18.04
ROS2 / Master branch
#### Steps to reproduce issue
1. launch navigation2
2. set initial pose A
3. set goal B
4. set obstacle on A to B path
 
Expect result:
ROS2 navigation can avoid obstacles while set goal from A to B.
Actual result:
ROS2 navigation cannot avoid obstacles while set goal from A to B.

**Comment by rafaelhuang1021** [comment]
![navigation cannot avoid obstacles while set goal from A to B](https://user-images.githubusercontent.com/49666471/56179495-7e9a7e80-6038-11e9-8337-836783d7e345.jpg)

**Comment by rafaelhuang1021** [comment]
![navigation cannot avoid obstacles while set goal from A to B](https://user-images.githubusercontent.com/49666471/56179730-6aa34c80-6039-11e9-93d0-d2b463a26fe8.gif)

**Comment by mkhansen-intel** [comment]
I don't see the obstacle showing up in the costmap layer.  How tall is the object? If you stand in front of the robot, do you show up in the costmap layer in RVIZ?

**Comment by mkhansen-intel** [comment]
I see that you haven't enabled the LaserScan plugin, can you turn that on to see if laser scans are being received?

One way to check from the command line is:
```
ros2 topic hz /scan
```

**Comment by rafaelhuang-intel** [comment]
hi matt, for your question:
1. If I stand in front of the robot, I'm not show up in the costmap layer in RVIZ
2. laser scan date can received after send goal from initial pose to point B

![laser_date](https://user-images.githubusercontent.com/49666471/56416021-3098ab80-62c2-11e9-8077-b95934667d30.gif)

intel@intel-desktop:~/turtlebot3$ ros2 topic hz /scan
average rate: 30.294
	min: 0.030s max: 0.036s std dev: 0.00080s window: 32
average rate: 30.295
	min: 0.030s max: 0.036s std dev: 0.00058s window: 63
average rate: 30.297
	min: 0.030s max: 0.036s std dev: 0.00049s window: 94
average rate: 30.297
	min: 0.030s max: 0.036s std dev: 0.00043s window: 125
average rate: 30.300
	min: 0.030s max: 0.036s std dev: 0.00040s window: 156
average rate: 30.304
	min: 0.030s max: 0.036s std dev: 0.00039s window: 187
average rate: 30.304
	min: 0.030s max: 0.036s std dev: 0.00036s window: 218
average rate: 30.304
	min: 0.030s max: 0.036s std dev: 0.00034s window: 249
average rate: 30.304
	min: 0.030s max: 0.036s std dev: 0.00032s window: 280
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00031s window: 311
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00030s window: 342
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00028s window: 373
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00027s window: 404
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00026s window: 435
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00026s window: 466
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00025s window: 497
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00024s window: 528
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00024s window: 559
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00023s window: 590
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00023s window: 621
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00022s window: 652
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00022s window: 683
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00022s window: 714
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00021s window: 745
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00021s window: 776
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00021s window: 807
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00020s window: 838
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00020s window: 869
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00020s window: 900
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00020s window: 931
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 962
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 993
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 1024
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 1055
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 1086
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00019s window: 1117
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1148
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1179
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1210
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1241
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1272
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00018s window: 1303
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1334
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1365
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1396
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1427
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1458
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1489
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1520
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00017s window: 1551
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1582
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1613
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1644
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1675
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1706
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1737
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1768
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1799
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1830
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1861
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1892
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00016s window: 1923
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 1954
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 1985
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2016
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2047
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2078
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2109
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2140
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2171
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2202
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2233
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2264
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2295
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2326
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2357
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2388
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2419
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2450
average rate: 30.303
	min: 0.030s max: 0.036s std dev: 0.00015s window: 2481

**Comment by mkhansen-intel** [comment]
> 1. If I stand in front of the robot, I'm not show up in the costmap layer in RVIZ

We need more information, as again we don't see this issue where objects aren't showing up in the costmap layers.  If I stand or put and object in front of the robot (or the side or behind for that matter), we see it show up. I will post a screenshot.

**Comment by mkhansen-intel** [comment]
Can you tell me what checkboxes are enabled in your RVIZ window? If you can attach your rviz config file that would be even better.

**Comment by mkhansen-intel** [comment]
Here is a screenshot with the path the robot took to avoid obstacles on the map and navigate from A to B. I am running this with all the latest changes in the PRs, which we'll merge ASAP. As you can see the robot sees and avoids boxes, people and other robots. 
![Uploading Screenshot from 2019-04-19 16-38-30.png…]()

This is in simulation but we'll also post a video or screenshot(s) from running on the physical turtlebot3 in the lab.

**Comment by mkhansen-intel** [comment]
![Screenshot from 2019-04-19 16-38-30](https://user-images.githubusercontent.com/12618239/56448959-dcdd9080-62c8-11e9-87c7-4ad24b8ad5d5.png)

**Comment by mkhansen-intel** [comment]
Here's our lab setup. Notice when we created the map there were no obstacles
![20190419_175817](https://user-images.githubusercontent.com/12618239/56462904-d6f6b680-637f-11e9-91a8-de4f1be50115.jpg)

![20190419_175808](https://user-images.githubusercontent.com/12618239/56462905-deb65b00-637f-11e9-82be-7b4dfb1c4490.jpg)

And here is the turtelbot3 navigating around an obstacle (a box) we put in the center of the map after it was created.

https://photos.app.goo.gl/8yVpVbSig9GjagAu6

**Comment by LeonJung** [comment]
@mkhansen-intel 

what I'm doing also shows same results as @rafaelhuang-intel said; seems like local costmap is not being drawn on the map. 

it just pushed anything on the road away, nothing changed on its path.

so does any current PRs that have any solutions for this?

**Comment by crdelsey** [comment]
@LeonJung 

We found out that the problem @rafaelhuang-intel ran into was caused by running the turtlebot 3 provided launch script with default options. ie. `ros2 launch turtlebot3_navigation2 navigation2.launch.py`

This script is using the navigation 2 parameters provided by Robitis. These parameters are a bit out of date with the latest improvements we've made in the navigation stack. Most importantly, they do not turn on obstacle detection. The latest set of parameters we've been using for Turtlebot 3 are located here: https://github.com/ros-planning/navigation2/tree/master/nav2_bringup/launch/nav2_params.yaml

You can use these latest parameters either by using the navigation 2 bringup scripts in the nav2_bringup package. See documentation here: https://github.com/ros-planning/navigation2/tree/master/nav2_bringup. Or you can use the params option provided by Robotis' launch script. ie
`ros2 launch turtlebot3_navigation2 navigation2.launch.py params:=<path to nav2_bringup/launch/nav2_params.yaml`

Please let us know if that solves your problem.

**Comment by LeonJung** [comment]
@crdelsey 

Great, now it works!

**Comment by mkhansen-intel** [comment]
@rafaelhuang-intel - can you verify this works for you and if so close this issue?

**Comment by rafaelhuang-intel** [comment]
@mkhansen-intel @crdelsey  Now it works, thanks for all, this issue closed.

**Comment by rafaelhuang-intel** [comment]
@mkhansen-intel could help to merge above command line to tutorial?

**Comment by mkhansen-intel** [comment]
Actually the command in our nav2_bringup is already correct, if you use our nav2_bringup the nav2_params.yaml file is used by default.
