### ISSUE TITLE
Remove "Unpadded" term from costmap_2d_ros function names?

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#688]
Should the 'Unpadded' term be removed from the costmap_2d_ros function names? For example, setUnpaddedRobotFootprint could be setRobotFootprint. It seems 'Unpadded' was included to specify that you could set the footprint value before the footprint_padding was applied.

**Comment by SteveMacenski** [comment]
I think that would be fair :+1:

**Comment by crdelsey** [comment]
Is this still relevant?

**Comment by crdelsey** [comment]
This may already be done. Investigate.

**Comment by bpwilcox** [comment]
This has been done
