### ISSUE TITLE
Wiki page for detailing defaults of parameters and/or recommended values 

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#690]

**Comment by crdelsey** [comment]
There was some push back in the working group on using the wiki for documentation. The suggestion was to use the same mechanism that OSRF is using for ROS 2 documentation or [Read the Docs](https://readthedocs.org/). I think in the meantime, just adding a markdown file in our docs directory is the way to go

**Comment by SteveMacenski** [comment]
This would also be the Wiki built into the repository as well. Read the docs would be great as well.

**Comment by crdelsey** [comment]
Dupe of #1305
