### ISSUE TITLE
Proposal: Rethink nav2_tasks

### ISSUE THREAD

**Issue by SteveMacenski** [ros-planning/navigation2#703]
See headers here (https://github.com/ros-planning/navigation2/tree/master/nav2_tasks/include/nav2_tasks)

There's alot of stuff going on here really breaking any concept of encapsulation across the repo. If I recall correctly, this started with some header files to replace actions while they weren't available. 

Then we added the eq. of [nav_core](https://github.com/ros-planning/navigation/tree/melodic-devel/nav_core/include/nav_core) which also makes sense to have a plugin-able interface for the necessary `move_base` plugins. Today, we're architecting things to look like individual servers rather than plugins. Having a common interface for a `planner` or `controller` is still necessary - subscribe to these things, publish these other things, here's some parameters you might care about.

Looking through this list now, it continues to grow and it covers everything and unclear how those pieces should be used for an end-user / someone trying to create their own application on top of the navigation2 metapackage. Frankly when trying to follow this myself I'm confused (we have a spin recovery, wait there's a spin action here? why is there something called a spin task that's just `typedef`-ing things? why aren't these just part of the recovery? is a templated command/result necessary (maybe)?)

 Looking back at all the components in [Navigation](https://github.com/ros-planning/navigation) after you learn a little about robotics you can look at this metapackage and kind of understand how the pieces come together, and then you look at `nav_core` for hints of places where you can easily add your application without breaking the rest of the ecosystem. I'd like to see something like that again. 

I'd like to open a discussion here about how to simplify or break this up. With a **strong** preference to simplification.

**Comment by crdelsey** [comment]
nav2_tasks is already getting broken up due to the transition to actions, but I think the larger issue of cleaning up the architecture, encapsulation, naming and directory structure are still valid.

I think we've finally reached the point where the nav2 stack is working well enough to use, so taking a step back to clean things up makes sense at this point
