### ISSUE TITLE
behaviortree_cpp dependency

### ISSUE THREAD

**Issue by facontidavide** [ros-planning/navigation2#749]
It was reported that behaviortree_cpp is blocking the release of navigation2 on Dashing.

https://github.com/BehaviorTree/BehaviorTree.CPP/issues/97

As you might now I focused 100% of my efforts on version 3.x, and I believe you are using version 2.x.

What do you need me to do?

**Comment by mkhansen-intel** [comment]
@facontidavide - we haven't had time to port to v3.x, so we would like you to release both versions for Dashing. We could potentially port to 3.x in a later Dashing sync.

**Comment by dirk-thomas** [comment]
Both versions v2 and v3 have been released in the meantime and passed building on Jenkins.

**Comment by crdelsey** [comment]
Sounds like this is resolved for now. Closing.
