### ISSUE TITLE
Add motion primitives to launch

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#756]
This is an issue against the `lifecycle` branch.
`nav2_bringup_launch.py` is missing the launching of the motion primitives node.
This is needed for recoveries.

**Comment by orduno** [comment]
Added in #777.

**Comment by orduno** [comment]
Re-opening as we haven't added this to the official user launch files, only to the simulation launch.

**Comment by crdelsey** [comment]
Fixed in #841
