### ISSUE TITLE
Commanded velocities are hardcoded

### ISSUE THREAD

**Issue by rotu** [ros-planning/navigation2#775]
The commanded speed in `nav2_motion_primitives::Spin::timedSpin` is hardcoded to 0.5 which is below the minimum turning velocity of my test robot. This value should probably be extracted to a parameter.

**Comment by mkhansen-intel** [comment]
I agree this is a bug. We have a couple of other open issues to re-do the spin code, we'll need to fix this as well.

**Comment by crdelsey** [comment]
Related to #423 and robot parameter server change

**Comment by mhpanah** [comment]
#423 Did not address hardcoded commanded velocities.  Next PR will address this and also hardcoded yaw angle.

**Comment by SteveMacenski** [comment]
@mhpanah @crdelsey anyone going to touch this? I can add to my queue. This has been in here a little longer than I'd like

**Comment by SteveMacenski** [comment]
In progress
