### ISSUE TITLE
Migrate to Behavior Tree CoRoutines

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#786]
#### Feature description
PR #761 backs out the use of the CoRoutine feature in the behavior tree navigator due to some issues with losing incoming messages. We should root cause that problem and re-enable the coroutine feature.

**Comment by mkhansen-intel** [comment]
I don't know the impact of this one, what if we never do it? Is something broken without Coroutines?

**Comment by crdelsey** [comment]
Maybe no real impact, but it would make me feel better for 2 reasons:
1. Fewer threads means fewer race conditions,
2. There was a problem in our old coroutine implementation that isn't fully understood. What if it is still there in the thread based implementation, but happens less frequently?

**Comment by crdelsey** [comment]
DUpe ofo #820
