### ISSUE TITLE
dwb consumes more than 150% cpu power when local planner is not running

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#792]
## Bug report

**Required Info:**

- Operating System:
  -Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  -lifecycle branch
- DDS implementation:
  - Fast-RTPS, 
 -ros2/src/eProsima/Fast-RTPS     -- “v1.7.2”
 -ros2/src/ros2/rmw_fastrtps       -- “0.7.1”

- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

Run our stack and look at top

#### Expected behavior
If local planner is not actuating the robot, the dwb thread should not consume 150% cpu
#### Actual behavior
dwb thread is consuming lots of cpu
#### Additional information
![issue](https://user-images.githubusercontent.com/39755151/58736208-deaf6f00-83b1-11e9-8779-6702eb759614.png)

----

**Comment by SteveMacenski** [comment]
Its probably the costmap rather than the dwb action if there's nothing being processed.

**Comment by rotu** [comment]
Any info on what's causing this? I'm seeing this on a bunch of Nav2 nodes, even though they are all in unconfigured status:

![Screenshot from 2019-06-11 16-42-58](https://user-images.githubusercontent.com/119948/59309124-65910100-8c68-11e9-8f76-ecdc0142f9ec.png)
![Screenshot from 2019-06-11 16-45-46](https://user-images.githubusercontent.com/119948/59309127-675ac480-8c68-11e9-9d3f-2069e599c76b.png)

**Comment by crdelsey** [comment]
@mjeronimo found this block that seems to be consuming as much CPU as available.
https://github.com/ros-planning/navigation2/blob/c530cd89eb2e23cd4e9928c9df9dcdf21eaa042a/nav2_util/src/lifecycle_node.cpp#L53-L55

**Comment by mjeronimo** [comment]
Fixed with #866.
