### ISSUE TITLE
-Wpedantic flag

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#80]
What to do with -Wpedantic flag? Should we remove it?

**Comment by crdelsey** [comment]
My recommendation is that we build with `-Wall -Wextra -Wpedantic -Werr` but get rid of -Wpedantic if it becomes a problem on specific components.

I think the escalation is:
1. Try to disable the warning using a pragma in the code
2. Add -Wno-pedantic in the narrowest scope of the CMakeLists.txt as possible
3. Remove -Wpedantic from the CXX_FLAGS for the package.

**Comment by mkhansen-intel** [comment]
I agree with you Carl.

The immediate problem is AMCL right? I think those are fixable, right? At least the ones I see are extra semicolons after the curly braces, are there others that can't be fixed?

**Comment by mhpanah** [comment]
Per Carl's suggestion I updated map_draw and  pf_draw with the following pragma:
#pragma GCC diagnostic ignored "-Wpedantic"
