### ISSUE TITLE
Cancelling nav2_goal causes the stack to crash

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#800]
## Bug report

**Required Info:**

- Operating System:
  -Ubuntu 18.04
- Installation type:
  - Source
- Version or commit hash:
  -lifecycle branch
- DDS implementation:
  - Fast-RTPS, 
 -ros2/src/eProsima/Fast-RTPS     -- “v1.7.2”
 -ros2/src/ros2/rmw_fastrtps       -- “0.7.1”

- Client library (if applicable):
  - rclcpp
#### Steps to reproduce issue

- Run stack, from rviz click on `Navigation2 Goal` 
- In the middle of the execution click on the `Cancel`
- Click on  `Navigation2 Goal` to set a new goal

#### Expected behavior
Start navigation to the new goal
#### Actual behavior
![lifecycle_crash](https://user-images.githubusercontent.com/39755151/58819275-bc516780-85e4-11e9-9687-def8ef6abe68.png)

**Comment by orduno** [comment]
I ran a test with #804 applied and am not seeing the stack crash. However, I do see another issue:

![cancel_fail](https://user-images.githubusercontent.com/39749557/58920021-218c8200-86e5-11e9-96d4-d4ca242c8f3b.gif)

You'll notice after the second time I cancel the navigation, I provide the third goal and the nav stack immediately returns succeeded. I don't see any output from DWB.

**Comment by mhpanah** [comment]
@orduno #804 might have fixed this issue.  I will test it out tomorrow.

**Comment by mhpanah** [comment]
This issue is fixed in #804.
