### ISSUE TITLE
Enable new goal pursuit

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#801]
The new feature will allow setting a new goal while pursuing one.

**Comment by SteveMacenski** [comment]
Just to make sure the terminology is in-line with the old style of actions, this is referred to as `preempt` that ROS2 actions seem to ignore (The ROS2 Actions doc about it doesn't explicitly mention why it was removed or if that was intentional).

**Comment by orduno** [comment]
@SteveMacenski Yes, this is action preemption, specifically `NavigateToPose` action preemption.

Agree, I think it would be useful to add a `SimpleActionServer` to ROS2 actions.

**Comment by orduno** [comment]
Closing the issue, implemented in #802.
