### ISSUE TITLE
Implement SimpleActionServer

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#811]
#### Background
ROS2 is missing an `rlcpp_action::SimpleActionServer` that is equivalent to ROS 1  `actionlib::SimpleActionServer`.

ROS2 does come with some basic examples for implementing action clients and servers, but these don't fully implement the ROS1 `SimpleActionServer` policy.

Not having a clear action policy implemented could lead to several issues such as #835 

#### Feature description

Implement a SimpleActionServer with a single goal policy on top of the ActionServer class. 

The specification of the policy could be the same as ROS1: 
- only one goal can have an active status at a time, new goals preempt previous goals
- an explicit preempt goal preempts all older goals
- accepting a new goal implies successful preemption of any old goal and the status of the old goal changed to abort.

Created an [issue](https://github.com/ros2/rclcpp/issues/759) upstream for this.

**Comment by crdelsey** [comment]
Can you add some detail to this?

**Comment by crdelsey** [comment]
Fixing the race condition in goal preemption is critical. The rearchitecting of SimpleAction* is medium. Need to create separate issues

**Comment by orduno** [comment]
I have updated the issue to reflect this.

**Comment by SteveMacenski** [comment]
Is this still an active need>

**Comment by orduno** [comment]
I've updated the issue to cover only the Server side. We can discuss the need for a `SimpleActionClient` on a separate issue.
