### ISSUE TITLE
Lifecycle nodes erroring out but not correctly reporting back to the lifecycle manager

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#817]
If one of the lifecycle nodes generates an exception in a state transition, such as on_configure or on_activate, the on_error callback is invoked. However, the failure is not propogated back to the lifecycle manager, which thinks that the node was successfully brought up and continues with the bring-up process instead of exiting and describing the failure.

**Comment by crdelsey** [comment]
This is fixed by #846. Closing.
