### ISSUE TITLE
All lifecycle nodes should pause and resume properly

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#818]
Currently, the lifecycle manager is able to bring up each lifecycle node (Configure, Activate) and also shutdown each node (Deactivate, Cleanup, and Shutdown). We should be able to return each node to its intial state (using Deactivate, Cleanup) and resume each node (using Configure, Activate). This will test several aspects of the stack, including that resources are properly release and re-allocated, that parameters are declared and undeclared properly, etc. Eventually, we will support interactive configuration of node parameters, which will require bringing the nodes to the appropriate state for the specific parameters.

**Comment by bpwilcox** [comment]
Fixed with #1108
