### ISSUE TITLE
Rename nav2_tasks 

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#821]
Now that we have moved from our old tasks implementation to ROS2's Actions we have removed the tasks-related code from nav2_tasks. What remains is Behavior Tree-related code: both a generic BT engine and our own BT nodes. So, we should rename nav2_tasks to something like nav2_bt or nav2_behavior_tree. There can be multiple directories/nodes that then use this BT core, such as nav2_mission_executor, nav2_bt_navigator, nav2_lifecycle_manager, etc.

**Comment by mkhansen-intel** [comment]
I'm re-opening this as the README.md file needs to be updated, it still says "Nav2 Tasks" and discusses the lack of actions in ROS2, etc. It's very confusing.
