### ISSUE TITLE
Restructure and write documentation for Dashing release

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#822]
Top level documentation should be targeted at users, not developers. There should be a link to developer documentation.

Top Level should be something like

- For Users
  - Quick Start

  - Porting to other robots

  - Parameter Tuning
    - Detailed parameter Docs

- For Developers

**Comment by mlherd** [comment]
In my opinion, #980 and #822 are duplicates. I think we can close one of these issues.

**Comment by SteveMacenski** [comment]
I think given the quantity of context in the other ticket, this can be more than safely closed
