### ISSUE TITLE
Position the "Navigating" window in a more convenient place

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#829]
Currently, when using rviz and the Nav2 Goal Tool to specify a destination pose, the tool pops up a "Navigating..." window. This comes up at 0,0. Instead, it would be handy if the window would pop up in a more convenient (and consistent) place, such as near the pose tool itself.

**Comment by SteveMacenski** [comment]
The navigation dialog has been gone for a bit.
