### ISSUE TITLE
Test nav2 stack on real TB3 prior to dashing release

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#834]

**Comment by mkhansen-intel** [comment]
I'm not going to be able to get this one done before release. We need to re-assign.

**Comment by crdelsey** [comment]
According to ROBOTIS-GIT/turtlebot3#431, it seems the turtlebot 3 is not yet ready to run with the dashing release. The MicroXRCEAgent that it uses to get on the DDS domain hasn't been updated to work with the FastRTPS version used by ROS now.

**Comment by crdelsey** [comment]
Done
