### ISSUE TITLE
Add Doxygen to navigation2 packages

### ISSUE THREAD

**Issue by bpwilcox** [ros-planning/navigation2#84]
We should add doxygen style comments to the navigation2 stack packages

- [ ] nav2_amcl
- [ ] nav2_astar_planner
- [ ] nav2_bt_navigator
- [ ] nav2_controller
- [ ] nav2_costmap_2d
- [ ] nav2_costmap_world_model
- [ ] nav2_dijkstra_planner
- [ ] nav2_dynamic_params
- [ ] nav2_map_server
- [ ] nav2_mission_executor
- [ ] nav2_msgs
- [ ] nav2_robot
- [ ] nav2_simple_navigator
- [ ] nav2_tasks
- [ ] nav2_util
- [ ] nav2_voxel_grid

**Comment by mkhansen-intel** [comment]
Do we still want to do this or can I close it?

**Comment by crdelsey** [comment]
Well ... I'd say we want better documentation. I think doxygen is part of that, though doxygen's main strength is API documentation, IMHO. We probably need it mostly in components that are meant to be used as a library, like utils and tasks.

**Comment by crdelsey** [comment]
Closing this until we figure out what exactly needs to be documented and why
