### ISSUE TITLE
The now() function in rclcpp::Node and rclcpp_lifecycle::LifecycleNode is not const

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#844]
This issue is a reminder to investigate the now() function in ROS2, considering whether it should be declared as const. This came up when in the costmap_2d_ros code where getRobotPose was declared as const, but uses the lifecycle node's own now() method, which is declared as non-const. The getRobotPose method had to have const removed. It seems that now() could be declared const (have to look into whether the node's state is actually being updated with a call to now).

**Comment by SteveMacenski** [comment]
This was approved by dirk
