### ISSUE TITLE
DWB: Handle a pending preemption after reaching a final state on current goal.

### ISSUE THREAD

**Issue by orduno** [ros-planning/navigation2#861]
#### Feature description
Define what to do with a pending preemption before setting a final state (succeed / failed) based on the current goal.

#### Implementation considerations

This is something to consider for all modules using Actions. In the case of DWB (path following) if the end pose is different between the current goal and new goal we might decide to pursue the new goal, however, if these have the same end pose we might set the final state without preempting.

**Comment by SteveMacenski** [comment]
@crdelsey I see a TODO in the nav2 controller on implementing the preemption condition. Is this tied in to that?

Any particular blocker?

**Comment by orduno** [comment]
Solved in #1356.
