### ISSUE TITLE
Map server publishing maps when not in active state

### ISSUE THREAD

**Issue by mjeronimo** [ros-planning/navigation2#878]
The map server is publishing its map periodically using a timer callback. However, this callback doesn't check what lifecycle state the map server is in. If the map server has been previously activated and then brought back to Unconfigured or Inactive, the map server could be reading a new map (during on_configure) or have an inactive publisher (activated during on_activate). So, the map server should only be publishing updates while it is in the active state. 

To demonstrate the publishing via in inactive publisher, run the following after the system is up and running:

`ros2 lifecycle set map_server deactivate`

**Comment by mkhansen-intel** [comment]
Yep. It's a bug. 
Linked to #867.
