### ISSUE TITLE
Cannot see error messages from map_server

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#881]
## Bug report

When running map_server with an invalid map file or filename, all useful error messages from exceptions are hidden. All I get is:
```
[INFO] [map_server]: Creating
[INFO] [map_server]: Configuring
[WARN] []: Error occurred while doing error handling.
[FATAL] [map_server]: Lifecycle node entered error state
```

This is likely due to the lifecycle transition service call catching the exception and silently transitioning to the error state, like we've seen in other nodes.

**Comment by rotu** [comment]
Blech. I just encountered this. Any fixes/workarounds?

**Comment by crdelsey** [comment]
Uncomment these lines
https://github.com/ros2/rclcpp/blob/378657865e61b9a0b0a1775d7391dcb4a950cf27/rclcpp_lifecycle/src/lifecycle_node_interface_impl.hpp#L429-L435

@yathartha3 Was working on a PR for this. Any update on whether that is ready?

**Comment by rotu** [comment]
Thanks, @crdelsey. Can confirm that patched the issue. Created bug report in rclcpp repo.

**Comment by yathartha3** [comment]
Seems to be working on after un-commenting those lines. I submitted a PR for in the rclcpp repo.

**Comment by crdelsey** [comment]
Upstream PR is ros2/rclcpp#777
