### ISSUE TITLE
Path retracing Recovery Behavior Feature request

### ISSUE THREAD

**Issue by yathartha3** [ros-planning/navigation2#894]
## Feature description
Add path retracing as a recovery behavior.

## Implementation considerations
This is a very simple method to back away from obstacles. This would require some form of motion memory (cmd_vel, or path). It can work in conjunction with rotate recovery (for omni-directional, skid steer robots).

**Comment by crdelsey** [comment]
We can raise the priority once we find a situation where we want this recovery behavior.

**Comment by yathartha3** [comment]
Closing it for now. Will reopen if there is a use case for it.
