### ISSUE TITLE
Rviz cannnot response when pressing the navigation2 goal button

### ISSUE THREAD

**Issue by MengNan-Li** [ros-planning/navigation2#905]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu18.04
- Installation type:
  - binaries
- Version or commit hash:
  - 0.2.0
- DDS implementation:
  -  Fast-RTPS
- Client library (if applicable):
  - rclcpp

#### Steps to reproduce issue

```
(1) start our robot driver.
(2) ros2 launch nav2_bringup nav2_bringup_launch.py autostart:=True map:=**.yaml use_sim_time:=False map_type:=occupancy
(3) ros2 run rviz2 rviz2 -d $(ros2 pkg prefix nav2_bringup)/share/nav2_bringup/launch/nav2_default_view.rviz
(4) rviz set initial pose successfully
(5) When seting the navigation2 goal, the rviz cannot response and crash.
```

#### Expected behavior
Robot move the goal point set in rviz  navigation2 goal button, and a pop-up window will appear on your screen with a 'cancel' button if you wish to cancel
#### Actual behavior
When seting the navigation2 goal, the rviz cannot response and crash.
#### Additional information

----

**Comment by mlherd** [comment]
Hi MengNan! I have a few questions. What robot do you have? Can you see the map after launching Rviz? Do you see any error messages in any of the terminals after setting the initial pose and the goal position?

**Comment by testkit** [comment]
Similar issue was found in rviz2 for simulation, but this rviz2 issue might be the curlprit https://github.com/ros2/rviz/issues/417.

**Comment by MengNan-Li** [comment]
@mlherd We use our own robots([YUNJI Technology](http://en.yunjichina.com.cn/)). I can the map and set the initial pose of robot.
![image](https://user-images.githubusercontent.com/27143147/60568628-ee024d80-9d9f-11e9-9e66-ed268b430c9f.png)

The log messages of setting the initial pose:
[amcl-3] [WARN] [amcl]: Waiting for map....
[amcl-3] [INFO] [amcl]: initialPoseReceived
[amcl-3] [INFO] [amcl]: Setting pose (1562135076.330833): 0.575 1.877 -1.570
[amcl-3] [INFO] [amcl]: Received a 384 X 384 map @ 0.050 m/pix
[amcl-3] 
[amcl-3] [INFO] [amcl]: Setting pose (1562135077.010127): 0.575 1.877 -1.570
[amcl-3] [INFO] [amcl]: createLaserObject

**Comment by MengNan-Li** [comment]
When seting the navigation2 goal, the rviz cannot response. And the terminal has no new log information.
![image](https://user-images.githubusercontent.com/27143147/60568820-7aad0b80-9da0-11e9-86f4-b28b0fdc539d.png)

**Comment by mkhansen-intel** [comment]
Hi @MengNan-Li - I'm sorry to see you're having issues. We have seen some issues with Rviz2, but let's see if the nav2 system is running correctly in this case.
1) Is Gazebo still running? can you verify that the simulation hasn't crashed for some reason?
2) Is there any log output after AMCL initialized, from the lifecycle_manager node? 
-- You should see it 'activating' the rest of the nodes in the system, and eventually see a message that says 'The system is active'. This will tell you that all the nodes were successfully transitioned to the 'active' lifecycle state. If you don't see that, there is a possibility that something failed. 
3) Another thing to check is whether the nodes are running. When you do a 'ros2 node list' what do you get? The bt_navigator node is the one that is providing the action server for the navigation2 button. Make sure that node is running and active. You can get its state by 'ros2 service call /bt_navigator/get_state lifecycle_srvs/GetState'

**Comment by MengNan-Li** [comment]
Hi @mkhansen-intel Thinks for your response.
1. I use our own real robot, not gazebo. 
2. The log information after starting the navigation launch file is as follows:
![image](https://user-images.githubusercontent.com/27143147/60637831-953dbe00-9e4e-11e9-91b5-b5df2c373d81.png)
The following information is continuously refreshed until acml is initialized.
![image](https://user-images.githubusercontent.com/27143147/60638039-68d67180-9e4f-11e9-99ca-978c31e4e9ea.png)
3. ros2 node list:
![image](https://user-images.githubusercontent.com/27143147/60638141-c4a0fa80-9e4f-11e9-883c-9b996ad28396.png)
ros2 service call /bt_navigator/get_state lifecycle_msgs/srv/GetState:
![image](https://user-images.githubusercontent.com/27143147/60638116-adfaa380-9e4f-11e9-94f1-c106f808661e.png)

**Comment by MengNan-Li** [comment]
Think you all. When the issue(#908) is solved, the problem is gone.
