### ISSUE TITLE
Local costmap not displayed (Could not transform from [odom] to [map])

### ISSUE THREAD

**Issue by AndreasAZiegler** [ros-planning/navigation2#921]
## Bug report

**Required Info:**

- Operating System:
  - Ubuntu 18.04
- Installation type:
  - binaries
- Version or commit hash:
  - dashing-devel da5360af1e69cabe394c1eb15191b1e0fb630d16
- DDS implementation:
  - Fast-RTPS

#### Steps to reproduce issue
* Follow steps in https://github.com/ros-planning/navigation2/tree/dashing-devel/nav2_bringup

#### Expected behavior
Rviz displays the local map if enabled

#### Actual behavior
Rviz can't display the local map. I says "Could not transform from [odom] to [map]" even though rviz shows the tf tree where map->odom is contained

![local_costmap](https://user-images.githubusercontent.com/6949508/60946520-b7bc5500-a2ee-11e9-94be-99b806d7aa64.png)

**Comment by crdelsey** [comment]
There are problems with Rviz displaying data at the moment. I believe it doesn't use message filters for all messages yet. The result is that Rviz tries to transform incoming data but the transformation hasn't arrived yet, so it just displays an error message instead.

I just checked and I see this is a known problem with Rviz. It is mentioned on their front page among "other features" to be ported. https://github.com/ros2/rviz

**Comment by crdelsey** [comment]
Looks like there is a PR for Rviz already. ros2/rviz#375

**Comment by ChristofGroschke** [comment]
Hey, has this issue been solved ? The PR is still on in review. Thanks.

**Comment by ChristofGroschke** [comment]
Quick question. Is this already fixed. I think i have a similar problem with turtlebot3, kinect and cartographer. Cartographer is running in localization mode. The global costmap is showing up but the for the local costmap rviz reports no transform from /odom to /map. The transform is valid, and is showing of under tf tree. If it's is fixed does someone now if this is already upstream in the Ubuntu 18.04 repositories ? Or do i have to use the devel branch ? Thanks. Sorry for opening this up.

**Comment by SteveMacenski** [comment]
Ask on ROS Answers
