### ISSUE TITLE
Modify TurtleBot3 RL Environment for Obstacle Avoidance Task

### ISSUE THREAD

**Issue by mhpanah** [ros-planning/navigation2#934]
Addressing #913 

- [x]  Add GetEntityState and SetEntityState to TB3 RL environment

- [x]  Add get robot pose to the environment

- [x] Add getting a random pose and setting random goal from file

- [x]  Modify the reset method to randomly place the robot at different pose

- [x]  Modify the observation method to contain laser scan, goal distance, and angle to goal

- [ ]  Add noise to robot pose

**Comment by SteveMacenski** [comment]
@mhpanah is this complete enough to close?
