### ISSUE TITLE
Nav2 system tests broken

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#941]
We get this error during test_localization
```
[amcl-5] terminate called after throwing an instance of 'tf2_ros::CreateTimerInterfaceException'
9: [amcl-5]   what():  timer interface not set before call to waitForTransform
```

This is likely related to upstream change ros2/geometry2#121

**Comment by crdelsey** [comment]
@nuclearsandwich FYI - Our system tests are currently broken due to an API change in TF2.

**Comment by SteveMacenski** [comment]
@crdelsey I see this issue on my 18.04 machine when trying to run the stack on most up to date geometry2 & stack
