### ISSUE TITLE
Make BT navigator support dynamically added BT nodes via pluginlib

### ISSUE THREAD

**Issue by crdelsey** [ros-planning/navigation2#942]
BT navigator provides flexibility in configuring behavior using behavior trees, however, users cannot added their own custom BT nodes without changing the source code and recompiling.

This could be fixed by making BT navigator accept additional node implementations via pluginlib.

**Comment by mjeronimo** [comment]
@crdelsey The 3.0 version of the Behavior Tree library supports plug-ins. Once we port to that version (moving our direct usage of the blackboard to the new port abstraction), we can take advantage of that feature. Another new feature that I've wanted is also in 3.0: the ability to using XML includes. This will allow us to specify sub-tree in separate files if we desire, increasing modularity and reusability of sub-tree components.
