### ISSUE TITLE
rviz does not start when using opensplice

### ISSUE THREAD

**Issue by Jconn** [ros-planning/navigation2#996]
Bug report
Required Info:

Operating System:
Ubuntu 18.04
Installation type:
binaries
Version or commit hash:
dashing-devel 756265f
DDS implementation:
RTI opensplice
Steps to reproduce issue
Follow steps in https://github.com/ros-planning/navigation2/tree/dashing-devel/nav2_bringup
When I try to start rviz it does not.
Expected behavior
Rviz starts

Actual behavior
I get the following console output

[johnconn@amadeus navigation2 (dashing-devel ✗)]$ ros2 run rviz2 rviz2 -d nav2_bringup/launch/nav2_default_view.rviz
[INFO] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [rviz2]: OpenGl version: 3 (GLSL 1.3)
[INFO] [rviz2]: Stereo is NOT SUPPORTED

I have nodes pubbing and subbing to topics on 3 computers in my network when this crash occurs. 

I am the only person on my network using ROS/ROS2

I tried with ROS_DOMAIN_ID unset and with ROS_DOMAIN_ID=42, a suggestion from the https://github.com/ros-planning/navigation2/issues/916

everything was working okay with fastrtps

**Comment by crdelsey** [comment]
I can reproduce this, even with nothing else running. However, if I remove `~/.rviz2/default.rviz` and run with just the default settings, it starts fine.

This suggests the problem is one of Rviz's display plugins.
